"""Original representation, circuit and programming questions with explicit models."""
import json
from pathlib import Path
BASE=Path(__file__).resolve().parent
questions=[]
def q(topic,title,stem,options,answer,solution,pattern,difficulty='Medium'):
 questions.append(dict(topic=topic,title=title,stem=stem,options=options,answer=answer,solution=solution,pattern=pattern,difficulty=difficulty,kind='Original examination analogue'))

q('g_number','Overflow and carry need separate decisions',r'Add eight-bit words `01111111` and `00000001`. What are the stored word, unsigned carry-out, and signed overflow flag?', ['10000000, 0, 1.','10000000, 1, 1.','00000000, 1, 0.','10000000, 0, 0.'],1,r'''Unsigned addition gives $127+1=128$, within zero through 255, so the stored word is 10000000 and carry-out is zero. Signed eight-bit two's complement allows only $[-128,127]$, so the same mathematical positive sum exceeds its upper endpoint.

The sign bit changes from positive to negative when adding two nonnegative operands, setting signed overflow. The flags answer different questions. A stored bit pattern alone does not identify whether the arithmetic was intended to be signed.''','Phd_CE_1405_Q31')
q('g_number','A quantized fixed-point product',r'Unsigned eight-bit values use four fractional bits. Multiply encoded words `00011001` and `00011000`, rescaling back to four fractional bits with nearest-even rounding. What is the resulting encoded integer?', ['37','38','39','600'],2,r'''The integer codes are 25 and 24. Their exact code product is 600; rescaling divides by sixteen to 37.5.

This is exactly halfway between codes 37 and 38. Nearest-even chooses 38, representing $38/16$. The wide intermediate must hold 600 before rescaling; wrapping the product in eight bits first would lose information. Truncation would give 37, a different rounding rule.''','Phd_CE_1405_Q31; MS_CS_1404_Q51','Hard')
q('g_number','A small normal floating-point encoding',r'A normal binary format has one sign bit, three exponent bits with bias three, and four fraction bits. Decode `0 100 1010`; exponent fields 000 and 111 are reserved.', ['3.25','1.625','6.5','2.625'],1,r'''The sign is positive. Stored exponent four gives true exponent one. The significand is $1.1010_2=1+1/2+1/8=1.625$.

Multiply by $2^1$ to get 3.25. The implicit leading one belongs only to normal encodings; the stated exponent is normal. Bias and significand must both be applied before interpreting the complete word.''','MS_CS_1404_Q51; Phd_CE_1405_Q31')
q('g_number','Nearest-even binary spacing',r'Use a binary format with three significant bits including the leading one. Round 5.5 to nearest, with ties to even.', ['5','6','5.5','4'],2,r'''At magnitudes from four through less than eight, representable values are four, five, six, and seven, with spacing one. The value 5.5 is halfway between five and six.

The significands are $1.01_2$ and $1.10_2$ respectively. Six has an even low significand bit, so it is selected. Tie-to-even concerns the encoded significand, not a general rule to round all inputs upward. Five would use ties downward; 5.5 requires an extra precision bit.''','MS_CS_1404_Q51','Hard')
q('g_number','Signed range after sign extension',r'Sign-extend six-bit two\'s-complement word `101101` to eight bits and state its mathematical value.', ['00101101 and 45.','11101101 and -19.','11101101 and -45.','10101101 and -19.'],2,r'''The original unsigned value is 45, so its six-bit signed value is $45-64=-19$. Repeat the original sign bit in the two added high positions to obtain 11101101.

Its eight-bit unsigned value is 237 and signed value $237-256=-19$, checking preservation. Zero extension would change the value to positive 45. Sign extension repeats the sign bit rather than copying an arbitrary high-bit prefix.''','Phd_CE_1405_Q31')
q('g_number','A decimal truncation counterexample',r'With exact real arithmetic, compare $T(x)=\operatorname{CHOP}(100x)/100$ and $R(x)=\operatorname{CHOP}(100x+0.5)/100$ at $x=2.376$. What are the values?', ['2.37 and 2.38.','2.38 and 2.38.','2.37 and 2.37.','2.38 and 2.37.'],1,r'''The scaled input is 237.6. Truncation gives 237 and therefore 2.37. Adding one half produces 238.1; truncating gives 238 and therefore 2.38.

The two expressions implement different operations despite sharing the CHOP primitive. Exact arithmetic is stipulated to isolate the rounding formula from binary-representation errors; actual software must also account for its numeric model.''','MS_CS_1393_Q165; MS_CS_1404_Q51')
q('g_number','A terminating binary expansion criterion',r'Which reduced rational has a terminating base-two fractional expansion?', ['3/20','7/24','13/32','5/18'],3,r'''A reduced denominator must divide some power of two for a finite binary expansion. Thus it must itself be a power of two.

Only denominator 32 satisfies the condition; the others contain odd prime factors five or three. The fractions are already reduced, which matters: an unreduced odd factor might cancel. The exact expansion is $13/32=0.01101_2$, confirming termination.''','MS_CS_1404_Q51; MS_CS_1405_Q38')
q('g_number','An endianness question with a fixed word',r'A 32-bit unsigned word has hexadecimal value `0x12345678`. In little-endian byte-addressable memory, what byte is at the smallest address, and what changes under big-endian storage?', ['0x78; only byte order changes.','0x12; numeric value changes.','0x78; each byte is bit-reversed.','0x87; only byte order changes.'],1,r'''Little-endian storage places the least significant byte, 0x78, at the smallest address. Big-endian storage instead places 0x12 there.

The abstract numeric value remains 0x12345678 when decoded with the matching storage convention. Endianness reverses byte placement, not the bits within each byte. Reading raw bytes under the wrong convention would produce a different decoded value, but that is a separate mismatch.''','Phd_CE_1405_Q31; MS_CS_1404_Q51')

q('g_boolean','Canonical indices under a specified bit order',r'For $F=(a\Rightarrow c)\land(a\Leftrightarrow b)$ with bit order $a,b,c$, which canonical sum represents $F$?', [r'$\sum m(0,1,7)$',r'$\sum m(2,3,4,5,6)$',r'$\prod M(0,1,7)$',r'$\sum m(0,2,7)$'],1,r'''The equivalence allows only $a=b=0$ or $a=b=1$. The first case permits either $c$, giving indices zero and one; the second case requires $c=1$, giving seven.

Use those true indices in a canonical sum. A product at the same indices would set those rows false. The final option changes one bit-index interpretation. The requested representation and the variable order both affect the answer.''','Phd_CS_1405_Q22')
q('g_boolean','A consensus term is logically redundant but physically useful',r'$F=ab+\overline a c$. Which added term preserves the function and protects the single-$a$ transition when $b=c=1$?', ['$bc$','$ac$',r'$\overline b c$',r'$a\overline c$'],1,r'''With $b=c=1$, the two original terms hand off responsibility as $a$ changes, and unequal gate delays can briefly make both terms zero. The term $bc$ remains one throughout the transition.

It is algebraically redundant because $bc=abc+\overline a bc$, with the first part covered by $ab$ and the second by $\overline a c$. The other terms either alter the truth function or fail to stay true during both endpoint states. Logical simplification and hazard elimination have different optimization goals.''','MS_CE_1405_Q78; Phd_CE_1405_Q23','Hard')
q('g_boolean','Count completions under a parity constraint',r'A three-input truth table has unknown entries at indices 0,1,6,7. Other entries are fixed. Require the completed function to be self-dual, $F(\overline x)=\overline{F(x)}$. If the fixed complementary pairs already satisfy this, how many completions remain?', ['2','4','8','16'],2,r'''Complementing all three bits pairs index zero with seven and one with six. Each unknown pair allows one free Boolean choice, with the other entry forced to its complement.

There are two independent pairs and therefore four completions. Sixteen would treat all four entries as free; two would incorrectly tie the pairs together. Feasibility of the fixed pairs is explicitly given and must otherwise be checked first.''','MS_CS_1405_Q99; Phd_CS_1405_Q15')
q('g_boolean','Existential elimination is OR of cofactors',r'$F(x,y,z)=(x\land y)\lor(\neg x\land z)$. What is $\exists x\,F$ as a Boolean function of $y,z$?', [r'$y\land z$',r'$y\lor z$',r'$y\oplus z$',r'$\neg y\lor z$'],2,r'''The two cofactors are $F(0,y,z)=z$ and $F(1,y,z)=y$. An existential Boolean quantifier permits either choice of $x$, so take their OR: $y\lor z$.

Universal elimination would take the AND instead. XOR would falsely reject $y=z=1$, where both witnesses work. The quantifier's meaning determines the operation combining cofactors.''','MS_CS_1405_Q95; MS_CS_1405_Q97')
q('g_boolean','A unique ANF coefficient',r'For three-input majority, $F=1$ when at least two inputs are one. Which algebraic normal form over $\mathbb F_2$ is correct?', [r'$ab\oplus ac\oplus bc$',r'$ab\oplus ac\oplus bc\oplus abc$',r'$a\oplus b\oplus c$',r'$abc$'],1,r'''At weight zero or one all pair products vanish. At weight two exactly one pair product is one. At weight three all three products are one and their XOR is one, so the first form matches every weight class.

Adding $abc$ would flip the all-one row to zero. Three-input parity is true at weight one and therefore not majority; the triple product misses every weight-two row. OR and XOR forms can agree for a function while using different coefficient rules.''','Phd_CS_1405_Q15; MS_CE_1405_Q77')
q('g_boolean','Boolean derivative and assignment counting',r'$F(x,y,z)=x\oplus(yz)$. How many input assignments change $F$ when only $x$ is flipped?', ['2','4','6','8'],4,r'''XOR with $x$ toggles the output for either value of $yz$. Thus the Boolean derivative $F(0,y,z)\oplus F(1,y,z)$ is one for all four choices of the remaining inputs.

Each choice has two original values of $x$, giving eight assignments under the stated counting convention. Counting only four would count settings of the other inputs rather than complete input assignments. No probabilistic assumption is involved.''','MS_CS_1405_Q99; Phd_CE_1405_Q23')
q('g_boolean','A simplified function from a noncanonical expression',r'Simplify $(a+b)(\overline a+c)(b+c)$ in Boolean algebra.', [r'$ac+\overline a b$',r'$ab+\overline a c$',r'$bc$',r'$a+b+c$'],2,r'''Expand the first two factors to get $ac+\overline a b+bc$. That seems to suggest option one, but the desired standard consensus orientation must be checked: $ac+\overline a b$ indeed has consensus $bc$. The correct answer is option one, corrected below.

The third factor is redundant under this product's expansion. Swapping the roles of $b,c$ changes the selector function.''','MS_CE_1405_Q77; MS_CE_1405_Q78')
questions[-1]['answer']=1
questions[-1]['solution']=r'''Expand $(a+b)(\overline a+c)$ to $ac+\overline a b+bc$. The term $bc$ is the consensus of the first two and is redundant, leaving $ac+\overline a b$.

That selector function already implies $b+c$, so multiplying by the final factor changes nothing. Option two reverses the selector's branches; taking $a=1,b=0,c=1$ distinguishes them. The final alternatives either discard valid one-cases or add false ones. Derive the expression rather than recognizing a similar-looking memorized template.'''
q('g_boolean','A count of monotone truth tables with fixed endpoints',r'How many two-input monotone Boolean functions satisfy $F(0,0)=0$ and $F(1,1)=1$?', ['2','3','4','6'],3,r'''Only entries 01 and 10 remain free. Neither is comparable to the other in the componentwise order, while both lie above 00 and below 11, so all four choices preserve monotonicity.

The resulting functions are AND, the first input, the second input, and OR. Without endpoint restrictions the two constant functions also qualify, giving six. The constraints remove exactly those two.''','Phd_CS_1405_Q15; MS_CS_1405_Q99')

q('g_gates','Recognize both outputs of a shared NAND network',r'Let $t=\operatorname{NAND}(x,y)$, $u=\operatorname{NAND}(x,t)$, $v=\operatorname{NAND}(y,t)$. Outputs are $D=\operatorname{NAND}(u,v)$ and $B=\operatorname{NAND}(v,v)$. For $(x,y)=(0,1)$, what are $(D,B)$ and the circuit function?', ['(1,1), half subtractor.','(1,0), half adder.','(0,1), equality comparator.','(0,0), half subtractor.'],1,r'''Substitution gives $t=1,u=1,v=0$, so $D=1$ and $B=1$. Algebraically $D=x\oplus y$ and $B=\overline x y$.

These are difference and borrow for subtracting $y$ from $x$. The first three XOR-producing gates do not establish a half-adder carry; the second output must also be derived. A borrow occurs at 0 minus 1, precisely the supplied input.''','Phd_CE_1405_Q23')
q('g_gates','A four-gate NOR network',r'Complements are available. Implement majority of $x,y,z$ by NOR gates using its POS $(x+y)(x+z)(y+z)$. What fan-in combination realizes it directly?', ['Three two-input NORs and one three-input NOR.','One three-input NOR only.','Three NANDs only.','Two two-input NORs only.'],1,r'''Each two-input NOR computes the complement of one pairwise sum. A final three-input NOR computes the complement of their OR; by De Morgan this is the product of the three original sums.

The total is four gates with the stated fan-ins. One NOR would instead compute the complement of the total input OR. A direct NAND-only or two-gate construction does not realize the specified two-level POS mapping. This asks for a construction rather than an unsupported minimum over all possible circuit libraries.''','MS_CE_1405_Q77')
q('g_gates','A static-one hazard interval',r'$F=ab+\overline a c$ with $b=c=1$. When $a$ rises, the falling old product reaches the final OR input at 2 ns and the rising new product arrives at 7 ns. The OR has a 1 ns transport delay. What low interval appears at its output?', ['2–7 ns.','3–8 ns.','1–6 ns.','No interval.'],2,r'''At the OR inputs, both products are zero from two through seven nanoseconds. Transport delay shifts both transitions by one nanosecond without suppressing the pulse, giving a low output from three to eight nanoseconds.

The Boolean endpoint values are both one; the glitch comes from path timing. An inertial model might reject a sufficiently narrow pulse, but the question explicitly uses transport. Adding a continuously high consensus path $bc$ would eliminate the static-one hazard.''','MS_CE_1405_Q78; Phd_CE_1405_Q23','Hard')
q('g_gates','Latest arrival at a reconvergent output',r'Two paths feed an AND. One takes 3 ns; the other contains gates taking 2 ns and 4 ns. A final AND takes 1 ns. Inputs transition at time zero and the output requires both paths. What worst-case arrival bound follows?', ['4 ns','6 ns','7 ns','10 ns'],3,r'''The path arrivals are three and six nanoseconds. The AND's required output cannot settle before the slower needed input and its own delay, giving $\max(3,6)+1=7$ ns.

Summing all gates in the circuit gives ten but counts parallel paths sequentially. Four uses only the fast path; six omits the final gate. This latest-arrival calculation assumes the stated transition sensitizes the paths and does not itself claim hazard freedom.''','Phd_CE_1405_Q23; MS_CE_1405_Q78')
q('g_gates','A tied-input gate is an inverter',r'$A=\operatorname{NAND}(x,y)$ and $F=\operatorname{NAND}(A,A)$. Which function and output at $(x,y)=(1,0)$ are correct?', [r'$xy$ and 0.',r'$x\lor y$ and 1.',r'$\overline{xy}$ and 1.',r'$x\oplus y$ and 1.'],1,r'''Tied NAND inputs invert: $\overline{AA}=\overline A$. Substituting the first NAND yields $F=xy$, so the output at 1,0 is zero.

This two-stage double inversion restores AND, not OR. An OR from NAND would first invert each individual input and then NAND those complemented inputs. Track the net actually inverted rather than counting two gates and guessing an operator.''','Phd_CE_1405_Q23')
q('g_gates','Dynamic-power scaling with an activity change',r'Dynamic power is proportional to $\alpha CV^2f$. Capacitance is unchanged; activity halves, frequency doubles, and voltage drops to 80% of its old value. What is the new/old power ratio?', ['0.32','0.64','0.8','1.28'],2,r'''Multiply the independent factors: $(1/2)\cdot1\cdot(0.8)^2\cdot2=0.64$. Activity and frequency changes cancel, leaving the squared voltage factor.

The ratio concerns dynamic switching power under the supplied model, not total power including leakage. A linear voltage factor gives 0.8; omitting either activity or frequency gives the other distractors. Define which physical quantity a formula models before applying it.''','MS_CE_1405_Q77; Phd_CE_1405_Q23')
q('g_gates','An RC transition threshold',r'A capacitor charges from zero toward $V$ through resistance $R$. At what time does it reach $3V/4$?', [r'$RC\ln2$',r'$RC\ln4$',r'$3RC/4$',r'$4RC$'],2,r'''The model is $v(t)=V(1-e^{-t/(RC)})$. Set $v/V=3/4$, so $e^{-t/(RC)}=1/4$ and $t=RC\ln4$.

The voltage supply cancels from the threshold ratio. Linear interpolation in time is not valid for an exponential charge curve; $RC\ln2$ corresponds to half voltage. The circuit model supplies a delay mechanism, rather than the ideal Boolean gate's zero-time semantics.''','MS_CE_1405_Q77; Phd_CE_1405_Q23')
q('g_gates','Noise margins and the limiting side',r'A logic family has $V_{OH}=4.2$, $V_{IH}=3.0$, $V_{IL}=0.9$, and $V_{OL}=0.3$ volts. What are high and low noise margins, and which is smaller?', ['1.2 and 0.6; low.','1.2 and 0.9; low.','0.6 and 1.2; high.','7.2 and 1.2; low.'],1,r'''The high margin is $V_{OH}-V_{IH}=1.2$ V, while the low margin is $V_{IL}-V_{OL}=0.6$ V. The low side is the limiting margin.

Subtract guaranteed output bounds from the appropriate input threshold in the correct direction. Adding voltage levels or using $V_{IL}$ alone omits the guaranteed nonzero low output. The smallest margin indicates the most vulnerable permitted steady level, not a dynamic hazard duration.''','Phd_CE_1405_Q23; MS_CE_1405_Q78')

q('p_types','Promote before complementing a narrow object',r'In C17, `unsigned char u=0x0F`; `CHAR_BIT=8` and `int` is 32-bit two\'s complement. What are the values of `~u` and `(unsigned char)~u`?', ['-16 and 240.','240 and 240.','-16 and -16.','15 and 240.'],1,r'''The unsigned character promotes to `int` because all its values are representable. Bitwise complement therefore acts on a 32-bit signed integer, giving negative sixteen in the stipulated representation.

Converting that result back to eight-bit unsigned character takes it modulo 256, giving 240. The narrow storage width does not control the intermediate expression width. This question's signed representation is stated rather than assumed for every C implementation.''','Phd_CE_1405_Q31; MS_CS_1393_Q165')
q('p_types','Integer division with casts at three locations',r'In C17, let `int a=7,b=3;`. Which values belong to `(double)(a/b)`, `(double)a/b`, and `a/(double)b`, respectively?', ['2, 7/3, 7/3.','7/3, 7/3, 7/3.','2, 2, 7/3.','2, 7/3, 2.'],1,r'''The first expression performs integer division before the cast, producing integer two then double 2.0. In each of the other expressions, an operand becomes double before division, so the other converts too and floating division approximates $7/3$.

The fractions in the options denote the mathematical target subject to the implementation's floating precision, not an exact binary representability claim. Destination type or a cast after an operation cannot recover discarded remainder information.''','MS_CS_1393_Q165; MS_CS_1404_Q51')
q('p_types','A mixed-signedness conditional changes a value',r'In C17 with 32-bit `int` and `unsigned int`, evaluate `int x=-1; unsigned int y=1;` followed by `(1 ? x : y) > 2u`.', ['0','1','Undefined behavior.','It depends on which branch executes.'],2,r'''The conditional operator determines a common arithmetic type from both alternatives, even though the first branch is selected. The result type is unsigned int, and selected $-1$ converts to $2^{32}-1$.

That value exceeds unsigned two, so the comparison is one. The unselected branch affects type conversion without being evaluated for a value. The conversion is defined; it is not signed arithmetic overflow.''','Phd_CE_1405_Q31; MS_CS_1393_Q165','Hard')
q('p_types','Short circuit prevents an invalid evaluation',r'In C17, `int x=0;`. What happens when evaluating `x != 0 && 10/x > 2`?', ['Division by zero.','The value is zero and the division is not evaluated.','The value is one.','The value is implementation-defined.'],2,r'''The left operand of logical AND is false. C sequences it first and does not evaluate the right operand, so no division occurs and the whole logical value is integer zero.

Replacing `&&` with bitwise `&` would remove this protection and evaluate the division. Parsing an invalid-looking subexpression is not the same as executing it. A reasoning trace must include evaluation-control rules.''','MS_CS_1393_Q167; Phd_CS_1405_Q20')
q('p_types','A defined unsigned wrap and an undefined signed counterpart',r'With 32-bit unsigned int and int, compare `UINT_MAX + 1u` and `INT_MAX + 1`. Which classification is correct?', ['Both wrap to zero.','Unsigned gives zero; signed overflow is undefined.','Both are undefined.','Unsigned gives zero; signed is guaranteed INT_MIN.'],2,r'''Unsigned arithmetic is modulo $2^{32}$, so the first expression yields zero. The second is a signed arithmetic result outside its type's representable range, producing undefined behavior in C17.

Two's-complement hardware does not change the language's signed-overflow rule. A fixed-width representation exercise may ask for wrapped low bits, but a C question must first classify whether the operation is defined. The unsigned suffix is essential to the first expression's type.''','Phd_CE_1405_Q31')
q('p_types','A floating equality after large-integer conversion',r'Use IEEE binary64 with nearest-even rounding. Let `double a=9007199254740992.0;`. What is the value of `a + 1.0 == a`, assuming each operation rounds to binary64?', ['0','1','Undefined behavior.','1 only if a is negative.'],2,r'''The number is $2^{53}$. Binary64 spacing there is two, so the exact sum $2^{53}+1$ is halfway between representable $2^{53}$ and $2^{53}+2$.

Nearest-even returns the former, making the equality true. The operation is finite and defined; no integer overflow occurs because it is floating arithmetic. The explicit rounding/storage assumption excludes extended-precision evaluation that could alter a comparison.''','MS_CS_1404_Q51','Hard')
q('p_types','A decimal-rounding implementation needs the right primitive',r'Under exact real arithmetic with truncation toward zero, which formula rounds negative $x=-2.376$ to two decimal places using halfway cases away from zero?', [r'$\operatorname{CHOP}(100x+0.5)/100$',r'$\operatorname{CHOP}(100x-0.5)/100$',r'$\operatorname{CHOP}(100x)/100$',r'$\operatorname{CHOP}(x-0.5)/100$'],2,r'''The scaled value is -237.6. Subtract one half to obtain -238.1; truncating toward zero gives -238, hence -2.38.

Adding one half gives -237.1 and truncates to -237, incorrectly producing -2.37. Plain truncation also gives -2.37, while scaling only after rounding destroys the intended decimal position. The sign-specific offset must match the truncation convention.''','MS_CS_1393_Q165')
q('p_types','A macro parses differently from a function',r'In C17, `#define SQR(x) x*x`. What is `SQR(1+2)`?', ['9','5','7','Undefined behavior.'],2,r'''Text substitution yields `1+2*1+2`. Multiplication has higher precedence, so this evaluates to five.

A fully parenthesized macro `((x)*(x))` would yield nine for this input, but argument side effects would still require separate analysis because the argument is used twice. The given expression has no side effects, so its error is parsing rather than undefined behavior.''','MS_CS_1393_Q167; Phd_CS_1405_Q20')

q('p_flow','Nested conditions and the dangling else',r'In C17, `int a=0,b=1,x=0; if(a) if(b) x=1; else x=2;`. What is the final value of `x`?', ['0','1','2','Undefined behavior.'],1,r'''The else associates with the nearest unmatched if, namely `if(b)`. The outer condition is false, so the entire inner conditional is skipped and x remains zero.

Reading indentation as syntax would incorrectly attach the else to the outer if and predict two. Braces make the intended grouping explicit. Defined control-flow syntax, not a probabilistic interpretation of the two conditions, determines execution.''','MS_CS_1393_Q167; Phd_CS_1405_Q20')
q('p_flow','Continue still reaches the for update',r'In C17, compute `s=0; for(i=1;i<=6;i++){if(i%2==0)continue; s+=i;}`.', ['9','12','21','The loop never terminates.'],1,r'''Odd values one, three, and five add to nine. At an even value, continue skips the remaining body but still proceeds to the for-loop update, so i advances normally.

Replacing a for loop with a while loop whose increment lies below continue would change termination behavior. The full sum 21 ignores the branch; twelve sums even values instead. Trace the loop's control-transfer target, not just its body text.''','Phd_CS_1405_Q20; MS_CS_1393_Q167')
q('p_flow','A switch fallthrough trace',r'In C17, `x=0; switch(2){case 1:x+=1; case 2:x+=2; case 3:x+=4; break; default:x=9;}`. Find x.', ['2','4','6','9'],3,r'''The matching label is case two. Execution adds two, then falls through case three and adds four before break exits the switch. Thus x is six.

Labels are entry points, not separate automatic condition checks with implicit breaks. The default block is not reached after an explicit break. Different languages may have different switch semantics, so the C17 specification is stated.''','MS_CS_1393_Q167; Phd_CS_1405_Q20')
q('p_flow','Unsigned orbit with an unreachable stopping target',r'An eight-bit unsigned variable starts at 0. Repeatedly add 6 modulo 256 while its value is not 1. Does the loop terminate?', ['Yes, after 1 step.','Yes, after 128 steps.','No; all reachable values are even.','No; every value eventually occurs twice.'],3,r'''The reachable subgroup generated by six modulo 256 consists of multiples of $\gcd(6,256)=2$, so every reachable value is even. The target one is outside that orbit.

The orbit has 128 states and returns to zero, after which it repeats without termination. A finite state space does not imply a stopping condition will be reached. This is defined unsigned modular behavior, not signed overflow.''','Phd_CE_1405_Q31; MS_CS_1405_Q125','Hard')
q('p_flow','A reverse-stride recursion count',r'Call a procedure at `(n,i)=(10,0)`; it stops when n<0, otherwise copies `a[n]` to `b[i]` and calls `(n-2,i+1)`. How many elements are copied and what is the last source index?', ['5 and 2.','6 and 0.','6 and 1.','11 and 0.'],2,r'''The source indices are 10,8,6,4,2,0, giving six copied elements; the next index -2 triggers the guard before access.

The destination indices are consecutively zero through five. Starting at ten corresponds to an eleven-element input segment, not an array length of ten. Distinguish a last index from a length and include the zero endpoint.''','MS_CS_1393_Q167')
q('p_flow','A modifying guard has one final failed test',r'In C17, `int x=0,c=0; while(x++<3)c++;`. Find the final pair (x,c).', ['(3,3).','(4,3).','(4,4).','(3,4).'],2,r'''The guard compares old x values zero, one, two, and three. The first three tests succeed and increment c; the fourth fails but still performs the post-increment of x.

Thus c is three and x is four. The side effect occurs even in a failed test because the guard was evaluated. The two values measure different events: tested increments and successful body executions.''','Phd_CS_1405_Q20; MS_CS_1393_Q167')
q('p_flow','A ranking must survive every branch',r'A loop over integer n>0 replaces n by n-1 when odd and by n/2 when even. Which ranking proves termination for every positive start?', ['n as a nonnegative integer.','Parity of n.','The number of ones in n\'s binary expansion.','The value n modulo 3.'],1,r'''At an odd positive state, n-1 is a strictly smaller nonnegative integer; at an even positive state, n/2 is also strictly smaller. Hence n is a well-founded ranking.

Parity can repeat; halving an even number preserves its binary population count, so that count is not strictly decreasing in every step. A residue is neither strictly decreasing nor an unbounded progress measure. A ranking must decrease in every transition, not merely tend downward over several observed examples.''','MS_CS_1393_Q167; Phd_CE_1405_Q3')
q('p_flow','Break exits the nearest loop only',r'For i=1,2,3, an inner loop runs j=1,2,3,4 but breaks when j==3 before incrementing a counter. How many counter increments occur?', ['2','6','9','12'],2,r'''For each outer i, the inner loop increments at j=1 and j=2, then breaks before j=3 contributes. Each of three outer iterations therefore supplies two increments, totaling six.

Break exits only the inner loop here; it does not exit the outer loop or the enclosing function. Nine counts the break-triggering iteration; twelve ignores the break. A return would create a different control-flow scope.''','Phd_CS_1405_Q20; MS_CS_1393_Q167')

(BASE/'original-computing.json').write_text(json.dumps(questions,indent=2)+'\n')
print('Authored',len(questions),'original computing questions.')
