"""Exact counts, parameter models, asymptotic conditions and recursive reasoning."""
import json
from pathlib import Path
BASE=Path(__file__).resolve().parent
questions=[]
def q(topic,title,stem,options,answer,solution,pattern,difficulty='Medium'):
 questions.append(dict(topic=topic,title=title,stem=stem,options=options,answer=answer,solution=solution,pattern=pattern,difficulty=difficulty,kind='Original examination analogue'))

q('a_model','Numeric value versus encoded length',r'A positive integer $N$ is encoded in exactly $b$ binary bits. An algorithm performs $N$ unit-cost iterations. Which tight worst-case bound in $b$ is correct?', [r'$\Theta(b)$',r'$\Theta(b^2)$',r'$\Theta(2^b)$',r'$\Theta(2^{2b})$'],3,r'''A $b$-bit positive integer ranges from $2^{b-1}$ through $2^b-1$. Thus $N$ iterations can number nearly $2^b$, and every such input already requires at least $2^{b-1}$ iterations.

The tight order in encoded length is exponential. Linear time in the numeric parameter does not imply polynomial time in its encoding. Squaring the exponential would require an extra nested value-dependent loop that is not present.''','Phd_CS_1405_Q20; Phd_CE_1405_Q1')
q('a_model','Information lower bound with duplicate keys',r'An array has eight distinguishable records, four with key 0 and four with key 1. A binary comparison decision tree must identify the positions of the four zero keys. What lower bound on its worst-case depth follows from counting outputs?', ['5','6','7','8'],3,r'''There are $\binom84=70$ possible zero-position subsets. A depth-$d$ binary tree has at most $2^d$ leaves, so $d\ge\lceil\log_2 70\rceil=7$.

Eight factorial would overcount by distinguishing permutations of records with the same key when the requested output does not do so. The result is an information lower bound, not a proof that a seven-comparison algorithm exists. The binary-answer assumption is part of the stated model.''','MS_CS_1405_Q120; Phd_CE_1405_Q16','Hard')
q('a_model','Bit cost for repeated doubling',r'Start with the exact integer 1 and double it $n$ times. Charging each doubling its operand bit length, what is the total tight cost?', [r'$\Theta(n)$',r'$\Theta(n\log n)$',r'$\Theta(n^2)$',r'$\Theta(2^n)$'],3,r'''Before doubling number $k$, the value is $2^{k-1}$ and has $k$ bits. The charged total is $\sum_{k=1}^n k=n(n+1)/2$, giving quadratic cost.

The final numeric value is exponential, but its bit length is only $n+1$ and the charged work is not proportional to that value. Unit-cost arithmetic would give linear time for a different model. This question tests the distinction between object magnitude and representation cost.''','Phd_CS_1404_Q71; Phd_CE_1405_Q1')
q('a_model','Output volume can exceed input length',r'Given $n$ distinct objects, a routine explicitly writes every unordered triple. If writing one object takes constant time, what output lower bound holds?', [r'$\Omega(n)$',r'$\Omega(n^2)$',r'$\Omega(n^3)$',r'$\Omega(2^n)$'],3,r'''There are $\binom n3$ triples and each is written explicitly with three object references. The output length is therefore $3\binom n3=\Theta(n^3)$, imposing a matching lower bound on writing time.

A formula or compressed representation could be produced faster, but the statement explicitly requests every triple. Exponential output applies to all subsets, not subsets of fixed size three. An algorithmic bound must respect the output contract.''','MS_CS_1405_Q120; Phd_CS_1405_Q20')
q('a_model','Two independent dimensions',r'A dense real $r\times c$ matrix is read entry by entry and multiplied by a vector using the usual row dot products. What is the count of multiplications and additions, respectively?', [r'$rc$ and $r(c-1)$',r'$rc$ and $c(r-1)$',r'$r+c$ and $rc$',r'$r^2$ and $c^2$'],1,r'''Each of the $r$ rows requires $c$ multiplications and $c-1$ additions to combine its products, under the stated usual dot-product implementation. Multiply those counts by $r$.

The second alternative adds down columns rather than along each row. The other counts replace the rectangular input with unrelated one-parameter shapes. For $c=1$, the addition count is zero, a useful boundary check. Counting an initial addition into a zero accumulator would be a different exact-cost convention.''','MS_CS_1405_Q113; Phd_CE_1405_Q16')
q('a_model','Actual comparison count versus a worst-case maximum',r'Two ascending lists have lengths three and five. Ordinary merging stops comparing when either list empties. What pair gives the minimum and maximum number of comparisons?', ['3 and 8.','3 and 7.','5 and 7.','1 and 7.'],2,r'''The earliest exhaustion is the three-element list, requiring three comparisons if all its values precede the other list's first value. No fewer comparisons can exhaust either list.

The maximum is $3+5-1=7$, attained when neither list is exhausted until one element remains overall. Copying the remainder uses no key comparison. The exact number for a supplied input may fall anywhere between these limits; the universal worst case is not its automatic trace count.''','Phd_CE_1405_Q16')
q('a_model','Recursive work and stack depth are different',r'A routine processes two equal half-sized children sequentially, uses constant local storage per call, and spends linear work combining. What are its total work and auxiliary recursion-stack space?', [r'$\Theta(n\log n)$ and $\Theta(\log n)$',r'$\Theta(n\log n)$ and $\Theta(n)$',r'$\Theta(n)$ and $\Theta(\log n)$',r'$\Theta(\log n)$ and $\Theta(n)$'],1,r'''The work recurrence is $W(n)=2W(n/2)+\Theta(n)$, yielding $\Theta(n\log n)$. Sequential depth-first recursion keeps only one root-to-leaf path active at once; its length is $\Theta(\log n)$.

Only constant per-frame local storage was specified. Counting every call as simultaneously resident would give the wrong stack model. A merge implementation with an additional length-$n$ output buffer would need more storage, but that buffer is not part of this question's stated contract.''','Phd_CE_1405_Q16; Phd_CE_1405_Q1')
q('a_model','A weighted leaf bound with an equality test',r'A binary tree has leaves at depths 1, 2, 3, and 3. What is the sum of $2^{-d}$, and can these depths belong to a finite full tree?', ['1 and yes.','1 and no.','7/8 and yes.','9/8 and no.'],1,r'''The weight sum is $1/2+1/4+1/8+1/8=1$. Construct the tree by taking one root child as a leaf, extending the other to a depth-two leaf and a final branch with two depth-three leaves.

Every internal node has two children, so the construction is full. Equality of the weight bound is consistent with this full tree; the explicit construction verifies that the proposed depths are realizable, rather than relying solely on an inequality.''','Phd_CE_1405_Q3')

q('a_asym','Two true upper bounds but one tight class',r'Let $f(n)=n\log n+n^{3/4}$. Which conjunction is correct?', [r'$f\in\Theta(n)$ and $f\in O(n\log n)$',r'$f\in\Theta(n\log n)$ and $f\in O(n^2)$',r'$f\in o(n\log n)$ and $f\in O(n^2)$',r'$f\in\Theta(n^2)$ and $f\in O(n\log n)$'],2,r'''Divide by $n\log n$: the ratio is $1+n^{-1/4}/\log n$, tending to one. Thus the tight order is $n\log n$.

That function is also bounded above by a constant times $n^2$ eventually. A larger upper bound can be true without being tight; the first and third alternatives misclassify the leading term, and the fourth asserts mutually incompatible tight orders.''','MS_CE_1405_Q58; Phd_CE_1405_Q1')
q('a_asym','A factor inside an exponential cannot be suppressed',r'Which statement is correct for $f(n)=2^{n^2+n}$ and $g(n)=2^{n^2}$?', [r'$f\in\Theta(g)$',r'$f\in o(g)$',r'$g\in o(f)$',r'$f/g=n$'],3,r'''Their ratio is $f/g=2^n$, which diverges. Therefore $g/f=2^{-n}$ tends to zero, so $g\in o(f)$.

An additive linear term in a quadratic exponent multiplies the final value by an unbounded exponential factor. It cannot be removed inside a tight bound. The final alternative treats exponentiation as if it were addition outside the exponential.''','Phd_CS_1404_Q71')
q('a_asym','Oscillation defeats a tight bound',r'$f(n)=n$ for even $n$ and $n^2$ for odd $n$. Which classification is correct?', [r'$f\in\Theta(n)$',r'$f\in\Theta(n^2)$',r'$f\in O(n^2)\cap\Omega(n)$ but neither listed tight class',r'$f\notin O(n^2)$'],3,r'''For every positive $n$, $n\le f(n)\le n^2$, so both one-sided bounds hold. Along odd inputs, $f(n)/n=n$ is unbounded, excluding $O(n)$ and hence $\Theta(n)$.

Along even inputs, $f(n)/n^2=1/n$ tends to zero, excluding $\Omega(n^2)$ and hence $\Theta(n^2)$. Bounds must hold uniformly after a threshold, not just on a favorable subsequence.''','Phd_CE_1405_Q2; MS_CE_1405_Q58','Hard')
q('a_asym','Cancellation before classifying a function',r'For positive integers $n$, simplify the growth of $f(n)=\sqrt{n^2+n}-n$.',[r'$\Theta(n)$',r'$\Theta(\sqrt n)$',r'$\Theta(1)$',r'$\Theta(1/n)$'],3,r'''Rationalize: $f(n)=n/(\sqrt{n^2+n}+n)=1/(\sqrt{1+1/n}+1)$. It tends to one half and is positive, so its tight order is constant.

Classifying the two large terms separately would miss their cancellation. The denominator and numerator after rationalization both have linear scale. A nonzero finite limiting value gives upper and lower positive constant bounds eventually.''','MS_CE_1405_Q58; Phd_CE_1405_Q2')
q('a_asym','Logarithmic change of variable',r'Which order belongs to $n^{1/\log_2 n}$ for $n>1$?', [r'$\Theta(n)$',r'$\Theta(\log n)$',r'$\Theta(1)$',r'$\Theta(1/\log n)$'],3,r'''Use $n=2^{\log_2 n}$. Raising to $1/\log_2 n$ yields exactly two, not merely an approximation.

The domain excludes $n=1$, where the exponent is undefined. Exponents depending on $n$ cannot be handled as fixed polynomial degrees. The two in the logarithm base determines the exact constant, while any fixed valid base would still produce constant order.''','MS_CE_1405_Q58; Phd_CS_1404_Q71')
q('a_asym','Independent parameters forbid a one-variable collapse',r'For integers $m,n\ge2$, $T(m,n)=m\log n+n$. Which uniform bound is tight?', [r'$\Theta(m\log n+n)$',r'$\Theta(n\log n)$',r'$\Theta(mn)$',r'$\Theta(m\log n)$'],1,r'''The first expression retains both independent contributions. Fixing $m=2$ and increasing $n$ makes the linear $n$ term dominate, refuting the last alternative.

Fixing $n=2$ and increasing $m$ makes the expression linear in $m$, while $n\log n$ stays constant, refuting the second. The product is an upper bound but not uniformly tight: with $m=2$, its ratio to the true cost is bounded, while with $m=n$ it is too large by roughly $n/\log n$. Neither parameter may be silently identified with the other.''','Phd_CE_1405_Q1; MS_CS_1405_Q113','Hard')
q('a_asym','The floor in an exponent',r'Compare $f(n)=2^{\lfloor\log_2 n\rfloor}$ to $n$. Which bounds hold for all positive $n$?', [r'$n/2<f(n)\le n$',r'$n\le f(n)<2n$',r'$f(n)=n$',r'$f(n)\le\log_2 n$'],1,r'''Let $k=\lfloor\log_2 n\rfloor$. Then $2^k\le n<2^{k+1}$. Rearranging the strict upper inequality gives $n/2<2^k$.

Thus the first bounds hold and imply $\Theta(n)$. Equality holds only at powers of two; the floor introduces an oscillating ratio between just above one half and one, not a change in the tight class. Testing $n=3$ eliminates the equality and reversed-bound choices.''','Phd_CE_1405_Q2; MS_CE_1405_Q58')
q('a_asym','A factorial comparison using logarithms',r'Which statement is correct as $n$ grows?', [r'$n!\in O(2^n)$',r'$2^n\in o(n!)$',r'$n!\in\Theta(n^n)$',r'$\log(n!)\in\Theta(n)$'],2,r'''The final half of the factorial's factors are each at least $n/2$. Thus $n!\ge(n/2)^{n/2}$, whose ratio to $2^n$ eventually diverges; hence $2^n=o(n!)$.

Stirling or elementary log-sum bounds give $\log(n!)=\Theta(n\log n)$, ruling out the last option. Also $n!/n^n$ tends to zero, since at least half the factors are at most $n/2$, giving a factor at most $2^{-n/2}$. Upper bounds alone do not establish a tight class.''','Phd_CS_1404_Q71; MS_CS_1405_Q120','Hard')

q('a_loop','Weak triples with one strict inequality',r'How many triples satisfy $1\le i\le j<k\le10$?', ['120','165','220','330'],2,r'''Fix $j$: there are $j$ choices for $i$ and $10-j$ for $k$. The sum is $\sum_{j=1}^{9}j(10-j)=10\cdot45-285=165$.

Equivalently, map the weak/strict triple to three strictly increasing positions in an eleven-element set, yielding $\binom{11}3$. Fully strict triples number 120; fully weak triples number 220. Read every equality permission separately.''','Phd_CS_1405_Q20')
q('a_loop','A divisibility-dependent inner bound',r'Count executions of the body of `for i=1..12: for j=1..12: if j mod i == 0: body`.', ['23','35','36','144'],2,r'''For a fixed $i$, the permitted $j$ values are its positive multiples up to twelve, numbering $\lfloor12/i\rfloor$. The counts are 12,6,4,3,2,2,1,1,1,1,1,1, totaling 35.

The condition does not remove loop tests: 144 pairs are inspected, but only 35 bodies execute. Distinguish tested index pairs from successful branches. An estimate such as $n\log n$ is insufficient when the question requests this exact finite count.''','Phd_CS_1405_Q20; MS_CS_1405_Q129')
q('a_loop','Geometric outer loop with growing work',r'Let $n=32$. Start $i=1$ and double it while $i\le n$; for each such $i$, execute a body $i$ times. What are the outer-iteration and body counts?', ['5 and 31.','6 and 63.','6 and 32.','32 and 63.'],2,r'''The outer states are 1,2,4,8,16,32, giving six iterations. The body count is their sum, $2^6-1=63$.

The endpoint is included, explaining why neither count stops at sixteen. A logarithmic outer loop does not imply logarithmic whole-program work when the inner work grows geometrically. The exact total is linear in $n$ on these power-of-two inputs.''','Phd_CS_1405_Q20; MS_CS_1405_Q130')
q('a_loop','A squaring update and an inclusive endpoint',r'Initialize $i=2$. While $i\le65536$, execute one body and replace $i$ by $i^2$. How many bodies execute?', ['4','5','8','16'],2,r'''The states satisfying the guard are 2,4,16,256,65536. The next square exceeds the bound, so there are five bodies.

The sequence is $i_k=2^{2^k}$, explaining the double-logarithmic general count. Replacing squaring by doubling would give a different loop. An exclusive guard would omit the last state and give four; the stated inclusive endpoint must be retained.''','Phd_CE_1405_Q2; MS_CE_1405_Q58')
q('a_loop','A branch-defined summation region',r'For $i=1,\ldots,8$, execute an inner body for each $j=1,\ldots,i$ except when $i+j$ is odd. How many bodies execute?', ['16','20','28','36'],2,r'''The kept $j$ values have the same parity as $i$. Their counts for successive $i$ are 1,1,2,2,3,3,4,4, totaling twenty.

The full triangular region has 36 pairs, but parity does not divide it into equal halves. The diagonal always has even sum and shifts the balance. Sixteen counts the opposite parity instead; thirty-six ignores the branch. Write the exact integer region before summing.''','MS_CS_1405_Q129; Phd_CS_1405_Q20')
q('a_loop','Guard tests and body executions',r'A nested loop has $i=1,\ldots,5$ and an inner C-style `for(j=1;j<=i;j++)`. Count inner-loop body executions and inner guard evaluations across the run.', ['15 and 20.','15 and 15.','20 and 25.','10 and 15.'],1,r'''The body count is $1+2+3+4+5=15$. Each invocation of the inner loop evaluates its guard once more than its body count, including the final failed test.

There are five inner invocations, so guard evaluations total $15+5=20$. Initialization and updates would add different costs if requested, but are not guard evaluations. Exact operation accounting requires naming the operation, not just giving a runtime class.''','Phd_CS_1405_Q20; Phd_CE_1405_Q16')
q('a_loop','Input order changes successful branches',r'A scan updates its running minimum whenever the next value is smaller. For array $[8,3,7,2,6,1,5,4]$, how many updates occur, and how many comparisons with the current minimum occur?', ['4 and 8.','4 and 4.','8 and 8.','3 and 7.'],1,r'''With an initial infinite minimum, the new record values are 8,3,2,1, so four assignments update it. Every one of the eight array elements is still compared with the current minimum.

Record updates are input-dependent, while the scan length is fixed. Initializing the minimum to the first array element and starting at the second would give three later updates and seven comparisons for a different implementation. The initialization convention is part of the count.''','Phd_CS_1404_Q72')
q('a_loop','A nonconstant body changes the exponent',r'An outer loop takes $i=1,\ldots,n$, an inner loop takes $j=1,\ldots,i$, and the body performs exactly $j$ unit operations. What is the tight total order?', [r'$\Theta(n)$',r'$\Theta(n^2)$',r'$\Theta(n^3)$',r'$\Theta(n^2\log n)$'],3,r'''For a fixed $i$, body work sums to $\sum_{j=1}^i j=i(i+1)/2$. Summing across $i$ gives $n(n+1)(n+2)/6$.

The cubic leading term proves the tight class. Counting only inner iterations would give a quadratic expression and implicitly treat each body as constant cost, contrary to the statement. Exact finite sums support both the numerical and asymptotic conclusions.''','Phd_CS_1405_Q20; Phd_CE_1405_Q16')

q('a_recurrence','An exact balanced recurrence',r'$T(1)=3$ and $T(n)=2T(n/2)+n$ for powers of two. What is $T(32)$?', ['160','192','256','96'],3,r'''At every internal level the total toll is 32. There are five such levels, totaling 160. Thirty-two leaves each cost three, totaling 96.

Thus $T(32)=256$. In general $T(n)=n\log_2 n+3n$. Ignoring leaf cost yields 160; inserting an extra level gives the wrong coefficient. The recurrence's base value is part of an exact answer.''','Phd_CE_1405_Q1; Phd_CE_1405_Q16')
q('a_recurrence','A polylog toll with one branch',r'For powers of two, $T(n)=T(n/2)+\log_2^3 n$ and $T(1)=1$. What is $T(16)$?', ['65','81','101','257'],3,r'''The tolls are $4^3,3^3,2^3,1^3$, totaling $64+27+8+1=100$. Add the base cost one to obtain 101.

For $n=2^m$, the exact expression is $1+\sum_{j=1}^m j^3=1+(m(m+1)/2)^2$, and the tight growth is $\Theta(\log^4 n)$. The root toll alone misses most of the cost.''','Phd_CE_1405_Q2')
q('a_recurrence','Change variables before applying the theorem',r'$T(n)=4T(\sqrt n)+\log n$ with a constant base region $n\le4$. Which order is tight?', [r'$\Theta(\log n)$',r'$\Theta(\log n\log\log n)$',r'$\Theta(\log^2 n)$',r'$\Theta(n)$'],3,r'''Set $m=\log_2 n$ and $S(m)=T(2^m)$. Then $S(m)=4S(m/2)+m$, whose branching exponent is two.

The linear toll is smaller than $m^2$ by a polynomial factor, so leaf cost dominates and $S(m)=\Theta(m^2)$. Transforming back gives $\Theta(\log^2 n)$. The bounded base region prevents a fixed-point issue in square-root reduction.''','MS_CE_1405_Q58','Hard')
q('a_recurrence','Subtract prefix equations with a multiplier',r'$a_0=1$ and $a_{n+1}=3\sum_{i=0}^n a_i$. What is $a_5$?', ['243','768','1024','729'],2,r'''The first value is $a_1=3$. For $n\ge1$, subtracting consecutive equations gives $a_{n+1}-a_n=3a_n$, hence $a_{n+1}=4a_n$.

Thus $a_5=3\cdot4^4=768$. Multiplying by three at each step ignores the cumulative prefix; applying $4^n$ immediately ignores the different first value. Derive the simplified recurrence's starting index before substituting a closed form.''','MS_CS_1405_Q130')
q('a_recurrence','Repeated-root initial conditions',r'$a_n=4a_{n-1}-4a_{n-2}$, $a_0=1$, and $a_1=6$. What is $a_4$?', ['64','80','144','160'],3,r'''The characteristic polynomial is $(r-2)^2$, so $a_n=(C+Dn)2^n$. The zero base gives $C=1$; the first base gives $2(1+D)=6$, hence $D=2$.

Therefore $a_4=(1+8)16=144$. The second independent solution $n2^n$ is required for a repeated root; using only $C2^n$ cannot fit both initial conditions. Direct iteration gives 1,6,20,56,144 as a check.''','MS_CS_1405_Q130; Phd_CS_1404_Q71')
q('a_recurrence','A decrementing recurrence has quadratic work',r'$T(n)=T(n-1)+2n-1$ with $T(0)=0$. What is the exact solution?', [r'$n$',r'$n^2$',r'$n(n+1)$',r'$2^n-1$'],2,r'''Unroll the one-child chain: $T(n)=\sum_{j=1}^n(2j-1)=n^2$. The induction step also follows from $(n-1)^2+2n-1=n^2$.

There are $n$ levels, but the toll is not constant, so a linear answer is insufficient. The sum of odd numbers differs from summing $2j$, which would give $n(n+1)$. No branching exists to produce exponential work.''','Phd_CS_1404_Q71; Phd_CE_1405_Q2')
q('a_recurrence','Unequal branches conserve input mass',r'$T(n)=T(n/4)+T(3n/4)+n^2$ with positive bounded base cost. Which order is tight?', [r'$\Theta(n)$',r'$\Theta(n\log n)$',r'$\Theta(n^2)$',r'$\Theta(n^2\log n)$'],3,r'''At one recursive expansion the squared input masses total $(1/4)^2+(3/4)^2=5/8$ times the parent's squared mass. Thus tolls across successive levels have a geometrically decaying upper bound with initial value $n^2$.

Their total is $O(n^2)$; the root toll alone gives $\Omega(n^2)$. Boundary rounding contributes lower-order effects under the usual bounded perturbation. Conservation of linear size does not make a quadratic toll critical.''','Phd_CE_1405_Q1','Hard')
q('a_recurrence','Memoization changes the counted recursion graph',r'Naive Fibonacci recursion uses two recursive calls for $F(n)$; memoization stores each $F(k)$ once. Assuming constant-cost integer additions, what are the naive and memoized work classes?', [r'$\Theta(n^2)$ and $\Theta(n)$',r'$\Theta(\phi^n)$ and $\Theta(n)$',r'$\Theta(2^n)$ and $\Theta(\log n)$',r'$\Theta(n)$ and $\Theta(n)$'],2,r'''Naive call counts follow a Fibonacci-type recurrence, giving $\Theta(\phi^n)$ with $\phi=(1+\sqrt5)/2$. The bound $O(2^n)$ is true but not the tight naive class.

Memoization computes each of $n+1$ states once and performs constant work per nonbase state, giving linear work under the stipulated arithmetic model. Bit-cost arithmetic would need a separate analysis because Fibonacci numbers grow in bit length. A call tree and a memoized state DAG count different objects.''','MS_CS_1405_Q130; Phd_CS_1404_Q71')

q('a_divide','Exact comparisons on a sorted input',r'Merge sort splits evenly and compares front elements until one child list is exhausted. On the already sorted array $[1,2,3,4,5,6,7,8]$, how many key comparisons occur?', ['7','12','16','17'],2,r'''Four size-two merges cost one each. Each size-four merge exhausts its two-element left child after two comparisons, adding four. The final merge exhausts its four-element left child after four comparisons.

Total comparisons are $4+4+4=12$. The general worst-case count seventeen for eight keys is not attained here. Seven counts only comparisons within one recursion path. The supplied input's relative ordering controls exhaustion.''','Phd_CE_1405_Q16')
q('a_divide','Equal values and strict cross inversions',r'Two sorted halves are $L=[1,3,3]$ and $R=[2,3,4]$. How many strict cross inversions $(l,r)$ satisfy $l>r$?', ['2','4','5','6'],1,r'''Only the right-side value two has larger left-side values, namely the two occurrences of three. This gives two ordered index pairs.

Equal values at three are not strict inversions. During merging, use a tie rule consistent with the strict comparison so equal cross values are not incorrectly counted. Values are repeated records, so both larger occurrences contribute separately.''','Phd_CE_1405_Q16; Phd_CE_1405_Q9')
q('a_divide','A sufficient summary for maximum subarray',r'A segment summary stores total sum, maximum nonempty prefix, maximum nonempty suffix, and maximum nonempty subarray. Left summary is $(-2,3,1,5)$ and right is $(4,6,4,6)$. What is the combined maximum subarray sum?', ['5','6','7','9'],3,r'''The optimum is either inside the left child, inside the right child, or crossing the boundary. The crossing value is left suffix plus right prefix, $1+6=7$.

Compare 5,6,7 to obtain seven. Totals are not the correct crossing endpoints; adding child optima could join nonadjacent pieces. The nonempty contract matters for all-negative inputs, where zero cannot be supplied as an automatic candidate.''','Phd_CE_1405_Q9; Phd_CE_1405_Q16')
q('a_divide','Karatsuba reconstruction with exact numbers',r'Use base ten blocks to multiply 23 by 47. Karatsuba computes $z_2=2\cdot4$, $z_0=3\cdot7$, and $z_1=(2+3)(4+7)-z_2-z_0$. What are $z_1$ and the reconstructed product?', ['26 and 1081.','55 and 1371.','29 and 1111.','26 and 821.'],1,r'''The shared multiplication is $5\cdot11=55$. Subtracting eight and twenty-one gives $z_1=26$.

Reconstruct $z_2\cdot100+z_1\cdot10+z_0=800+260+21=1081$. The fifty-five option forgets to remove diagonal terms; the final alternative neglects the cross term. Internal blocks may exceed the base and are not required to be single digits.''','Phd_CE_1405_Q1; MS_CE_1405_Q58')
q('a_divide','A changed combine cost changes the recurrence',r'A divide-and-conquer algorithm makes three half-sized recursive calls. Its combine work is $\Theta(n^2)$. Which class is tight?', [r'$\Theta(n^{\log_2 3})$',r'$\Theta(n^2)$',r'$\Theta(n^2\log n)$',r'$\Theta(3^n)$'],2,r'''The branching exponent is $\log_2 3<2$. The quadratic toll is polynomially larger, and regularity holds since $3(n/2)^2=(3/4)n^2$.

Therefore the root-dominated Master case gives quadratic total work. The first class would apply to a sufficiently smaller combine cost, not the specified one. The logarithmic factor occurs at a critical exponent match, which is absent here.''','Phd_CE_1405_Q1; MS_CE_1405_Q58')
q('a_divide','Padding for linear convolution',r'Polynomials have coefficient counts five and four. What is the smallest power-of-two transform length sufficient to recover their complete linear convolution without wraparound?', ['4','8','16','32'],2,r'''The product has at most $5+4-1=8$ coefficients. A length-eight transform represents all of them without circular aliasing and is already a power of two.

Length four would identify distinct output positions modulo four and lose information; sixteen and thirty-two are sufficient but not minimal. Coefficient count is degree plus one, so adding degrees without restoring the final one leads to an endpoint error.''','Phd_CE_1405_Q16; MS_CS_1405_Q125')
q('a_divide','What a sampling guarantee actually ensures',r'A pivot is the median of nine sampled distinct elements from an array of length $n$. In the worst case, what lower bound on the numbers strictly below and above it is guaranteed solely by the sample?', ['At least four on each side.','At least $n/2$ on each side.','At least nine on each side.','No element on either side is guaranteed.'],1,r'''The sample contains four smaller and four larger elements, so these elements certify the two lower bounds in the whole array.

All remaining elements could lie on the same side, so the sample alone does not guarantee a balanced full-array partition. The pivot itself is excluded from both strict sides. Partition-time and sample-sorting cost are separate from the rank guarantee.''','MS_CE_1405_Q59')
q('a_divide','Sorting every level versus sorting once',r'A closest-pair implementation has $T(n)=2T(n/2)+\Theta(n\log n)$ because it re-sorts at each recursion node. Another maintains sorted child information and combines in $\Theta(n)$. What are their respective classes?', [r'$\Theta(n\log^2 n)$ and $\Theta(n\log n)$',r'$\Theta(n^2)$ and $\Theta(n)$',r'$\Theta(n\log n)$ and $\Theta(n)$',r'$\Theta(n\log n)$ for both'],1,r'''At depth $j$, the re-sorting version spends total $\Theta(n(\log n-j))$. Summing over logarithmically many levels gives $\Theta(n\log^2 n)$.

The maintained-order version spends $\Theta(n)$ per level and has $\Theta(\log n)$ levels, giving $\Theta(n\log n)$. A linear combine is not a linear whole algorithm. The child summary contract determines whether sorting work must be repeated.''','Phd_CE_1405_Q1; Phd_CE_1405_Q16','Hard')

(BASE/'original-algorithms.json').write_text(json.dumps(questions,indent=2)+'\n')
print('Authored',len(questions),'original algorithm questions.')
