"""Original medium/hard examination analogues; authored, never attributed to an exam."""
import json
from pathlib import Path
BASE=Path(__file__).resolve().parent
questions=[]
def q(topic,title,stem,options,answer,solution,pattern,difficulty='Medium'):
 questions.append(dict(topic=topic,title=title,stem=stem,options=options,answer=answer,solution=solution,pattern=pattern,difficulty=difficulty,kind='Original examination analogue'))

q('d_logic','A formula with conditional and parity constraints',r'How many assignments to $p,q,r,s$ satisfy $(p\Leftrightarrow q)\land(p\Rightarrow r)\land(r\oplus s)$?', ['2','3','4','6'],2,r'''First force $q=p$. If $p=0$, the implication permits either value of $r$; each determines exactly one $s$ through XOR, giving two assignments. If $p=1$, then $r=1$ and $s=0$, giving one more. The total is three.

Count cases after propagating equalities. Four treats $r$ as free even when $p=1$; six fails to enforce all dependent choices; two omits the valid all-one antecedent case. This is a model count, not a count of distinct syntactic formulas.''','MS_CS_1405_Q99; Phd_CS_1405_Q22')
q('d_logic','The exact CNF index set',r'The true rows of $F(p,q,r)$ have indices 1, 2, 4, and 7, with $p$ the most significant bit. Which canonical product of maxterms represents $F$?', [r'$\prod M(1,2,4,7)$',r'$\prod M(0,3,5,6)$',r'$\sum m(0,3,5,6)$',r'$\prod M(0,2,4,6)$'],2,r'''The full index set is zero through seven. Complement the given true indices to obtain false indices 0, 3, 5, and 6. Canonical CNF contains a maxterm for each of those false rows, so the second option is correct.

The first product represents the complemented function. The third is a sum rather than the requested product and also selects the complemented truth set. The final product corresponds to a fixed least-significant-bit condition. As a cross-check, the stated true rows have an odd number of true bits, so this function is three-input parity.''','MS_CS_1405_Q99; Phd_CS_1405_Q15')
q('d_logic','A cyclic successor and two universal formulas',r'The domain is $\{0,1,2,3\}$, $f(x)=x+1\pmod4$, and $R(x,y)$ means $y=f(x)$. Assess (I) $\forall x\exists y(R(x,y)\land R(y,x))$ and (II) $\forall x\exists y\exists z(R(x,y)\land R(y,z)\land R(z,f(x)))$.',['Only I.','Only II.','Both.','Neither.'],4,r'''A successor edge forces $y=x+1$ modulo four. For I, the reverse edge would force $x=x+2$ modulo four, which is impossible. Thus I is false for every $x$.

For II the first two edges force $y=x+1$ and $z=x+2$. The final edge would require $f(x)=x+3$ modulo four, but $f(x)=x+1$. Again no witness exists. Both formulas fail. The tempting existential choice is not free after the first relational constraint fixes it.''','MS_CS_1405_Q95; MS_CS_1405_Q97')
q('d_logic','Translate exactly one without an accidental injection',r'Every researcher reviews exactly one paper, but several researchers may review the same paper. Which formula states this, with predicates $R(x),P(y),V(x,y)$?', [r'$\forall x(R(x)\Rightarrow\exists y(P(y)\land V(x,y)\land\forall z((P(z)\land V(x,z))\Rightarrow z=y)))$',r'$\forall y(P(y)\Rightarrow\exists!x(R(x)\land V(x,y)))$',r'$\forall x\exists y(R(x)\land P(y)\land V(x,y))$',r'$\exists y(P(y)\land\forall x(R(x)\Rightarrow V(x,y)))$'],1,r'''The first formula imposes existence for each researcher and makes every other reviewed paper equal to the chosen paper. It does not compare choices made by different researchers, so shared targets are allowed.

The second reverses the source and target roles and requires exactly one researcher per paper. The third asserts that every domain object is a researcher and supplies no uniqueness clause. The fourth requires one common paper for all researchers, which the statement does not require. Here $\exists!$ in option two abbreviates existence and uniqueness, rather than a new primitive proof rule.''','Phd_CS_1405_Q13; Phd_CS_1405_Q14','Hard')
q('d_logic','An implication under an empty restriction',r'A nonempty model has no objects satisfying $A(x)$. Which pair of truth values belongs to $\forall x(A(x)\Rightarrow B(x))$ and $\exists x(A(x)\land B(x))$?', ['True, true.','True, false.','False, true.','False, false.'],2,r'''For every domain object the implication has a false antecedent, hence is true. Its universal closure is true. The existential conjunction requires an $A$ witness, but none exists, so it is false.

The nonempty domain does not ensure that a restricted predicate has a witness. Options one and three invent an $A$ object; options three and four also confuse vacuous truth with failure of universal quantification. This distinction is essential when converting an English subject restriction into a formula.''','Phd_CS_1405_Q14; Phd_CS_1405_Q16')
q('d_logic','Entailment with a missing converse',r'Premises are $p\Rightarrow q$, $r\Rightarrow q$, and $\neg q\lor s$. Which statement must follow?', [r'$s\Rightarrow p$',r'$p\Rightarrow s$',r'$q\Rightarrow p$',r'$\neg s\Rightarrow r$'],2,r'''Rewrite the third premise as $q\Rightarrow s$. Compose it with $p\Rightarrow q$ to obtain $p\Rightarrow s$.

For the first and third options, take $p=0,q=1,r=0,s=1$; the premises hold, but both conclusions fail. For the final option, all four variables false satisfy the premises while $\neg s\Rightarrow r$ is false. A conditional chain supports its forward implication and contrapositive, not its converse.''','Phd_CS_1405_Q16; Phd_CS_1405_Q22')
q('d_logic','Count assignments with precisely two true implications',r'Among $p\Rightarrow q$, $q\Rightarrow r$, and $r\Rightarrow p$, exactly two must be true. How many assignments to $p,q,r$ meet this requirement?', ['2','3','4','6'],4,r'''The all-zero and all-one assignments make all three implications true. Each of the other six binary cycles contains exactly one transition from 1 to 0, so exactly one implication is false and two are true.

For example, 110 makes the middle implication false and the other two true. Three would count only the rows with a single true variable; four would miscount the mixed rows. The cyclic structure limits the number of false transitions, which is more informative than evaluating each implication independently.''','MS_CS_1405_Q99; Phd_CS_1405_Q22','Hard')
q('d_logic','Negate a uniqueness specification',r'Let $S(x,y)$ mean that $y$ is a solution for input $x$. What is the negation of “every input has exactly one solution”?',['Every input has no solution.','Some input has no solution or at least two distinct solutions.','Some input has exactly two solutions.','Every input has at least two solutions.'],2,r'''Write the original as $\forall x\exists y(S(x,y)\land\forall z(S(x,z)\Rightarrow z=y))$. Negating the outer universal supplies an input at which existence or uniqueness fails.

Existence fails when no $y$ satisfies $S$. Uniqueness fails when two distinct solutions both satisfy $S$. Their disjunction is the complete negation. Exactly two excludes three or infinitely many solutions, while the universal alternatives change the quantifier and are too strong.''','Phd_CS_1405_Q13; Phd_CS_1405_Q14')

q('d_sets','Recover exactly-two and outside counts',r'Three subsets of a 60-element universe have sizes 25, 22, and 20. Their pairwise intersections have sizes 10, 9, and 8; the triple intersection has size 4. What are the numbers in exactly two sets and in none?', ['15 and 16.','27 and 16.','15 and 20.','19 and 16.'],1,r'''The sum of pair intersections is 27, but each triple member contributes three. Exactly-two membership is $27-3\cdot4=15$.

Inclusion-exclusion gives union size $25+22+20-10-9-8+4=44$, so sixteen elements are outside. These data are feasible: exclusive pair cells have sizes 6, 5, and 4; the single-only cells are 10, 8, and 7. The distractors either retain triple overcounts or subtract the triple correction with the wrong sign.''','Phd_CS_1405_Q21','Hard')
q('d_sets','Two nested strict inclusions',r'If $|U|=5$, how many ordered pairs $(A,B)$ satisfy $\varnothing\ne A\subsetneq B\subsetneq U$?', ['150','120','180','90'],1,r'''Partition $U$ into the three nonempty labeled regions $A$, $B\setminus A$, and $U\setminus B$. Every element chooses a region, so start with $3^5$ assignments.

Exclude assignments missing at least one region: $3^5-3\cdot2^5+3=150$. The intersections of two missing-region events leave one region, yielding the final three. There is no division by $3!$: the regions have different roles. The other counts lose a strictness condition or confuse labeled regions with unlabeled groups.''','MS_CS_1405_Q120; MS_CS_1405_Q124','Hard')
q('d_sets','Power-set difference is not a power set',r'$|A|=4$, $|B|=3$, and $|A\cap B|=2$. What is $|\mathcal P(A)\setminus\mathcal P(B)|$?', ['4','8','12','16'],3,r'''A set belongs to both power sets exactly when it is a subset of $A\cap B$. Hence the intersection of the two power sets has size $2^2=4$.

There are $2^4=16$ subsets of $A$, so the requested difference has size $16-4=12$. It is not $\mathcal P(A\setminus B)$: a subset using both shared and exclusive elements is still counted in the requested difference. Four counts only subsets of the exclusive region; sixteen ignores shared subsets.''','MS_CS_1405_Q101; MS_CS_1405_Q37')
q('d_sets','A symmetric-difference cancellation',r'$|A|=11$, $|B|=9$, and $|A\triangle B|=12$. Find $|A\cap B|$ and $|(A\triangle B)\triangle B|$.',['4 and 11.','8 and 11.','4 and 12.','4 and 9.'],1,r'''Use $|A\triangle B|=|A|+|B|-2|A\cap B|$, yielding an intersection size of four.

Membership in symmetric difference is XOR. Each membership bit of $B$ is toggled twice in $(A\triangle B)\triangle B$, so the resulting set is $A$ and has size eleven. The two quantities ask different questions: one is recovered numerically, the other follows from algebraic cancellation.''','MS_CS_1405_Q37; MS_CS_1405_Q99')
q('d_sets','An equation between unions imposes one missing region',r'Fix $B\subseteq U$ with $|U|=8$ and $|B|=3$. How many $A\subseteq U$ satisfy $A\cup B=U$ and $A\cap B\ne\varnothing$?', ['7','31','56','63'],1,r'''Every one of the five elements outside $B$ must lie in $A$. The only free choices are which elements of $B$ to include. At least one must be chosen, giving $2^3-1=7$.

These seven choices each determine a unique whole set $A$; the fixed outside region supplies no multiplicative factor. Thirty-one incorrectly makes the outside region variable, while the other values introduce independent choices that the union equation already forbids.''','MS_CS_1405_Q37; Phd_CS_1405_Q21')
q('d_sets','Transitivity versus downward closure of all subsets',r'For $S=\{\varnothing,\{\varnothing\},\{\varnothing,\{\varnothing\}\}\}$, which is correct?', [r'$\bigcup S=S$ and $S=\mathcal P(S)$.',r'$\bigcup S\subsetneq S$ and $S\subsetneq\mathcal P(S)$.',r'$\bigcup S\not\subseteq S$.',r'$S\not\subseteq\mathcal P(S)$.'],2,r'''The union is $\{\varnothing,\{\varnothing\}\}$, containing two elements versus the family's three, so it is a proper subset.

Each member of $S$ is a subset of $S$, establishing $S\subseteq\mathcal P(S)$. It is proper because the power set has eight elements. Transitivity does not make a set equal to its power set and does not mean it contains every subset of itself. The other alternatives confuse those distinct claims.''','MS_CS_1405_Q101; Phd_CS_1405_Q18')
q('d_sets','Count a prescribed Venn-region population',r'$U$ has six distinct elements. Count ordered pairs $(A,B)$ with $|A\setminus B|=2$, $|B\setminus A|=1$, and $|A\cap B|=1$.',['360','180','720','90'],2,r'''The four labeled membership regions have sizes 2, 1, 1, and 2, the last being the complement of the union. Assign six distinct elements to these regions by a multinomial count: $6!/(2!1!1!2!)=180$.

There is no further division for exchanging the two size-two regions: one is $A$-only and the other is outside both. Likewise, exchanging $A$ and $B$ changes the specified sizes. The distractors omit or add a symmetry factor without checking the labels.''','MS_CS_1405_Q120; Phd_CS_1405_Q21')
q('d_sets','A Cartesian-product identity with a boundary case',r'Which identity holds for every set $C$, including $C=\varnothing$?', [r'$(A\setminus B)\times C=(A\times C)\setminus(B\times C)$',r'$(A\times C)\setminus(B\times C)=(A\setminus B)\times(C\setminus C)$',r'$A\times C=B\times C\Rightarrow A=B$',r'$(A\cup B)\times C=(A\times C)\cap(B\times C)$'],1,r'''A pair lies in the left side exactly when its first coordinate lies in $A$ but not $B$ and its second coordinate lies in $C$. This is precisely membership in the right-side product difference.

The second proposed identity always has empty right side. The third fails when $C$ is empty and $A\ne B$. The fourth would require union on the right, not intersection. Product cancellation requires a nonempty common factor, whereas the distributive difference identity needs no such assumption.''','MS_CS_1405_Q37; MS_CS_1405_Q40')

q('d_proof','A congruence implication and its converse',r'For integers $n$, assess (I) $6\mid n\Rightarrow6\mid n^2$ and (II) $6\mid n^2\Rightarrow6\mid n$.',['Only I.','Only II.','Both.','Neither.'],3,r'''I follows by writing $n=6k$. For II, divisibility of $n^2$ by two implies $n$ is even, and divisibility by three implies $n$ is divisible by three, since two and three are prime. Their coprimality gives $6\mid n$.

The corresponding converse for a non-squarefree divisor can fail: $4\mid2^2$ but $4\nmid2$. The correct proof therefore uses the prime structure of six, rather than asserting that squaring preserves every divisibility equivalence.''','MS_CS_1405_Q38; MS_CS_1405_Q125')
q('d_proof','An existence-and-uniqueness parameter',r'For which real $a$ does $(a^2-1)x=a-1$ have exactly one real solution?', [r'$a\ne1$',r'$a\ne-1$',r'$a\notin\{-1,1\}$','Every real $a$.'],3,r'''A linear equation has a unique solution exactly when its coefficient $a^2-1$ is nonzero. Thus both $a=1$ and $a=-1$ are excluded.

At $a=1$, the equation is $0=0$, giving every real number as a solution. At $a=-1$, it is $0=-2$, giving none. For all remaining parameters, division gives $x=(a-1)/((a-1)(a+1))=1/(a+1)$. Cancelling $a-1$ before classifying $a=1$ loses the infinite-solution case.''','MS_CS_1405_Q40; Phd_CS_1405_Q13')
q('d_proof','Which counterexample refutes a universal claim?',r'The claim is “for all positive integers $a,b$, if $a+b$ is even then $a$ and $b$ are both even.” Which pair is a valid counterexample?', ['(2,4).','(1,2).','(3,5).','(0,2).'],3,r'''A counterexample must satisfy the domain, make the antecedent true, and make the consequent false. The pair $(3,5)$ consists of positive integers with even sum eight, but neither is even.

The first pair satisfies the conclusion and is not a counterexample. The second has odd sum and therefore does not activate the implication. Zero violates the stated positive domain in the last pair. This three-part check avoids a common mistake: refuting the conclusion where the theorem makes no assertion.''','MS_CS_1405_Q95; Phd_CS_1405_Q16')
q('d_proof','Two forms of evidence',r'A formula $P(n)$ has been verified for $1\le n\le10^6$. Which additional statement proves it for all positive integers?', ['It also holds at $10^6+1$.',r'For every $n\ge1$, $P(n)\Rightarrow P(n+1)$.','A random integer above $10^6$ satisfies it.','No counterexample was found.'],2,r'''The verified range contains the base case $P(1)$. A universal valid successor implication propagates truth from that base through all positive integers, completing induction.

One more check still leaves infinitely many untested inputs. A random success and absence of a found counterexample are evidence, not a proof of a universal theorem. The second statement must itself be proved; assuming it merely repeats the missing obligation.''','MS_CS_1405_Q98; Phd_CE_1405_Q3')
q('d_proof','Witnesses depend on quantifier order',r'Over the integers, compare (I) $\forall x\exists y(y>x)$ and (II) $\exists y\forall x(y>x)$.',['Both are true.','Only I is true.','Only II is true.','Both are false.'],2,r'''For I, choose $y=x+1$ after the input $x$ is known. It is an integer and larger than $x$.

For II, any proposed fixed witness $y$ is defeated by choosing $x=y$. The strict inequality then fails. A witness depending on the universal variable cannot be used before that variable has been chosen. The difference is dependency, not the number of symbols or the domain's nonemptiness.''','Phd_CS_1405_Q14; MS_CS_1405_Q95')
q('d_proof','An inequality and its equality condition',r'For positive $x,y$ with $x+y=10$, which statement is correct?', [r'$xy\ge25$, equality iff $x=y$.',r'$xy\le25$, equality iff $x=y=5$.',r'$xy<25$ for every such pair.',r'$xy=25$ for every such pair.'],2,r'''The nonnegative square $(x-y)^2=(x+y)^2-4xy$ implies $100-4xy\ge0$, so $xy\le25$.

Equality is equivalent to $x-y=0$ and, under the sum constraint, occurs only at $x=y=5$. The first alternative reverses the inequality; the strict alternative excludes the attainable equality case; the final alternative confuses a maximum with a constant value. A complete extremum proof includes both the bound and an attaining witness.''','Phd_CS_1405_Q21; Phd_CS_1404_Q32')
q('d_proof','What follows from inconsistency?',r'In classical propositional logic, premises include $p$ and $\neg p$. Which statement is correct?', ['Only contradictions can be derived.','An arbitrary formula $q$ is derivable, and the premise set has no satisfying assignment.','Every formula becomes a tautology.','A satisfying assignment exists with $p$ both true and false.'],2,r'''From $p$ infer $p\lor q$. Combine it with $\neg p$ by disjunctive syllogism to obtain $q$. Semantically, no assignment satisfies both premises, so entailment from this premise set is vacuous.

Derivability under inconsistent assumptions does not make $q$ a tautology under no assumptions. Classical assignments give each variable one truth value, not both. Keeping the premises attached to a conclusion distinguishes explosion from a change in the logic's definition of validity.''','Phd_CS_1405_Q16; MS_CS_1405_Q98')
q('d_proof','A false cancellation in a proof',r'A proof starts with $x=y\ne0$, obtains $(x-y)(x+y)=y(x-y)$, cancels $x-y$, and concludes $2=1$. Where does it fail?',['The factorization is false.',r'The assumption $x=y\ne0$ is impossible.','It divides by zero.','It uses integers instead of reals.'],3,r'''The starting assumption is possible and the displayed identity is true: both sides equal zero when $x=y$. The cancelled factor $x-y$ is exactly zero.

Cancellation in a field is justified only for a nonzero common factor. Since that hypothesis fails, the purported equation $x+y=y$ does not follow. The nonzero condition on $x$ does not make $x-y$ nonzero. Checking the precise divisor, rather than any nearby quantity, exposes the invalid step.''','MS_CS_1405_Q40; Phd_CS_1405_Q19')

q('d_induction','A weighted sum with a boundary',r'For $n\ge1$, determine $S_n=\sum_{k=1}^n k2^{k-1}$.',[r'$(n-1)2^n+1$',r'$n2^n$',r'$(n+1)2^n-1$',r'$2^n-1$'],1,r'''At $n=1$ the proposed formula gives one, matching the sum. If it holds at $n$, then $S_{n+1}=S_n+(n+1)2^n=((n-1)+(n+1))2^n+1=n2^{n+1}+1$, exactly the formula with $n+1$.

The other choices already fail small base values or the increment identity. A correct closed form must pass both tests. The additive one is not negligible in an exact formula, even though it can be ignored in an asymptotic order.''','MS_CS_1405_Q121; MS_CS_1405_Q130')
q('d_induction','A residue-class induction requires multiple bases',r'A proposed proof uses $P(n)\Rightarrow P(n+4)$ for all $n\ge3$. Which minimal consecutive base set proves $P(n)$ for every $n\ge3$?', ['3 only.','3,4.','3,4,5.','3,4,5,6.'],4,r'''A step of four never changes the residue class modulo four. The four bases 3 through 6 represent all four classes among integers at least three.

For each target, repeatedly subtract four until reaching exactly one of those bases. Fewer bases leave at least one progression unreachable. This is a dependency argument, not a requirement to test arbitrary extra values; the number of bases comes from the step's residue classes.''','MS_CS_1405_Q130; MS_CS_1405_Q125')
q('d_induction','A divisibility induction with a factored step',r'Which statement is correct for every integer $n\ge0$?', [r'$8\mid5^{2n}-1$',r'$8\mid5^n-1$',r'$16\mid5^{2n}-1$',r'$3\mid5^{2n}+1$'],1,r'''For the first statement, the base $n=0$ is zero. In the step, $5^{2(n+1)}-1=25(5^{2n}-1)+24$. Both terms are divisible by eight if the hypothesis holds.

The second fails at $n=1$, since four is not divisible by eight. The third fails there too, since 24 is not divisible by sixteen. The fourth fails at $n=0$, where the value is two. Factoring the successor expression connects it directly to the induction hypothesis.''','MS_CS_1405_Q125; MS_CS_1405_Q38')
q('d_induction','The exact prefix-doubling exception',r'$u_0=2$ and $u_{n+1}=\sum_{i=0}^n u_i$. What is $u_8$?', ['128','256','512','1024'],2,r'''Compute $u_1=2$. For $n\ge1$, subtract consecutive prefix equations to obtain $u_{n+1}=2u_n$. Induction then gives $u_n=2^n$ for $n\ge1$, so $u_8=256$.

The formula is not intended at zero, where $u_0=2$ rather than one. Using the initial value as if doubling began immediately gives 512; failing to count one doubling gives 128. A simplified recurrence often starts later than the original one.''','MS_CS_1405_Q130')
q('d_induction','An inequality starts later than expected',r'What is the smallest positive $N$ such that $2^n>n^2$ holds for every integer $n\ge N$?', ['3','4','5','6'],3,r'''The claim fails at three and is equality at four. At five it holds: 32 is greater than 25.

For $n\ge5$, $2n^2-(n+1)^2=n^2-2n-1>0$. Hence $2^n>n^2$ implies $2^{n+1}>2n^2>(n+1)^2$. Induction proves the entire tail from five, and failure at four establishes minimality. Merely observing rapid exponential growth does not identify the earliest universal threshold.''','Phd_CE_1405_Q2; MS_CS_1405_Q130','Hard')
q('d_induction','A full branching-tree formula',r'A finite rooted tree has exactly three children at every internal node. If it has 17 internal nodes, how many leaves does it have?', ['34','35','36','51'],2,r'''Let $I$ and $L$ count internal nodes and leaves. Counting edges by parents gives $3I$; counting edges in a finite tree gives $I+L-1$. Equating yields $L=2I+1=35$.

Alternatively, replacing a leaf by an internal node with three leaves increases $I$ by one and $L$ by two, preserving the formula from the one-leaf base tree. The finite and full-branching assumptions are essential; arbitrary missing children would change the identity.''','Phd_CE_1405_Q3')
q('d_induction','Induction on a two-step recurrence',r'$a_0=2$, $a_1=3$, and $a_n=2a_{n-1}-a_{n-2}$ for $n\ge2$. Which formula holds?', [r'$a_n=n+2$',r'$a_n=2^n+2$',r'$a_n=3n$',r'$a_n=n^2+2$'],1,r'''Check both bases: $n+2$ gives two and three. If the formulas hold at consecutive predecessors, the recurrence yields $2((n-1)+2)-((n-2)+2)=n+2$.

This proof needs two predecessor hypotheses, not just one base value. The exponential and quadratic candidates fail the recurrence even where an initial value happens to agree; the linear candidate $3n$ fails the zero base. A recurrence of order two requires sufficient initial data to select a unique solution.''','MS_CS_1405_Q130; Phd_CS_1404_Q71')
q('d_induction','A weighted binomial identity',r'Evaluate $\sum_{k=2}^{8}\binom8k\binom k2$.',['896','1792','3584','28'],2,r'''Choose two marked elements from the eight first, then an arbitrary subset of the other six. This counts the same objects as choosing a $k$-element subset and marking two within it.

The result is $\binom82 2^6=28\cdot64=1792$. The identity can also be proved algebraically from $\binom8k\binom k2=\binom82\binom6{k-2}$. Twenty-eight omits all optional elements; doubling or halving the result inserts a nonexistent symmetry or constraint.''','MS_CS_1405_Q121','Hard')

q('d_relations','A relation defined by a modular difference',r'On $\mathbb Z$, $xRy$ iff $x-y\pmod6$ lies in $\{0,2,4\}$. How many equivalence classes are there?', ['2','3','6','It is not an equivalence.'],1,r'''The permitted residues are the multiples of two modulo six. A difference is permitted exactly when it is even. The relation therefore identifies integers of the same parity.

Zero belongs to the permitted set, negatives preserve it, and sums preserve it, proving equivalence. There are exactly two classes, even and odd. Counting the three allowed differences as three classes confuses a subgroup's size with its index.''','MS_CS_1405_Q38; Phd_CS_1405_Q23')
q('d_relations','Transitive closure is not union',r'$R_1$ has classes $\{1,2\},\{3\},\{4\}$ and $R_2$ has classes $\{1\},\{2,3\},\{4\}$. How many ordered pairs are in the smallest equivalence containing $R_1\cup R_2$?', ['8','10','12','16'],2,r'''The edges joining 1 to 2 and 2 to 3 force all of 1,2,3 into one class by transitivity. Element four remains alone.

The generated relation therefore has $3^2+1^2=10$ ordered pairs. The original union has only eight, missing both 1-to-3 directions. Sixteen would join the isolated fourth element without justification. Equivalence closure merges connected blocks, not all blocks.''','Phd_CS_1405_Q23')
q('d_relations','Count relations with two compatible properties',r'On a four-element set, how many relations are simultaneously symmetric and antisymmetric, without any reflexivity requirement?', ['1','4','16','64'],3,r'''If an off-diagonal pair occurs, symmetry requires its reverse, while antisymmetry then forces equal endpoints, a contradiction. Thus only diagonal pairs may occur.

Each of the four diagonal pairs can independently be present or absent, yielding $2^4=16$. Reflexivity would force all four and leave only one relation, but it is explicitly not required. The other counts confuse optional diagonal pairs with mandatory ones or permit forbidden off-diagonal pairs.''','Phd_CS_1405_Q23; MS_CS_1405_Q38')
q('d_relations','Composition direction and transitivity',r'On $\{1,2,3,4\}$ let $R=\{(1,2),(2,3),(3,4)\}$. What is $R^2\cup R^3$, where $xR^2z$ means $\exists y(xRy\land yRz)$?', [r'$\{(1,3),(2,4),(1,4)\}$',r'$\{(3,1),(4,2),(4,1)\}$',r'$R$',r'$\{(1,4)\}$'],1,r'''Two-edge paths yield $(1,3)$ and $(2,4)$. The only three-edge path yields $(1,4)$. Their union is the first set.

The reverse pairs would require reversing the directed edges; the original relation consists of length-one paths and is not what was requested. Keeping only $(1,4)$ omits all length-two paths. Stating the composition convention prevents notation differences from changing the answer.''','Phd_CS_1405_Q23; Phd_CS_1405_Q13')
q('d_relations','Count an equivalence with prescribed block sizes',r'A labeled six-element set is partitioned into two classes of size two and two classes of size one. How many distinct equivalence relations have this shape?', ['45','90','180','15'],1,r'''Choose the two singleton elements in $\binom62=15$ ways. The remaining four elements can be partitioned into two unordered pairs in three ways. Thus the count is 45.

Equivalently $6!/((2!)^2 2!2!)=45$, with separate divisors for ordering inside pairs and exchanging equal-size blocks. Ninety labels one pair block; 180 also labels singleton blocks. Fifteen omits pairing the four remaining elements.''','MS_CS_1405_Q120; Phd_CS_1405_Q23','Hard')
q('d_relations','Minimal does not mean least',r'Order divisors of 12 by divisibility. Within the induced subposet $\{2,3,4,6\}$, which statement is correct?',['2 is least.','There are two minimal elements and no least element.','6 is greatest.','There are four minimal elements.'],2,r'''Elements 2 and 3 have no smaller elements in this induced set, so both are minimal. Neither divides the other, so no element is below all elements and there is no least element.

The maximal elements are 4 and 6; neither divides the other, so six is not greatest. Four is not minimal because two lies below it, and six is not minimal because two and three lie below it. Ambient elements such as one cannot be used when the question restricts to an induced subposet.''','Phd_CS_1405_Q19; MS_CS_1405_Q38')
q('d_relations','A difference condition that fails one property',r'On $\mathbb R$, define $xRy$ iff $x-y\in\{0,1,-1\}$. Which classification is correct?',['Reflexive, symmetric, and transitive.','Reflexive and symmetric, but not transitive.','Symmetric and transitive, but not reflexive.','Only reflexive.'],2,r'''Zero difference proves reflexivity, and the allowed set is closed under negation, proving symmetry. It is not closed under addition: 1 and 1 are allowed, but 2 is not.

Concretely, $2R1$ and $1R0$ hold while $2R0$ does not. Thus transitivity fails. The first alternative assumes symmetry and reflexivity imply equivalence; the others discard properties directly established by the permitted differences.''','MS_CS_1405_Q38')
q('d_relations','A quotient map and relation inclusion',r'$R,S$ are equivalences on finite $A$, with $R\subseteq S$. What can be asserted about the numbers of classes?', [r'$|A/R|\le|A/S|$',r'$|A/R|\ge|A/S|$','They are always equal.','They are unrelated.'],2,r'''Each $R$ class lies within exactly one $S$ class. Sending an $R$ class to that containing $S$ class defines a surjective map of quotient sets.

Finite surjectivity implies at least as many source classes as target classes. Strict inequality occurs when equality classes are merged into one block; equality occurs when $R=S$. Adding related pairs coarsens a partition rather than creating more blocks.''','MS_CS_1405_Q40; Phd_CS_1405_Q23')

q('d_functions','Exactly three output values',r'How many functions from a five-element set to a four-element set have an image of size exactly three?', ['600','360','240','1024'],1,r'''Choose the three used outputs in four ways. For that chosen labeled codomain, count onto maps: $3^5-3\cdot2^5+3=150$.

Multiply to get 600. Selecting three outputs and then using unrestricted maps would include functions omitting one of the selected values. The factor $3!$ must not be added after inclusion-exclusion because the outputs were labeled from the start.''','MS_CS_1405_Q124; MS_CS_1405_Q40','Hard')
q('d_functions','Number of sections of a fixed map',r'A surjection has three fibers of sizes 2, 3, and 4. How many right inverses $g$ satisfy $f\circ g=\operatorname{id}$?', ['9','24','12','36'],2,r'''A right inverse chooses one representative from each fiber. These are independent choices, giving $2\cdot3\cdot4=24$.

Summing the fiber sizes counts domain elements rather than representative combinations. A section must choose one in every fiber, and cannot choose a value outside the matching fiber. Distinguish right inverses of this fixed map from the number of possible surjections with those fiber sizes.''','MS_CS_1405_Q40; MS_CS_1405_Q124')
q('d_functions','Weakly increasing with fixed endpoints',r'Count weakly increasing functions $f:\{1,\ldots,6\}\to\{1,2,3,4\}$ with $f(1)=1$ and $f(6)=4$.',['15','35','56','70'],2,r'''The middle four values form a weakly increasing sequence drawn from four possibilities. The fixed endpoints impose no additional restriction on those interior values.

Encode their four multiplicities as nonnegative integers summing to four. Stars and bars gives $\binom73=35$. Counting all six values would ignore the fixed endpoints, while treating them as strictly increasing would prohibit repetition that the statement permits.''','MS_CS_1405_Q122')
q('d_functions','An idempotent map with two fixed points',r'On a five-element set, how many functions have exactly two fixed points and satisfy $f\circ f=f$?', ['40','80','160','20'],2,r'''For an idempotent map, every image point is fixed: if $y=f(x)$ then $f(y)=f(f(x))=f(x)=y$. Conversely, sending every nonfixed point into the fixed set makes the map idempotent.

Choose the two fixed points in ten ways; each of the other three points chooses one of them, giving $2^3$ maps. The total is eighty. No other fixed point can appear because all three remaining points are sent into the chosen set.''','MS_CS_1405_Q40; Phd_CS_1404_Q31','Hard')
q('d_functions','Which composition implication survives?',r'$f:A\to B$ and $g:B\to C$ are arbitrary maps. Which implication is always correct?',[r'If $g\circ f$ is injective, $g$ is injective.',r'If $g\circ f$ is surjective, $f$ is surjective.',r'If $g\circ f$ is bijective, $f$ is injective and $g$ is surjective.',r'If $f$ is surjective, $g\circ f$ is injective.'],3,r'''Injectivity of the composite implies injectivity of $f$: equal $f$ outputs would produce equal composite outputs. Surjectivity of the composite implies surjectivity of $g$: every target is reached through some intermediate $f$ output. Hence the third claim holds.

The composite tests $g$ only on $f(A)$, so $g$ may fail injectivity elsewhere. Likewise, $f$ may miss elements that $g$ does not need to cover $C$. Surjectivity of $f$ alone gives no injectivity guarantee for either stage.''','MS_CS_1405_Q40; Phd_CS_1405_Q19')
q('d_functions','Count functions with a prescribed fiber',r'$A$ has seven elements, $B$ has three labeled elements, and one distinguished $b\in B$ must have exactly three preimages. How many functions satisfy this?', ['560','280','840','2187'],1,r'''Choose the three preimages of $b$ in $\binom73=35$ ways. Each of the other four inputs must avoid $b$ and has two output choices, giving $2^4=16$.

The count is $35\cdot16=560$. There is no onto requirement for the other outputs. Dividing by two would incorrectly identify their labels; using $3^4$ would permit extra preimages of the distinguished value.''','MS_CS_1405_Q124; Phd_CS_1405_Q13')
q('d_functions','Preimages and images behave differently',r'For any $f:A\to B$ and subsets $X,Y\subseteq A$, which statement always holds?', [r'$f(X\cap Y)=f(X)\cap f(Y)$',r'$f(X\setminus Y)=f(X)\setminus f(Y)$',r'$f(X\cup Y)=f(X)\cup f(Y)$',r'$f(X)=f(Y)\Rightarrow X=Y$'],3,r'''An output is in the image of a union exactly when some preimage lies in at least one input set, proving preservation of union.

For all other alternatives, use a constant map on two distinct inputs and take the two distinct singleton subsets. Their image intersection is nonempty although their input intersection is empty; their image difference is empty although the image of their input difference is not; and their equal images do not force equal inputs. Extra injectivity would fix these failures, but was not assumed.''','MS_CS_1405_Q40; MS_CS_1405_Q37')
q('d_functions','Count involutions by their two-cycles',r'How many bijections on a five-element set satisfy $f^2=\operatorname{id}$ and have exactly one fixed point?', ['15','30','45','60'],1,r'''Choose the sole fixed point in five ways. The other four points must be paired into two transpositions, since every cycle of an involution has length one or two.

There are $4!/(2^2 2!)=3$ unordered pairings, giving fifteen maps. Ordered pairs and an ordering of the transpositions describe the same bijection and must not be counted again. A five-cycle is a bijection but not an involution.''','MS_CS_1405_Q120; MS_CS_1405_Q40','Hard')

q('d_invariants','A modular move obstruction',r'A state is $(x,y)\in\mathbb Z^2$. Allowed moves add either $(2,1)$ or $(-1,2)$, or subtract either vector. Starting at $(0,0)$, which target is impossible?', ['(5,0).','(0,5).','(2,1).','(1,0).'],4,r'''The residue $x-2y\pmod5$ is unchanged: the two move increments are zero and negative five. The initial residue is zero, while $(1,0)$ has residue one, proving impossibility.

The other targets are explicitly reachable: twice $(2,1)$ minus $(-1,2)$ gives $(5,0)$; once $(2,1)$ plus twice $(-1,2)$ gives $(0,5)$; the third is a permitted move. An invariant proves impossibility, but reachability of the other choices needs a construction.''','MS_CS_1405_Q125; Phd_CE_1405_Q3','Hard')
q('d_invariants','An invariant that is true but insufficient',r'A sum loop processes $a_0,\ldots,a_{n-1}$ with initialization $s=0,k=0$ and update `s+=a[k]; k++`. Which invariant directly proves that the final sum is correct?', [r'$s\ge0$',r'$s=\sum_{i=0}^{k-1}a_i$ and $0\le k\le n$',r'$s=\sum_{i=0}^{n-1}a_i$ at every iteration',r'$k<n$'],2,r'''At initialization the empty prefix sum is zero. The update adds the next element and advances the boundary by one, preserving the prefix equation and bounds.

At exit, $k=n$, so the prefix is the entire array. Nonnegativity is not even valid for arbitrary signed data and would not identify the sum. The third equation is generally false before completion; the final strict inequality fails at exit. A useful invariant connects progress state to the desired postcondition.''','MS_CS_1393_Q167; Phd_CE_1405_Q9')
q('d_invariants','Binary powering: exact multiplication count',r'Binary exponentiation starts with $r=1,b=a,e=13$. Each iteration multiplies $r$ by $b$ if $e$ is odd, then squares $b$ unconditionally and replaces $e$ by $\lfloor e/2\rfloor$. Count all multiplications, including the final square.', ['6','7','8','13'],2,r'''The exponent states are 13, 6, 3, and 1, so four iterations square the base. The odd states 13, 3, and 1 each multiply the accumulator, adding three.

Seven multiplications are performed. The preserved identity is $rb^e=a^{13}$; odd iterations move one factor to the accumulator before halving. Omitting the final unused square would give six for a different implementation. Counts depend on the exact code, not just the logarithmic complexity.''','Phd_CS_1405_Q20; MS_CS_1393_Q167')
q('d_invariants','A lexicographic termination bound',r'For integer state $(i,j)$ with $0\le i\le m$ and $0\le j\le n$, a loop decreases $j$ by one when $j>0$; when $j=0$ and $i>0$, it decreases $i$ and sets $j=n$. Which integer ranking decreases by one at every step?', [r'$i+j$',r'$i(n+1)+j$',r'$ij$',r'$i-j$'],2,r'''Within a row, decrementing $j$ decreases $i(n+1)+j$ by one. At a row boundary, the new value is $(i-1)(n+1)+n=i(n+1)-1$, again one less.

The ranking is nonnegative and zero only at $(0,0)$, so it proves termination and an exact number of steps equal to its initial value. The simple sum can increase on reset; the product is zero along whole boundaries; $i-j$ increases when $j$ decreases.''','MS_CS_1393_Q167; Phd_CS_1405_Q20','Hard')
q('d_invariants','Parity in a coefficient problem',r'A polynomial is built by multiplying ten factors, each contributing either $x^3$ or $x^{-1}$. Which exponent cannot occur?', ['-10','-2','6','8'],4,r'''If $j$ factors contribute $x^3$, the exponent is $3j-(10-j)=4j-10$. Thus every exponent is congruent to two modulo four and $0\le j\le10$.

The first three values correspond to $j=0,2,4$. Eight would require $j=18/4$, not an integer. Both congruence and range are required; a congruent exponent outside the achievable interval would also be impossible.''','MS_CS_1405_Q125')
q('d_invariants','A conservation law for a full tree',r'A finite full binary tree has 19 leaves. What pair gives its number of internal nodes and total edges?', ['18 and 36.','19 and 38.','18 and 37.','20 and 38.'],1,r'''For a full binary tree, $L=I+1$. Hence $I=18$ and the total node count is 37. A finite tree has one fewer edge than nodes, giving 36.

Equivalently, each of the eighteen internal nodes supplies two child edges. This double check verifies both coordinates. The distractors confuse leaves with internal nodes or count edges as all nodes. Fullness is necessary for the internal-node formula.''','Phd_CE_1405_Q3')
q('d_invariants','Safety without inductiveness',r'A program starts at $x=0$ and repeatedly adds two, never using other moves. Which statement is true of property $x\ne1$?',['It is false at initialization.','It is inductive over all states satisfying it.','It is true on all reachable states, but not inductive over all states satisfying it.','It proves termination.'],3,r'''Every reachable value is a nonnegative even integer, so no reachable value is one. However the property also permits state $x=-1$, whose next state is one. Therefore the property alone is not closed under the transition over its full state set.

The stronger invariant “$x$ is even and nonnegative” excludes the spurious predecessor. Safety can be true without the proposed assertion being inductive. The program can run forever, so a safety condition does not prove termination.''','Phd_CE_1405_Q3; MS_CS_1393_Q167')
q('d_invariants','A recursive permutation preserves a sum but changes order',r'A recursive routine splits distinct values around a pivot and returns greater-block, pivot, smaller-block. Which specification is sufficient to prove descending sorting?', ['The output sum equals the input sum.','The output length equals input length.','The output is a permutation, each child is descending, and both cross-block inequalities hold.','The pivot occurs somewhere in the output.'],3,r'''Permutation preservation ensures no value is lost or duplicated. Child sortedness handles within-block neighbors, and cross-block inequalities place all greater values before the pivot and all smaller values after it. Together they prove the complete ordering and preservation contract.

Length and sum alone allow many incorrect multisets; retaining a pivot says nothing about the remaining order. A recursive proof must retain enough information about each child to justify the combine step.''','Phd_CE_1405_Q9; Phd_CE_1405_Q16')

q('d_number','A congruence with several solutions',r'How many integers $x$ with $0\le x<84$ satisfy $12x\equiv18\pmod{30}$?', ['5','6','17','0'],3,r'''The gcd of twelve and thirty is six, and it divides eighteen. Divide the congruence by six to obtain $2x\equiv3\pmod5$, hence $x\equiv4\pmod5$.

The solutions in the stated interval are 4 through 79 in steps of five, numbering $(79-4)/5+1=16$? The interval also includes 84? It excludes 84, so there are sixteen solutions. The correct answer must therefore be 16, not a count of residues modulo thirty. The authored options below are corrected to include 16.''','MS_CS_1405_Q125; MS_CS_1405_Q129','Hard')
questions[-1]['options']=['5','6','16','0']
questions[-1]['solution']=r'''The gcd is six and divides eighteen. Divide by six: $2x\equiv3\pmod5$. Invert two modulo five to obtain $x\equiv4\pmod5$.

Solutions in the interval are $4,9,\ldots,79$, giving sixteen. Eighty-four is the next solution, but the upper bound is strict. Six counts the solution residues modulo thirty, not occurrences in this longer interval; zero ignores compatibility. Reduce the modulus and then count actual integers in the requested range.'''
q('d_number','Compatible noncoprime remainders',r'Solve $x\equiv5\pmod8$ and $x\equiv1\pmod6$. What is the least positive solution and period?', ['13 and 24.','5 and 48.','13 and 48.','No solution.'],1,r'''Compatibility requires the residues to agree modulo $\gcd(8,6)=2$; both are odd, so they do. Set $x=5+8k$. Reduction modulo six gives $2k\equiv2\pmod6$, hence $k\equiv1\pmod3$.

Thus $x=13+24t$. The period is the lcm, twenty-four, not the product forty-eight. The first residue five fails the second congruence. Compatibility precedes inversion because the original moduli are not coprime.''','MS_CS_1405_Q38; MS_CS_1405_Q125')
q('d_number','Exponent reduction with a nonunit',r'Find $6^{100}\pmod{15}$.',['1','6','0','9'],2,r'''Six is idempotent modulo fifteen: $6^2=36\equiv6$. Multiplying by six therefore preserves the same residue for every positive exponent, giving six.

Euler's unit theorem cannot be applied because $\gcd(6,15)=3$. Reducing the exponent to zero modulo the totient and returning one would be invalid. The same result follows from CRT: the power is zero modulo three and one modulo five, whose combined residue is six.''','MS_CS_1405_Q38; MS_CS_1405_Q125')
q('d_number','Cancel a factor and change the modulus',r'$8x\equiv8y\pmod{20}$ is equivalent to which condition?', [r'$x\equiv y\pmod{20}$',r'$x\equiv y\pmod5$',r'$x\equiv y\pmod{10}$',r'$x=y$'],2,r'''The original equation means $20\mid8(x-y)$. Divide both the coefficient and modulus by their gcd four: $5\mid2(x-y)$.

Two is invertible modulo five, so this is equivalent to $5\mid x-y$. The original coefficient is not invertible modulo twenty, so retaining the original modulus after cancellation would be too strong. For example, $x-y=5$ satisfies the original but not congruence modulo ten or twenty.''','MS_CS_1405_Q38; MS_CS_1405_Q125')
q('d_number','A factorial valuation',r'What is the largest $k$ such that $12^k$ divides $30!$?', ['7','13','14','26'],2,r'''The two-adic valuation is $15+7+3+1=26$. The three-adic valuation is $10+3+1=14$.

Since $12^k=2^{2k}3^k$, both $2k\le26$ and $k\le14$ must hold. The limiting value is thirteen. Fourteen would exhaust enough threes but demand twenty-eight twos; twenty-six counts individual twos rather than powers of twelve.''','MS_CS_1405_Q125; MS_CS_1405_Q129','Hard')
q('d_number','Count modular units and a required residue',r'Among $0\le x<30$, how many are invertible modulo thirty and satisfy $x\equiv1\pmod3$?', ['2','4','8','10'],2,r'''The candidates congruent to one modulo three are $1,4,7,10,13,16,19,22,25,28$. Invertibility also requires avoiding factors two and five.

Exactly 1, 7, 13, and 19 survive, giving four. Eight is the total number of units without the residue restriction; ten counts all candidates without checking invertibility. CRT also gives the result: choose the unique nonzero class modulo two, the fixed class modulo three, and one of four nonzero classes modulo five.''','MS_CS_1405_Q38; MS_CS_1405_Q125')
q('d_number','Integer equation with a bounded variable',r'How many integer pairs satisfy $6x+9y=45$ with $0\le x\le10$?', ['3','4','5','0'],2,r'''Divide by three to obtain $2x+3y=15$. Modulo three, $2x=0$, so $x$ is a multiple of three.

The permitted values are 0, 3, 6, and 9, each determining exactly one integer $y=5-2x/3$. Negative $y$ is allowed because only $x$ is bounded. Imposing nonnegativity on both variables would answer a different question and produce too few pairs.''','MS_CS_1405_Q129; MS_CS_1405_Q125')
q('d_number','A modular difference subgroup',r'On $\mathbb Z_{12}$, $xRy$ iff $x-y$ is divisible by four modulo twelve. What pair gives the size of every class and the number of classes?', ['3 and 4.','4 and 3.','3 and 3.','12 and 1.'],1,r'''The allowed difference subgroup is $\{0,4,8\}$ and has size three. Each equivalence class is one coset of that subgroup, so has three elements.

There are $12/3=4$ classes. The residue classes modulo four display them explicitly. Swapping subgroup size and index gives the second distractor; the remaining options fail the partition size check: class size times class count must equal twelve.''','MS_CS_1405_Q38; Phd_CS_1405_Q23')

(BASE/'original-discrete.json').write_text(json.dumps(questions,indent=2)+'\n')
print('Authored',len(questions),'original discrete questions.')
