 function formula(m){return '<math xmlns="http://www.w3.org/1998/Math/MathML"><mrow>'+Object.entries(m).map(([k,v])=>`<mtext>${esc(k)}</mtext><mo>=</mo><mn>${v}</mn><mspace width="1em"/>`).join('')+'</mrow></math>';}
 function picture(f){
  const N=Math.max(1,...f.rows.map(r=>r.cells.length)),width=Math.max(860,194+70*N);let height=110+112*f.rows.length,s='';
  const cell=(r,x,y,id,final=false)=>`<g data-entity="${esc(id)}"><rect data-box="" x="${x}" y="${y}" width="60" height="64" rx="12" fill="${final?'#d3ebe5':'#eff4f5'}" stroke="#9fb8bd"/><text data-contained="" class="sort-key" x="${x+30}" y="${y+27}" text-anchor="middle">${r?esc(r.key):'hole'}</text><text data-contained="" class="sort-id" x="${x+30}" y="${y+49}" text-anchor="middle">${r?esc(r.id):''}</text></g>`;
  if(f.layout==='heap'){
   height=540;const a=f.rows[0].cells,positions=[];
   for(let i=0;i<f.heapSize;i++){const d=Math.floor(Math.log2(i+1)),k=i-(2**d-1);positions.push([width*(k+.5)/2**d,95+90*d]);}
   for(let i=1;i<positions.length;i++){const [x,y]=positions[i],[p,q]=positions[Math.floor((i-1)/2)],dx=x-p,dy=y-q,len=Math.hypot(dx,dy);s+=`<path data-edge="" d="M ${p+dx*29/len} ${q+dy*29/len} L ${x-dx*29/len} ${y-dy*29/len}" stroke="#819ea9" fill="none"/>`;}
   positions.forEach(([x,y],i)=>{s+=`<g data-entity="${a[i].id}"><circle data-box="" cx="${x}" cy="${y}" r="29" fill="#eff4f5" stroke="#829fa7"/><text data-contained="" class="sort-key" x="${x}" y="${y-2}" text-anchor="middle">${a[i].key}</text><text data-contained="" class="sort-id" x="${x}" y="${y+17}" text-anchor="middle">${i}: ${a[i].id}</text></g>`;});a.forEach((r,i)=>s+=cell(r,156+70*i,449,'array-'+r.id,i>=f.heapSize));
  }else f.rows.forEach((row,j)=>{const y=74+j*112;s+=`<text class="sort-label" x="24" y="${y+31}">${esc(row.name)}</text>`;row.cells.forEach((r,i)=>s+=cell(r,156+i*70,y,(row.role?row.role+'-':'')+(r?r.id:'hole-'+j+'-'+i)));});
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(f.caption)}"><text class="sort-meta" x="24" y="28">${esc(Object.entries(f.metrics).map(([k,v])=>k+' '+v).join(' · '))}</text>${s}</svg>`;
 }
 function evaluate(kind,p){
  let A=p.values.map((key,i)=>({key,id:String.fromCharCode(97+i)})),C=0,W=0,S=0;const frames=[],extra={},copy=x=>structuredClone(x),row=(name,cells,role='')=>({name,cells,role});
  const add=(caption,rows=[row('Array',A)],data={})=>{const f={caption,rows:copy(rows),metrics:{comparisons:C,writes:W,swaps:S},...data};f.formulaHtml=formula(f.metrics);f.svg=picture(f);frames.push(f);};
  const swap=(i,j)=>{if(i!==j){[A[i],A[j]]=[A[j],A[i]];W+=2;S++;}};const n=A.length;add('Initial labeled records; only keys are compared.');
  if(kind==='selection'){for(let i=0;i<n-1;i++){let m=i;for(let j=i+1;j<n;j++){C++;if(A[j].key<A[m].key)m=j;add(`Scan ${j}; current minimum index ${m}.`);}swap(i,m);add(`Final prefix grows through ${i}.`);}}
  else if(kind==='insertion'){let shifts=0;for(let i=1;i<n;i++){const x=A[i];A[i]=null;let j=i,rows=()=>[row('Array',A),row('Held key',[x])];add(`Hold ${x.id}; hole at ${j}.`,rows());while(j>0){C++;add(`Compare predecessor ${j-1} with held key.`,rows());if(A[j-1].key<=x.key)break;A[j]=A[j-1];A[j-1]=null;j--;W++;shifts++;add(`Shift predecessor; hole moves to ${j}.`,rows());}A[j]=x;W++;add(`Insert ${x.id} without crossing equal keys.`);}extra.shifts=shifts;extra.gaps=[1];}
  else if(kind==='bubble'){let passes=0;for(let end=n-1;end>0;end--){let moved=false;passes++;for(let j=0;j<end;j++){C++;if(A[j].key>A[j+1].key){swap(j,j+1);moved=true;}add(`Pass ${passes}; adjacent pair ${j}, ${j+1}; final suffix starts after ${end}.`);}if(!moved)break;}extra.passes=passes;}
  else if(kind==='merge'){const merges=[];function rec(lo,hi){if(hi-lo<=1)return;const mid=Math.floor((lo+hi)/2);rec(lo,mid);rec(mid,hi);const L=copy(A.slice(lo,mid)),R=copy(A.slice(mid,hi)),out=[];let i=0,j=0,c0=C;const rows=()=>[row('Left run',L,'left'),row('Right run',R,'right'),row('Output',out.concat(Array(hi-lo-out.length).fill(null)),'output')];while(i<L.length&&j<R.length){C++;out.push(L[i].key<=R[j].key?L[i++]:R[j++]);W++;add('Compare heads and emit one; equality chooses left.',rows());}while(i<L.length){out.push(L[i++]);W++;add('Copy left remainder without key comparisons.',rows());}while(j<R.length){out.push(R[j++]);W++;add('Copy right remainder without key comparisons.',rows());}A.splice(lo,hi-lo,...out);W+=hi-lo;merges.push({lo,mid,hi,comparisons:C-c0});add(`Merged range [${lo},${hi}).`);}rec(0,n);extra.merges=merges;}
  else if(kind==='quick'||kind==='three'){const partitions=[];let depth=0;function rec(lo,hi,level){depth=Math.max(depth,level);if(hi-lo<=1)return;if(kind==='quick'){const pivot=A[hi-1].key;let b=lo;for(let j=lo;j<hi-1;j++){C++;if(A[j].key<pivot){swap(b,j);b++;}add(`Lomuto: less [${lo},${b}), scanned through ${j}, pivot ${pivot} at ${hi-1}.`);}swap(b,hi-1);partitions.push({lo,hi,pivot:b});add(`Pivot is final at ${b}; exclude it from both children.`);rec(lo,b,level+1);rec(b+1,hi,level+1);}else{const pivot=A[lo].key;let lt=lo,i=lo+1,gt=hi;while(i<gt){C++;if(A[i].key<pivot){swap(lt,i);lt++;i++;}else if(A[i].key>pivot){gt--;swap(i,gt);}else i++;add(`Less [${lo},${lt}); equal [${lt},${i}); unknown [${i},${gt}); greater [${gt},${hi}); pivot ${pivot}.`);}partitions.push({lo,hi,equal:[lt,gt]});rec(lo,lt,level+1);rec(gt,hi,level+1);}}rec(0,n,0);extra.partitions=partitions;extra.recursionDepth=depth;}
  else if(kind==='heap'){const snap=(s,end)=>add(s,[row('Array',A)],{layout:'heap',heapSize:end});function sink(i,end){while(2*i+1<end){let j=2*i+1;if(j+1<end){C++;if(A[j+1].key>A[j].key)j++;}C++;snap(`Choose larger child ${j}; compare with parent ${i}.`,end);if(A[i].key>=A[j].key)break;swap(i,j);snap('Exchange parent and larger child.',end);i=j;}}for(let i=Math.floor(n/2)-1;i>=0;i--)sink(i,n);extra.buildComparisons=C;for(let end=n-1;end>0;end--){swap(0,end);snap(`Maximum leaves the live heap; live size ${end}.`,end);sink(0,end);}}
  else if(kind==='counting'){const low=p.low??Math.min(...p.values),K=p.K??Math.max(...p.values)-low+1,counts=Array(K).fill(0);for(const r of A)counts[r.key-low]++;for(let k=1;k<K;k++)counts[k]+=counts[k-1];const cumulative=[...counts],out=Array(n).fill(null);for(const r of [...A].reverse()){const k=r.key-low;counts[k]--;out[counts[k]]=r;W++;add(`Scatter ${r.id} to ${counts[k]}; right-to-left preserves ties.`,[row('Input',A,'reference'),row('Ends',counts.map((key,i)=>({key,id:String(i+low)})),'counts'),row('Output',out)]);}A=out;Object.assign(extra,{cumulative,K,low});}
  else if(kind==='radix'||kind==='bucket'){const low=kind==='radix'?(p.low??Math.min(...p.values)):0,B=kind==='bucket'?(p.buckets??5):(p.base??10);let maximum=Math.max(...p.values.map(x=>x-low)),d=1,exp=1;while(maximum>=B){maximum=Math.floor(maximum/B);d++;}if(kind==='bucket')d=1;if(p.digits)d=p.digits;const passes=[];for(let t=0;t<d;t++){const bins=Array.from({length:B},()=>[]),ref=copy(A),rows=()=>[row('Input reference',ref,'reference'),...bins.map((bs,k)=>row('Bucket '+k,bs))];for(const r of A){const k=kind==='radix'?Math.floor((r.key-low)/exp)%B:Math.floor(r.key*B/100);bins[k].push(r);W++;add(`Pass ${t+1}: append ${r.id} to FIFO bucket ${k}.`,rows());}if(kind==='bucket')for(let k=0;k<B;k++){const bs=bins[k];for(let i=1;i<bs.length;i++){let j=i;while(j>0){C++;if(bs[j-1].key<=bs[j].key)break;[bs[j-1],bs[j]]=[bs[j],bs[j-1]];j--;S++;W+=2;add(`Insertion repair inside bucket ${k}.`,rows());}}}A=bins.flat();W+=n;passes.push(A.map(r=>r.key));add(`Concatenate buckets after pass ${t+1}.`);exp*=B;}Object.assign(extra,{passes,base:B,low});}
  else throw Error('Unknown algorithm.');add('Final sorted records. Counters belong to this exact implementation.');return {id:'editable',title:'Computed '+kind+' laboratory',kind,params:p,frames,result:{keys:A.map(r=>r.key),ids:A.map(r=>r.id),comparisons:C,writes:W,swaps:S,...extra}};
 }
 function editable(model){return `<section class="sort-model" data-sort-model="editable" tabindex="0"><h3>${esc(model.title)}</h3><p class="sort-invariant">Labeled records retain their original identity. Each caption identifies the current invariant and operation. All counts exclude loop-bound tests.</p><div class="sort-stage"></div><p class="sort-caption" aria-live="polite"></p><div class="sort-controls"><button type="button" data-reset>Restart</button><button type="button" data-prev>Previous</button><button type="button" data-play>Play</button><button type="button" data-next>Next</button><label>Speed<select data-speed><option value="2400">Slow</option><option value="1600" selected>Normal</option><option value="950">Fast</option></select></label><label>Checkpoint<input type="range" data-seek min="0" max="${model.frames.length-1}" value="0"></label></div><p data-progress></p><div class="formula-block sort-formula"></div><div class="sort-print-trace"></div></section>`;}
 function read(form){const kind=form.kind.value,values=form.values.value.split(',').map(s=>{if(!/^-?\d+$/.test(s.trim()))throw Error('Every key must be an integer.');const x=Number(s);if(!Number.isSafeInteger(x)||Math.abs(x)>999)throw Error('Keys must be from −999 to 999.');return x;});if(values.length<1||values.length>10)throw Error('Use 1–10 records.');const base=Number(form.base.value);if(!Number.isInteger(base)||base<2||base>10)throw Error('Base / bucket count must be 2–10.');if(kind==='counting'&&Math.max(...values)-Math.min(...values)+1>24)throw Error('Counting interval may contain at most 24 keys.');if(kind==='bucket'&&values.some(x=>x<0||x>99))throw Error('Bucket keys must be from 0 to 99.');return evaluate(kind,{values,base,buckets:base});}
 function fitInline(){for(const m of document.querySelectorAll('.lesson p math')){m.classList.remove('sort-wide-math');if(m.getBoundingClientRect().width>m.parentElement.clientWidth-1)m.classList.add('sort-wide-math');}}
 window.addEventListener('resize',fitInline);
 async function init(){try{const response=await fetch('a_sort-models.json');if(!response.ok)throw Error('Could not load checkpoint data.');const data=await response.json(),models=new Map(data.models.map(x=>[x.id,x]));for(const el of document.querySelectorAll('[data-sort-model]'))player(el,models.get(el.dataset.sortModel));const form=document.getElementById('sort-form'),output=document.getElementById('sort-output'),error=document.getElementById('sort-lab-error');let active;form.onsubmit=ev=>{ev.preventDefault();try{const model=read(form);if(active){active.pause();players.splice(players.indexOf(active),1);}output.innerHTML=editable(model);active=player(output.firstElementChild,model);output.dataset.result=JSON.stringify(model.result);error.textContent='';}catch(e){error.textContent=e.message;}};form.requestSubmit();window.SortingChapter={players,evaluate,read};fitInline();document.documentElement.dataset.sortLoaded='true';}catch(e){document.documentElement.dataset.sortLoaded='error';const p=document.createElement('p');p.textContent='Interactive models unavailable: '+e.message;document.querySelector('.hero').append(p);}}
 window.addEventListener('beforeprint',()=>{for(const p of players){p.pause();p.print();}});window.addEventListener('afterprint',()=>{for(const p of players)p.clearPrint();});document.fonts.ready.then(init);
})();
