 function picture(f){
  const N=Math.max(1,...f.rows.map(r=>r.cells.length)),width=Math.max(900,194+70*N);let height=160+140*f.rows.length,s='';
  const cell=(r,x,y,id,final=false,slot=null)=>`<g data-entity="${esc(id)}"><rect data-box="" x="${x}" y="${y}" width="60" height="64" rx="10" fill="${final?'#d5ede7':'#eef4f8'}" stroke="#7b98aa"/><text data-contained="" class="sort-key" x="${x+30}" y="${y+27}" text-anchor="middle">${r?esc(r.key):'hole'}</text>${r?`<text data-contained="" class="sort-id" x="${x+30}" y="${y+49}" text-anchor="middle">${esc(r.id)}</text>`:''}</g>`+(slot!==null?`<text class="sort-index" x="${x+30}" y="${y+88}" text-anchor="middle">${esc(slot)}</text>`:'');
  if(f.layout==='heap'){
   height=590;const a=f.rows[0].cells,positions=[];
   for(let i=0;i<f.heapSize;i++){const d=Math.floor(Math.log2(i+1)),k=i-(2**d-1);positions.push([width*(k+.5)/2**d,110+90*d]);}
   for(let i=1;i<positions.length;i++){const [x,y]=positions[i],[p,q]=positions[Math.floor((i-1)/2)],dx=x-p,dy=y-q,len=Math.hypot(dx,dy);s+=`<path data-edge="" d="M ${p+dx*29/len} ${q+dy*29/len} L ${x-dx*29/len} ${y-dy*29/len}" stroke="#678ba3" stroke-width="1.8" fill="none"/>`;}
   positions.forEach(([x,y],i)=>{s+=`<g data-entity="${a[i].id}"><circle data-box="" cx="${x}" cy="${y}" r="29" fill="#eef4f8" stroke="#7b98aa"/><text data-contained="" class="sort-key" x="${x}" y="${y-2}" text-anchor="middle">${a[i].key}</text><text data-contained="" class="sort-id" x="${x}" y="${y+17}" text-anchor="middle">${a[i].id}</text></g><text class="sort-index" x="${x}" y="${y+46}" text-anchor="middle">slot ${i}</text>`;});a.forEach((r,i)=>s+=cell(r,156+70*i,465,'array-'+r.id,i>=f.heapSize,'slot '+i));
  }else if(f.layout==='buckets'){
   f.rows[0].cells.forEach((r,i)=>s+=cell(r,156+i*70,84,'reference-'+r.id,false,'slot '+i));s+='<text class="sort-label" x="24" y="115">Current input</text><text class="sort-pointer" x="24" y="194">FIFO arrival order: top to bottom</text>';
   const cols=Math.min(5,f.rows.length-1),cardW=(width-48-(cols-1)*16)/cols;let top=205;
   for(let start=1;start<f.rows.length;start+=cols){const chunk=f.rows.slice(start,start+cols),depth=Math.max(1,...chunk.map(r=>r.cells.length)),cardH=70+74*depth;chunk.forEach((r,c)=>{const x=24+c*(cardW+16);s+=`<rect data-card="" x="${x}" y="${top}" width="${cardW}" height="${cardH}" rx="12" fill="${start-1+c===f.bucketIndex?'#fff0c9':'#f7fafc'}" stroke="#a8becb"/><text class="sort-label" x="${x+14}" y="${top+29}">${esc(r.name)}</text>`;r.cells.forEach((v,j)=>s+=cell(v,x+(cardW-60)/2,top+49+j*74,v.id));if(!r.cells.length)s+=`<text class="sort-id" x="${x+14}" y="${top+77}">empty</text>`;});top+=cardH+22;}height=top+20;
  }else{
   f.rows.forEach((row,j)=>{const y=116+140*j;s+=`<text class="sort-label" x="24" y="${y+31}">${esc(row.name)}</text>`;row.cells.forEach((r,i)=>s+=cell(r,156+i*70,y,(row.role?row.role+'-':'')+(r?r.id:'hole-'+j+'-'+i),false,'slot '+i));});
   if(f.transfer){const t=f.transfer,ri=t.row==='left'?0:1,r=f.rows[ri].cells[t.index],x1=216+70*t.index,y1=148+140*ri,x2=186+70*t.dest,y2=396,c=222+140*ri,lane=width-18;const d=ri===0?`M ${x1} ${y1} L ${x1+5} ${y1} L ${x1+5} ${c} L ${lane} ${c} L ${lane} ${y2-18} L ${x2} ${y2-18} L ${x2} ${y2}`:`M ${x1} ${y1} L ${x1+5} ${y1} L ${x1+5} ${c} L ${x2} ${c} L ${x2} ${y2}`;s+=`<path data-edge="" data-source-entity="${t.row}-${r.id}" data-target-entity="output-${r.id}" d="${d}" fill="none" stroke="#426e91" stroke-width="2" marker-end="url(#sort-arrow)"/>`;}
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(f.caption)}"><defs><marker id="sort-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M 0 1 L 9 5 L 0 9" fill="none" stroke="#426e91" stroke-width="1.5"/></marker></defs><text class="sort-meta" x="24" y="30">${esc(Object.entries(f.metrics).map(([k,v])=>k+' '+v).join(' · '))}</text>${s}</svg>`;
 }
