from pathlib import Path
import json,itertools,math
B=Path(__file__).resolve().parent;Q=[]
def add(title,stem,solution,kind='reasoning',data=None,difficulty='Hard',origin='Original mathematical/conceptual problem'):
 Q.append(dict(id='COMBIN_'+str(len(Q)+1).zfill(3),title=title,stem=stem,solution=solution,difficulty=difficulty,origin=origin,certificate=dict(kind=kind,data=data)))
functions=[('Priority with fallback',[1,2,3,5,7]),('Odd parity',[1,2,4,7]),('Majority',[3,5,6,7]),('Exactly one request',[1,2,4]),('A conditional implication',[0,1,3,4,5,7]),('A sparse alarm',[0,3,5,6]),('A guarded selection',[1,3,4,5]),('A threshold exception',[0,2,3,7])]
for name,on in functions:
 for rem in range(3):
  sel=[k for k in range(3) if k!=rem];r='ABC'[rem];s=''.join('ABC'[k] for k in sel);data=[];rows=[]
  for j in range(4):
   vals=[];ids=[]
   for b in range(2):
    a=[0]*3;a[sel[0]]=j>>1;a[sel[1]]=j&1;a[rem]=b;i=4*a[0]+2*a[1]+a[2];ids.append(i);vals.append(int(i in on))
   expr=['0',r,'\\overline '+r,'1'][2*vals[0]+vals[1]];data.append(expr);rows.append('| '+format(j,'02b')+' | '+', '.join(map(str,ids))+' | '+''.join(map(str,vals))+' | $'+expr+'$ |')
  inv=sum(x.startswith('\\overline') for x in set(data));distinct=len(set(data))
  stem=f'$F(A,B,C)=\\sum m('+','.join(map(str,on))+f')$. Implement it with one 4:1 mux whose select order is ${s}$ and residual input is ${r}$. Derive every data connection, count distinct nonconstant data functions and required shared residual inversions, and explain whether exchanging the select pins without rewiring is legal.'
  sol='**1. Preserve row significance.** The original minterm number is $4A+2B+C$, independent of which variable becomes a data signal. For each selected pair, explicitly enumerate residual values zero and one. This avoids treating a select pair as two adjacent decimal indices when the free coordinate is a more significant bit.\n\n**2. Read the four cofactors.**\n\n| Select pair | Original indices, residual 0 then 1 | Output pair | Data function |\n|---|---|---|---|\n'+'\n'.join(rows)+'\n\n**3. Construct the exact function.** A residual output pair 00 is constant zero, 01 is the residual variable, 10 is its complement, and 11 is constant one. The data tuple is $('+','.join(data)+')$. Each mux-selected branch now reproduces both rows belonging to its select pair, so all eight rows are correct by the four exhaustive cases.\n\n**4. Count external data preparation.** There are '+str(len({x for x in data if x not in ['0','1']}))+' distinct nonconstant functions. Only '+str(inv)+' shared residual inverter is needed under a library with free direct wires and constants; repeated use of the same complement does not require a separate inverter for every pin. The mux itself remains a physical component and must be counted if total cost is requested.\n\n**5. Diagnose a select exchange.** Swapping the two select pins exchanges addresses 01 and 10, while 00 and 11 remain fixed. Leaving the data tuple unchanged is legal precisely when $D_1=D_2$ as functions, not merely when they agree for one tested residual value. Here that condition is '+('satisfied' if data[1]==data[2] else 'not satisfied')+'. A different select choice can reduce external logic, but it must be recomputed from the table; apparent geometric adjacency is not a cofactor proof.'
  add(name+' — select '+s,stem,sol,'cofactor',dict(on=on,remaining=rem,data=data),origin='Original extension of reviewed MIT/Cambridge cofactor implementation families')

contracts=[('enabled priority',3,2,lambda a:[a[0]*a[1],a[0]*(1-a[1])*a[2]],['ER_1','E\\overline{R_1}R_0'],'E,R_1,R_0'),('exclusive request alarm',3,2,lambda a:[a[0]*(a[1]^a[2]),a[1]*a[2]],['E(R_1\\oplus R_0)','R_1R_0'],'E,R_1,R_0'),('saturating increment',2,2,lambda a:[a[0]|a[1],a[0]|(1-a[1])],['A+B','A+\\overline B'],'A,B'),('two-bit modular increment',2,2,lambda a:[a[0]^a[1],1-a[1]],['A\\oplus B','\\overline B'],'A,B'),('one-bit equality and greater',2,2,lambda a:[1-(a[0]^a[1]),a[0]*(1-a[1])],['\\overline{A\\oplus B}','A\\overline B'],'A,B'),('one-bit difference and borrow',2,2,lambda a:[a[0]^a[1],(1-a[0])*a[1]],['A\\oplus B','\\overline A B'],'A,B'),('parity and majority',3,2,lambda a:[a[0]^a[1]^a[2],int(sum(a)>=2)],['A\\oplus B\\oplus C','AB+AC+BC'],'A,B,C'),('exactly-one and any request',3,2,lambda a:[int(sum(a)==1),int(sum(a)>0)],['A\\overline B\\overline C+\\overline A B\\overline C+\\overline A\\overline B C','A+B+C'],'A,B,C'),('even parity with validity',3,2,lambda a:[int(4*a[0]+2*a[1]+a[2]<6),int(4*a[0]+2*a[1]+a[2]<6)*(1-(a[0]^a[1]^a[2]))],['\\overline{AB}','\\overline{AB}\\overline{A\\oplus B\\oplus C}'],'A,B,C'),('two-bit Gray and inverse',2,2,lambda a:[a[0],a[0]^a[1]],['A','A\\oplus B'],'A,B')]
requirements={
 'enabled priority':'Outputs are G1 then G0. Enable E=0 suppresses both; when E=1 and both requests are high, R1 has priority.',
 'exclusive request alarm':'Outputs are P then K. P is high exactly when E=1 and exactly one of R1,R0 is high; K is high exactly when both requests are high, regardless of E.',
 'saturating increment':'Input x=2A+B. Output word Y0Y1 represents min(x+1,3), with Y0 most significant.',
 'two-bit modular increment':'Input x=2A+B. Output word Y0Y1 represents (x+1) modulo four, with Y0 most significant.',
 'one-bit equality and greater':'Outputs are equality of A,B followed by the unsigned one-bit predicate A>B.',
 'one-bit difference and borrow':'Outputs are the low bit of A−B followed by its one-bit borrow flag.',
 'parity and majority':'Outputs are odd parity of ABC followed by a flag high exactly when at least two input bits are high.',
 'exactly-one and any request':'Outputs are a flag for exactly one asserted ABC bit followed by a flag for at least one asserted bit.',
 'even parity with validity':'Outputs are validity V followed by parity P. V is high on binary indices 0–5; P indicates even bit parity on valid rows and is forced zero on invalid rows.',
 'two-bit Gray and inverse':'For binary input AB, output the two-bit Gray encoding G1G0. Also explain why applying the same mapping again recovers the binary input.'}
for title,n,m,fn,expr,names in contracts:
 table=[fn(list(map(int,format(i,'0'+str(n)+'b')))) for i in range(1<<n)];words=[''.join(map(str,x)) for x in table];ones=[[i for i,x in enumerate(table) if x[j]] for j in range(m)]
 stem='Design the **'+title+'** block with input order $'+names+'$. '+requirements[title]+' Give a complete output table, independent Boolean equations, a ROM content list, and the output active-low transformation. For incrementers, explicitly distinguish saturation from modulo-four arithmetic.'
 sol='**1. Interpret each row numerically or by its request predicate.** Do not use a previous input value. The complete output words, in increasing input index, are `'+', '.join(words)+'`. Each word follows directly from the named predicate: '+('the enabled high-priority request suppresses the lower grant' if title=='enabled priority' else 'evaluate each stated output independently before combining their bits into a word')+'.\n\n**2. Derive one-sets.** Output zero is one on $\\{'+','.join(map(str,ones[0]))+'\\}$; output one is one on $\\{'+','.join(map(str,ones[1]))+'\\}$. These sets provide a canonical sum-of-minterms construction even if a shorter formula is later chosen.\n\n**3. Simplify with semantic structure.** The equations are $Y_0='+expr[0]+'$ and $Y_1='+expr[1]+'$. Substitution in every listed row proves both outputs, including the endpoint and zero-request cases. Recognizing only one equation is insufficient for a two-output design.\n\n**4. Give a technology-independent implementation.** A $'+str(1<<n)+'\\times2$ ROM stores the displayed words and uses '+str(2*(1<<n))+' bits. A shared decoder can instead OR each output’s required one rows. The word order must remain the declared output order; reversing it transposes the meanings without changing the address sequence.\n\n**5. Transform polarity and test the boundary.** If the interface requires active-low outputs, use $Y_{0n}=\\overline{Y_0}$ and $Y_{1n}=\\overline{Y_1}$, complementing each displayed output bit rather than its index. Saturating increment sends input three to three; modular increment sends it to zero. The correct arithmetic convention is an obligation, not a freedom that Boolean minimization can decide. The complete table is also an independent reference for checking an HDL implementation.'
 if title=='two-bit Gray and inverse':sol+='\n\n**6. Prove inversion.** Applying the same two-bit map twice gives first bit A and second bit $A\\oplus(A\\oplus B)=B$. This involution is specific to this two-bit mapping; larger Gray-code inverses require a prefix XOR rather than blindly repeating the same adjacent-bit transformation.'
 add('Complete multi-output design: '+title,stem,sol,'contract',dict(name=title,n=n,words=words,ones=ones),origin='Original extensions of reviewed Cornell/Berkeley multi-output design families')

# Each network is distinct; compare a specific faulty candidate against a reference.
nets=[('masked product','AB+C','A+B+C',lambda a,b,c,d:(a*b)|c,lambda a,b,c,d:a|b|c),('factored select','A(B+C)','AB+C',lambda a,b,c,d:a*(b|c),lambda a,b,c,d:(a*b)|c),('consensus branch','AB+\\overline A C','AB+AC',lambda a,b,c,d:(a*b)|((1-a)*c),lambda a,b,c,d:(a*b)|(a*c)),('three-input parity','A\\oplus B\\oplus C','A\\oplus(B+C)',lambda a,b,c,d:a^b^c,lambda a,b,c,d:a^(b|c)),('two-product shared logic','AB+CD','(A+B)(C+D)',lambda a,b,c,d:(a*b)|(c*d),lambda a,b,c,d:(a|b)*(c|d)),('product of sums','(A+B)(C+D)','AC+BD',lambda a,b,c,d:(a|b)*(c|d),lambda a,b,c,d:(a*c)|(b*d)),('majority omission','AB+AC+BC','AB+AC',lambda a,b,c,d:int(a+b+c>=2),lambda a,b,c,d:(a*b)|(a*c)),('priority low grant','E\\overline{R_1}R_0','ER_0',lambda a,b,c,d:a*(1-b)*c,lambda a,b,c,d:a*c),('active-low confusion','\\overline{A(B+C)}','\\overline A(B+C)',lambda a,b,c,d:1-a*(b|c),lambda a,b,c,d:(1-a)*(b|c)),('NAND associativity','\\overline{ABC}','\\overline{\\overline{AB}C}',lambda a,b,c,d:1-a*b*c,lambda a,b,c,d:1-(1-a*b)*c),('one-hot confusion','A\\oplus B\\oplus C','A\\overline B\\overline C+\\overline A B\\overline C+\\overline A\\overline B C',lambda a,b,c,d:a^b^c,lambda a,b,c,d:int(a+b+c==1)),('shared-output mutation','AB','AB(C+D)',lambda a,b,c,d:a*b,lambda a,b,c,d:a*b*(c|d))]
for title,fx,gx,f,g in nets:
 vals=[];diff=[]
 for i in range(16):
  a=list(map(int,format(i,'04b')));v=f(*a);w=g(*a);vals.append([v,w]);diff.extend([i] if v!=w else [])
 stem='A proposed circuit changes $F='+fx+'$ to $G='+gx+'$. Use input order $A,B,C,D$; in the priority case rename $A,B,C$ as $E,R_1,R_0$. Derive the full equivalence miter, list all detecting rows, choose one smallest-index counterexample, and state whether a care restriction could legitimize the change.'
 witness=diff[0];v,w=vals[witness]
 sol='**1. Compare settled functions, not visual similarity.** Form $M=F\\oplus G$. Each input row is evaluated with exactly the same primary bits in both networks. Constants or an unused D do not alter the declared index width.\n\n**2. Exhaust the miter.** Its one-set is $\\{'+','.join(map(str,diff))+'\\}$. These and only these rows reject equivalence. Thus agreement on zero input, all-one input, or one familiar subnetwork cannot replace a complete comparison.\n\n**3. Exhibit a minimal-index witness.** Row `'+format(witness,'04b')+'` has $F='+str(v)+'$ and $G='+str(w)+'$. Substituting those bits into the displayed equations supplies a concrete failure rather than an unsupported claim of difference.\n\n**4. State the only possible care exception.** A care predicate C could make the change acceptable only if it excludes **every** listed discrepancy row: $CM=0$. Excluding one witness is not enough. Such a restriction must come from the environment contract; inventing it after discovering a circuit error changes the task.\n\n**5. Transfer the lesson to multiple outputs.** If these are one output of a larger block, include every other output discrepancy in an OR miter. A shared gate modification may create several observable failures. The reference should be independently specified from predicates or arithmetic behavior, because copying the same wrong netlist into both sides produces a vacuous pass. This problem concerns functional equality, not whether the two circuits also have identical timing.'
 add('Counterexample surgery: '+title,stem,sol,'miter',dict(name=title,reference=fx,candidate=gx,values=vals,diff=diff))

for n in [3,4,5,6,7,8,9,10,12,16]:
 late=n+2;chain=n-1;tree=math.ceil(math.log2(n));arr=[0]*(n-1)+[late]
 # late input added last; early inputs have a balanced tree.
 unbalanced=max(math.ceil(math.log2(n-1)),late)+1
 stem=f'An n-way AND has $n={n}$ independent inputs, one arriving at time {late} and the others at time zero. Only two-input AND gates of unit propagation delay are allowed. Compare a balanced tree for simultaneous inputs, a chain with the late input last, and a balanced early-input subtree followed by the late input. Give gate count, depth lower bound, and arrival-time reasoning. Do not infer physical delay from literal count.'
 sol=f'**1. Count binary combination gates.** A full binary tree with {n} leaves has {n-1} internal vertices, so each listed AND-tree realization uses {n-1} gates. This count excludes wires and supplies no claim about a different gate library.\n\n**2. Prove the simultaneous-arrival depth.** At depth d, fan-in two can combine at most $2^d$ independent leaves. Since this function depends on all {n} inputs, $d\\ge\\lceil\\log_2 {n}\\rceil={tree}$. A balanced construction achieves this lower bound; a chain instead has worst-case depth {chain}.\n\n**3. Use arrival recurrences rather than the depth slogan.** Place the late input at the last chain gate. The early chain settles at time {max(n-2,0)}, so the output latest bound is $\\max({n-2},{late})+1={late+1}$. It is not {late}+{chain}, because that late input does not traverse every gate.\n\n**4. Balance only the early subtree.** Its latest bound is $\\lceil\\log_2({n-1})\\rceil={math.ceil(math.log2(n-1))}$. The final gate combines this with the late input, giving $\\max({math.ceil(math.log2(n-1))},{late})+1={unbalanced}$. It retains a shallow path for the slow signal and improves the early inputs compared with a long chain.\n\n**5. Qualify comparisons with a fully balanced tree.** The exact delay for its late leaf is its leaf depth added to {late}; for a non-power-of-two tree, leaf depths can differ. Knowing only the maximum balanced depth does not specify which depth the late input receives. A delay claim needs the actual placement. Gate count ties can therefore coexist with different arrival bounds; the best structure depends on input timing, not merely on n. Each bound assumes the AND side inputs permit a transition and ignores electrical loading.'
 add('Arrival-sensitive AND design, width '+str(n),stem,sol,'tree',dict(n=n,late=late,gates=n-1,balancedDepth=tree,lateLast=unbalanced),origin='Original extension of MIT bounded-fan-in and arrival-time analysis')

for w,x,y in [(3,6,3),(4,12,5),(4,15,1),(5,24,9),(5,31,7),(6,40,25),(6,63,2),(7,96,33),(8,200,70),(8,255,129)]:
 mask=(1<<w)-1;sx=x-(1<<w) if x&(1<<(w-1)) else x;sy=y-(1<<w) if y&(1<<(w-1)) else y
 vals=dict(bitNot=mask^x,logicalNot=int(x==0),unsignedLess=int(x<y),signedLess=int(sx<sy),modsum=(x+y)&mask,carry=(x+y)>>w)
 stem=f'Two w-bit buses have $w={w}$, unsigned bit patterns $X={x}$ and $Y={y}$. Compute bitwise complement of X, logical negation of X, unsigned and signed less-than flags, and the low-w-bit arithmetic sum with carry. Then state which results change under zero-extension versus sign-extension. All comparison and addition semantics are explicitly fixed-width hardware semantics.'
 sol='**1. Fix the range.** The unsigned range is $0$ through '+str(mask)+', while the signed two’s-complement range is $-'+str(1<<(w-1))+'$ through '+str((1<<(w-1))-1)+'. The patterns are `'+format(x,'0'+str(w)+'b')+'` and `'+format(y,'0'+str(w)+'b')+'`.\n\n**2. Keep complement operations distinct.** Bitwise complement flips each of the '+str(w)+' bits and equals $'+str(mask)+'-'+str(x)+'='+str(vals['bitNot'])+'$. Logical negation asks whether X equals zero; because X is nonzero, the one-bit result is zero. Signed arithmetic negation would be a third operation and cannot be substituted for either.\n\n**3. Decode the comparison operands.** Unsigned comparison yields '+str(vals['unsignedLess'])+'. Signed values are '+str(sx)+' and '+str(sy)+', so signed comparison yields '+str(vals['signedLess'])+'. A comparator’s truth table must encode the intended interpretation, not just the visible bus width.\n\n**4. Separate low bits from carry.** The mathematical unsigned sum is '+str(x+y)+'. Division by $2^{'+str(w)+'}$ gives carry '+str(vals['carry'])+' and remainder '+str(vals['modsum'])+'. That remainder is the low-word result. Carry is not a signed-overflow flag; the latter requires checking the signed mathematical sum against its representable range.\n\n**5. Explain extension.** Zero-extension preserves the unsigned numbers '+str(x)+' and '+str(y)+'. Sign-extension preserves signed values '+str(sx)+' and '+str(sy)+' by replicating the sign bit. It consequently gives different unsigned extended values for a negative pattern. A bitwise complement at the larger width flips the newly added bits too, so its numerical result changes even if its original low bits match. State operand widths before manipulating an HDL expression; unsized-literal defaults must not be inferred from this deliberately explicit hardware model.'
 add('Bit-vector contract and signedness '+str(w)+'/'+str(x)+'/'+str(y),stem,sol,'word',dict(w=w,x=x,y=y,signed=[sx,sy],results=vals))

manual=[
('Correlated output freedom','A legal input permits output pairs 01 or 10, but never 00 or 11. Can both output bits independently be treated as don’t-cares? Count the permitted completions for three such independent input rows.','No. Independent X bits permit four words, including both forbidden words. The relational requirement is $Y_0\\oplus Y_1=1$. Each row has two permissible words, so three independent rows admit $2^3=8$ completions, not $2^6=64$. To construct an implementation, choose a Boolean function for the first bit on those rows and set the second to its complement. This imposes the correlation for every chosen completion. A minimizer that handles separate output care sets cannot silently preserve a cross-output restriction it was never given. A validity bit can safely make both data bits irrelevant only if the environment permits every data word at that validity. The word “unspecified” must therefore identify allowed vectors, not merely isolated output marks. A useful verification reference tests membership in the allowed relation rather than equality to one arbitrarily chosen output word.'),
('Acyclic closure by induction','Prove that a finite acyclic network of total Boolean gates with one driver per net produces a unique output for every primary input. Does the converse forbid every possible redundant feedback equation?','Topologically order the gates. The first gate consumes only known primary inputs and therefore has one output. Inductively, all inputs of the next gate are outputs of earlier gates or primary inputs and have unique values, so its total Boolean truth function gives one value. Finite repetition computes every observed output. Substituting predecessor functions also proves that each output is a function of current primary inputs alone. Uniqueness here concerns the settled Boolean model; finite propagation needs each block’s delay bound. The converse is not a theorem about every algebraic feedback equation: $q=q\\cdot0$ has the unique Boolean fixed point zero, while $q=q$ has two and $q=\\overline q$ has none. The structural DAG restriction provides a general construction and settling guarantee without needing a special feedback analysis. It must not be strengthened into an unsupported claim that every loop has exactly two stable states.'),
('Missing assignment stores history','Analyze `if (en) y = d;` with no assignment when en is false. Exhibit two histories reaching identical current inputs but different outputs. Give a correction for a disabled-zero contract.','History one enables with d=0, producing y=0, then disables while the current d becomes 1. History two enables with d=1, producing y=1, then disables while d stays 1. Both have current inputs (en,d)=(0,1), yet their retained y values differ. This is the decisive history-dependence counterexample. A disabled-zero contract instead requires y=0 whenever en=0, so `y = en ? d : 1\'b0;` supplies both branches. In a procedural block, assigning a default zero before the conditional has the same functional effect when later branches deliberately override it. An `always_comb` keyword expresses intent and enables diagnostics; it does not supply a mathematically missing branch value. If the desired disabled behavior is hold, then the requirement intentionally calls for storage and should be represented as a sequential element. One initial disabled test cannot distinguish these histories.'),
('Fault activation is not detection','For Y=AB+C, find all tests detecting stuck-at-zero and stuck-at-one at internal net t=AB. Explain the masking condition.','For stuck-at-zero, the correct t must be one, so A=B=1. To observe its loss, the other OR input C must be zero. Therefore only 110 detects this fault. For stuck-at-one, the correct t must be zero and C must again be zero; the detecting rows are 000,010,100. A row with C=1 masks either internal discrepancy by forcing both correct and faulty outputs to one. These conditions separate activation from propagation: activation creates the wrong internal value, propagation allows it to change an observed output. The union of the two detecting sets does not mean one test detects both opposing faults. In fact their activation conditions are disjoint, so at least two tests are required to cover this pair; 110 and 000 achieve that lower bound. This proof refers to the stated single stuck-at fault model, not arbitrary electrical faults.'),
('Exact minimum test cover','Four allowed tests detect faults as T0={a,b}, T1={b,c}, T2={c,d}, T3={a,d}. Find every minimum cover of all four faults and explain why a greedy tie can be harmless here but not generally.','A single test detects only two distinct faults, so at least two tests are necessary. T0 with T2 covers all four, as does T1 with T3. No other pair covers the universe: neighboring pairs in the cycle leave the opposite fault uncovered. Therefore these are exactly the two optimum covers of size two. Selecting T0 then the test with greatest new coverage chooses T2 and succeeds, but this instance supplies no general greedy-optimality theorem. A cover with three selected tests can be redundant or merely nonminimum depending on its members; verifying its union proves coverage but not optimum size. Set-cover optimality needs a lower bound plus attainment, exhaustive subset enumeration, or another valid certificate under the same fault universe. This test-selection problem is structurally related to choosing prime implicants, but its elements are faults rather than truth-table one rows.'),
('Functional irrelevance versus transient sensitivity','A network implements Y=A times NOT A. Is its stable function zero? Can a structural path prove a stable output transition, and does stable constancy prove no glitches?','The stable Boolean identity $A\\overline A=0$ holds for A=0 and A=1. Thus no change in A can alter the settled output. Structural paths still exist through the direct and inverted branches, but their correlated side conditions cannot be treated as independent assignments to prove a settled functional transition. Conversely, after A rises, the direct signal can briefly be one before its delayed complement falls. An AND may then produce a transient one depending on gate delays and pulse rejection. The existence and width of that pulse require a stated timing model. These are separate conclusions: the truth function is constant; a structural path need not be a sensitizable settled change; and physical glitch freedom is not implied by constancy. Replacing the circuit with a constant-zero source preserves the stable function but may change its waveform and loading.'),
('NAND is not associative','Find a counterexample to NAND(NAND(A,B),C)=NAND(A,B,C), and give a valid all-two-input-NAND construction of the latter.','Set A=B=0 and C=1. The inner NAND is one, so the nested NAND is zero. The desired three-input NAND is one because ABC=0. Thus associativity fails. A correct construction computes t=NAND(A,B), u=NAND(t,t)=AB, and Y=NAND(u,C)=complement(ABC), using three two-input NANDs. The tied-input operation is a real gate unless complemented internal signals are explicitly free. The intermediate u restores the polarity before combining with C; omitting it gives the wrong expression. Checking 111 alone would not reveal the error because the two circuits already differ in other rows, and a familiar symbol sequence does not establish a truth function. The gate count is a cost for this construction under the stated library. A proof that no other two-input realization uses fewer gates would require a separate lower-bound argument.'),
('Shared logic and fan-out buffering','One shared internal net must drive seven receiving pins. Every source may drive at most two loads, and each inserted noninverting buffer also may drive two. What minimum number of such buffers is needed to distribute the net without duplicating its logic?','Without buffers, the original source has two available load slots. Replacing one slot by a buffer consumes that one slot but creates two downstream slots, a net increase of one. To support seven leaf loads, at least five buffers are required. A binary distribution tree with the original source as root, five inserted buffer vertices and seven receiving leaves attains that count. Its buffer placement can be balanced to reduce the longest distribution path; the exact leaf delays depend on the chosen topology. This result assumes binary fan-out for every source, no inverter pairs, no load weighting, and a noninverting buffer counted as one component. It does not claim that a physical pin can always drive any two gates equally fast. Sharing a product across many outputs is not free under such a fan-out contract; buffers must enter the total cost and timing analysis.'),
('ROM capacity and programmability','Compare a fixed asynchronous ROM implementing a 6-input, 5-output function with a programmable 6-input LUT. Count logical stored bits and independent functions, and state whether a clocked read is combinational.','There are 64 addresses and five output bits per address, so the logical truth table stores 320 bits. There are $2^{320}$ completely specified functions with this interface. A single-output 6-input LUT stores 64 bits and can represent $2^{64}$ Boolean functions. Five independent such LUTs can represent the same function count as the five-output ROM, but their physical storage, decoder sharing and routing need not match. A fixed asynchronous read gives a settled word determined by the present address after access delay. A clocked read produces a word associated with sampled address state and is a sequential interface. Logical capacity does not establish electrical delay, minimum gate cost, hazard freedom or a transistor count. The address bits and output word order must be named to reproduce the intended table.'),
('Active-low decoder union','An enabled decoder gives outputs d_i_n that are zero on their selected rows. Implement the active-high union of rows 1,3,6 with one combining gate, then derive its disabled result if all decoder outputs go high.','Each d_i_n is the complement of the active-high minterm d_i. The requested function is $d_1+d_3+d_6=\\overline{d_{1n}d_{3n}d_{6n}}$, so one three-input NAND combines the selected active-low outputs. Using OR would yield one on almost every row rather than the required union. When disabled and all decoder outputs are high, the NAND output is zero, consistent with a disabled-no-selection contract. If the final interface instead needs an active-low union indication, the required result is the AND of the three decoder outputs and is one when disabled. This distinction is driven by both source and destination polarity. Complemented-output notation cannot be dropped between schematic blocks; label internal nets and evaluate at least one selected row and one unselected row before declaring the mapping correct.'),
('Independent care miters','Two implementations disagree on input indices 2,5,7 of a three-bit input. One environment promises A=0; another promises B=0. Is either contract sufficient for equivalence? Give every surviving discrepancy.','With order A,B,C, care A=0 includes indices 0,1,2,3, so discrepancy 2 survives and equivalence fails. Care B=0 includes indices 0,1,4,5, so discrepancy 5 survives and equivalence also fails. Combining both promises includes only indices 0 and 1, so the discrepancy intersection is empty and equivalence holds on that restricted domain. The check is set intersection with care, or algebraically care AND the miter, not simply asking whether one chosen counterexample is illegal. A user must justify those environmental assumptions independently. An implementation satisfying a stronger care restriction does not automatically satisfy a broader input domain. A truth-table verifier should record both the reference table and the exact care set so that a passing result can be interpreted correctly.'),
('Cost reduction with changed gate library','Compare Y=A(B+C) mapped as two ANDs followed by OR and as a factored OR followed by AND. Then map both into two-input NAND with no free input complements.','In an AND/OR library, the expanded form AB+AC uses three gates while the factored form uses two, both with depth two for relevant paths. In a NAND-only library, the expansion uses p=NAND(A,B), q=NAND(A,C), Y=NAND(p,q), totaling three. The direct factored mapping complements B and C, forms their OR by NAND, forms the complemented product with A, and inverts the result, totaling five. Thus the expression with fewer algebraic operations can yield more gates in a particular naive mapping. One can of course refactor again during technology mapping to recover the better construction; the example warns against mechanically freezing a representation. It does not prove the five-gate result is the optimal NAND mapping of the factored specification. Complement availability, fan-in, desired output polarity and sharing all change the objective.'),
('Propagation and contamination are different extrema','For p=AB, q=p+C, Y=qD, use propagation bounds 3,4,2 and contamination bounds 1,2,1. All inputs may change at zero. Compute bounds and sensitize the longest path.','The latest arrival of p is 3, q is max(3,0)+4=7, and Y is max(7,0)+2=9. The earliest possible p change is 1, q is min(1,0)+2=2, and Y is min(2,0)+1=1. The resulting structural bounds are contamination 1 and propagation 9, not a claim that one chosen transition takes nine or can occur continuously throughout that interval. To propagate an A transition through all gates, choose B=1,C=0,D=1. Then each gate’s side input is noncontrolling, so this path is logically sensitized. With D=0, the output remains zero irrespective of the internal transition. Physical rise/fall differences and loading are outside the declared interval model. Compute minima and maxima separately; adding the minimum delay along the longest path does not find the shortest path.'),
('Priority controller invariants','Prove mutual exclusion, enabled-service completeness and disabled suppression for G1=ER1, G0=E NOT R1 R0. Is one-hot correctness sufficient to prove the selected payload?', 'Mutual exclusion follows from $G_1G_0=E^2R_1\\overline{R_1}R_0=0$. Service completeness follows from $G_1+G_0=E(R_1+\\overline{R_1}R_0)=E(R_1+R_0)$. With E=0 both grants are zero, proving suppression. These identities quantify over all inputs and therefore include simultaneous requests; priority grants requester one in that case. They do not prove the payload data follows the granted requester. A circuit that gives the correct one-hot grants but swaps the two data sources satisfies all three properties while delivering the wrong word whenever sources differ. Add a fourth obligation that the payload equals the selected requester’s data under each grant. Keeping grant and payload checks separate prevents a misleading partial certificate. An active-low grant interface needs complemented observed outputs before interpreting these same invariants.')]
for title,stem,sol in manual:add(title,stem,sol)
assert len(Q)==80,len(Q)
(B/'g_combin-questions.json').write_text(json.dumps(Q,indent=2)+'\n')
print('Authored 80 fully solved mathematical/conceptual tasks plus two separate authentic revisits.')
