"""Mathematical and conceptual tasks with explicit independent-check certificates."""
from pathlib import Path
import json
from kmap_model import cells,primes,optimum,term,expr,essentials,petrick,cost
B=Path(__file__).resolve().parent;Q=[]
def add(title,stem,solution,kind='reasoning',data=None,origin='Original mathematical/conceptual problem',difficulty='Hard'):
 Q.append(dict(id='KMAP_'+str(len(Q)+1).zfill(3),title=title,stem=stem,solution=solution,origin=origin,difficulty=difficulty,certificate=dict(kind=kind,data=data)))
cases=[
 ('Four corners',4,[0,2,8,10],[], 'wrap-around adjacency'),
 ('Two rows and a bridge',4,[0,1,2,3,5,7,8,9,10,11],[], 'overlapping cubes'),
 ('A cyclic chart',3,[0,2,3,4,5,7],[], 'no essential prime and nonunique optima'),
 ('A decimal prime detector',4,[2,3,5,7],list(range(10,16)), 'reachable decimal inputs'),
 ('A binary prime detector',4,[2,3,5,7,11,13],[], 'isolated obligations'),
 ('A Fibonacci detector',4,[0,1,2,3,5,8,13],[], 'nonlocal sharing'),
 ('A decimal Fibonacci detector',4,[0,1,2,3,5,8],list(range(10,16)), 'care-set restriction'),
 ('A three-of-four voter',4,[7,11,13,14,15],[], 'threshold and lower-bound witnesses'),
 ('Even parity',4,[0,3,5,6,9,10,12,15],[], 'isolated minterms'),
 ('BCD segment with a split',4,[0,2,3,5,6,8,9],list(range(10,16)), 'don’t-care-assisted expansion'),
 ('A sparse consensus bridge',4,[1,3,6,7,9,11,14,15],[], 'absorption versus necessary terms'),
 ('Residual obligations',4,[0,1,2,4,5,6,8,9,10,12,13],[], 'chart choices after essentials'),
 ('A cost-sensitive tie',4,[0,2,3,4,5,7,8,10,11,13],[], 'enumerating rather than guessing a tie'),
 ('A five-variable plane merge',5,[0,1,2,3,16,17,18,19,28,29,30,31],[], 'corresponding cells across planes'),
 ('A five-variable sparse decoder',5,[1,3,7,9,11,15,17,19,23,25,27,31],[], 'fixed versus free coordinates'),
 ('Zero ON obligations',4,[],[1,2,3], 'empty cover and optional outputs'),
 ('All care rows are one',4,list(range(12)),list(range(12,16)), 'constant implementation'),
 ('A displaced four-cell block',4,[4,5,12,13],[], 'bit significance and vertical wrapping'),
 ('A DC-only tempting cube',4,[1,5], [8,9,10,11], 'no required coverage of DC-only groups'),
 ('A tabular covering chain',4,[1,2,3,5,6,7,9,10,11,13,14],[], 'complete prime enumeration')]
for title,n,on,dc,focus in cases:
 for pos in [False,True]:
  required=sorted(set(range(1<<n))-set(on)-set(dc)) if pos else on
  ps,solutions,k=optimum(n,required,dc);es=essentials(ps,required)
  spec='$F('+','.join('ABCDEF'[:n])+')=\\sum m('+','.join(map(str,on))+')$'
  if not on:spec='$F$ has no required one rows'
  stem=f'{spec}; '+('the don’t-care set is $D=\\{'+','.join(map(str,dc))+'\\}$.' if dc else 'all other rows are specified zero.')+f' Find **every** optimal {"POS" if pos else "SOP"} under the lexicographic cost (number of {"sum factors" if pos else "product terms"}, total literals). Use the stated variable order. Identify prime candidates, essential candidates and a lower-bound certificate; explain the role of {focus}.'
  rows='\n'.join('| `'+c+'` | $'+term(c,pos)+'$ | $\\{'+','.join(map(str,sorted(s&set(required))))+'\\}$ | '+str(sum(x!='-' for x in c))+' |' for c,s in sorted(ps.items()))
  sol='**1. Translate the obligation set.** '+('POS is obtained by covering the specified zero rows with product cubes of $\\overline F$, then complementing each product into a sum factor. DC rows stay optional.' if pos else 'SOP must cover precisely the required one rows, may cover don’t-cares, and must avoid every specified zero.')+' The required rows are $\\{'+','.join(map(str,required))+'\\}$.\n\n**2. Enumerate valid maximal cubes.** Expand a fixed bit only when both resulting halves remain inside the allowed set. Discard a cube contained in a larger valid cube. The resulting complete candidate table is:\n\n| Cube | '+('POS factor' if pos else 'SOP term')+' | Required rows covered | Literals |\n|---|---|---|---|\n'+rows+'\n\n**3. Mark compulsory candidates.** '+('The essential cube patterns are '+', '.join('`'+c+'`' for c in es)+'. Each owns at least one required row that no other prime covers.' if es else 'There is no essential cube; no individual prime is compulsory merely because it is large.')+'\n\n**4. Solve the complete covering chart.** '+('There are no required rows, so the empty cover is valid and has cost (0,0). Optional DC rows do not force hardware.' if not required else f'The optimum cost is **{k}**. Every subset with fewer than {k[0]} candidates fails at least one obligation; among covers with {k[0]} candidates, no literal sum below {k[1]} succeeds. This is an exact finite certificate because every useful product can be expanded to a listed prime without increasing this cost. The accompanying verification enumerates all candidate subsets and also checks the independent Petrick construction.')+'\n\n**5. Write all tied optimum expressions.**\n\n'+ '\n\n'.join('$$F='+expr(c,pos)+'.$$' for c in solutions)+'\n\n**6. Check the specification.** Evaluate every required-one and required-zero row, rather than comparing only the pictured groups. DC outputs need not match a different minimization. A prime candidate is a permitted building block, not automatically a selected term; overlapping candidates are legal, whereas including a forbidden row is not. This distinction is what prevents the common largest-group-first mistake.'
  add(title+' — '+('POS' if pos else 'SOP'),stem,sol,'cover',dict(n=n,on=on,dc=dc,pos=pos,primes=sorted(ps),covers=[list(x) for x in solutions],cost=list(k)),origin='Original extension of reviewed MIT/Cambridge/Stanford/Cornell covering families')

for c in ['0-11','1--0','-01-','--10','0---','10-1-','-0-11','11---','--0--','0-1-0','101--','-11-0','1-0-1','---01','01---']:
 n=len(c);s=sorted(cells(c));mx=sorted(set(range(1<<n))-set(s));perm=list(reversed(range(n)));mapped=sorted(sum(((i>>(n-1-j))&1)<<(n-1-perm.index(j)) for j in range(n)) for i in s)
 add('Canonical expansion and reversed significance: '+c,'Let $F='+term(c)+'$ in variable order $'+','.join('ABCDE'[:n])+'$. Expand it into a canonical minterm sum and maxterm product. Then reverse the variable order and give the new minterm indices. Count the literals in the original canonical SOP and compare them with the compressed product.',f'**1. Read the cube.** Pattern `{c}` fixes '+str(n-c.count('-'))+' coordinates and frees '+str(c.count('-'))+' coordinates. Each free coordinate admits either bit independently, so the product represents $2^{'+str(c.count('-'))+'}='+str(len(s))+'$ rows.\n\n**2. Enumerate the rows in the declared order.** The canonical one indices are $\\{'+','.join(map(str,s))+'\\}$. Thus $F=\\sum m('+','.join(map(str,s))+')$. The complement set is $\\{'+','.join(map(str,mx))+'\\}$, giving $F=\\prod M('+','.join(map(str,mx))+')$. A zero bit is complemented in a minterm but uncomplemented in its indexed maxterm.\n\n**3. Change significance, not the function.** Reversing the variable order reverses each row’s bit string before conversion to decimal. The new one indices are $\\{'+','.join(map(str,mapped))+'\\}$. Reusing the old indices would generally describe a different function.\n\n**4. Compare representation cost.** The canonical SOP contains '+str(len(s)*n)+' literal occurrences, versus '+str(n-c.count('-'))+' in the single compressed product. The compression is valid because repeated application of $P X+P\\overline X=P$ eliminates each free coordinate. It does not mean the canonical form itself was written incorrectly; canonical and minimal representations serve different purposes.', 'canonical',dict(cube=c,ones=s,zeros=mx,reversed=mapped,literals=n*len(s)),difficulty='Medium')

manual=[
('Prime is not minimum','For $F=\\sum m(0,2,3,4,5,7)$ in order $A,B,C$, prove that an irredundant cover of primes can be nonminimum.','The complete prime set is `0-0`, `01-`, `-00`, `1-1`, `-11`, `10-`. The four-prime cover `-00`, `-11`, `0-0`, `1-1` covers all six rows. It is irredundant: rows 4,3,2,5 respectively certify necessity within that selected cover. Yet `-00`, `01-`, `1-1` is a three-prime cover. Every prime has two cells, so two primes cover at most four required rows; three is a lower bound and is achieved. “No term can be removed” is therefore a local statement about a chosen cover, not proof of globally minimum term count. All terms also have two literals, so the four-prime cover loses on literal count as well.','irredundant',None),
('Two exact covers of a cycle','Solve $F=\\sum m(0,2,3,4,5,7)$ and show why no essential prime exists.','Every required vertex in this six-cycle has two incident valid two-cell cubes; none has a unique prime owner. A three-edge cover must pair all six vertices without overlap, because three two-cell cubes have capacity exactly six. There are two perfect matchings: `-00`, `01-`, `1-1`; and `0-0`, `-11`, `10-`. They give $F=\\overline B\\overline C+\\overline A B+AC$ and $F=\\overline A\\overline C+BC+A\\overline B$. A two-term cover cannot cover six rows. Thus both achieve cost (3,6), and absence of essentials does not imply absence of a solution or uniqueness. The exact chart shows that all six prime pairs matter before a matching is selected.','cycle',None),
('Petrick absorption','Reduce $(P+Q)(Q+R)(P+R)$ and interpret its products as selections, not signal values.','Multiply the first two factors: $PQ+PR+Q+QR=Q+PR$, since $Q$ absorbs $PQ$ and $QR$. Multiplication by $P+R$ gives $PQ+QR+PR$. Each surviving product selects a pair of chart candidates; every pair covers all three obligations, while no single candidate appears in all three clauses. Under unit candidate cost, each product is a minimum cover of size two. With literal costs $w_P=2,w_Q=3,w_R=5$, the second objective selects $PQ$ with literal sum five; $PR$ costs seven and $QR$ costs eight. The Boolean variables here mean “choose this candidate,” which is a different domain from the circuit’s original input variables.','petrick3',None),
('Dominance needs cost','A covers residual rows {1,2,3}; B covers {1,2}. Their literal costs are four and two. Can B be discarded when minimizing literal cost alone?','No. Coverage inclusion alone does not prove a cost-preserving replacement. If a compulsory candidate C already covers row 3, B can finish rows 1 and 2 at cost two, whereas substituting A costs four. A dominates B safely only when its replacement cost is no greater under the objective being optimized. Under term-count-only minimization, both cost one term, so replacing B with A preserves or improves the objective; under lexicographic terms then literals, the literal comparison remains necessary. Dominance is applied to residual obligation sets after compulsory candidates are accounted for. Confusing the objective is enough to invalidate an otherwise correct covering algorithm.','dominance',None),
('Obligation dominance direction','In a chart, row requirement u can be met by {P,Q}, and v by {P,Q,R}. Which requirement may be deleted?','Delete v, the easier requirement, because satisfying u necessarily chooses P or Q and therefore also satisfies v. Do not delete u: choosing R would satisfy v and leave u uncovered. The reasoning uses inclusion of the candidate-choice sets, not the geometric size of a K-map group. It is unchanged when a textbook transposes rows and columns. If the two sets are equal, keep one representative obligation. If two candidate columns have equal coverage and equal cost, keeping either one preserves the optimum value but can lose a different tied expression; retain both when asked for every optimum.','obligation',None),
('An illegal diagonal','For $F=\\sum m(0,3)$ in two variables, can the two ones be combined into a single one-literal product?','No. The binary rows 00 and 11 differ in two coordinates. A one-literal product fixes one coordinate and includes both values of the other, so it would necessarily contain row 01 or row 10, each specified zero. The valid SOP is $\\overline A\\overline B+AB$, which is XNOR, with two two-literal terms. Its apparent diagonal position on a square does not create Boolean adjacency. A visually connected shape is useful only if it is exactly a subcube: all combinations of its free coordinates must occur. This also explains why a bent three-cell group cannot represent one product.','diagonal',None),
('Power of two is not enough','Is the four-cell set {0,1,2,4} a cube in four variables? Prove the answer.','No. The smallest cube containing those rows frees B, C and D while fixing A to zero, so it contains eight rows: 0 through 7. The stated four rows omit 3,5,6,7. A cube is defined by coordinate restrictions, not just by a power-of-two cardinality. One can verify this by inspecting which bit columns vary: three independent bit positions vary, so closure under all combinations would require eight rows. The set may be covered by several valid pairs when its omitted rows are zero, but it cannot be replaced by one two-literal term. Cardinality is a necessary condition for a cube, not a sufficient one.','shape',None),
('The largest-cube trap','In the six-cycle chart, choose `-00` first and `-11` second. Can the cover finish with one more prime?','After those choices, rows 2 and 5 remain uncovered. Their bit patterns are 010 and 101, differing in all three positions, and no valid prime contains both. At least two more primes are needed, so the greedy path uses four terms. Choosing `-00`, `01-`, `1-1` instead covers all six rows with three. Every available prime has the same size; “take the largest group” supplies no tie-breaking proof. The first choice does not itself destroy optimality, but the second does. Exact methods maintain the remaining chart and compare feasible completions, rather than treating each locally attractive group as compulsory.','greedy',None),
('Different DC completions','Let $O=\\{1\\}$, $D=\\{0,3\\}$ in two variables. Compare $\\overline A$ with B.','Both implement the incomplete specification. The first is one at rows 0 and 1 and zero at 2 and 3; the second is one at 1 and 3 and zero at 0 and 2. They agree on required row 1 and specified zero row 2, but disagree at both don’t-care rows. Each is a one-literal optimum. Their XOR is nonzero only inside D, so it does not witness a specification violation. If the external system later makes row 0 or 3 reachable with a required output, the contract changes and the design must be reverified. “Don’t-care” is permission attached to the specification, not a third runtime logic value.','dc',None),
('No ON rows','A four-input specification has $O=\\varnothing$ and $D=\\{1,3,5\\}$. What is the minimum SOP?','The constant zero, represented by an empty OR, satisfies every specified row. It requires no product terms and no literals under the chapter’s expression model. Cubes contained entirely within D may be generated during QM combination, but they do not force coverage and must not turn into essential obligations. Including one of them can produce another legal completion, but cannot improve cost below (0,0). Hardware constants may have technology-specific cost; that is a different objective and must be stated separately. The dual case with no required zero rows admits constant one. An empty minterm sum and an empty maxterm product therefore have different identities.','empty',None),
('Correct QM merging','Explain why `01-0` and `11-0` can merge but `0-10` and `01-0` cannot merge directly.','The first pair has identical dash positions and differs in exactly one fixed coordinate, A. Its union is the cube `-1-0`, representing four rows, with product $B\\overline D$. The second pair has different dash positions; their union contains three rows and is not a cube. Dropping every disagreeing coordinate would invent row 0000 or other rows not licensed by either input cube. QM’s same-mask condition ensures that merging changes exactly one fixed dimension and doubles cardinality. Duplicate merged cubes can arise from several parent pairs and must be deduplicated, while all legitimate parents are marked as combined.','merge',None),
('Cube counts','How many syntactically distinct cubes of n variables have exactly k free coordinates? How many cubes exist in total?','Choose the k free positions in $\\binom nk$ ways, then assign each remaining position either zero or one in $2^{n-k}$ ways. The count is $\\binom nk2^{n-k}$. Summing over k gives $(2+1)^n=3^n$, including the all-free constant-one cube. These are possible cubes before checking any particular function; most may intersect its forbidden zero set. For n=4, the counts for k=0,1,2,3,4 are 16,32,24,8,1 and total 81. The number of Boolean functions is instead $2^{2^n}$, because each truth-table row chooses an independent output. Mixing these two spaces is a frequent counting error.','counts',None),
('Parity lower bound','Prove that odd parity of n inputs needs $2^{n-1}$ terms in a two-level SOP when no DC rows exist.','For n at least one, changing any single bit toggles parity. Every cube with a free bit contains an adjacent pair of opposite parity and therefore contains a forbidden zero. Consequently each valid implicant of odd parity fixes all n variables and covers exactly one required row. Exactly half of the $2^n$ rows have odd parity: toggling the first bit bijects the odd and even classes. Thus the minimum SOP needs $2^{n-1}$ n-literal minterms and $n2^{n-1}$ literal occurrences. An XOR gate tree can be much smaller; that changes the permitted gate basis and is not a counterexample to the two-level SOP lower bound.','parity',None),
('Threshold lower bound','For an n-input “at least t ones” function, where $1\\le t\\le n$, identify the prime implicants and minimum SOP cost.','A valid product must fix at least t inputs to one; otherwise all free bits could be zero and the threshold would fail. Fixing zero inputs is unnecessary because replacing a fixed zero with a free coordinate cannot decrease the number of ones. A prime therefore consists of exactly t positive literals. There are $\\binom nt$ such primes. Each row of Hamming weight exactly t is covered by its corresponding t-literal prime and no other, so every prime is essential. The optimum has $\\binom nt$ terms and $t\\binom nt$ literals. For n=4,t=3 this yields four three-literal terms, not one term for the all-one row plus arbitrary pairs.','threshold',None),
('POS through complement','Find a minimum POS for $F=AB+AC+BC$ and prove it.','The zero rows have at most one one: 000,001,010,100. They are covered in the complement by $\\overline A\\overline B$, $\\overline A\\overline C$, and $\\overline B\\overline C$. Each product is necessary because the zero row with its remaining variable one has no other owner. Applying De Morgan gives $F=(A+B)(A+C)(B+C)$. Each factor is zero on exactly its associated pair of zero rows and true on every required one. Three factors with six literals are therefore minimum under the two-level POS model. Expanding this POS recovers the majority SOP, but expansion is not needed to prove equivalence.','majority',None),
('Static-one hazard','For $F=\\overline A B+AC$, identify the vulnerable single-input transition and derive a hazard-free SOP.','With B=C=1, the transition of A between zero and one should leave F at one. The selected terms cover the two endpoints separately; unequal delays can briefly make both products zero. The consensus product BC contains both endpoints and is independent of A, so $F=\\overline A B+AC+BC$ holds the OR output high throughout that change. The added product is logically redundant because $BC=(A+\\overline A)BC$ and each part is absorbed by an original term. Logical redundancy can therefore be physically necessary. This proves removal of this static-one risk in the two-level SOP and single-input-change model; it does not establish freedom from arbitrary multilevel dynamic hazards.','hazard',None),
('Hazard pulse width','A falls at time zero in $F=AB+\\overline A C$, with B=C=1. Inverter delay is 3, each AND delay 1, OR delay 1. Use transport delay to calculate the output low interval.','Initially AB is one and the second product is zero. At time 1 the AB output falls. The inverter rises at time 3, so the second AND output rises at time 4. The final OR falls at time 2 and rises at time 5, yielding a three-unit low pulse. A consensus BC product, stable at one, prevents the OR input set from becoming all zero. Under inertial delay, a short pulse may be rejected according to the specific gate model; the transport calculation does not automatically describe every physical gate. State the transition direction, initial settled state and delay convention before reporting a width, because reversing A can reverse which path is slow.','timing',[2,5,3]),
('Static-zero dual','Show why $(A+B)(\\overline A+C)$ may have a static-zero hazard and repair it.','Set B=C=0. The function is zero for both A=0 and A=1, but the two OR factors can both become one briefly while A and its complement propagate through unequal paths. Multiplying by the consensus sum B+C, which remains zero, fixes the two-level POS realization: $(A+B)(\\overline A+C)(B+C)$. The added factor is logically redundant by the dual consensus theorem. The repair groups adjacent zero rows, whereas the SOP repair groups adjacent one rows. A static-zero hazard is a 0–1–0 excursion despite equal settled endpoint values; it is not an ordinary intended rising output. The gate and transition assumptions must accompany the claim.','hazard0',None),
('Required edges beyond required vertices','For $O=\\{5,6,7,8,9,15\\}$ and $D=\\{0,1\\}$ in four variables, find a minimum-cost prime SOP that removes static-one hazards only for transitions with both endpoints in O. Use lexicographic term/literal cost.','The required adjacent pairs are (5,7), (6,7), (7,15) and (8,9). Their respective necessary prime owners are `01-1`, `011-`, `-111` and `-00-`. They give $F=\\overline A BD+\\overline A BC+BCD+\\overline B\\overline C$, with cost (4,11). Each edge has only one valid prime capable of containing both endpoints, so every term is forced by edge obligations and the lower bound is achieved. The last cube assigns DC rows 0 and 1 to one, introducing realized edge (1,5), which is not jointly covered. If that transition is allowed, add $\\overline A\\overline C D$ or assign both DC rows zero and use the twelve-literal nonexpanded alternative. The eleven-literal certificate protects the stated O-to-O transition set only. Vertex coverage alone would allow dropping a bridge term and still reproduce the truth table, but could leave a static-one risk.','edgecover',None),
('Multi-output sharing','Let $F=AB+AC$ and $G=AB+BC$. Compare separate versus shared PLA product counts.','Separate SOP realizations list four product occurrences: AB and AC for F, AB and BC for G. A shared PLA uses three distinct products AB, AC and BC, with AB connected to both output OR gates. The two functions still need their own output connections. Counting distinct products gives three, while counting product-output connections gives four; these are different cost measures. Independently minimizing each output can miss useful common cubes in other instances, and a shared product must avoid the forbidden zero rows of every output to which it is connected. Sharing does not make AC a legal product for G: input 101 is a witness with AC=1 and G=0.','sharing',None),
('Factored versus two-level cost','Compare $F=A(B+C)(D+E)$ with its expanded two-level SOP.','Distribution yields ABD+ABE+ACD+ACE. Under two-level SOP counting this has four terms and twelve literal occurrences. The factored form has five literal occurrences in its expression tree, two two-input ORs and one three-input AND if arbitrary fan-in is allowed. Both compute the same function. A minimum SOP certificate proves optimality only in the specified two-level representation; it does not prove minimum gates in every multilevel technology. Factoring may also change delay, fan-out and hazard behavior. A question asking for “simplest” without fixing the representation or cost can therefore be underdetermined. Report both models and do not silently compare incompatible literal counts.','factoring',None),
('Shannon split and map planes','Derive a five-variable SOP when the E=0 and E=1 cofactors are both $AB+CD$.','Shannon expansion gives $F=\\overline E(AB+CD)+E(AB+CD)=(\\overline E+E)(AB+CD)=AB+CD$. Corresponding groups in the two planes join and eliminate E. If the cofactors differ, only cubes that occur in both planes can merge across E; separate groups cannot be joined just because their sizes match. With variable order A,B,C,D,E, plane indices must retain E as the least significant bit, so the two planes contain alternating indices. If E is the most significant variable, their index sets are 0–15 and 16–31 instead. Plane geometry must follow the declared index convention, not an unstated textbook arrangement.','shannon',None),
('Consensus proof','Prove $AB+\\overline A C+BC=AB+\\overline A C$ without relying on a picture.','Insert $A+\\overline A=1$ into BC, yielding $ABC+\\overline A BC$. Absorb ABC into AB and the other new term into $\\overline A C$. The result is exactly the original two terms. The proof licenses algebraic deletion for steady-state equivalence, but says nothing about path delays: BC can be a useful hazard-cover bridge. Conversely, if a term merely resembles a consensus term but uses incompatible literals, deletion must be justified again. A truth table over all eight assignments provides an independent verification of this identity. Keep algebraic reduction and hazard-constrained implementation as two distinct optimization problems.','consensus',None),
('Uniform costs and lower bounds','A residual chart has nine obligations and every candidate covers at most two. Is five necessarily attainable?','At least five candidates are required, because four can cover at most eight obligations even with no overlap. This is only a lower bound. Attainability depends on the actual chart: if candidates all cover pairs among the same eight obligations and the ninth has a singleton owner, further overlap constraints may require more. A valid upper bound must exhibit a complete cover. A packing bound can strengthen the result: find obligations no single candidate can cover together; each needs a distinct selected candidate. Equality between a demonstrated upper bound and a proved lower bound certifies optimality. Counting capacity alone cannot manufacture a missing compatible cover.','bound',None),
('All optimal covers versus one optimum','Does deleting one of two equal-cost identical-coverage candidates preserve all optimum expressions?','It preserves existence and value of at least one optimum: replace the deleted candidate by its equal-cost equivalent coverage partner, without uncovering any obligation. It does not preserve every expression, because a cover using the deleted candidate is no longer listed. This matters when two primes cover the same residual rows but differ on already covered or don’t-care rows. Their final Boolean expressions can differ outside the care set and remain equally optimal. For an “all minimum SOPs” question, retain the equivalence class and expand alternatives after reduction, or solve the full unpruned chart. A newly forced candidate after pruning is conditional, not a globally essential prime in the original chart.','allcovers',None),
('Input specification validity','A BCD circuit marks 10–15 as don’t-care. May an asynchronous transition from decimal 7 to 8 freely pass through those inputs?','The steady-state statement that only decimal codes are stored does not by itself forbid transient non-BCD combinations during a multi-bit change. Binary 7 is 0111 and 8 is 1000, so all four bits change; arbitrary arrival orders can pass through intermediate codes, including forbidden steady-state codes. DC simplification is safe only under the external timing/use contract, such as outputs sampled after settling, input qualification, or a protocol guaranteeing admissible transitions. K-map care-set correctness does not provide that contract. Likewise, single-input static-hazard coverage does not solve every multi-input functional hazard. Specify how outputs are used before claiming safe physical behavior.','contract',None)]
for title,stem,solution,kind,data in manual:add(title,stem,'**Derivation and interpretation.** '+solution+'\n\n**Examination check.** State the permitted representation, variable order and cost before applying the result. Verify a candidate against every care-row obligation; a familiar visual pattern does not replace a proof.',kind,data)
assert len(Q)==81,len(Q)
(B/'g_kmap-questions.json').write_text(json.dumps(Q,indent=2)+'\n')
d=json.loads((B/'exam-calibration/actual-items.json').read_text());auth=[]
for id in ['MS_CS_1405_Q99','Phd_CS_1405_Q22','MS_CE_1405_Q78']:
 q=next(x for x in d if x['id']==id);q=dict(q);q['qNumber']=q['questionNumber'];q['stem']=q['stem'].replace("don\\'t", "don't")
 if id.endswith('Q78'):
  q['options'][3]='$\\overline a bd+\\overline a bc+bcd+\\overline b\\overline c+\\overline a\\overline c$'
  q['solution']=q['solution'].replace('Option 4 misses required ones 8 and 9.','Option 4 includes specified zero row 4 through its extra term $\\overline a\\overline c$, so it violates the truth-table contract. The fifth product in the original printed option is retained in this corrected transcription.')
  q['solution']+='\n\n**Explicitly costed extension.** Under two-level prime SOP, single-input transitions with both endpoints in O, and lexicographic (terms, literals), the required edge owners force $\\overline a bd$, $\\overline a bc$, $bcd$, and $\\overline b\\overline c$. These give cost (4,11). A twelve-literal candidate with both DC outputs zero and complete realized-one edge protection is not optimal under that declared objective. The original question is retained as an ambiguity tutorial, not an unqualified single-answer test.'
 auth.append(q)
(B/'g_kmap-authentic.json').write_text(json.dumps(auth,indent=2)+'\n')
print('81 authored/course-inspired tasks and 3 verified archive revisits, including one ambiguity tutorial.')
