"""Distinct original derivations; no copied university problem statements."""
import json
from pathlib import Path
BASE=Path(__file__).resolve().parent;Q=[]
def code(s,lang='c'):return '\n\n~~~'+lang+'\n'+s+'\n~~~\n\n'
def add(title,stem,solution,origin='Original examination-style problem',kind='reasoning',data=None):
 Q.append(dict(id=f'PA{len(Q)+1:02}',title=title,stem=stem,solution=solution,origin=origin,difficulty='Medium–Hard',certificate=dict(kind=kind,data=data)))

add('A lower bound is not the first value','A flat representation declares indices -3 through 8 inclusive, four-byte elements and base address 1600 for the first element. Find the address of index 5, total storage and final occupied byte.',
 'There are $8-(-3)+1=12$ positions. Index 5 is eight positions after the first, regardless of the values stored. Its address is $1600+4(5+3)=1632$. Storage is $12\\cdot4=48$ bytes, so the last occupied byte is 1647 and the one-past boundary is 1648. Using 1600+4·5 would silently treat the lower bound as zero. The final byte and final element start differ by three. These are numerical layout statements; the negative declaration bound is not ordinary C array syntax.',kind='address',data=[1600,4,-3,8,5,1632])
add('Invert a two-dimensional row-major address','A matrix has row indices 2..6 and column indices -1..5. Each element occupies eight bytes; its first element starts at 4096. Which element starts at address 4312?',
 'The byte difference is 216, divisible by eight, so the element offset is 27. There are seven columns. Divide $27=3\\cdot7+6$: normalized row 3 and column 6 recover declared row 5 and column 5. Both lie in bounds. Thus the requested element is (5,5). The total extent is 35 elements, so 27 is valid. Dividing by the number of rows instead would invert a column-major representation. Address 4313 would be inside this element but not its start, so it would fail the element-start divisibility check.',kind='inverse',data=[4096,8,2,-1,5,7,4312,5,5])
add('Recover a missing column extent','In row-major storage of four-byte elements, A[1,2] starts at 1028 and A[3,1] starts at 1064. Both dimensions start at zero. Determine the number of columns, then the base address.',
 'Subtract the addresses to eliminate the base. The offset difference is $2C-1$ elements, so $4(2C-1)=36$ and C=5. Substitute the first observation: $1028=B+4(5+2)$, giving B=1000. A necessary consistency check is that columns 1 and 2 fit within five columns; at least four rows must exist because row 3 is present. The pair of observations does not determine the total row count. An answer that reports a unique complete matrix shape goes beyond the evidence.',kind='recover',data=[5,1000])
add('Distinguish row-major from column-major numerically','A 4×6 matrix begins at 800, uses two-byte elements and zero-based indices. Calculate the address of (2,3) in each layout and explain why the addresses need not differ at every index.',
 'Row-major offset is $2\\cdot6+3=15$, yielding 830. Column-major offset is $3\\cdot4+2=14$, yielding 828. Equality of the two layouts at an index requires $i(C-1)=j(R-1)$; here $5i=3j$. Both layouts start at the same address for (0,0), and the last element also occupies their common final slot. Therefore a single matching address does not identify the layout. The two formulas describe separately declared representations, not two legal interpretations of one C rectangular-array object.',kind='layouts',data=[4,6,2,3,15,14])
add('Three-dimensional mixed-radix recovery','A row-major array has extents 3×4×5, base 2000 and four-byte elements. Find the address of (2,1,3), then recover the indices of element offset 47.',
 'The selected offset is $(2\\cdot4+1)5+3=48$, giving address 2192. To invert 47, first divide by five: final index 2 and quotient 9. Divide 9 by four: middle index 1 and first index 2. Thus 47 belongs to (2,1,2), the immediate predecessor in the final axis. There are 60 elements, so both offsets are valid. A common error sums the three indices without strides, which loses the complete earlier planes and rows. The product-of-extents bound is a separate part of the inverse proof.',kind='mixed',data=[3,4,5,2,1,3,48])
add('A transpose changes the destination shape','A 2×5 row-major matrix is copied into a 5×2 transpose. Where does original flat offset 7 move, and where does offset 9 move?',
 'Divide by the original column count five: offset 7 is original (1,2). Transpose to destination (2,1), whose new row-major offset is $2\\cdot2+1=5$. Offset 9 is original (1,4), which moves to (4,1), destination offset 9. A fixed last element therefore does not imply that the whole transpose is unchanged. The destination stride uses two columns, not five. The mapping $iC+j\\mapsto jR+i$ is a bijection because transposing the recovered destination coordinates returns the original pair.',kind='transpose',data=[2,5,7,5,9,9])
add('Affine strides with a reversed axis','A numerical view has row stride 40 bytes and column stride -4 bytes. Its logical (0,0) starts at address 1020, and its shape is 3×6. Find the addresses of (2,5) and (1,0), and the minimum and maximum selected element-start addresses.',
 'The address map is $1020+40i-4j$. At (2,5) it yields 1080; at (1,0) it yields 1060. Since the row term increases and the column term decreases, the minimum start is (0,5) at 1000 and maximum is (2,0) at 1100. This view selects rows in reverse column order and has gaps between rows. Shape alone cannot substitute the usual dense row-major formula. The numerical model still needs a backing allocation covering every selected element; its bounds are logical bounds, not a proof of C pointer provenance.',kind='strides',data=[1080,1060,1000,1100])
add('Packed lower triangle and symmetric lookup','A zero-based symmetric 6×6 matrix stores its lower triangle including the diagonal, in row order, with eight-byte elements and base 3000. Find the stored address for logical (1,4).',
 'Symmetry redirects (1,4) to lower-triangle position (4,1). Four earlier rows contain $1+2+3+4=10$ elements. Add column offset one to obtain flat offset 11 and address 3088. The full packed length is $6\\cdot7/2=21$, not 36. Applying the lower-triangle formula directly to an upper-triangle coordinate would violate its domain and can collide with another row. This answer assumes symmetry of values and the specified storage convention; a general matrix cannot discard its upper half this way.',kind='lower',data=[6,4,1,11])
add('Packed upper triangle cannot reuse the lower formula','An upper-triangular 5×5 matrix includes its diagonal and is packed by rows. Find the flat offset of (2,4), and identify which coordinates occupy flat offset 9.',
 'Earlier row lengths are five and four, totaling nine. Within row two, column four is two positions after its first column two, so the offset is 11. Offset 9 is the beginning of row two and therefore belongs to (2,2). The general preceding-row count is $in-i(i-1)/2$; adding j-i yields the required offset. Row lengths decrease here, whereas they increase in lower-triangle storage. Both representations have 15 elements, but equal total capacity is not enough to identify their individual element positions.',kind='upper',data=[5,2,4,11,2,2])
add('Repeated jagged boundaries','Rows have lengths [2,0,3,1]. Construct the packed boundary array and recover the logical coordinate for flat offsets 2 and 5.',
 'Prefix accumulation gives Q=[0,2,2,5,6]. Offset 2 lies in row two, interval [2,5), at column zero; the empty row one also begins at boundary two but contains no element. Offset 5 lies in row three, interval [5,6), at column zero. Taking the first equal boundary would wrongly choose the empty row for offset 2. The valid reconstruction finds i with $Q[i]\\le o<Q[i+1]$. The final boundary 6 is one-past and has no coordinate. Every valid flat offset is covered by exactly one nonempty interval.',kind='jagged',data=[[2,0,3,1],[0,2,2,5,6]])
add('Diagonal offsets and loop count','For an n×n dense row-major matrix, derive the diagonal offsets and their sum, then evaluate for n=5. Count distinct positions selected.',
 'Coordinate (i,i) has flat offset $in+i=i(n+1)$ for i=0 through n-1. Their sum is $(n+1)n(n-1)/2$. At n=5 the offsets are 0,6,12,18,24 and the sum is 60. There are five positions, not 25; the arithmetic progression spacing is n+1. For n=0 the abstract selected set and sum are empty, while a C fixed zero-size declaration is a separate invalid construction. The sum of offsets does not equal the sum of matrix values unless values were specifically defined from their offsets.',kind='diagonal',data=[5,60])
add('When is a flat byte difference meaningful?','Two separate malloc allocations appear at numerical addresses 1000 and 1040 on one run. Each stores integers. Is their C pointer difference necessarily ten? Explain what additional facts are needed.',
 'No portable pointer-difference result follows. C subtraction requires both pointers to be within the same array object or its one-past boundary, with a representable ptrdiff_t result. Separate allocations fail that object relation even if they are adjacent numerically. Four-byte integers and the observed difference forty support only a numerical address calculation under that run’s representation. They do not create a shared array. If instead both pointers designate positions zero and ten of one live integer array, with legal endpoints and representable subtraction, the result is ten elements.',kind='provenance')

add('Interior negative indexing is ordinary pointer arithmetic','For int a[7]={2,4,6,8,10,12,14}, let p=a+4. Evaluate p[-3], p[2], and the complete range of legal element-access offsets k.',
 'p designates a[4]. Subtracting three selects a[1], so p[-3]=4; adding two selects a[6], so p[2]=14. Element access requires $0\\le4+k<7$, hence $-4\\le k\\le2$. Offset three forms the legal one-past pointer p+3 but cannot be dereferenced. This negative index is relative to the pointer’s current position, not Python’s end-of-sequence normalization. The legality follows from the shared live array object and bounds, rather than from the sign of the written subscript.',kind='interior',data=[7,4,-4,2,4,14])
add('Array sizeof and parameter sizeof','Assume sizeof(int)=4 and sizeof(int *)=8. For a real int a[9], evaluate sizeof a / sizeof a[0]. What does the same expression mean inside void f(int a[9])?',
 'In the caller’s actual-array scope, sizeof a is 36 and sizeof a[0] is four, so the quotient is nine. In f, the array-parameter declaration is adjusted to int *, even though nine appears in its syntax. sizeof a is therefore eight and the quotient is two; it is not a runtime length computation. The length must be passed or supplied by a valid interface contract. Different pointer sizes would change the misleading quotient, while the true caller array length would remain nine. No array elements are read by these non-VLA sizeof expressions.',kind='sizeof',data=[9,4,8,9,2])
add('Whole-array pointer versus first-element pointer','For int a[6] and sizeof(int)=4, compare the numerical advances of a+1 and &a+1. Why can both begin at the same storage?',
 'After expression conversion, a+1 has type int * and advances to the next integer, numerically four bytes in the given model. &a is a pointer to the whole six-int array, so &a+1 advances over 24 bytes to one past that entire array object. Their beginnings coincide because the first element starts at the array beginning. The identical beginning does not make their pointed-to types or strides identical. The whole-array one-past result is valid to form, but dereferencing it would ask for a nonexistent following array object.',kind='whole',data=[4,24])
add('A row pointer retains the inner extent','For int m[3][5] with four-byte integers, let p=m. Interpret p+2, *(p+2), and sizeof *(p+2). Is p correctly declared int **?',
 'The converted type is pointer to a five-int row: int (*p)[5]. Adding two advances two complete rows, forty bytes, to row two. Dereferencing gives the row-array lvalue m[2]; in ordinary expressions it can then convert to an int * to that row’s first element. sizeof on this row-array operand is 20. Declaring p as int ** would falsely expect stored pointer objects where integers are actually stored. A cast cannot repair that representation mismatch. Both the row index and any subsequent column index need their own valid bounds.',kind='rowpointer',data=[3,5,4,40,20])
add('Numerical adjacency does not erase a C subarray boundary','For int m[2][3], does a int *p=m[0] authorize p[4] merely because the matrix stores six adjacent integers?',
 'No portable justification follows from total adjacency. p points into the first three-element row subarray. Its permitted pointer formation reaches that row’s one-past boundary, but p[4] goes beyond it. Use m[1][1], whose row and column accesses are each within their proper array objects, to select the physically corresponding integer. A separately allocated genuine six-int flat buffer would allow flat[4]. The row-major numerical offset four is useful for deriving layout; it is not a replacement for the typed object-boundary requirements of C pointer arithmetic.',kind='subarray')
add('Partial initialization and definite values','At block scope consider int a[5]={9,2}; int b[5]; static int c[5]; Which values of a[4], b[4], c[4] are determined by these declarations?',
 'The initializer for a supplies two entries and zero-initializes the remaining three, so a[4]=0. c has static storage duration and no explicit initializer, which also zero-initializes all its integer elements, so c[4]=0. b is an uninitialized automatic array; b[4] cannot be assigned a portable numeric output by reading it. This is not an array-bound error—index four fits—but an initialization problem. Correct tracing separates valid storage, valid index and a usable stored value. Changing the scope or initialization of b can change that third condition.',kind='initialization')
add('Constraint violation is not a surprise numeric output','Which declarations or statements require a C diagnostic: int a[3]; int b[3]; a=b; int z[0];? How do you copy the contents instead?',
 'Array assignment a=b violates a constraint because an array object is not a modifiable lvalue for assignment. A fixed array bound zero also violates the array-declaration requirements; accepting it as an extension does not make it standard C. Declare valid arrays and copy elements in a bounded loop, or use an appropriate nonoverlapping byte-copy operation for suitable objects. An array name does not become a writable pointer variable merely because it often converts to a pointer in expressions. Rebinding a separate pointer changes the reference, not the original array contents.',kind='constraints')
add('One-past use and dereference are different questions','For a four-element initialized array, classify a+4, *(a+4), a+5 and (a+4)-a under C17.',
 'a+4 forms the permitted one-past pointer. Dereferencing it to read or write an element is invalid because there is no fifth element. a+5 exceeds even the permitted one-past boundary and is invalid pointer arithmetic. Subtracting a from a+4 is permitted within the same array relation and returns four elements if that result fits ptrdiff_t. The pointer’s permitted formation and the object’s permitted access are distinct checks. The legal subtraction does not require a read at the endpoint, and it does not make the endpoint into a real element.',kind='onepast')
add('Unsigned reverse loop trap','Explain why for(size_t i=n-1; i>=0; --i) use(a[i]); is incorrect. Give a version that also handles n=0 and prove its first and last accessed indices.',
 'The condition i>=0 is always true for unsigned size_t. At n=0, n-1 wraps before any valid index exists; at nonzero n, decrementing zero wraps to a huge value instead of stopping. Initialize i=n, test i>0, decrement i, then access a[i]. For n>0 the first body decrements to n-1. Each subsequent body selects one smaller index; the final access is zero, after which the next test fails. For n=0 the body is skipped. This proves n valid accesses and avoids relying on unsigned wraparound as termination.',kind='reverseguard')

add('A stride count with nonzero boundaries','A loop visits indices 3,7,11,... while i<26. List the final index and number of visits; derive the count without simulating every iteration.',
 'Write i=3+4t. The guard becomes $3+4t<26$, so $0\\le t\\le5$. There are six visits and the last index is 23. Equivalently the count is $\\lceil(26-3)/4\\rceil=6$. Replacing the strict guard by i<=26 happens to give the same result here because 26 is not in the progression; that coincidence is not a general equivalence. At boundary 27 the strict and non-strict guards would differ. An array hosting the loop must contain every selected index, not merely the number of visits.',kind='stride',data=[3,26,4,6,23])
add('Two different reduction initializations','For [5,5,2,2,7,1,1], compare the number of comparisons and successful minimum updates when initialized from the first element versus mathematical positive infinity, always using strict comparison.',
 'Initializing from the first element leaves six later comparisons. Strict decreases occur at value two and value one, so there are two updates. Initializing from infinity performs seven comparisons and the first five is an additional update, giving three. Equal occurrences never update under strict comparison, so the selected minimum position is the first one, index five. A non-strict comparison changes tie handling and update count. The number of loop comparisons is fixed here, whereas successful assignments depend on the data and initialization policy.',kind='minimum',data=[[5,5,2,2,7,1,1],6,2,7,3])
add('Weighted prefix invariant','For mathematical integers A=[2,-1,4,3], compute S=sum((i+1)A[i]) and give a loop invariant for the weighted scan.',
 'The contributions are 2,-2,12,12, so S=24. At boundary i the invariant is $0\\le i\\le4$ and $S=\\sum_{k=0}^{i-1}(k+1)A[k]$. It starts with the empty sum zero. When i<4, reading A[i] is valid and adding (i+1)A[i] extends the relation through that index. Advancing i preserves the boundary condition. At exit i=4 and the invariant gives the required result. A loop that uses i rather than i+1 computes a different weighting, so an unweighted total cannot serve as its certificate.',kind='weighted',data=[[2,-1,4,3],24])
add('Prefix construction and three ranges','Construct P for A=[3,-2,5,1,-4]. Find sums on [1:4), [0:5) and [3:3).',
 'Start P[0]=0 and accumulate each original element to obtain P=[0,3,1,6,7,3]. The first sum is P[4]-P[1]=7-3=4. The whole-array sum is P[5]-P[0]=3. The empty range subtracts P[3] from itself and is zero. P has six entries for five data elements because its indices label boundaries. Using P[r-1]-P[l] would omit the final included element and fail for empty ranges. After changing any data entry, update the affected prefixes before reusing these answers.',kind='prefix',data=[[3,-2,5,1,-4],[0,3,1,6,7,3]])
add('Difference-array range updates','Starting from five zeros, add 4 on [1:4), then subtract 2 on [2:5). Use a six-entry boundary difference array and reconstruct the result.',
 'The first update adds four at boundary one and subtracts four at boundary four. The second subtracts two at boundary two and adds two at boundary five. D becomes [0,4,-2,0,-4,2]. Accumulating its first five entries gives [0,4,2,2,-2]. The sixth entry is a sentinel that brings the running total back to zero beyond the array; it is not a sixth data value. The signs follow from starting and ending each added constant segment. Applying both plus signs at the right boundaries would continue the change after the intended interval.',kind='difference',data=[[0,4,-2,0,-4,2],[0,4,2,2,-2]])
add('Rectangle inclusion–exclusion','For A=[[1,2,3],[4,5,6]], build the boundary prefix table and find the sum of rows [0:2), columns [1:3).',
 'Include a zero row and column to obtain P=[[0,0,0,0],[0,1,3,6],[0,5,12,21]]. The requested sum is $P[2,3]-P[0,3]-P[2,1]+P[0,1]=21-0-5+0=16$. Directly, the selected entries are 2,3,5,6, also totaling 16. The table recurrence removes the overlap already counted by the top and left accumulated rectangles. Boundary indexing avoids substituting -1 at the top edge. The same four-term relation yields zero for an empty row or column interval.',kind='rect',data=[[[1,2,3],[4,5,6]],16])
add('An in-place recurrence uses modified predecessors','For A=[1,2,3,4,5], execute A[i]+=A[i-1] for i=1..4 in increasing order. Derive the general final relation to original values.',
 'The successive complete states are [1,3,3,4,5], [1,3,6,4,5], [1,3,6,10,5], and [1,3,6,10,15]. After processing index i, A[i] equals the sum of original entries zero through i. The already updated predecessor supplies the earlier prefix, so the operation implements a prefix accumulation. A formula $A_0[i]+A_0[i-1]$ would incorrectly assume an untouched predecessor. This can be proved by induction on i: the base leaves A[0] original, and each update adds the next original value to the established prefix.',kind='inplace',data=[[1,2,3,4,5],'forward',[1,3,6,10,15]])
add('Reverse execution computes another map','Execute the same update A[i]+=A[i-1] on [1,2,3,4,5] for i=4,3,2,1. Why is the result not a prefix sum?',
 'The reverse order yields [1,2,3,4,9], then [1,2,3,7,9], then [1,2,5,7,9], and finally [1,3,5,7,9]. At each update the predecessor index is lower and has not yet been changed. Therefore the final value for i>0 is $A_0[i]+A_0[i-1]$, not a growing prefix total. Index zero remains original. Both executions use valid indices and the same statement, so the difference is a data dependency rather than an undefined-behavior issue. A snapshot-based implementation would make the neighbor-sum intent explicit.',kind='inplace',data=[[1,2,3,4,5],'reverse',[1,3,5,7,9]])

add('An overlapping right move fails in forward order','For original A=[2,4,6,8,10,12], copy four entries from source offset 0 to destination offset 1, in increasing t. Give all resulting writes and compare with an original-value move.',
 'At t=0, A[1] receives 2. At t=1, the source A[1] has already become 2, so A[2] also receives 2. The same dependency propagates through t=2 and t=3. The final array is [2,2,2,2,2,12]. The desired snapshot move is [2,2,4,6,8,12]. All individual indices are valid; the failure is preservation of unread original values. Copying the same region in descending t avoids it, because each source is read before a higher destination overwrites it.',kind='move',data=[[2,4,6,8,10,12],0,1,4,'forward',[2,2,2,2,2,12]])
add('An overlapping right move succeeds in reverse order','Repeat the previous move but process t=3,2,1,0. State the unchanged region and a suffix invariant.',
 'Writes occur as A[4]=A[3]=8, A[3]=A[2]=6, A[2]=A[1]=4, and A[1]=A[0]=2. The final array is [2,2,4,6,8,12], while positions zero and five remain unchanged. Before a descending step t, every destination d+k for k>t contains original source s+k, and the remaining source prefix through s+t is unchanged. Since d>s, writing d+t cannot affect any still unread smaller source position. The invariant proves both the final destination and absence of damage outside the moved region.',kind='move',data=[[2,4,6,8,10,12],0,1,4,'reverse',[2,2,4,6,8,12]])
add('Leftward overlap needs the opposite direction','Move four entries of [2,4,6,8,10,12] from source offset 1 to destination offset 0. Compare increasing and decreasing processing orders.',
 'Increasing order writes values 4,6,8,10 into positions zero through three, giving [4,6,8,10,10,12]. Each destination is below the current source, so no future larger source index is overwritten. Decreasing order first writes A[3]=10; the next read of A[3] therefore repeats ten, eventually producing [10,10,10,10,10,12]. This reverses the safety relation of a rightward move. The correct rule depends on relative offsets and overlap, not on a universal preference for increasing or decreasing loops.',kind='move',data=[[2,4,6,8,10,12],1,0,4,'forward',[4,6,8,10,10,12]])
add('Bounds alone do not prove a copy contract','A copy_into loop has valid source/destination bounds but its postcondition compares final source and final destination segments. Explain why those bounds are insufficient if both parameters alias.',
 'Take a=[1,2,3,4], source start zero, target start one and length three. A forward loop produces [1,1,1,1]. Its final source segment and target segment happen to be equal, yet the intended original-value copy [1,1,2,3] was not achieved. In the opposite direction, a forward move produces [2,3,4,4] and even final source/target equality can fail. Therefore a meaningful specification must refer to original source values and control interference. Require disjointness, or use a snapshot/overlap-safe move. The CMU array-copy exercise is extended here precisely to expose this missing obligation.',origin='Course-inspired extension — CMU 15-122 Lecture 3, exercise 2',kind='copycontract')
add('Copy a segment with a complete proof','For initialized A of length n and 0≤l≤r≤n, construct a distinct B of length r-l with B[k]=original A[l+k]. State initialization, preservation, exit and termination.',
 'Initialize t=0 and use the invariant $0\\le t\\le r-l$ plus equality for all copied positions k<t. Initially the equality is vacuous. When t<r-l, destination t is valid and source l+t satisfies $l\\le l+t<r\\le n$. Writing that original source extends the equality through k=t; distinct storage ensures that the source is unchanged. Advance t to preserve the bound. At exit t=r-l and every result position satisfies the contract. The nonnegative variant r-l-t decreases each time. When l=r, allocate/represent a distinct empty result appropriately without a zero-size fixed C declaration.',origin='Course-inspired extension — CMU 15-122 Lecture 3, exercise 1',kind='segmentproof')
add('Insertion shifts and the end case','A logical sequence [3,6,9,12] occupies the first four positions of capacity six. Insert 7 at index two. Give the write order, new contents and shift count; compare insertion at index four.',
 'Move original index three to four, then index two to three, then write seven at index two. The logical result is [3,6,7,9,12], length five. There are n-k=2 shifts; descending movement preserves the original values. Insertion at boundary four uses zero shifts and writes only the new last value. Boundary n is valid for insertion although it is not a valid old element index. Capacity must permit the new length, and spare positions need not have meaningful initialized values before they are assigned.',kind='insert',data=[[3,6,9,12],2,7,[3,6,7,9,12],2])
add('Deletion changes length rather than erasing storage','Delete index one from [3,6,9,12,15] using stable compaction. How many shifts occur and what may remain in the spare slot?',
 'Move indices two, three and four left once, yielding the logical prefix [3,9,12,15] and length four. There are n-k-1=3 shifts. The physical slot at old index four can still contain fifteen; it is outside the logical sequence and need not be zeroed for correctness. Reading it as an allocated initialized element is a different question from including it in the container’s valid logical contents. Forward copy is safe because each write is below unread source positions. Deleting the last logical element would require no shifts.',kind='delete',data=[[3,6,9,12,15],1,[3,9,12,15],3])
add('Reverse a half-open segment exactly','Reverse A[1:6) in [0,1,2,3,4,5,6]. List the swapped pairs and final sequence. Why is the central element untouched?',
 'The segment length is five, so there are floor(5/2)=2 swaps: (1,5) and (2,4). The final array is [0,5,4,3,2,1,6]. Index three maps to itself, so writing it again is unnecessary. An invariant fixes completed pairs to the reversed original values and leaves the intervening middle original. Using r instead of r-1 for the first high index would incorrectly include index six, outside the requested segment. Length zero or one requires no swaps and is already reversed.',kind='reverse',data=[[0,1,2,3,4,5,6],1,6,[0,5,4,3,2,1,6]])
add('Three reversals implement left rotation','Rotate [0,1,2,3,4,5,6] left by three using three segment reversals. Show each intermediate state and explain the block algebra.',
 'Reverse the first block to get [2,1,0,3,4,5,6]. Reverse the second block to get [2,1,0,6,5,4,3]. Reverse the whole sequence to obtain [3,4,5,6,0,1,2]. If the original is XY, the first two stages produce reverse(X) reverse(Y), and reversing that concatenation gives YX. This proves the rotation without assuming particular values. Normalize k modulo n only when n>0. The method uses constant auxiliary element storage and linear swaps, whereas a copied result requires separate output storage.',kind='rotate',data=[[0,1,2,3,4,5,6],3,[3,4,5,6,0,1,2]])
add('Rotation cycles and visit count','For a 12-element sequence rotated left by eight, determine the number and length of permutation cycles, and list the cycle beginning at index zero.',
 'The step permutation is addition by eight modulo twelve. Since gcd(12,8)=4, there are four cycles, each of length three. The cycle from zero is 0→8→4→0. Distinct starting representatives can be 0,1,2,3. Repeating a cycle from another already visited member would duplicate work. The cycle length is the smallest positive t with 12 dividing 8t, namely three. All twelve indices appear across the four disjoint cycles; the direction used to move values must match whether the map denotes original-to-destination or destination-to-source.',kind='cycles',data=[12,8,4,3])
add('A stable read/write filter','Remove odd entries from [5,2,7,4,6,9,8] in place without changing the order of retained entries. Give final logical contents and explain why writes cannot destroy unread data.',
 'Use read r from zero upward and write w starting at zero. Copy a[r] to a[w] only when the entry is even, then increment w. Retained entries are 2,4,6,8, giving logical length four and prefix [2,4,6,8]. At every boundary $0\\le w\\le r\\le7$, and the output prefix equals the retained original entries from the processed prefix. Because w≤r, a retained write affects the current or an earlier position, never a larger unread position. Stability follows because retained values are appended in original encounter order.',kind='filter',data=[[5,2,7,4,6,9,8],[2,4,6,8]])
add('Dependency analysis of a two-pass difference transform','For A=[3,5,9,10], compute the adjacent differences A[i]-A[i-1] for i>0 in place while retaining A[0]. Which loop direction gives original differences?',
 'Process from index three down to one. The writes are 10-9=1, then 9-5=4, then 5-3=2, so the final sequence is [3,2,4,1]. Each predecessor is still original when read. Forward processing first changes index one to two; index two then reads that changed two and becomes seven, and the final index becomes three. That wrong result is [3,2,7,3]. The desired difference map is the inverse of a forward prefix accumulation when all arithmetic is exact. Direction follows from which neighbor must remain original.',kind='difftransform',data=[[3,5,9,10],[3,2,4,1]])

add('Python single indices and clipped slices','For a=list(range(6)), evaluate a[-2], a[-8:20:3] and a[8:20]. Which corresponding single-index access raises an exception?',
 'The single index -2 normalizes to four and returns 4. For the second expression, start -8 clips to zero and stop 20 clips to six; step three selects indices zero and three, giving [0,3]. The third slice starts beyond the end and clips both boundaries to six, producing []. A single access a[8] raises IndexError, as does a[-8]. This difference is deliberate: slice boundaries can be clipped while an element request needs an actual element. It is incorrect to infer single-access safety from an empty slice at similar written bounds.',kind='python',data=['a=list(range(6));result=(a[-2],a[-8:20:3],a[8:20])',[4,[0,3],[]]])
add('Omitted negative stop versus explicit -1','For a=list(range(7)), evaluate a[::-1], a[:-1:-1] and a[5:0:-2]. Explain the stop semantics.',
 'The omitted negative-step start defaults to six, and the omitted stop is a before-first sentinel, so the reversal is [6,5,4,3,2,1,0]. In a[:-1:-1], the explicitly supplied -1 normalizes to six. The start is also six, and a strict decreasing progression cannot begin above that stop, so the result is empty. The third slice visits indices 5,3,1 and returns [5,3,1]. Replacing an omitted negative stop with written -1 is therefore not a harmless spelling change. Normalize the slice before counting its selected indices.',kind='python',data=['a=list(range(7));result=(a[::-1],a[:-1:-1],a[5:0:-2])',[[6,5,4,3,2,1,0],[],[5,3,1]]])
add('Extended slice replacement count','For a=[0,1,2,3,4,5], assign a[1:6:2]=[9,8,7]. What is the result? Why does replacing it with [9,8] fail?',
 'The selected indices are 1,3,5, so three replacement values produce [0,9,2,8,4,7]. An extended slice whose step is not one cannot change the number of selected slots, and a two-item replacement raises ValueError instead of shrinking the list. Ordinary step-one slice assignment uses a different rule and can change length. The resulting list’s unselected values at indices zero, two and four remain unchanged. Count the normalized index progression before matching replacement length; the written difference between stop and start is not the number of selected entries.',kind='python',data=['a=[0,1,2,3,4,5];a[1:6:2]=[9,8,7];result=a',[0,9,2,8,4,7]])
add('Ordinary slice assignment can change length','For a=[1,2,3,4,5], assign a[1:4]=[8,9], then a[2:2]=[6,7]. Give both states and lengths.',
 'The first replacement removes three selected entries and inserts two, giving [1,8,9,5] of length four. The empty slice at boundary two then inserts two values before the old entry there, yielding [1,8,6,7,9,5] of length six. A slice of length zero can be an insertion location; it is not an element access. The second operation uses the current list positions after the first length change. Treating both statements as updates to original indices would select the wrong position. These Python semantics are not fixed-capacity C array assignment.',kind='python',data=['a=[1,2,3,4,5];a[1:4]=[8,9];first=a[:];a[2:2]=[6,7];result=(first,a)',[[1,8,9,5],[1,8,6,7,9,5]]])
add('Outer copy and inner alias','Compute the final a and b:'+code('a = [[2], [5]]\nb = a[:]\nb[0].append(7)\nb[1] = [9]\nresult = (a, b)','python'),
 'The slice creates a distinct outer list but copies the two inner references. Appending seven changes the shared first inner list, so both outer lists observe [2,7]. Assigning b[1]=[9] changes one slot in b’s outer list and does not redirect a’s second slot. Therefore a=[[2,7],[5]] and b=[[2,7],[9]]. The two outer lists are not identical, while their first entries are identical objects. This trace separates mutation of a referenced object from replacement of a reference slot; the word copy alone does not say which level is independent.',origin='Course-inspired extension — UC Berkeley CS61A, Composing Programs §2.4.2',kind='python',data=['a=[[2],[5]];b=a[:];b[0].append(7);b[1]=[9];result=(a,b)',[[[2,7],[5]],[[2,7],[9]]]])
add('Repeated rows share one inner object','Compare bad=[[0]*4]*3 with good=[[0]*4 for _ in range(3)] after setting index [1][2] to nine in each.',
 'bad contains three references to one inner row. Modifying that row through the second reference changes the displayed value in all three rows, giving three copies in appearance of [0,0,9,0]. good creates three distinct rows, so only its second row changes. Repetition copies references, not recursively referenced objects. Distinct outer slot positions can therefore share one inner identity. For a matrix whose rows should vary independently, create the row inside the comprehension. A shallow outer copy of bad still preserves the same inner sharing and cannot repair it.',kind='python',data=['bad=[[0]*4]*3;good=[[0]*4 for _ in range(3)];bad[1][2]=9;good[1][2]=9;result=(bad,good)',[[[0,0,9,0],[0,0,9,0],[0,0,9,0]],[[0,0,0,0],[0,0,9,0],[0,0,0,0]]]])
add('Deletion during iteration skips shifted entries','Trace:'+code('a = [2, 4, 6, 7]\nfor x in a:\n    if x % 2 == 0:\n        a.remove(x)\nresult = a','python'),
 'The iterator first selects two at position zero and removes it, leaving [4,6,7]. Its next index is one, which now contains six rather than four, so it removes six and leaves [4,7]. The next index is two, beyond the current list, and iteration ends. Final result is [4,7], despite four also being even. The issue is index advancement combined with leftward shifting, not a failure of the predicate. A new filtered list [x for x in a if x%2] or the proved read/write compaction avoids skipping unread values.',kind='python',data=['a=[2,4,6,7]\nfor x in a:\n if x%2==0:a.remove(x)\nresult=a',[4,7]])
add('Identity versus equal contents','Let a=[[1],[2]], b=a[:], c=[row[:] for row in a]. Evaluate a==b, a is b, a[0] is b[0], and a[0] is c[0]. What later mutation distinguishes b from c?',
 'Initially a==b is true because the contents compare equal, but a is b is false because the outer slice made a different list. a[0] is b[0] is true because the shallow copy retained its inner references. a[0] is c[0] is false because the row slicing created distinct inner lists. Appending to a[0] also changes b[0] but not c[0]. The row-copy construction gives independence at this two-level example; it is not a universal deep copy when rows themselves contain mutable nested objects.',kind='python',data=['a=[[1],[2]];b=a[:];c=[row[:] for row in a];result=(a==b,a is b,a[0] is b[0],a[0] is c[0])',[True,False,True,False]])
add('Mapped values and filtered values are different outputs','For a=[-2,0,3,5], compare [x*x for x in a if x>0] with [x for x in a if x*x>0], then derive the first output sum.',
 'The first expression filters original positive values three and five, then maps them to nine and twenty-five, giving [9,25] and sum 34. The second filters all nonzero original values because their squares are positive, but returns those original values, giving [-2,3,5]. The order and position of the map/filter expressions determine the result. The original input list is unchanged in this example because evaluating squares and comparisons does not mutate its integer objects. The output comprehension creates a new list but that alone does not imply deep copying for arbitrary mapped objects.',origin='Course-inspired extension — UC Berkeley CS61A, Composing Programs §2.3.3',kind='python',data=['a=[-2,0,3,5];result=([x*x for x in a if x>0],[x for x in a if x*x>0])',[[9,25],[-2,3,5]]])
add('Code points, UTF-8 bytes and display units','For Python s=\"Aé\", give len(s), len(s.encode(\"utf-8\")), and the number of stored characters in a UTF-8 C array initialized with the same two symbols plus a terminator. State the encoding assumption.',
 'Python counts two Unicode code points, so len(s)=2. UTF-8 encodes A in one byte and é in two, giving three encoded bytes. A C char array containing those UTF-8 bytes and a final zero occupies four C bytes in the stated eight-bit-byte UTF-8 environment, while its string byte length is three. None of these automatically counts grapheme clusters in more complex text. The C source/execution encoding assumption must be explicit; a literal containing a non-ASCII symbol need not use UTF-8 on every implementation. Mixing byte and code-point indices gives incorrect bounds.',kind='python',data=['s=\"Aé\";result=(len(s),len(s.encode(\"utf-8\")))',[2,3]])

add('Embedded zero separates capacity from string length','In C, char s[8]={\\x27a\\x27,\\x27b\\x27,0,\\x27c\\x27}; determine sizeof s, strlen(s), s[3] and whether later initialized entries extend the string.',
 'The real array has capacity eight bytes because sizeof(char)=1. Its first zero is at index two, so strlen(s)=2. s[3] is the initialized character c, and the remaining unspecified initializer entries are zero. Later initialized bytes exist as array elements but are not part of the string beginning at s. Thus a string length does not identify the array capacity, and a terminator does not end the storage object. A bounded array access to index three is valid even though a string operation starting at index zero stops earlier.',kind='string',data=[8,2])
add('An exactly filled C character array lacks a terminator','Classify char a[3]=\"cat\" and char b[]=\"cat\" in C17, then evaluate which may be passed to strlen without another change.',
 'C permits the first initializer to fill the three-element array with c,a,t and omit the zero because there is no remaining slot. The declaration itself is allowed, but a is not a valid terminated string. strlen(a) cannot be assigned a portable result; it may read beyond its storage seeking a zero. b has four elements including the terminator and strlen(b)=3. The distinction is specifically C; language variants can differ. A known capacity and initialized characters are not sufficient—the string operation requires an accessible terminating zero.',kind='string')
add('Writable array versus literal target','Contrast char a[]=\"cat\"; const char *p=\"cat\"; a[0]=\\x27b\\x27;. What changes, and why is casting away const not permission to modify the literal?',
 'The array a owns four writable character objects initialized from the literal, so the assignment changes its string to bat while keeping the terminator. p designates a separate string-literal array and still presents cat. A string literal is not a permitted modification target in C even if a cast changes the written pointer type. Type casts do not change storage permissions, object origin or lifetime. The caller’s array and the literal can have equal initial values without being the same modifiable object. sizeof a counts its array, whereas sizeof p counts the pointer.',kind='literal')
add('Bounded length finds a terminator or reports absence','For bytes [65,66,67,0,88] with capacity five, derive a safe length scan. What should the same scan report for [65,66,67,88,89]?',
 'Initialize k=0 and continue while k<capacity and a[k]!=0, checking the bound before the element access. The first buffer returns k=3 and reports a terminator found. The second reaches k=5 without reading a[5] and reports absence, not a valid string length for an unbounded string operation. The invariant states that every earlier position is nonzero and all tested indices were within storage. Short-circuit evaluation protects the current access at the boundary. Returning five without the absence status would confuse a buffer length with a verified string length.',kind='boundedlength',data=[[65,66,67,0,88],3])
add('Naive matching comparison count','Search pattern \"aaab\" in text \"aaaaab\" by comparing left to right at starts zero upward, stopping each candidate at its first mismatch. Find the first match and total character comparisons.',
 'There are three candidate starts, zero through two. At start zero, the first three a characters match and the fourth comparison mismatches a against b, costing four. Start one has the same four-comparison failure. Start two matches all four characters, so the result index is two and total comparisons are twelve. The worst-case bound $(6-4+1)4=12$ is attained here. Counting only failed comparisons would report two and omit successful tests. A match stops the search, so later candidate costs would not be charged even if they existed.',kind='search',data=['aaaaab','aaab',2,12])
add('An empty pattern and a longer pattern','Specify first-match results for text \"abc\" with patterns \"\" and \"abcd\". Why should unsigned n-m not be calculated before the length comparison in C?',
 'Under the explicit convention, the empty pattern matches at boundary zero and requires no character comparisons. The four-character pattern cannot fit within the three-character text, so it fails immediately. If n and m are size_t, n-m wraps when m>n and can create a huge apparent candidate count. Test the empty-pattern convention and m>n case first, then subtract. A candidate start is a boundary, whereas successful nonempty matching must keep all compared positions within actual elements. The failure case is determined by lengths and does not require examining text contents.',kind='searchboundaries')
add('Appending requires one more slot than the visible result','A writable C buffer of capacity nine contains \"abcd\". Can it append \"wxyz\" with a valid final terminator? What changes if capacity is eight?',
 'The initial length is four and the appended length is four. The result needs $4+4+1=9$ slots, including the zero at index eight, so capacity nine is exactly enough. Capacity eight can store all eight visible characters but has no slot for the required terminator; it cannot hold that complete string. The proof must establish source termination, destination capacity and any overlap restrictions of the chosen copy operation. Counting only visible symbols is the standard off-by-one distractor. An unused spare slot before the operation is not automatically a verified terminator.',kind='append',data=[4,4,9])
add('Argument pointer sentinel versus character sentinel','Assume argc=3 and arguments are \"prog\", \"x\", \"yz\". Identify argv[2][1], argv[2][2], argv[3], and why argv[3][0] is invalid.',
 'argv[2] points to the third argument string yz. Its element one is z and element two is the terminating zero character. argv[3] is the null pointer sentinel required after the argc argument pointers. Dereferencing argv[3] to request its first character is invalid; it does not point to a one-character empty string. There are three string pointers followed by a pointer sentinel, and each pointed-to string has its own character terminator. Confusing these two representation levels loses the distinction between an array of pointers and an array of characters.',kind='argv')
add('A signed char cannot be passed blindly to ctype','A byte 0xE9 is stored in a char on an implementation where char is signed. Explain why toupper(s[i]) may violate its contract and how to prepare the argument.',
 'The promoted char can be a negative int that is neither EOF nor representable as unsigned char. C’s character-classification and conversion functions require EOF or an unsigned-char-representable value. Convert the stored byte to unsigned char before the call, for example toupper((unsigned char)s[i]). This fixes the argument-domain issue, not general Unicode uppercasing. In UTF-8 the byte may be one part of a multi-byte code point, and bytewise conversion is not a full text transformation. Stating an ASCII-only domain can simplify a separate arithmetic exercise but cannot justify passing arbitrary negative char values.',kind='ctype')
add('Returned substring pointer and lifetime','A C search returns a pointer to a matching character inside its text argument. What ownership and lifetime facts permit later use? Contrast a pointer into a local automatic buffer returned by the function.',
 'The returned pointer designates part of the original text storage, not a new allocated copy. Later access requires that the text object remain alive and that its intended characters stay initialized and within bounds. The search cannot transfer ownership merely by returning an interior pointer; freeing that interior pointer is not equivalent to freeing an owning allocation pointer. A pointer into a local automatic buffer becomes invalid when that buffer’s lifetime ends at function return. A numerically plausible address or unchanged bytes observed later do not restore the ended object lifetime.',kind='lifetime')

add('Exact doubling work for a particular length','An initially empty container reserves capacity one and doubles when full. After 13 successful appends, find final capacity, total elements copied during expansions, total writes including new values and peak simultaneously allocated slots.',
 'Expansion capacities are 2,4,8,16, copying the old live counts 1,2,4,8. Final capacity is 16 and copy work is 15. Adding the thirteen new-element writes gives 28 writes. During the final expansion, blocks of capacity eight and sixteen coexist, so the peak is 24 slots. Logical length is thirteen, distinct from both final capacity and peak capacity. An individual ninth append copies eight elements before its own write; amortized constant cost therefore does not imply constant cost for that operation.',origin='Course-inspired extension — Stanford CS106B Lecture 17, expansion model',kind='doubling',data=[13,16,15,28,24])
add('General doubling bound and exact powers','Prove copied-element work is c-1 when final capacity c is a power of two reached from capacity one. Relate it to final positive length n, including n=1.',
 'Each expansion copies its previous full capacity, so the sum is $1+2+\\cdots+c/2=c-1$. At c=1 no expansion occurs and the empty sum is zero, matching the formula. Choosing the least power of two at least n gives $n\\le c<2n$, hence c-1<2n. Including new writes gives less than 3n. If n itself is a power of two, c=n and the exact copy work is n-1. These relations assume no deletions, failed allocations or costly element copies; they count element assignments rather than every machine instruction.',kind='doublingproof')
add('Additive growth causes a quadratic sum','Initial capacity is three; whenever full it grows by three. After 12 appends, calculate copied elements and derive the order for n=3m appends.',
 'For twelve appends, expansions copy 3,6,9 live elements and final capacity is twelve, so copy work is 18. For n=3m, expansions copy $3,6,\\ldots,3(m-1)$, totaling $3m(m-1)/2$. Since m=n/3, the leading term grows quadratically in n. New-element writes add only n. A fixed additive increment therefore cannot use the same geometric bound as doubling. The exact sum depends on whether initial allocation is counted and whether a capacity expansion happens only before an append that would exceed current capacity; those conventions are stated here.',kind='additive',data=[12,3,18])
add('A growth factor other than two','Capacity begins at one and triples when full. After ten appends, find final capacity and copy work. Explain why this does not prove tripling universally better or worse than doubling.',
 'Full capacities one, three and nine are copied before reaching capacity 27. Thus copy work is 1+3+9=13 and new writes add ten. The total is 23 element writes, but 17 final spare slots remain. With doubling, ten appends reach capacity sixteen and copy fifteen elements, so that particular comparison trades less copying for more reserved storage. Different operation counts and memory constraints can favor different factors. Both fixed factors above one give linear total copy work under the simple model; the phrase “most efficient” requires a specified objective and cost model.',kind='tripling',data=[10,27,13])
add('Allocation overflow and an exact boundary','Assume SIZE_MAX=65535 and an eight-byte element type. What is the largest n for which n*sizeof(element) fits, and why is checking the wrapped product afterward insufficient?',
 'The multiplication is representable exactly when $n\\le\\lfloor65535/8\\rfloor=8191$. That maximum requests 65528 bytes. n=8192 would need 65536 and wraps to zero in the stated unsigned arithmetic. Comparing a wrapped product with SIZE_MAX cannot detect the original mathematical overflow because every wrapped unsigned result already lies in the type’s range. Check n against the quotient before multiplication, then handle allocation failure. This arithmetic certificate permits a byte-count computation; it does not guarantee that memory is available or that all created elements have been initialized.',kind='allocation',data=[65535,8,8191])
add('A failed realloc must not lose the owner','Explain the problem with p=realloc(p,new_bytes) when failure is possible. What references remain valid after a successful move versus after failure?',
 'On allocation failure, realloc returns null while the original allocation remains valid. Assigning the result directly to the sole owner p overwrites the only saved original pointer and can leak that block. Store the result in a temporary, test success and update p only afterward. On successful reallocation, use the returned pointer; old interior pointers and references into the prior allocation are not retained as valid access handles, even if observed addresses seem unchanged. On failure, the old allocation and its existing valid interior pointers remain available. State new_bytes>0 here to avoid version-dependent zero-size corner cases.',kind='realloc')
add('Shifts and growth costs in one insertion','A full dynamic sequence of length/capacity eight inserts at index two after doubling. Count old-element copies, subsequent shifts, new-element write and peak slots under an implementation that first expands then shifts.',
 'Expansion copies all eight old live elements into capacity sixteen. Insertion then shifts n-k=6 elements from indices seven down to two, followed by one new-element write. The specified implementation therefore performs fifteen element writes: eight copies, six shifts and one new write. Peak capacity during expansion is 8+16=24 slots. A different implementation could copy directly into final shifted positions and avoid some duplicate assignments, so the count is tied to the declared execution strategy. The logical result still needs length nine and stable preservation of the old order around the inserted value.',kind='growthinsert',data=[8,2,8,6,15,24])
add('Shrink threshold thrashing','A container of capacity eight shrinks to four as soon as length becomes four, and doubles when a fifth element is inserted. Explain the cost of repeatedly deleting and re-appending the fifth item.',
 'Each deletion reaches length four and copies four elements into a capacity-four block. The next append finds that block full, copies four elements into capacity eight and writes the new item. Repeating the pair causes eight copied elements every cycle despite the sequence length fluctuating by only one. For a scaled capacity c with shrink at c/2, the pair can cost a linear number of copies in c. A lower shrink threshold, such as one quarter with a suitable minimum-capacity policy, leaves room for many operations before the opposite resize and prevents this immediate oscillation.',kind='hysteresis')
add('A precise cold cache-line comparison','An 8×8 row-major integer matrix uses four-byte elements and starts on a 32-byte line boundary. With one cache line, count line fills for complete row-major and column-major traversals, assuming every new line evicts the previous one.',
 'One cache line holds eight integers, exactly one row. Row-major traversal reads all eight entries of a row after one fill and then moves to the next line, totaling eight fills. Column-major traversal visits rows zero through seven for each column; every next access selects a different line and the one-line cache cannot retain an earlier row. It therefore causes 64 fills. Both traversals perform 64 element reads. The conclusion depends on alignment and the explicitly one-line cache; a cache large enough to retain all eight rows would have different reuse behavior.',kind='cache',data=[8,8,8,64])
add('Cold lines for a misaligned contiguous scan','Read eleven consecutive four-byte elements beginning at byte offset eight within a 16-byte cache line. Count distinct lines touched in a simple no-prefetch model.',
 'The read occupies bytes from relative offset eight through $8+44-1=51$. Line indices range from floor(8/16)=0 through floor(51/16)=3, so four distinct lines are touched. Dividing the total 44 bytes by sixteen and rounding up gives three, but misses the partially occupied initial and final lines due to alignment. The exact interval formula is $\\lfloor(B+nw-1)/L\\rfloor-\\lfloor B/L\\rfloor+1$ for positive n. A zero-length read touches no lines and must be handled before subtracting one.',kind='cacheinterval',data=[8,11,4,16,4])

add('Circular buffer length distinguishes full and empty','A circular buffer has capacity seven, head five and logical length four. List physical indices in logical order and the next append position. What does head=tail alone reveal?',
 'Logical offsets zero through three map to $(5+t)\\bmod7$, giving physical indices [5,6,0,1]. The next append position is (5+4) mod seven, namely two. With a separate length, full is n=7 and empty is n=0. In both cases head can equal tail, so equality of those indices alone cannot distinguish them. Another design reserves one unused slot, but that changes usable capacity and must be stated. Modulo requires positive capacity; the logical-bound proof also requires 0≤n≤c and 0≤head<c.',kind='ring',data=[7,5,4,[5,6,0,1],2])
add('Rectangular transpose cycle','For a 2×3 row-major sequence, list the original-to-destination transpose permutation and its nontrivial cycle. Why is a square diagonal-swap loop insufficient?',
 'The coordinate map sends original offsets [0,1,2,3,4,5] to destination offsets [0,2,4,1,3,5]. Thus zero and five are fixed, and the nontrivial cycle is 1→2→4→3→1. A square matrix’s pairwise (i,j)↔(j,i) swaps rely on equal source and destination shapes. Here the new row width is two rather than three, so the physical permutation has a four-cycle instead of only disjoint transpositions. A cycle algorithm must retain one temporary value and move in the appropriate direction, or use separate output storage.',kind='transposecycle',data=[[0,2,4,1,3,5],[1,2,4,3]])
add('Packed triangular inversion without a floating shortcut','A lower-triangular row-major packing including the diagonal has flat offset 17. Recover its row and column, and give an exact method that avoids floating rounding.',
 'Find i with $i(i+1)/2\\le17<(i+1)(i+2)/2$. Triangular starts are 0,1,3,6,10,15,21, so i=5 and j=17-15=2. The coordinates are (5,2), requiring at least six rows in the containing matrix. A binary search over triangular starts gives an exact integer inversion when products are safely computed; blindly flooring a floating square-root expression can misclassify large boundary values. The column must satisfy 0≤j≤i after inversion. The address of an interior byte would first require conversion to an aligned element offset.',kind='triangleinverse',data=[17,5,2])
add('Pairwise distinct index count','How many pairs (i,j) satisfy 0≤i<j<n, and how does it differ from a loop that includes i=j? Derive from row lengths.',
 'For each i, there are n-i-1 possible larger j values. Summing lengths n-1 down to zero gives n(n-1)/2. Including the diagonal adds n pairs and produces n(n+1)/2. At n=5 the counts are ten and fifteen. A rectangular n² iteration counts ordered pairs and includes both orientations and the diagonal, so it is not the same region. The triangular count also explains the number of swaps in square transposition. A finite-type implementation must preserve the products or reduce a factor before multiplying.',kind='pairs',data=[5,10,15])
add('A minimum interface can be safe with a stronger contract','The C0 course asks what useful function can inspect an array without an ordinary length parameter. Discuss the role of a known nonempty contract versus an arbitrary array with no such contract.',
 'For an arbitrary array that may be empty and whose length cannot be read in ordinary C0 code, no unconditional element access is proved safe. However, a stronger contract that guarantees at least one element allows a useful function returning A[0], even without a length parameter. A sentinel-terminated contract can also permit a specified scan, provided the sentinel is guaranteed within accessible storage. The source’s negative answer depends on the unconstrained interface, not on a universal impossibility of array functions without a separate length argument. Precisely state which information the caller promises before rejecting or constructing an implementation.',origin='Course-inspired extension — CMU 15-122 Lecture 3, exercise 3',kind='interface')
add('Signed sum range and cancellation','For signed 32-bit integers, A=[2147483647,1,-1] has mathematical sum 2147483647. Is the straightforward left-to-right int accumulator safe? Give a safer representability argument.',
 'The second addition mathematically produces 2147483648, outside the signed 32-bit range, so the straightforward C int accumulation overflows even though the final mathematical sum fits. Signed overflow is not a guaranteed wraparound computation. Accumulate in a type wide enough for every partial sum, or check each addition against its representable limits. Reordering these particular terms to combine one and minus one first avoids this instance but is not a general safety proof. The invariant must include both the mathematical partial-sum relation and its machine representability at every operation.',kind='overflow')
add('A bounding proof for two source indices','A loop reads A[i] and A[n-1-i] for i=0..floor(n/2)-1. Prove both accesses are valid for every n≥0 and identify whether an odd center is visited.',
 'When the loop executes, n≥2 and $0\\le i<\\lfloor n/2\\rfloor<n$, proving the low access. Also i≤n-1 gives n-1-i≥0, and i≥0 gives n-1-i≤n-1. Thus the high access is valid. The two positions lie on opposite sides because the bound stops before they meet. For odd n, the center (n-1)/2 is not visited; it would pair with itself and is unnecessary for reversal. At n=0 or one the body is skipped, so no invalid n-1 element access occurs.',kind='boundsproof')
add('A polynomial fill with machine-range qualification','Construct a length-n sequence B[k]=(k+1)² for 0≤k<n and prove the fill invariant. If using signed 32-bit multiplication, find the largest n whose values fit.',
 'Before iteration i, keep $0\\le i\\le n$ and $B[k]=(k+1)^2$ for every k<i. Initially there are no filled entries. The guard i<n proves a valid destination, and writing (i+1)² extends the invariant through i. Advancing i preserves the bound; n-i proves termination. At exit every required value is filled. For signed 32-bit values, the largest square root bound is 46340 because 46340²=2147395600 fits while 46341²=2147488281 does not. Thus n≤46340, with a valid positive allocation bound if represented by a C VLA.',origin='Course-inspired extension — CMU 15-122 Lecture 3, array-fill specification',kind='fill',data=[46340,2147395600])
add('Pointer-negative-index exercise with explicit domain','For a pointer p into a live n-element C array at normalized position r, derive every integer k for which p[k] is a valid element access. What changes for pointer formation without dereference?',
 'The selected position is r+k. Element access requires $0\\le r+k<n$, giving $-r\\le k\\le n-1-r$. Pointer formation p+k permits the one-past endpoint and therefore extends the upper bound to n-r. The difference is exactly one endpoint, not permission for arbitrary negative or large offsets. If p itself is one-past, r=n, negative offsets down to -n can access earlier elements, but zero cannot be dereferenced. This independently worded extension supplies the complete domain behind Cambridge’s negative-index prompt.',origin='Course-inspired extension — Cambridge Programming in C, Lecture 3 exercise 1',kind='pointerdomain')
add('Array mean and a hidden integer division','For scores [7,8,10], compare (scores[0]+scores[1]+scores[2])/3 with the same numerator divided by 3.0, under C arithmetic. What contract does a general average require?',
 'The sum is twenty-five. Integer division by three gives eight, discarding the fractional part for these positive operands. Division by 3.0 converts the operation to floating arithmetic and gives an approximation to 25/3. A general average requires positive length to avoid division by zero, valid initialized entries for every scanned index and safe accumulator arithmetic or an explicitly chosen wider representation. A cast after integer division cannot restore the lost fraction. This extension of the CS50 array-average pattern adds the complete numerical and interface obligations rather than assuming every nonempty-looking parameter is safe.',origin='Course-inspired extension — Harvard CS50x 2025 Lecture 2, array average',kind='average',data=[25,3,8])

assert len(Q)==81,len(Q)
(BASE/'p_arrays-questions.json').write_text(json.dumps(Q,indent=2,ensure_ascii=True)+'\n')
actual=json.loads((BASE/'exam-calibration/actual-items.json').read_text())
auth=[]
for id in ['MS_CS_1393_Q167','Phd_CS_1404_Q72']:
 q=next(q for q in actual if q['id']==id);q=dict(q)
 q.update(origin='Authentic examination bridge revisit',qNumber=q['questionNumber'],sourceSHA=q['sourceSha256'],provenance='Original scan rechecked this turn. Explicit bridge revisit of an already taught archive item; not a new unique question.',difficulty='Medium–Hard')
 auth.append(q)
(BASE/'p_arrays-authentic.json').write_text(json.dumps(auth,indent=2)+'\n')
print('Authored 81 distinct problems and two explicitly labeled authentic bridge revisits.')
