"""Build only the reviewed mux chapter; retain the preceding library byte for byte."""
from pathlib import Path
import json,re,subprocess,hashlib
B=Path(__file__).resolve().parent;R=B.parent;E=B/'g_mux-evidence';E.mkdir(exist_ok=True)
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
specs=[('decoder-gates','Four enabled address minterms at gate level',dict(operation='decoder',n=2,address=2,enable=1,diagram='gates'),'decoder'),('mux-basic','2:1: select zero, data one and zero',dict(operation='mux',n=1,address=0,data=[1,0]),'mux'),('shannon-compare','Cofactors at address three with residual zero',dict(operation='shannon',n=2,address=3,residual=0),'shannon'),('four-select','4:1: address two chooses a zero',dict(operation='mux',n=2,address=2,data=[1,1,0,1]),'mux'),('tree-eight','Eight sources: address five selects source five',dict(operation='tree',n=3,address=5,data=[7,3,9,2,4,11,6,8]),'tree'),('decoder-high','Active-high 2:4 decoder at address two',dict(operation='decoder',n=2,address=2,enable=1),'decoder'),('decoder-low','Active-low outputs at the same address',dict(operation='decoder',n=2,address=2,enable=1,polarity='low'),'decoder'),('two-banks','3:8 decoder at global address six',dict(operation='banks',n=3,address=6,enable=1),'banks'),('demux-zero','Selected route five transmits zero',dict(operation='demux',n=3,address=5,residual=0),'demux'),('priority-high','Requests 01011010: highest index wins',dict(operation='priority',n=3,requests=90,order='high'),'priority'),('priority-low','The same requests: lowest index wins',dict(operation='priority',n=3,requests=90,order='low'),'priority'),('rotating-wrap','Start six: seven wins before wrapping to zero',dict(operation='rotate',n=3,requests=137,pointer=6),'rotate'),('rom-address','ROM address thirteen: row three, column one',dict(operation='rom',n=4,address=13,data=[3*i for i in range(16)]),'rom'),('display-two','Digit two: active-high abcdefg segment order',dict(operation='display',n=4,address=2),'display'),('bus-conflict','Opposing enabled drivers: a contention witness',dict(operation='bus',n=1,data=[0,1],enables=[1,1]),'bus'),('adder-selector','Adder inputs one and zero, select two',dict(operation='integrated',n=2,a=1,b=0,address=2),'integrated'),('authentic-nor','Original two-multiplexer topology at a=b=0',dict(operation='cascade',n=1,a=0,b=0),'mux')]
js="const {makeModel}=require('./dist/chapters/g_mux.js');const specs="+json.dumps(specs)+";process.stdout.write(JSON.stringify(specs.map(x=>makeModel(x[0],x[1],x[2]))));"
models=json.loads(subprocess.check_output(['node','-e',js],cwd=R,text=True,encoding='utf-8'));groups={}
for id,title,s,g in specs:groups.setdefault(g,[]).append(id)
save(R/'dist/chapters/g_mux-models.json',dict(models=models,groups=groups))
parts=re.split(r'^### (\d+)\. (.+)$',(B/'g_mux-problems.en.md').read_text(encoding='utf-8'),flags=re.M)
visuals={1:'mux-basic',4:'authentic-nor',6:'shannon-compare',9:'four-select',11:'four-select',15:'tree-eight',16:'tree-eight',19:'tree-eight',22:'decoder-high',24:'decoder-low',26:'two-banks',27:'decoder-low',29:'two-banks',32:'demux-zero',37:'priority-high',38:'priority-low',40:'priority-high',42:'priority-high',45:'rotating-wrap',48:'rom-address',53:'display-two',54:'display-two',56:'bus-conflict',57:'bus-conflict',58:'bus-conflict',68:'priority-high',79:'adder-selector',80:'adder-selector'}
questions=[]
for i in range(1,len(parts),3):
 n=int(parts[i]);stem,solution=parts[i+2].strip().split('#### Solution',1)
 questions.append(dict(id=f'g_mux_original_{n:02d}',title=parts[i+1],stem=stem.strip(),solution=solution.strip(),origin='Original problem with independent derivation. Named course-pattern reconstructions are identified in their solutions.',**({'modelId':visuals[n]}if n in visuals else{})))
assert len(questions)==80
save(B/'g_mux-questions.json',questions)
items=json.loads((B/'exam-calibration/actual-items.json').read_text(encoding='utf-8'));q=dict(next(q for q in items if q['id']=='MS_CE_1404_Q80'));q.update(modelId='authentic-nor',visualQualification='Original topology, shown at a=b=0. The derivation covers every input row, whereas this trace shows one declared sample.')
q2=dict(q);q2.update(id='MS_CE_1404_Q82',title='Full adder feeding a four-input selector',questionNumber=82,topics=['g_arithmetic','g_mux'],pattern='arithmetic data cofactors and selector minterms',stem='A full adder has inputs $a,b,C_{in}=1$. Its sum and carry feed an XOR, producing $t$. A 4:1 multiplexer receives $(I_0,I_1,I_2,I_3)=(\\overline{C_{out}},C_{out},t,\\overline t)$, with $S_1=c,S_0=d$. Which minterm set represents the output in variable order $abcd$?',options=['$\\Sigma m(0,2,5,6,9,10,13,15)$','$\\Sigma m(0,2,5,6,9,11,12,15)$','$\\Sigma m(1,3,5,6,9,10,13,14)$','$\\Sigma m(1,3,4,7,8,11,12,14)$'],answer=1,solution='1. With fixed carry-in one, $C_{out}=a+b$ and $S=\\overline{a\\oplus b}$. Compute $t=S\\oplus C_{out}=\\overline{ab}$.\n2. For $ab=00$, data are $(1,0,1,0)$, contributing minterms 0 and 2. For $ab=01$, data are $(0,1,1,0)$, contributing 5 and 6. For $ab=10$, the same local vector contributes 9 and 10. For $ab=11$, data are $(0,1,0,1)$, contributing 13 and 15.\n3. The union is the first option. The original diagram explicitly connects c to the high selector and d to the low selector. Reversing them changes the mapping.\n4. The lesson uses x,y for the selector names to avoid confusing an intermediate carry with the original selector c; the authenticated question retains the original a,b,c,d naming.',modelId='adder-selector',visualQualification='Original adder–XOR–MUX topology, shown at a=1,b=0,c=1,d=0. The complete solution enumerates all sixteen truth rows.',translationStatus='checked against newly rendered original PDF page 19')
save(B/'g_mux-authentic.json',[q,q2])
save(E/'reading.json',dict(topicId='g_mux',coreUniversities=['Stanford','MIT','Cambridge','ETH Zurich'],readScopes={'Stanford':'PDF 119–146, 150–162; relevant core passages and diagrams reread. Chapter 7/8 exercises inspected, not copied wholesale.','MIT':'Lecture 4 written multiplexer/lookup/ROM passages, web-text lines 697–759.','Cambridge':'PDF 64–76 and all three pages of Examples Paper 1; diagrams 66,68,75 rendered.','ETH Zurich':'PDF 37–43; diagrams 39,43 rendered.'},corrections=['Stanford selector universality uses 2^n data ports, not n ports.','Cambridge page 68 system-one example contradicts explicitly MSB-first x,y,z wiring; derive address independently.','PLA products are cubes, not necessarily complete minterms.','Stanford prime-number lookup includes one; one is not prime.','Stanford priority prose must include negated lower requests; HDL has the correct complement.'],exam={'ids':['MS_CE_1404_Q80','MS_CE_1404_Q82'],'sha256':q['sourceSha256'],'page':19,'sourceCommit':q['sourceCommit'],'answerProvenance':'independently derived, not official key'},limits='Bounded source pool and scoped actual readings; not every course worldwide. No new authenticated doctoral MUX item claimed.'))
css=(R/'dist/chapters/g_arithmetic.css').read_text(encoding='utf-8').replace('ar-','mx-').replace('ar-form','mx-form').replace('ar-error','mx-error');(R/'dist/chapters/g_mux.css').write_text(css,encoding='utf-8')
# Adapt the established renderer, changing only this chapter's outputs.
s=(B/'render_g_arithmetic.py').read_text(encoding='utf-8').replace('g_arithmetic','g_mux').replace('ar-','mx-').replace('ar-form','mx-form').replace('ar-error','mx-error').replace('ar-output','mx-output')
start=s.index("lab='''");end=s.index("source=",start)
lab="""<section class="lab"><form id="mx-form"><label>Operation<select name="operation">"""+''.join('<option value="'+x+'">'+x+'</option>'for x in['mux','tree','shannon','decoder','banks','demux','priority','rotate','rom','display','bus','integrated','cascade'])+"""</select></label><label>Address width<input name="n" type="number" min="1" max="4" value="2"></label><label>Address integer<input name="address" type="number" min="0" value="2"></label><label>Comma-separated data words<input name="data" value="1,1,0,1"></label><label>Request integer<input name="requests" type="number" min="0" value="0"></label><label>Residual variable / demux data<input name="residual" type="number" min="0" max="1" value="0"></label><label>Enable<input name="enable" type="number" min="0" max="1" value="1"></label><label>Output polarity<select name="polarity"><option>high</option><option>low</option></select></label><label>Priority order<select name="order"><option>high</option><option>low</option></select></label><label>Rotating start<input name="pointer" type="number" min="0" value="0"></label><label>Adder / cascade bit a<input name="a" type="number" min="0" max="1" value="0"></label><label>Adder / cascade bit b<input name="b" type="number" min="0" max="1" value="0"></label><label>Two bus enable bits<input name="enables" value="0,0"></label><button type="submit">Build the exact circuit trace</button></form><p id="mx-error" role="alert"></p><p>Multiplexer data must contain exactly 2 to the address-width power entries. Tree and priority diagrams support up to eight sources. Cofactor and adder examples use width two; the cascade uses width one. Bank expansion uses width three. ROM and BCD examples use width four; the ROM has sixteen words and a fixed two-bit column split. Bus classification uses exactly two binary data and enable values. Irrelevant fields are validated for basic domain bounds but do not influence other operations. Every new trace starts paused; invalid input preserves the previous valid trace. The models show exact logic, not physical propagation time.</p><div id="mx-output"></div></section>"""
s=s[:start]+'lab='+repr(lab)+'\n'+s[end:]
s=s.replace("<!-- LAB: arithmetic -->","<!-- LAB: mux -->")
start=s.index("body=text(source);anchors=");end=s.index(";it=iter(anchors)",start)
s=s[:start]+"body=text(source);anchors="+repr(['sources','contract','mux','shannon','four','cofactors','trees','timing','decoder','polarity','banks','functions','demux','encoder','priority','groups','rotation','rom','pla','display','bus','hdl','verification','integration','summary','problems','review','laboratory','references'])+s[end:]
s=s.replace('Adders, Comparators, and Arithmetic Circuits','Multiplexers, Decoders, Encoders, and Function Realization').replace('82 worked problems · 80 final reasoning rules · 15 circuit/process models','82 worked problems · 80 final reasoning rules · 17 exact circuit/selection models').replace('four reviewed written university courses','four reviewed written university courses').replace('Authenticated doctoral examination bridges','Authenticated MSc examination bridges').replace('authenticQuestionCount=2','authenticQuestionCount=2').replace('animationCount=15','animationCount=17').replace('animationWalkthroughCount=15','animationWalkthroughCount=17')
s=s.replace("if visual and not q.get('visualQualification'):visual='<p class=\"visual-scope\">Companion visualization: the diagram title specifies its sample operands and width. Follow the written solution for the stated problem parameters; this sample illustrates the reasoning pattern.</p>'+visual\n",'',1)
s=s.replace('sample operands and width','sample inputs and address width')
s=s.replace('\n  if visual','\n if visual')
s=s.replace("Longrightarrow='⟹'","Longrightarrow='⟹',Sigma='Σ'")
s=s.replace('def text(s):return','def text(s):\n s=s.replace(r"\\mathbin{\\&}",r"\\&")\n return')
(B/'render_g_mux.py').write_text(s,encoding='utf-8')
subprocess.run(['python','-X','utf8',str(B/'render_g_mux.py')],cwd=R,check=True)
print('Built 82 problems, 80 rules, 17 models,',sum(len(m['frames'])for m in models),'checkpoints.')
