from pathlib import Path
import json,re,subprocess,hashlib,fitz
B=Path(__file__).resolve().parent;R=B.parent;E=B/'d_generating-evidence';E.mkdir(exist_ok=True)
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
specs=[('inverse-pell','Reciprocal of one minus twice the variable minus its square',{'operation':'inverse','n':7},'inverse'),('convolution-five','Every contribution to the degree-five convolution coefficient',{'operation':'convolution','n':5},'convolution'),('residue-one','Retain original indices congruent to one modulo three',{'operation':'filter','n':8},'filtering'),('three-boxes','Three named boxes capped at three; target six',{'operation':'bounded','n':6},'bounded'),('change-six','Unordered change of six with weights one, two, and three',{'operation':'coins','n':6},'coins'),('ordered-five','Every ordered one/two composition of total five',{'operation':'composition','n':5},'composition'),('partition-seven','Exact partition product coefficients through total seven',{'operation':'partitions','n':7},'partitions'),('durfee-seven','Every size-seven partition decomposed into square, arm, and leg',{'operation':'durfee','n':7},'partitions'),('catalan-four','All fourteen four-pair paths and their first returns',{'operation':'catalan','n':4},'catalan'),('label-five','All thirty-two allocations of five distinct labels to two recipients',{'operation':'labelled','n':5},'labelled'),('binary-six','All sixty-four length-six words and their total ones',{'operation':'marking','n':6},'marking'),('triple-pole','Third-order pole at one-half: exact exponential/binomial factors',{'operation':'poles','n':7},'poles')]
specs += [('question-four','Degree-three product: linear coefficients times powers of three',{'operation':'convolution','n':3,'base':3},'problem-only'),('question-nine','Retain indices congruent to two modulo three',{'operation':'filter','n':8,'residue':2},'problem-only'),('question-thirtyone','Four named boxes capped at three; total nine',{'operation':'bounded','n':9,'boxes':4},'problem-only'),('question-thirtysix','Unordered change of ten with weights one, two, and five',{'operation':'coins','n':10,'weights':[1,2,5]},'problem-only'),('question-eighty','Every ordered one/two composition of total six',{'operation':'composition','n':6},'problem-only')]
js="const {makeModel}=require('./dist/chapters/d_generating.js');const specs="+json.dumps(specs)+";process.stdout.write(JSON.stringify(specs.map(x=>makeModel(x[0],x[1],x[2]))));"
models=json.loads(subprocess.check_output(['node','-e',js],cwd=R,text=True,encoding='utf-8'));groups={}
for id,title,s,g in specs:groups.setdefault(g,[]).append(id)
save(R/'dist/chapters/d_generating-models.json',dict(models=models,groups=groups))
problems='\n\n'.join((B/f'd_generating-problems{x}.en.md').read_text(encoding='utf-8')for x in['','-2','-3']);parts=re.split(r'^### (\d+)\. (.+)$',problems,flags=re.M)
visuals={2:'inverse-pell',4:'convolution-five',5:'inverse-pell',9:'residue-one',18:'triple-pole',31:'three-boxes',36:'change-six',37:'ordered-five',43:'ordered-five',46:'partition-seven',47:'durfee-seven',49:'catalan-four',50:'catalan-four',56:'label-five',69:'binary-six',75:'residue-one',77:'triple-pole',80:'ordered-five'}
visuals.update({4:'question-four',9:'question-nine',31:'question-thirtyone',36:'question-thirtysix',80:'question-eighty'})
# A companion uses explicitly declared sample parameters, not a false claim of identical input.
# Remove examples whose actual construction differs from the visual.
for n in[5,18,43,46,50,75,77]:visuals.pop(n,None)
qs=[]
for i in range(1,len(parts),3):
 n=int(parts[i]);stem,solution=parts[i+2].strip().split('#### Solution',1);qs.append(dict(id=f'd_generating_original_{n:02d}',title=parts[i+1],stem=stem.strip(),solution=solution.strip(),origin='Original mathematical/conceptual problem, or explicitly credited course-pattern reconstruction; independently derived solution.',**({'modelId':visuals[n]}if n in visuals else{})))
for q in qs:
 n=int(q['id'].split('_')[-1])
 if n in[4,9,31,36,37,47,49,56,69]:q['visualQualification']='This walkthrough uses the same target and inventory as the problem. Compare its exact checkpoints with the coefficient derivation above.'
 if n==80:q['visualQualification']='This walkthrough enumerates the ordered strings in the first part of this question. The unordered and labelled classes are derived separately above.'
assert len(qs)==80;save(B/'d_generating-questions.json',qs)
auth=[dict(q)for q in json.loads((B/'d_recurrence-authentic.json').read_text())if q['id']in['MS_CS_1405_Q130','Phd_CS_1404_Q28']]
assert len(auth)==2
for q in auth:
 p=Path('C:/Users/bheydari/AppData/Local/Temp/exam-calibration-1406/source')/q['repoPath'];assert hashlib.sha256(p.read_bytes()).hexdigest()==q['sourceSha256'];d=fitz.open(p);d[q['pdfPage']-1].get_pixmap(matrix=fitz.Matrix(1.4,1.4)).save(str(E/(q['id']+'.png')))
 q['translationStatus']='Revisited exact original PDF page, re-rendered for this chapter; independently derived answer.'
 if q['id']=='MS_CS_1405_Q130':q['solution']='Sum the given recurrence over nonnegative n after multiplying by $x^{n+1}$. Its left side is $C(x)-1$; its right side is $xC(x)/(1-x)$ by inclusive prefix convolution. Therefore $(1-2x)C(x)=1-x$, so $\\alpha=2$. The constant remains one and the first terms are 1,1,2,4,8. In particular, the initial term is not $2^{n-1}$ at index zero. The other proposed values already predict an incorrect coefficient at degree two. This derives the required rational function directly while retaining the complete boundary.'
# Store only the correct derivation, never a knowingly wrong intermediate formula.
for q in auth:
 if q['id']=='Phd_CS_1404_Q28':q['solution']=q['solution'].split('**Generating-function extension.**')[0]+'**Generating-function extension.** Shift to $b_n=a_{n+16}$, with $b_0=1403$, $b_1=2025$. The shifted recurrence starts at index two, so its OGF is $B(x)=(1403-2184x+4x^2/(1-x))/(1-3x-5x^2)$. The coefficient correction is $2025-3\\cdot1403=-2184$, and the constant forcing four begins only at two. The first coefficients are 1403,2025,13094,49411, which independently confirm both the initial polynomial and forcing shift. The parity-state derivation above is the faster route to the original examination question.'
save(B/'d_generating-authentic.json',auth)
css=(R/'dist/chapters/g_mux.css').read_text(encoding='utf-8').replace('mx-','gf-');css+='\n.gf-model{max-width:760px;margin:1.5rem auto}.gf-stage{max-height:420px;overflow:auto}.gf-stage svg{width:760px;max-width:100%;height:auto}.gf-model svg .gf-prose{font-family:"Source Sans 3",sans-serif!important;font-size:18px!important;fill:#163d55}.gf-model svg .gf-math{font-family:"STIX Two Math",serif!important;font-size:18px!important;fill:#163d55}.gf-formula math{font-family:"STIX Two Math",serif}\n';(R/'dist/chapters/d_generating.css').write_text(css,encoding='utf-8')
s=(B/'render_d_recurrence.py').read_text(encoding='utf-8').replace('d_recurrence','d_generating').replace('rc-','gf-').replace('Recurrence Relations: Exact Solutions, Counting Models, and Boundary Conditions','Generating Functions: Formal Algebra, Exact Coefficients, and Counting Structures').replace('83 worked','82 worked').replace('==83','==82').replace('questionCount=83','questionCount=82').replace('authenticQuestionCount=3','authenticQuestionCount=2').replace('animationCount=14','animationCount=17').replace('animationWalkthroughCount=14','animationWalkthroughCount=17').replace('14 distinct mathematical models','17 distinct mathematical models').replace('Recurrence chapter audit','Generating-function chapter audit').replace('Recurrence chapter','Generating-function chapter')
start=s.index("lab='");end=s.index('\nsource=',start)
lab='<section class="lab"><form id="gf-form"><label>Exact model<select name="operation">'+''.join('<option>'+op+'</option>'for op in['inverse','convolution','filter','bounded','coins','composition','partitions','durfee','catalan','labelled','marking','poles'])+'</select></label><label>Target index or size<input name="n" type="number" min="1" max="10" value="5"></label><button type="submit">Build the exact checkpoints</button></form><p id="gf-error" role="alert"></p><p>The equations and inventory constraints are fixed as stated in each model. Target indices are one through ten; the convolution grid stops at six, compositions and complete Durfee enumeration at seven, labelled and binary enumeration at six, Catalan paths at four pairs, and the three capped boxes at total nine. Each model starts paused. Invalid input preserves the preceding valid model. Enumeration checkpoints are different complete objects; coefficient-table checkpoints add one factor or one algebraic contribution.</p><div id="gf-output"></div></section>'
s=s[:start]+'lab='+repr(lab)+s[end:];s=s.replace('<!-- LAB: recurrence -->','<!-- LAB: generating -->')
start=s.index('body=text(source);anchors=');end=s.index(';it=iter(anchors)',start)
anchors=['sources','meaning','formal','coefficient','shifts','derivatives','transforms','dictionary','rational','recurrences','forcing','translation','bounds','coins','sequences','partitions','catalan','inversion','exponential','surjections','cycles','distinguished','marking','probability','asymptotic','verification','summary','problems','review','laboratory','references'];s=s[:start]+'body=text(source);anchors='+repr(anchors)+s[end:]
s=s.replace('import mathml', 'import mathml\nmathml.SYMBOLS.update(cosh="cosh")')
(B/'render_d_generating.py').write_text(s,encoding='utf-8');subprocess.run(['python','-X','utf8',str(B/'render_d_generating.py')],cwd=R,check=True)
native=json.loads(Path('C:/Users/bheydari/AppData/Local/Temp/d-generating-sources/acquisition.json').read_text());save(E/'reading.json',dict(coreUniversities=['MIT','UC Berkeley','Carnegie Mellon','Princeton'],nativeAcquisition=native,readScopes={'MIT':'Chapter 15, PDF pages 636–670','Berkeley':'Ordinary 7 pages, exponential 10 pages, partitions 9 pages, all read','CMU':'All 9 official PDF pages through references, web text','Princeton':'All 52 written slides, author official mirror, web text; damaged extracted glyphs independently derived'},limits='Bounded nine-candidate pool; no native hash claimed for remote-only source reads. See source audit for corrections.'))
print('Built generating-functions chapter:',len(qs)+len(auth),'solutions;',len(models),'models;',sum(len(m['frames'])for m in models),'checkpoints.')
