from pathlib import Path
B=Path(__file__).resolve().parent;R=B.parent
old=(R/'dist/chapters/l_spaces.js').read_text(encoding='utf-8');mount=old[old.index('function mount(host,m)'):old.index('const api=')].replace('vs-','ag-').replace('/vector-geometry|plane-geometry|quotient-geometry|polynomial-plot/','/probability-threshold|belief-bars|vacuum-motion|decision-belief/').replace("line,circle,polygon,text","line,circle,polygon,text,rect").replace("'cx','cy','points'","'cx','cy','width','height','points'")
prefix=r'''/* Agent decision laboratory. Exact rational probabilities and utilities. */
(() => {'use strict';
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const gcd=(a,b)=>{a=a<0n?-a:a;b=b<0n?-b:b;while(b){[a,b]=[b,a%b];}return a;};
class Q {constructor(n,d=1n){n=BigInt(n);d=BigInt(d);if(!d)throw Error('Zero divisor.');if(d<0n){n=-n;d=-d;}const g=gcd(n,d);this.n=n/g;this.d=d/g;}add(b){return new Q(this.n*b.d+b.n*this.d,this.d*b.d);}neg(){return new Q(-this.n,this.d);}sub(b){return this.add(b.neg());}mul(b){return new Q(this.n*b.n,this.d*b.d);}div(b){return new Q(this.n*b.d,this.d*b.n);}cmp(b){const z=this.n*b.d-b.n*this.d;return z<0n?-1:z>0n?1:0;}toString(){return String(this.n)+(this.d===1n?'':'/'+this.d);}valueOf(){return Number(this.n)/Number(this.d);}}
const zero=new Q(0),one=new Q(1);
const read=x=>{const [n,d='1']=String(x).split('/');return new Q(n,d);};
function parse(x){const a=String(x).trim();if(!/^[-+]?\d{1,5}(\/\d{1,5})?$/.test(a))throw Error('Use integers or fractions with numerator magnitude at most 10000 and denominator 1–10000.');const [n,d='1']=a.split('/');if(Math.abs(Number(n))>10000||Number(d)<1||Number(d)>10000)throw Error('Numerator magnitude must be at most 10000; denominator must be 1–10000.');return new Q(n,d);}
const num=x=>{let a=String(x).split('/');const mn=s=>s.startsWith('-')?'<mrow><mo>−</mo><mn>'+s.slice(1)+'</mn></mrow>':'<mn>'+esc(s)+'</mn>';return a.length===2?'<mfrac>'+mn(a[0])+mn(a[1])+'</mfrac>':mn(a[0]);};
const math=x=>'<math xmlns="http://www.w3.org/1998/Math/MathML">'+num(x)+'</math>';
const tx=(x,y,s,cls='label',anchor='start')=>`<text x="${x}" y="${y}" text-anchor="${anchor}" class="ag-${cls}">${esc(s)}</text>`;
function fraction(x,y,v){const a=String(v).split('/'),fit=(yy,s)=>{const t=tx(x,yy,s,'math','middle');return s.length>12?t.replace('<text','<text textLength="138" lengthAdjust="spacingAndGlyphs"'):t;};if(a.length===1)return fit(y,a[0]);const w=Math.min(146,Math.max(22,Math.max(...a.map(s=>s.length))*12));return fit(y-12,a[0])+`<line x1="${x-w/2}" x2="${x+w/2}" y1="${y-5}" y2="${y-5}" stroke="#365668"/>`+fit(y+19,a[1]);}
const rect=(x,y,w,h,c)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="7" fill="${c}" stroke="#a2b9b4"/>`;
const svg=s=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 560" role="img" data-visual-type="decision-belief">${s}</svg>`;
function calc(prior,lh,ll,U,cost){const p=parse(prior),h=parse(lh),l=parse(ll),c=parse(cost);if([p,h,l].some(x=>x.cmp(zero)<0||x.cmp(one)>0))throw Error('Prior and signal likelihoods must lie in [0, 1].');if(c.cmp(zero)<0)throw Error('Information cost must be nonnegative.');if(U.length!==2||U.some(r=>r.length!==2))throw Error('Supply exactly two action rows and two state columns: A in H,L; then B in H,L.');U=U.map(r=>r.map(parse));const expected=b=>U.map(r=>b.mul(r[0]).add(one.sub(b).mul(r[1]))),best=values=>{const v=values[0].cmp(values[1])>=0?values[0]:values[1];return {value:v,actions:values.map((x,i)=>x.cmp(v)===0?['A','B'][i]:null).filter(Boolean)};};
const priorUtilities=expected(p),priorBest=best(priorUtilities),signals=[];let after=zero;
for(const [name,a,b]of[['Positive',h,l],['Negative',one.sub(h),one.sub(l)]]){const massH=p.mul(a),massL=one.sub(p).mul(b),prob=massH.add(massL);if(!prob.n){signals.push({name,prob:'0',posterior:null,utilities:null,optimal:[],value:null});continue;}const posterior=massH.div(prob),utilities=expected(posterior),winner=best(utilities);after=after.add(prob.mul(winner.value));signals.push({name,prob:String(prob),posterior:String(posterior),utilities:utilities.map(String),optimal:winner.actions,value:String(winner.value)});}
const bestH=U[0][0].cmp(U[1][0])>=0?U[0][0]:U[1][0],bestL=U[0][1].cmp(U[1][1])>=0?U[0][1]:U[1][1],perfect=p.mul(bestH).add(one.sub(p).mul(bestL)),evsi=after.sub(priorBest.value),vpi=perfect.sub(priorBest.value),net=after.sub(c),gain=evsi.sub(c);
if(evsi.cmp(zero)<0||vpi.cmp(evsi)<0)throw Error('Internal information-value consistency check failed.');return {prior:String(p),likelihoods:[String(h),String(l)],utilities:U.map(r=>r.map(String)),cost:String(c),priorUtilities:priorUtilities.map(String),priorOptimal:priorBest.actions,priorValue:String(priorBest.value),signals,afterValue:String(after),perfectValue:String(perfect),evsi:String(evsi),vpi:String(vpi),netValue:String(net),netGain:String(gain),purchase:gain.cmp(zero)>0?'Buy the signal':gain.cmp(zero)<0?'Act without buying':'Both purchase decisions tie',checks:{probabilitiesSum:read(signals[0].prob).add(read(signals[1].prob)).cmp(one)===0,nonnegativeEvsi:evsi.cmp(zero)>=0,perfectBoundsSample:vpi.cmp(evsi)>=0}};}
function decisionLab(prior,h,l,U,cost){const r=calc(prior,h,l,U,cost),m={id:'editable-agent-decision',title:'Your signal-and-action model',kind:'decision-belief',invariant:'The sensor does not change the state, delay action or restrict choices. Every branch and total uses exact rational arithmetic.',code:['Compute prior action utilities.','Condition on each possible signal.','Choose a conditional maximizing action.','Average branch values and subtract information cost.'],frames:[],result:r};
function add(name,p,prob,utilities,optimal,description,impossible=false){const snapshot={phase:name,posteriorH:p,branchProbability:prob,utilities,optimal,impossible},prev=m.frames.at(-1)?.snapshot;let s=tx(40,35,name);if(impossible){s+=tx(80,165,'This observation has probability zero under your model.')+tx(80,225,'No posterior or action value is invented for this branch.');}else{const b=Number(read(p));s+=tx(80,115,'Hidden-state belief: H (teal), L (sand)')+`<g data-entity="H">${rect(80,145,800*b,70,'#b6d4d0')}</g><g data-entity="L">${rect(80+800*b,145,800*(1-b),70,'#e9d6b3')}</g>`+tx(80,265,'H probability:')+fraction(310,270,p)+tx(480,265,'Branch probability:')+fraction(790,270,prob)+tx(80,350,'EU(A):')+fraction(250,355,utilities[0])+tx(480,350,'EU(B):')+fraction(650,355,utilities[1])+tx(80,435,'Best action: '+optimal.join(' or '));}s+=tx(80,505,'Arithmetic checks describe this complete checkpoint, not intermediate bar motion.');
const f='<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mtext>'+esc(name)+': </mtext>'+(!impossible?num(p):'<mtext>undefined posterior</mtext>')+'</mrow></math>';m.frames.push({snapshot,svg:svg(s),caption:description,formulaHtml:f,teaching:{operation:name,why:description,checks:[{mathHtml:math(r.evsi),result:String(r.checks.nonnegativeEvsi)},{mathHtml:math(r.vpi),result:String(r.checks.perfectBoundsSample)}],changes:prev?Object.entries(snapshot).filter(([k,v])=>JSON.stringify(prev[k])!==JSON.stringify(v)).map(([field,after])=>({field,before:prev[field],after})):[],currentState:snapshot,initial:!prev,reading:m.invariant,guide:m.code,activeLine:Math.min(m.frames.length,3),mode:m.kind}});}
add('Before sensing',r.prior,'1',r.priorUtilities,r.priorOptimal,'Compare prior expectations before paying for information.');for(const b of r.signals)add(b.name+' observation',b.posterior,b.prob,b.utilities,b.optimal,b.posterior===null?'The branch is impossible under the declared likelihood model.':'Use the conditional belief to optimize this branch.',b.posterior===null);add('Final policy and cost',r.prior,'1',r.priorUtilities,r.priorOptimal,r.purchase+'. Optimized free-signal value '+r.afterValue+', net value '+r.netValue+', net gain '+r.netGain+'.');
const last=m.frames.at(-1);let finalSvg=tx(40,35,'Compare the complete purchase decision before observing the signal');for(const [x,label,value]of[[50,'Act without purchase',r.priorValue],[370,'Buy, then act',r.netValue],[690,'Net gain from purchase',r.netGain]])finalSvg+=rect(x,100,260,150,'#e6efea')+tx(x+130,140,label,'label','middle')+fraction(x+130,205,value);finalSvg+=tx(70,305,r.purchase)+tx(70,355,'If the signal is purchased, use this conditional policy:');r.signals.forEach((b,i)=>{finalSvg+=tx(90,405+45*i,b.name+': '+(b.posterior===null?'impossible observation':b.optimal.join(' or ')));});last.svg=svg(finalSvg);last.snapshot={phase:'Final policy and cost',priorValue:r.priorValue,netPurchaseValue:r.netValue,netGain:r.netGain,purchase:r.purchase,conditionalPolicy:r.signals.map(b=>({signal:b.name,optimal:b.optimal,impossible:b.posterior===null}))};last.teaching.currentState=last.snapshot;last.teaching.changes=Object.entries(last.snapshot).map(([field,after])=>({field,before:null,after}));last.formulaHtml='<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mtext>Net gain</mtext><mo>=</mo>'+num(r.evsi)+'<mo>−</mo>'+num(r.cost)+'<mo>=</mo>'+num(r.netGain)+'</mrow></math>';return m;}
const controls=()=>'<div class="ag-controls"><button type="button" data-reset>Restart</button><button type="button" data-prev>Previous</button><button type="button" data-play>Play</button><button type="button" data-next>Next</button><label>Speed<select data-speed><option value="2600">Slow</option><option value="1800" selected>Normal</option><option value="1300">Fast</option></select></label><label>Step<input type="range" data-seek min="0" value="0" aria-label="Laboratory checkpoint"></label></div><div class="ag-stage"></div><p class="ag-caption"></p><p data-progress></p><div class="ag-formula formula-block"></div><div class="ag-print"></div>';
'''
suffix=r'''
const api={Q,parse,calc,decisionLab};if(typeof module!=='undefined'){module.exports=api;return;}globalThis.AgentModels=api;
async function boot(){const data=await(await fetch('i_agents-models.json')).json();globalThis.AgentPlayers=[];for(const host of document.querySelectorAll('[data-ag-model]')){const m=data.models.find(x=>x.id===host.dataset.agModel);if(!m)throw Error('Missing agent model.');AgentPlayers.push(mount(host,m));}
const form=document.querySelector('#ag-form'),out=document.querySelector('#ag-output'),error=document.querySelector('#ag-error');let current=null;
form.addEventListener('submit',event=>{event.preventDefault();try{const f=form.elements,U=f.utilities.value.trim().split(';').map(r=>r.split(',').map(x=>x.trim())),m=decisionLab(f.prior.value,f.lh.value,f.ll.value,U,f.cost.value),r=m.result;current?.pause();current?.teaching.root.remove();out.innerHTML='<section class="ag-model" tabindex="0"><h3>'+esc(m.title)+'</h3><p>'+esc(m.invariant)+'</p>'+controls()+'</section><section class="lab-results"><h3>Exact decision values</h3><p>Prior best: '+math(r.priorValue)+'. Best actions: '+esc(r.priorOptimal.join(' or '))+'.</p><p>Optimized value after a free signal: '+math(r.afterValue)+'.</p><p>Sample-information value: '+math(r.evsi)+'. Perfect-information value: '+math(r.vpi)+'.</p><p>Net value after purchase: '+math(r.netValue)+'. Gain over acting without purchase: '+math(r.netGain)+'.</p><p><strong>'+esc(r.purchase)+'.</strong></p><p>Conditional policy: '+r.signals.map(b=>esc(b.name)+': '+(b.posterior===null?'impossible branch; no posterior':esc(b.optimal.join(' or ')))).join('; ')+'.</p></section>';current=mount(out.firstChild,m);globalThis.AgentLab=current;error.textContent='';}catch(err){error.textContent=err.message;}});
form.dispatchEvent(new Event('submit',{cancelable:true}));}
boot().catch(err=>{const p=document.createElement('p');p.setAttribute('role','alert');p.textContent='The interactive laboratory could not initialize: '+err.message;document.querySelector('.lesson').prepend(p);throw err;});})();
'''
(R/'dist/chapters/i_agents.js').write_text(prefix+mount+suffix,encoding='utf-8')
print('Built exact-rational information value laboratory, zero-probability handling and actual-state visual transitions.')
