from pathlib import Path
import json,re,subprocess
B=Path(__file__).resolve().parent;R=B.parent;E=B/'d_recurrence-evidence'
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
specs=[('weighted-forcing','Forcing n: five exact contributions, multiplier two',dict(operation='unrolling',n=5,p=2,a0=0),'unrolling'),('quadratic-differences','Repeated-root explanation: differences of (n + 1) squared',dict(operation='differences',n=6),'differences'),('zero-root-prefix','Independent prefix four, five; exponential tail starts at two',dict(operation='boundary',n=6),'boundary'),('all-domino-eight','Every tiling of a two-by-eight board',dict(operation='tiling',n=8),'tiling'),('double-resonance','Double root two: normalized quadratic and exact residual',dict(operation='resonance',n=6),'resonance'),('ternary-forbidden','No 00 or 11: exact aggregate states through length six',dict(operation='automaton',n=6),'automaton'),('derangement-cases','Derangement cases through size five',dict(operation='derangements',n=5),'derangements'),('stirling-bell','Stirling insertion rows and Bell counts through size six',dict(operation='partitions',n=6),'partitions'),('ferrers-seven','Every partition of seven into exactly three parts',dict(operation='ferrers',n=7),'ferrers'),('first-return-three','All five Dyck paths with three pairs',dict(operation='catalan',n=3),'catalan'),('fib-mod-three','Complete Fibonacci pair cycle modulo three',dict(operation='modular',n=8,modulus=3),'modular'),('companion-state','Exact matrix states for initial values two and five',dict(operation='matrix',n=6),'matrix')]
specs += [('ferrers-conjugate','Seven-cell Ferrers transposition: three rows to largest part three',dict(operation='conjugate',n=7),'conjugate'),('reflection-six','Bad six-pair path and its reflected-prefix image',dict(operation='reflection',n=6),'reflection')]
js="const {makeModel}=require('./dist/chapters/d_recurrence.js');const specs="+json.dumps(specs)+";process.stdout.write(JSON.stringify(specs.map(x=>makeModel(x[0],x[1],x[2]))));"
models=json.loads(subprocess.check_output(['node','-e',js],cwd=R,text=True,encoding='utf-8'));groups={}
for id,title,s,g in specs:groups.setdefault(g,[]).append(id)
save(R/'dist/chapters/d_recurrence-models.json',dict(models=models,groups=groups))
problems='\n\n'.join((B/f'd_recurrence-problems{x}.en.md').read_text(encoding='utf-8')for x in['','-2','-3']);parts=re.split(r'^### (\d+)\. (.+)$',problems,flags=re.M)
visuals={1:'zero-root-prefix',25:'quadratic-differences',26:'quadratic-differences',29:'zero-root-prefix',34:'double-resonance',42:'ternary-forbidden',45:'all-domino-eight',49:'derangement-cases',50:'derangement-cases',52:'stirling-bell',54:'stirling-bell',57:'ferrers-seven',59:'ferrers-conjugate',61:'first-return-three',62:'reflection-six',69:'companion-state',74:'fib-mod-three',77:'double-resonance'}
questions=[]
for i in range(1,len(parts),3):
 n=int(parts[i]);stem,solution=parts[i+2].strip().split('#### Solution',1)
 questions.append(dict(id=f'd_recurrence_original_{n:02d}',title=parts[i+1],stem=stem.strip(),solution=solution.strip(),origin='Original problem, or explicitly labeled course-pattern reconstruction; independent full derivation.',**({'modelId':visuals[n]}if n in visuals else{})))
assert [int(q['id'].split('_')[-1])for q in questions]==list(range(1,81));save(B/'d_recurrence-questions.json',questions)
css=(R/'dist/chapters/g_mux.css').read_text(encoding='utf-8').replace('mx-','rc-').replace('mx-form','rc-form').replace('mx-error','rc-error')
css+='\n.rc-stage svg{width:760px;max-width:100%;height:auto}.rc-stage .rc-prose{font-family:"Source Sans 3",sans-serif;font-size:18px;fill:#163d55}.rc-stage .rc-math{font-family:"STIX Two Math",serif;font-size:19px;fill:#163d55}.rc-stage{max-height:420px;overflow:auto}.rc-model{max-width:760px;margin:1.5rem auto}.rc-formula math{font-family:"STIX Two Math",serif}\n'
css+='\n.rc-model svg .rc-node{font-family:"STIX Two Math",serif!important;font-size:17px!important}.rc-model svg .rc-math{font-family:"STIX Two Math",serif!important;font-size:19px}.rc-model svg .rc-prose{font-family:"Source Sans 3",sans-serif;font-size:18px}\n'
(R/'dist/chapters/d_recurrence.css').write_text(css,encoding='utf-8')
s=(B/'render_g_mux.py').read_text(encoding='utf-8').replace('g_mux','d_recurrence').replace('mx-','rc-').replace('mx-form','rc-form').replace('mx-error','rc-error').replace('mx-output','rc-output')
s=s.replace('Multiplexers, Decoders, Encoders, and Function Realization','Recurrence Relations: Exact Solutions, Counting Models, and Boundary Conditions').replace('Digital Logic · Week 3','Discrete Mathematics · Week 4').replace('#week-3','#week-4').replace("w['week']==3","w['week']==4")
s=s.replace('82 worked problems · 80 final reasoning rules · 17 exact circuit/selection models','83 worked problems · 80 final reasoning rules · 14 distinct mathematical models').replace('Authenticated MSc examination bridges','Authenticated MSc and doctoral examination bridges').replace('authenticQuestionCount=2','authenticQuestionCount=3').replace('questionCount=82','questionCount=83').replace('==82','==83').replace('animationCount=17','animationCount=14').replace('animationWalkthroughCount=17','animationWalkthroughCount=14')
s=s.replace('sample inputs and address width','sample inputs and index range').replace('Arithmetic chapter audit','Recurrence chapter audit').replace('Arithmetic chapter','Recurrence chapter')
s=s.replace('Revisited authenticated bridge; independently derived answer, not an official key.','Revisited original examination bridge; independently derived answer, not an official key.')
s=s.replace("Sigma='Σ'", "Sigma='Σ',psi='ψ'")
s=s.replace(' s=s.replace(r"\\mathbin{\\&}",r"\\&")',' s=s.replace(r"\\mathbin{\\&}",r"\\&").replace(r"\\bigl", "").replace(r"\\bigr", "")')
start=s.index("lab='");end=s.index('\nsource=',start)
lab='<section class="lab"><form id="rc-form"><label>Model<select name="operation">'+''.join('<option>'+x+'</option>'for x in['unrolling','differences','boundary','tiling','resonance','automaton','derangements','partitions','ferrers','catalan','modular','matrix'])+'</select></label><label>Target index / size<input name="n" type="number" min="1" max="8" value="5"></label><label>First-order multiplier<input name="p" type="number" min="-4" max="4" value="2"></label><label>First-order starting value<input name="a0" type="number" min="-10" max="10" value="0"></label><label>Modulus<input name="modulus" type="number" min="2" max="8" value="3"></label><button type="submit">Build an exact trace</button></form><p id="rc-error" role="alert"></p><p>All indices are integers from one through eight. Full Dyck-path enumeration is limited to four pairs. Exact three-part Ferrers diagrams require a total of at least three. The multiplier and starting value affect only first-order unrolling; the modulus affects only the Fibonacci residue model. Other model equations and boundaries are explicitly fixed in their titles and descriptions. Every trace starts paused, and invalid input preserves the previous valid trace. Enumeration checkpoints represent different objects, rather than time evolution of one object.</p><div id="rc-output"></div></section>'
s=s[:start]+'lab='+repr(lab)+s[end:];s=s.replace('<!-- LAB: mux -->','<!-- LAB: recurrence -->')
start=s.index('body=text(source);anchors=');end=s.index(';it=iter(anchors)',start)
anchors=['sources','domain','classification','unrolling','variable','uniqueness','characteristic','distinct','repeated','completeness','zero','complex','fibonacci','forcing','resonance','mixed','counting','patterns','derangements','set-partitions','integer-partitions','catalan','prefix','generating','matrix','modular','verification','summary','problems','review','laboratory','references']
s=s[:start]+'body=text(source);anchors='+repr(anchors)+s[end:]
s=s.replace("print('Rendered only", "print('Rendered only").replace('82 worked problems, 80 final rules, 15 stored circuit/process models.','83 worked problems, 80 final rules, 14 distinct mathematical models.')
s=s.replace("w=next(w for w in weeks if w['week']==4)", "w=next((w for w in weeks if w['week']==4),None)\nif w is None:\n w=dict(week=4,title='Week 4 chapter library',description='Source-reviewed chapters are added sequentially under your standing authorization. Completed drafts remain available for student review.',chapters=[]);weeks.append(w)\nw['title']='Week 4 chapter library'\nw['description']='Source-reviewed chapters are added sequentially under your standing authorization. Completed drafts remain available for student review.'")
(B/'render_d_recurrence.py').write_text(s,encoding='utf-8')
subprocess.run(['python','-X','utf8',str(B/'render_d_recurrence.py')],cwd=R,check=True)
print('Built recurrence draft:',len(questions),'original/reconstructed questions,',len(models),'models,',sum(len(m['frames'])for m in models),'checkpoints.')
