from pathlib import Path
import json,re,subprocess,hashlib
B=Path(__file__).resolve().parent;R=B.parent;E=B/'a_heap-evidence';E.mkdir(exist_ok=True)
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
source=(B/'a_heap-problems.en.md').read_text(encoding='utf-8');qs=[]
for n,title,stem,sol in re.findall(r'## Q(\d+)\. (.*?)\n\n### Prompt\n([\s\S]*?)\n### Solution\n([\s\S]*?)(?=\n## Q|\Z)',source):
 qs.append(dict(id='a_heap_Q'+n,title=title,stem=stem.strip(),solution=sol.strip(),origin='Original or independently reconstructed written-course exercise family; exact data and full solution authored for this chapter.',difficulty='Foundation diagnostic'if int(n)in[1,4,6,7]else'Medium to hard'))
assert len(qs)==80
specs=[('shape','Complete shape: one child at the final internal node',dict(operation='build',keys=list(range(1,11)))),('up','Q13: insert 2 through three ancestors',dict(operation='insert',keys=[5,9,8,12,10,14,11],value=2)),('down','Q16: extract 2 and repair two edges',dict(operation='extract',keys=[2,5,8,9,10,14,11,12])),('build','Q25: exact bottom-up construction',dict(operation='build',keys=[9,4,7,1,0,3,2])),('indexed','Q37: decrease F from 14 to 1; IDs follow records',dict(operation='change',keys=[2,5,8,9,10,14,11],index=5,value=1)),('sort','Q43: max-heap prefix and final suffix',dict(operation='sort',keys=[9,4,7,1,0,3,2])),('multiway','Ternary construction with clipped final children',dict(operation='multiway',keys=[9,4,7,1,0,3,2,8,6,5,12,10,11],arity=3)),('binomial','Singleton carries: canonical binomial size 13',dict(operation='binomial',keys=list(range(13,0,-1)))),('fibonacci','Q73: first child loss, second loss and cascade',dict(operation='fibonacci')),('insert-large','Q14: an insertion stopping immediately',dict(operation='insert',keys=[2,5,8,9,10,14,11],value=20)),('extract-small','Q17: choose the right child during extraction',dict(operation='extract',keys=[1,4,2,9])),('equal-children','Q19: left preference on equal child priorities',dict(operation='change',keys=[1,4,4,7,9,8,10],index=0,value=6)),('max-insert','Q22: max orientation and three upward exchanges',dict(operation='insert',keys=[15,10,12,8,6,9,11],value=16,orientation='max')),('increase','Q38: increase the root to 12',dict(operation='change',keys=[2,5,8,9,10,14,11],index=0,value=12)),('delete-up','Q39: arbitrary deletion repairs upward',dict(operation='delete',keys=[1,10,2,11,12,3,4],index=3)),('delete-down','Q40: arbitrary deletion repairs downward',dict(operation='delete',keys=[1,3,2,5,4,6,7],index=1)),('equal-sort','Q44: early stopping with equal numeric priorities',dict(operation='sort',keys=[4,4,4,4,4,4,4])),('unstable','Q45: three record identities expose instability',dict(operation='sort',keys=[2,2,1])),('topk','Q53: retain the three largest stream entries',dict(operation='topk',keys=[5,1,9,4,8,2,10],k=3)),('frontier','Q54: fourth smallest without changing the source',dict(operation='frontier',keys=[1,4,2,8,5,3,7],k=4)),('binomial-eight','Carry-only insertion ending at one rank-three root',dict(operation='binomial',keys=[8,7,6,5,4,3,2,1]))]
temp=E/'model-specs.json';save(temp,[dict(id=id,title=t,spec=s)for id,t,s in specs]);node="const fs=require('fs'),h=require('./dist/chapters/a_heap.js'),a=JSON.parse(fs.readFileSync('research/a_heap-evidence/model-specs.json'));process.stdout.write(JSON.stringify(a.map(x=>h.makeModel(x.id,x.title,x.spec))))"
p=subprocess.run(['node','-e',node],cwd=R,capture_output=True,text=True,check=True);models=json.loads(p.stdout)
groups={k:[k]for k in['shape','up','down','build','indexed','sort','multiway','binomial','fibonacci']}
save(R/'dist/chapters/a_heap-models.json',dict(models=models,groups=groups))
match={13:'up',14:'insert-large',16:'down',17:'extract-small',19:'equal-children',22:'max-insert',25:'build',37:'indexed',38:'increase',39:'delete-up',40:'delete-down',43:'sort',44:'equal-sort',45:'unstable',53:'topk',54:'frontier',64:'binomial-eight',73:'fibonacci'}
for i,id in match.items():
 qs[i-1]['modelId']=id;qs[i-1]['visualQualification']='Exact companion for the stated inputs. Stable E/B/F identifiers in the saved state distinguish records, including equal priorities. For Q43 the first two completed sortdown checkpoints are the requested intermediate answer; later checkpoints finish the same sort. For Q64 the displayed eight-record carry illustrates the same rank rule, while the written solution computes the stated larger size boundary.'if i in[43,64]else'Exact companion for this problem\'s stated records and operation; intermediate states are labeled separately from completed invariants.'
save(B/'a_heap-questions.json',qs)
base=json.loads((B/'exam-calibration/actual-items.json').read_text());q=copyq=next(x for x in base if x['id']=='MS_CE_1405_Q56').copy();q['title']='Sequential merge versus a heap-head frontier';q['topics']=['a_heap'];q['translationStatus']='Original PDF page 12 re-rendered and visually read for this chapter.'
ph=dict(id='Phd_CE_1405_Q4',booklet='Phd_CE_1405',pdfPage=2,questionNumber=4,topics=['a_heap'],title='Selecting a logarithmic rank from an existing max heap',stem='In an existing binary max heap of size $n$, in what running-time order can the $(\\log n)$th largest entry be obtained efficiently?',options=['$O(n)$','$O((\\log n)^2)$','$O(\\log n)$','$O(\\log n\\log\\log n)$'],answer=4,solution='Use a second max heap of frontier positions in the existing source heap. Initially insert the source root. Each time a frontier record is extracted, insert its existing source children. Every unreturned source record lies below a frontier ancestor no smaller than it, so successive frontier extractions yield the next source ranks without modifying the source. After $k$ selections, frontier size is at most $k+1$; the total is $O(k\\log(k+1))$. For the intended asymptotic rank $k=\\Theta(\\log n)$, this gives $O(\\log n\\log\\log n)$, option 4. Repeatedly extracting from the source instead gives a valid but larger $O((\\log n)^2)$ upper bound. A full scan ignores heap order. The listed answer is a constructive bound for the standard frontier algorithm; this derivation does not claim an optimal-selection lower bound. The original notation leaves integer rounding implicit; choose floor or ceiling consistently for sufficiently large n.',repoPath='Exams/Phd/CE/1405/Q707A-phd1405-[www.konkur.in].pdf',sourceSha256='34d7e4f8f1d347be2ede1be4ff027efc2e17680c3aedf633a13857f27955b75a',sourceCommit='bdadf6e2c9cadc4772ae137a96a3da753c7cfd08',translationStatus='Original PDF page 2 visually read for this chapter; independently derived answer.',answerProvenance='Independently derived; not an official key')
save(B/'a_heap-authentic.json',[ph,q])
sources=[]
for file in['acquisition.json','acquisition-more.json']:
 sources+=json.loads((E/file).read_text())
save(E/'reading.json',dict(status='reviewed_written_sources',coreUniversities=['MIT','CMU','Princeton','Cambridge'],additionalUniversities=['Stanford'],nativeHashes=[x for x in sources if x.get('sha256')],readRanges=dict(MIT='Lecture 8 all seven PDF pages; page three rendered.',CMU='Lecture 25 all 13 pages and Lecture 26 all 24 pages official web PDF text; native file unavailable.',Princeton='Spring 2025 all 43 slide PDF pages plus full written booksite §2.4.',Cambridge='Algorithms 2 PDF pages 53–76, printed 51–74; both pages of example sheet six; PDF page 69 diagram rendered.',Stanford='Spring 2020 all 16 written HTML slides; Autumn 2023 written heap page.'),limits='Nine offerings from eight universities screened; inaccessible/inventory sources are not counted as read.'))
css=(R/'dist/chapters/a_balanced.css').read_text().replace('bl-','hp-').replace('#bl','#hp').replace('svg .hp-key-long','svg .hp-long');css+='\n.hp-model svg .hp-key{font-family:"STIX Two Math",serif!important;font-size:16px!important;fill:#163d55}.hp-model svg .hp-medium{font-size:14px!important}.hp-model svg .hp-long{font-size:12px!important}.hp-model svg .hp-meta{font-size:14px!important}.hp-stage svg{min-width:680px;max-width:none}.hp-stage{max-height:420px}.hp-model svg .hp-prose{font-size:16px!important}\n'
css+='\n.hp-model svg .hp-id{font-family:STIX Two Math,serif!important;font-size:12px!important;fill:#385d6e}\n'
(R/'dist/chapters/a_heap.css').write_text(css,encoding='utf-8')
print('Prepared 80 fully worked original/reconstructed questions, 2 checked authentic questions, 80 final rules and',len(models),'exact models /',sum(len(m['frames'])for m in models),'checkpoints.')
