const fs=require('fs'),path=require('path');
require('../dist/chapters/a_select.js');const M=globalThis.SelectionModels,models=[],groups={};
function add(group,m){models.push(m);if(group)(groups[group]??=[]).push(m.id);}
add('rank',M.rank([8,3,3,9,3,1],3,'rank-example'));
add('rank',M.rank([2,2,2,2],2,'rank-all-equal'));
add('linear',M.linear([8,2,9,1,7,4],7,'linear-success'));
add('linear',M.linear([8,2,9,1,7,4],5,'linear-failure'));
add('binary',M.bound([1,3,3,3,7,9,12,18],3,false,'binary-example'));
add('binary',M.bound([2,4,6,8,10],20,false,'binary-after-end'));
add('boundary',M.bound([1,3,3,3,7,9,12,18],3,true,'upper-repeats'));
add('boundary',M.bound([0,1,4,9,16,25,36,49,64,81,100],70,false,'threshold-example'));models.at(-1).title='Monotone square predicate: first true candidate';models.at(-1).invariant='Each slot is integer t and each key is t squared; sortedness corresponds to predicate monotonicity on nonnegative integers.';
add('extrema',M.tournament([5,1,9,4,8,2,7,3],'tournament-example'));
add('extrema',M.minmax([5,1,9,4,8,2,7,3],'paired-extrema'));
add('partition',M.quick([3,2,1],1,{id:'partition-example',partitionOnly:true,pivot:2}));
add('partition',M.quick([5,2,5,9,1,5,7],4,{id:'partition-repeats',partitionOnly:true,pivot:5}));
add('select',M.quick([9,3,5,1,8,5,2,7],6,{id:'quick-rank-six'}));
add('select',M.quick([4,4,4,4,4],3,{id:'quick-all-equal'}));
add('random',M.quick([1,2,3,4,5,6,7,8],8,{id:'extreme-pivot-run',policy:'first'}));models.at(-1).title='An unlucky or adversarial extreme-pivot path';
add('groups',M.groups([1,2,3,10,11,4,5,6,12,13,7,8,9,14,15],'groups-example'));
add('groups',M.groups([14,2,17,4,7,8,19,1,20,3,18,5,11,16,9,10,6],'groups-partial'));
add('two',M.two([1,4,9],[2,3,7,10],4,'two-example'));
add('two',M.two([1,2,2],[2,2,9],4,'two-repeated'));
add('weighted',M.weighted([1,4,9],[1,7,2],'weighted-example'));
add('weighted',M.weighted([1,5,5,8],[2,2,3,3],'weighted-repeat'));
add(null,M.bound([1,2,2,2,4,4,9],2,false,'problem-frequency-lower'));
add(null,M.bound([1,3,3,5,8,8,11],8,true,'problem-range-upper'));
add(null,M.quick([3,2,1],1,{id:'problem-replacement',partitionOnly:true,pivot:2}));
add(null,M.quick([1,2,3,4,5,6],6,{id:'problem-quadratic',policy:'first'}));
add(null,M.quick([1,2,2,2,2,8],4,{id:'problem-top-k'}));
add(null,M.two([],[2,5,8,11],3,'problem-two-empty'));
add(null,M.tournament([4,1,5,2,3],'problem-tournament-bye'));
add(null,M.weighted([2,10],[1,1],'problem-weight-gap'));
add(null,M.weighted([0,10,20,30,40],[96,1,1,1,1],'problem-heavy-weight'));
add(null,M.quick([9,2,6,5,1,8,7,3,4],7,{id:'problem-deterministic',policy:'deterministic'}));
add(null,M.groups([9,1,8,2,7,3,6,4,5,10],'problem-two-groups'));
add(null,M.expected());
fs.writeFileSync(path.join(__dirname,'../dist/chapters/a_select-models.json'),JSON.stringify({groups,models},null,2)+'\n');
console.log(JSON.stringify({models:models.length,frames:models.reduce((n,m)=>n+m.frames.length,0),lessonModels:Object.values(groups).flat().length}));
