from pathlib import Path
import json
from a_sort_visuals import GUIDES
B=Path(__file__).parent;D=B.parent/'dist/chapters'
s=(B/'a_sort_player.js').read_text(encoding='utf-8').replace("'use strict';","'use strict';\n const teachingGuides="+json.dumps(GUIDES)+";")
(D/'a_sort.js').write_text(s+(B/'a_sort_lab.js').read_text(encoding='utf-8'),encoding='utf-8')
s=(D/'a_stackqueue.css').read_text(encoding='utf-8').replace('sq-','sort-')
s+='\n.sort-key{font-family:"STIX Two Math",serif!important;font-size:22px}.sort-id{font-family:"Source Sans 3",sans-serif!important;font-size:13px}.sort-label{font-family:"Source Sans 3",sans-serif!important;font-size:17px}.sort-meta{font-size:15px}.sort-index{font-size:13px}.sort-stage svg{max-height:none}.sort-stage svg text{font-weight:400}#sort-form input[name=values]{width:260px;max-width:100%}.sort-print-trace .sort-key{font-size:22px}.sort-print-trace .sort-label{font-size:17px}\n'
s+='\n.sort-teaching{margin:18px 0;padding:18px 20px;background:#eef5fb;border-left:3px solid #4679a5;border-radius:6px}.sort-teaching p{margin:10px 0}.sort-decision{display:flex;gap:20px;align-items:center;flex-wrap:wrap}.sort-decision>strong{text-transform:capitalize;font-size:.9rem;color:#355f82}.sort-decision>span{display:flex;gap:18px;align-items:center}.sort-truth{font-size:.85rem;color:#315a70}.sort-regions{display:flex;flex-wrap:wrap;gap:10px;padding:0!important;list-style:none}.sort-regions li{padding:7px 12px;border-radius:5px;font-size:.85rem;background:white;border-top:3px solid #b3832c}.sort-regions [data-role=less],.sort-regions [data-role=done]{border-color:#287d6b}.sort-regions [data-role=equal],.sort-regions [data-role=pivot]{border-color:#8057aa}.sort-regions [data-role=greater]{border-color:#476d9e}.sort-guide summary{cursor:pointer;color:#355f82;font-size:.9rem}.sort-guide ol{padding-left:25px}.sort-guide li{padding:5px 8px;font-size:.9rem}.sort-guide li.current{background:#dbe9f6;font-weight:600;border-radius:5px}.sort-pointer{font-family:"STIX Two Math",serif!important;font-size:14px}.sort-controls{margin:15px 0}.sort-stage{padding-top:8px}.sort-stage svg{min-width:0}.sort-print-trace svg{min-width:0}@media(max-width:650px){.sort-teaching{padding:14px}.sort-model{padding:15px}.sort-controls input{max-width:120px}.sort-stage svg{min-width:900px}}@media print{.sort-teaching{display:none}}\n'
(D/'a_sort.css').write_text(s,encoding='utf-8')
