from pathlib import Path
import json,re,subprocess,hashlib
B=Path(__file__).resolve().parent;R=B.parent;E=B/'a_hash-evidence';E.mkdir(exist_ok=True)
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
qs=[]
for n,title,stem,sol in re.findall(r'## Q(\d+)\. (.*?)\n\n### Prompt\n([\s\S]*?)\n### Solution\n([\s\S]*?)(?=\n## Q|\Z)',(B/'a_hash-problems.en.md').read_text(encoding='utf-8')):
 qs.append(dict(id='a_hash_Q'+n,title=title,stem=stem.strip(),solution=sol.strip(),origin='Original or independently reconstructed written-course exercise family; numerical data and complete reasoning authored for this chapter.',difficulty='Medium to hard, with foundational diagnostics'))
assert len(qs)==80
specs=[
('chaining','Head insertion and exact chain comparisons',dict(operation='chain',capacity=5,keys=[1,6,11,2,7,3],commands=[dict(type='get',key=1)])),
('linear','Q31: wraparound linear route and an unsuccessful search',dict(operation='open',capacity=11,keys=[10,21,32,43,9],commands=[dict(type='get',key=54)])),
('tombstone','Q35: a deleted marker preserves displaced keys',dict(operation='open',capacity=11,keys=[10,21,32,43,9],commands=[dict(type='delete',key=21),dict(type='get',key=32)])),
('update','Q36: search beyond a marker before updating 32',dict(operation='open',capacity=11,keys=[10,21,32,43,9],commands=[dict(type='delete',key=21),dict(type='put',key=32,value=99)])),
('reuse','Q37: establish absence before reusing a tombstone',dict(operation='open',capacity=11,keys=[10,21,32,43,9],commands=[dict(type='delete',key=21),dict(type='put',key=54)])),
('shift','Q39: repair a circular cluster after deleting 21',dict(operation='shift',capacity=11,keys=[10,21,32,43,9],commands=[dict(type='delete',key=21)])),
('mixed-shift','Q40: skip an at-home record during repair',dict(operation='shift',capacity=5,keys=[0,1,5],commands=[dict(type='delete',key=0)])),
('square','Q47: square offsets at prime capacity eleven',dict(operation='open',capacity=11,policy='square',keys=[10,21,32,43])),
('square-failure','Q48: a composite square route can exhaust early',dict(operation='open',capacity=8,policy='square',keys=[0,8,16,24])),
('alternating','Q50: signed square coverage at prime capacity seven',dict(operation='open',capacity=7,policy='alternating',keys=[0,7,14,21,28,35,42])),
('triangular','Q51: a triangular permutation at capacity eight',dict(operation='open',capacity=8,policy='triangular',keys=[0,8,16,24,32,40,48,56])),
('double','Q54: key-dependent double-hash steps',dict(operation='open',capacity=11,policy='double',keyStep=True,keys=[10,21,32,43],commands=[dict(type='get',key=54)])),
('double-failure','Q52: step eight visits only three slots at capacity twelve',dict(operation='open',capacity=12,policy='double',step=8,keys=[2,14,26,38])),
('rebuild','Recompute homes while changing capacity seven to eleven',dict(operation='rebuild',capacity=7,newCapacity=11,keys=[12,26,19,33])),
('perfect','Q68: bucket zero and fourteen second-level slots',dict(operation='perfect',capacity=6,keys=[0,6,12,2,3,9])),
('horner','Q4: base-five polynomial prefix residues modulo seventeen',dict(operation='horner',capacity=17,base=5,keys=[1,2,3])),
('bloom','Bit sharing and a possible false-positive query',dict(operation='bloom',capacity=13,hashes=3,keys=[2,7,11],commands=[dict(type='get',key=15)])),
('cuckoo','Successful two-candidate placement with displacements',dict(operation='cuckoo',capacity=3,keys=[0,1,4,5])),
('cuckoo-failure','Three keys competing for two candidate positions',dict(operation='cuckoo',capacity=3,keys=[0,9,18])),
('robin','Displacement comparison in Robin Hood insertion',dict(operation='robin',capacity=7,keys=[0,7,1,14])),
('all-markers','Q38: one live key, nine markers and bounded reuse',dict(operation='open',capacity=10,keys=list(range(10)),commands=[dict(type='delete',key=k)for k in range(9)]+[dict(type='get',key=10),dict(type='put',key=10)]))]
save(E/'model-specs.json',[dict(id=i,title=t,spec=s)for i,t,s in specs])
node="const fs=require('fs'),h=require('./dist/chapters/a_hash.js'),a=JSON.parse(fs.readFileSync('research/a_hash-evidence/model-specs.json'));process.stdout.write(JSON.stringify(a.map(x=>h.makeModel(x.id,x.title,x.spec))))"
p=subprocess.run(['node','-e',node],cwd=R,capture_output=True,text=True,check=True);models=json.loads(p.stdout)
groups=dict(arithmetic=['horner'],chaining=['chaining'],linear=['linear'],deletion=['tombstone','update','shift'],quadratic=['square','square-failure','triangular'],double=['double','double-failure'],rebuild=['rebuild'],perfect=['perfect'],advanced=['bloom','cuckoo','cuckoo-failure','robin'])
save(R/'dist/chapters/a_hash-models.json',dict(models=models,groups=groups))
match={4:'horner',31:'linear',35:'tombstone',36:'update',37:'reuse',38:'all-markers',39:'shift',40:'mixed-shift',47:'square',48:'square-failure',50:'alternating',51:'triangular',52:'double-failure',54:'double',63:'rebuild',68:'perfect',73:'bloom',75:'cuckoo-failure'}
for n,id in match.items():
 qs[n-1]['modelId']=id;qs[n-1]['visualQualification']='Exact deterministic companion for the stated inputs and declared operation. Read the saved state to distinguish intermediate repair from completed lookup invariants.'
for n,note in {4:'Exact companion for the first part: [1,2,3] at base five modulo seventeen. The written second part separately demonstrates the degenerate base eighteen.',40:'The compact five-slot example illustrates why an at-home record is skipped; use the written solution for its particular slot layout.',63:'The compact companion changes capacity seven to eleven, rather than the fourteen-slot calculation in the prompt. It illustrates recomputing homes and preserving records.',73:'The thirteen-bit mechanism demonstration uses explicitly declared deterministic bit functions. It is not a numerical visualization of the ideal 1000-bit probability calculation.',75:'The compact three-key example has candidate positions L0 and R0 for each key, so three records cannot fit in two positions. This illustrates the same candidate-set obstruction with different inputs.',78:'The Robin Hood companion illustrates displacement exchange. The prompt asks for a multi-operation ordered dictionary design, whose proof is given in the written solution.'}.items():qs[n-1]['visualQualification']=note
save(B/'a_hash-questions.json',qs)
commit='bdadf6e2c9cadc4772ae137a96a3da753c7cfd08';root=Path('C:/Users/bheydari/AppData/Local/Temp/exam-calibration-1406/source')
paths=['Exams/Phd/CE/1404/Q906A-PHD1404-[www.konkur.in].pdf','Exams/MS/CE/1404/Daftarche-Soalat-Konkur-Arshad-Computer-1404 (konkurcomputer.ir).pdf']
auth=[dict(id='Phd_CE_1404_Q4',booklet='Phd_CE_1404',pdfPage=3,questionNumber=4,title='Total collisions versus the collisions of one key',stem='Insert $n$ distinct keys into $m$ buckets using simple uniform hashing and separate chaining. For any fixed distinct pair, collision probability is $1/m$. What is the asymptotic order of the expected total number of colliding pairs?',options=[r'$\Theta(n/m)$',r'$\Theta(m/n)$',r'$\Theta(1/m)$',r'$\Theta(n^2/m)$'],answer=4,solution=r'For each unordered pair $\{i,j\}$ define $I_{ij}=1$ if their homes coincide and zero otherwise. The total pair count is $C=\sum_{i<j}I_{ij}$. Linearity gives $E[C]=\sum_{i<j}E[I_{ij}]=\binom n2/m=n(n-1)/(2m)$. Therefore the intended asymptotic answer is option 4, for $n\geq2$ and the standard growing-input interpretation. At $n=1$ the exact answer is zero, so the formula rather than an unqualified Theta statement should be used for degenerate inputs. Option 1 describes the order of collisions involving one selected key, whose expectation is $(n-1)/m$; it does not count all unordered pairs. The argument needs the specified pair probability but does not need independent pair indicators.'),
dict(id='MS_CE_1404_Q65',booklet='MS_CE_1404',pdfPage=15,questionNumber=65,title='A hash index within a dynamic priority and median structure',stem='A dynamic priority list stores a key and priority in every record. It must support insert(x,p), DeleteMax(), FindMedian() over the keys, and IncreasePriority(x,k). DeleteMax removes the first record from the left when maximum priorities tie. Which combined structure best supports efficient operations?',options=['A heap and a queue for entry order and removal.','A Fibonacci heap and a simple classification of keys and priorities.','A double-ended heap for priorities and a sorted structure for median access.','A balanced binary search tree storing keys and priorities, plus a hash table for fast access.'],answer=4,answerLabel='Independently justified construction: option',solution=r'Option 4 supports an explicit efficient construction, provided the tree is augmented rather than treated as an unmodified search tree. Order the balanced tree by key; store subtree size and the best-priority record, with actual list-order metadata breaking ties. A hash index maps a unique key to its tree record. Insert changes one search path and rebalances, updating both aggregates. DeleteMax follows the best-record aggregate, removes that record and its hash entry, and repairs the same aggregates. FindMedian performs a rank selection using subtree sizes. IncreasePriority finds the record through the index and propagates the changed priority aggregate to the root. Tree work is $O(\log n)$ per operation; hash-index access is expected $O(1)$ under its declared model, with a linear worst case unless a stronger dictionary is supplied. This construction assumes insertion appends to the list, so a stable arrival identifier gives the left-to-right tie order. If insertion instead chooses an arbitrary list position, additional order-maintenance machinery and its costs must be analyzed. If duplicate keys are legal, the key-to-record contract needs explicit disambiguation; if insertion changes list position, tie metadata must represent that position rather than blindly assume arrival order. The short booklet options do not specify augmentations or the meaning of the sorted structure in option 3. If that structure is itself a balanced order-statistic tree with handles into an indexed double-ended heap, option 3 can also support logarithmic updates. Thus this chapter demonstrates option 4 as a viable intended combination; it does not assert a uniquely certified official answer. The important lesson is to design every operation and tie rule, rather than infer efficiency from names of structures alone.')]
for q,path in zip(auth,paths):q.update(topics=['a_hash'],repoPath=path,sourceCommit=commit,sourceSha256=hashlib.sha256((root/path).read_bytes()).hexdigest(),translationStatus='Original PDF page visually read; English mathematical adaptation.',answerProvenance='Independently derived; no official key claimed')
save(B/'a_hash-authentic.json',auth)
acq=[]
for name in ['acquisition.json','acquisition-more.json']:acq+=json.loads((E/name).read_text(encoding='utf-8'))
save(E/'reading.json',dict(status='reviewed_written_sources',coreUniversities=['MIT','CMU','Princeton','ETH Zurich'],additionalUniversities=['Stanford','Cambridge'],nativeHashes=[x for x in acq if x.get('sha256')],readRanges=dict(MIT='All five pages of 6.006 Spring 2020 lecture 4 through official web PDF text; native attempts timed out.',CMU='All eleven pages of 15-122 lecture 12 including exercises through official web PDF text; native connection refused.',Princeton='All 46 slide PDF pages and complete written Algorithms section 3.4 including exercises.',ETH='All 98 English Lecture 9 PDF pages; probing, universal parameters, birthday and perfect formulas additionally rendered and inspected.',Stanford='Entire 19-part Summer 2025 written hashing page, code and exam discussion.',Cambridge='All 22 lecture 8 PDF pages inspected; hashing specifically PDF pages 16–17.'),limits='Bounded candidate evaluation from eight universities; inaccessible candidates not counted as read. Source corrections and distinct probability assumptions explicitly recorded.'))
css=(R/'dist/chapters/a_heap.css').read_text(encoding='utf-8').replace('hp-','hs-').replace('#hp','#hs');css+='\n.hs-model svg text{font-size:15px}.hs-model svg .hs-key{font-size:16px!important}.hs-model svg .hs-caption{font-size:17px!important}.hs-model [data-hs-model=chaining] svg .hs-key{font-size:14px!important}.hs-stage svg{min-width:680px;max-width:none}.hs-stage{max-height:420px}\n'
css+='\n.hs-model svg [data-entity="probe"] .hs-key{font-family:"Source Sans 3",sans-serif!important;font-size:13px!important}\n'
css+='\n.hs-model svg [data-entity^=bucket-] .hs-key,.hs-model svg [data-entity^=K] .hs-key{font-size:14px!important}\n'
(R/'dist/chapters/a_hash.css').write_text(css,encoding='utf-8')
print('Built',len(qs),'original and',len(auth),'authentic problems;',len(models),'models and',sum(len(m['frames'])for m in models),'checkpoints.')
