from pathlib import Path
import json,re,subprocess,hashlib,fitz
B=Path(__file__).resolve().parent;R=B.parent;E=B/'a_bst-evidence'
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
js=R/'dist/chapters/a_bst.js';s=js.read_text(encoding='utf-8')
s=s.replace('ratio=Math.min(1,Math.abs(dy/dx)),sx=p.x+Math.sign(dx)*25,sy=p.y+ratio*21,ex=c.x-Math.sign(dx)*25,ey=c.y-ratio*21,mid=(sy+ey)/2','len=Math.hypot(dx,dy),sx=p.x+dx/len*25,sy=p.y+dy/len*25,ex=c.x-dx/len*25,ey=c.y-dy/len*25,mid=(sy+ey)/2')
s=s.replace('C\'+sx+\' \'+mid+\' \'+ex+\' \'+mid+\' \'+ex+\' \'+ey', 'L\'+ex+\' \'+ey')
s=s.replace("'<g data-key=\"'+n.key+'\"><rect x=\"'+(p.x-25)+'\" y=\"'+(p.y-21)+'\" width=\"50\" height=\"42\" rx=\"10\" fill=\"'", "'<g data-key=\"'+n.key+'\"><circle cx=\"'+p.x+'\" cy=\"'+p.y+'\" r=\"25\" fill=\"'")
js.write_text(s,encoding='utf-8')
if 'data-entity="bst-entry-' not in s:
 s=s.replace("'<g data-key=\"'+n.key+'\">'", "'<g data-entity=\"bst-entry-'+n.key+'\" data-key=\"'+n.key+'\">'")
# Replace the opening group when circle markup is part of the same literal.
s=s.replace("'<g data-key=\"'+n.key+'\"><circle", "'<g data-entity=\"bst-entry-'+n.key+'\" data-key=\"'+n.key+'\"><circle")
s=s.replace('Reasoning checkpoint','Exact checkpoint').replace('height="31" rx="6"','height="42" rx="6"').replace('(by+21)','(by+27)')
s=s.replace('by=H-45','by=H-55')
js.write_text(s,encoding='utf-8')
base=[40,20,70,10,30,60,80,25,65]
specs=[('owned-tree','Nine nodes, ten null gaps, edge height three',dict(operation='structure',keys=base),'structure'),('ancestor-bound','Why the grandchild 25 violates root 20',dict(operation='bounds',keys=[20,10,30,25]),'bounds'),('search-27','Absent query 27: four comparisons and its bracketing keys',dict(operation='search',keys=base,q=27),'search'),('insert-nine','The nine exact insertions and sixteen comparisons',dict(operation='insert',keys=base),'insert'),('neighbors-27','Floor 25 and ceiling 30 for absent query 27',dict(operation='neighbors',keys=base,q=27),'neighbors'),('successor-30','Climb from 30 to the first larger ancestor 40',dict(operation='successor',keys=base,q=30),'successor'),('delete-leaf','Remove actual leaf 10 without losing another key',dict(operation='delete',keys=base,q=10),'simple-delete'),('delete-one','Remove 60 while retaining its child 65',dict(operation='delete',keys=base,q=60),'simple-delete'),('delete-deep','Delete 40: successor 60 has surviving right child 65',dict(operation='delete',keys=base,q=40),'deep-delete'),('delete-immediate','Delete 40: immediate successor 60 retains child 70',dict(operation='delete',keys=[40,20,60,70],q=40),'immediate-delete'),('inorder-stack','Emit the nine increasing keys exactly once',dict(operation='traversal',keys=base),'traversal'),('preorder-eight','Build eight nodes from inherited preorder intervals',dict(operation='reconstruct',keys=[50,30,20,40,35,80,70,90]),'reconstruct'),('preorder-invalid','Reject the unconsumed key 15 after entering the right block',dict(operation='reconstruct',keys=[20,10,5,30,15]),'reconstruct'),('strict-rank-65','Strict rank of 65 is six',dict(operation='rank',keys=base,q=65),'rank'),('select-six','Zero-based select at six returns 65',dict(operation='select',keys=base,q=6),'rank'),('range-inclusive','Prune and report the six keys from 25 through 70',dict(operation='range',keys=base,a=25,b=70),'range'),('counted-three','Three distinct nodes own six occurrence ranks',dict(operation='multiplicity',keys=[8,3,11]),'multiplicity'),('exact-costs','Internal sum sixteen, external sum thirty-four',dict(operation='cost',keys=base),'path-cost'),('perfect-orders','All eighty producing permutations of the perfect seven-node tree',dict(operation='orders',keys=[4,2,1,3,6,5,7]),'orders'),('left-rotation','Rotate 20 below 40 while preserving all five keys',dict(operation='rotation',keys=[20,10,40,30,50]),'rotation'),('three-permutations','Six equiprobable insertion orders produce five unequal-probability shapes',dict(operation='random',keys=[1,2,3]),'random')]
code="const{makeModel}=require('./dist/chapters/a_bst.js');const a="+json.dumps(specs)+";process.stdout.write(JSON.stringify(a.map(x=>makeModel(x[0],x[1],x[2]))));"
specs += [('minimum-child','Question 6: removing minimum 20 preserves its right child 25',dict(operation='delete',keys=[30,20,25],q=20),'problem-only'),('chain-root','Question 11: delete root 9 and return its surviving child 5',dict(operation='delete',keys=[9,5,3],q=9),'problem-only'),('stack-seven','Question 13: the exact seven-key inorder emissions',dict(operation='traversal',keys=[8,4,12,2,6,10,14]),'problem-only'),('pair-reconstruction','Question 16: reconstruct the exact five-key preorder',dict(operation='reconstruct',keys=[3,2,1,5,4]),'problem-only'),('leaf-parent','Question 59: leaf 10 has parent 20 as its successor',dict(operation='successor',keys=[20,10,30],q=10),'problem-only'),('compound-result','Question 80: the final nine-key tree and exact path sums',dict(operation='cost',keys=[60,20,10,30,25,50,70,65,80]),'problem-only')]
code="const{makeModel}=require('./dist/chapters/a_bst.js');const a="+json.dumps(specs)+";process.stdout.write(JSON.stringify(a.map(x=>makeModel(x[0],x[1],x[2]))));"
models=json.loads(subprocess.check_output(['node','-e',code],cwd=R,text=True,encoding='utf-8'));groups={}
for id,title,raw,g in specs:groups.setdefault(g,[]).append(id)
save(R/'dist/chapters/a_bst-models.json',dict(models=models,groups=groups))
parts=re.split(r'^### (\d+)\. (.+)$','\n\n'.join((B/f'a_bst-problems{x}.en.md').read_text(encoding='utf-8')for x in['','-2','-3']),flags=re.M)
visuals={1:'ancestor-bound',3:'insert-nine',4:'search-27',7:'successor-30',8:'delete-deep',9:'delete-immediate',14:'preorder-eight',15:'preorder-invalid',18:'select-six',19:'range-inclusive',22:'counted-three',24:'exact-costs',28:'perfect-orders',30:'three-permutations',41:'left-rotation'}
visuals.update({6:'minimum-child',11:'chain-root',13:'stack-seven',16:'pair-reconstruction',59:'leaf-parent',80:'compound-result'})
qs=[]
for i in range(1,len(parts),3):
 n=int(parts[i]);stem,solution=parts[i+2].strip().split('#### Solution',1);qs.append(dict(id=f'a_bst_original_{n:02d}',title=parts[i+1],stem=stem.strip(),solution=solution.strip(),origin='Independently authored mathematical/conceptual problem; explicitly identified university-pattern reconstructions use new data and original solutions.',**({'modelId':visuals[n],'visualQualification':'This checkpoint model uses the same tree or structural witness and target as the relevant part of this problem. Other requested quantities are derived in the written solution.'}if n in visuals else{})))
assert len(qs)==80;save(B/'a_bst-questions.json',qs)
for q in qs:
 if q['id']=='a_bst_original_11':q['visualQualification']='This model shows the first root deletion in the stated chain. The subsequent absent, leaf and singleton deletions are derived separately in the solution.'
 if q['id']=='a_bst_original_59':q['visualQualification']='This three-key witness illustrates the left-leaf case of the general statement. The nonleaf counterexample and mirror proof are given in the solution.'
 if q['id']=='a_bst_original_80':q['visualQualification']='This model audits the final tree after the compound update, with the exact nine surviving keys and path sum. It does not replay the earlier association replacement and deletion.'
save(B/'a_bst-questions.json',qs)
cache=Path('C:/Users/bheydari/AppData/Local/Temp/exam-calibration-1406/source');manifest=json.loads((B/'exam-calibration/archive-manifest.json').read_text());actual=json.loads((B/'exam-calibration/actual-items.json').read_text());auth=[dict(next(q for q in actual if q['id']=='Phd_CE_1405_Q3'))]
q=dict(id='MS_CE_1404_Q65',booklet='MS_CE_1404',pdfPage=15,questionNumber=65,topics=['a_bst','a_balanced','a_hash'],title='Dynamic priorities and median keys: an augmentation bridge',stem='A dynamic priority list stores entries with a key and priority. It supports insert(x,p), deleting a maximum-priority entry (ties select the leftmost entry), finding the median of all keys, and increasing the priority of key x by k. Which proposed combination best supports all operations efficiently?',options=['A stack and a queue for arrivals, departures, keys and priorities.','A Fibonacci heap and a plain linked list for entries and priorities.','A double-ended heap for priorities and an ordered structure for direct entry access.','A balanced binary search tree for keys and priorities, with a hash table for entry access.'],answer=4,solution='The required key median is an order statistic, not the maximum priority. A balanced key-ordered BST stores subtree sizes for select and a subtree maximum-priority entry with a deterministic leftmost tie rule. Its root aggregate identifies the deletion candidate; deleting that known key and refreshing aggregates costs logarithmic tree height. Insert and priority increase likewise refresh only one ancestor route. The tie rule can be represented by a stable list-position label; it is distinct from key order. A hash table maps keys to entries, subject to its expected lookup assumptions; searching the balanced BST by key can also retain logarithmic worst-case lookup without relying on hashing. If equal keys are allowed, entry identities or occurrence collections must be specified. A plain stack/queue or linked list cannot maintain median keys and arbitrary mutable priorities at logarithmic route cost; a heap alone does not maintain key ranks. Option 4 is the proposed combination that accommodates both requirements. Its subtree augmentations and declared tie policy are necessary details, not automatic features of a bare tree. This is an augmentation bridge: the next chapter supplies the height-guarantee proof, and hashing is analyzed separately. The answer is independently derived, not an official key.',sourceCommit=manifest['commit'],repoPath='Exams/MS/CE/1404/Daftarche-Soalat-Konkur-Arshad-Computer-1404 (konkurcomputer.ir).pdf',translationStatus='Checked English adaptation of original PDF page; leftmost tie wording retained.',answerProvenance='Independently derived; not an official key')
q['sourceSha256']=next(x['sha256']for x in manifest['files']if x['repoPath']==q['repoPath']);auth.insert(0,q)
for q in auth:
 p=cache/q['repoPath'];assert hashlib.sha256(p.read_bytes()).hexdigest()==q['sourceSha256'];d=fitz.open(p);d[q['pdfPage']-1].get_pixmap(matrix=fitz.Matrix(1.5,1.5)).save(str(E/(q['id']+'.png')))
 q['translationStatus']='Exact original PDF page re-rendered and visually read for this chapter; independently derived answer.'
 if q['id']=='Phd_CE_1405_Q3':q['solution']+='\n\n**BST connection and boundary.** This question concerns actual leaves in a general binary tree, not null search gaps. Extending a finite BST by its null positions instead gives exact dyadic gap mass one. The three-node chain has actual-leaf mass one quarter and null-gap mass one, separating the two notions. No BST ordering is needed for the original inequality.'
save(B/'a_bst-authentic.json',auth)
css=(R/'dist/chapters/g_mux.css').read_text(encoding='utf-8').replace('mx-','bt-')
css+='\n.bt-model{max-width:760px;margin:1.5rem auto}.bt-stage{max-height:420px;overflow:auto}.bt-stage svg{width:760px;max-width:100%;height:auto}.bt-model svg .bt-prose{font-family:"Source Sans 3",sans-serif!important;font-size:17px!important;fill:#163d55}.bt-model svg .bt-math{font-family:"STIX Two Math",serif!important;font-size:20px!important;fill:#163d55}.bt-model svg .bt-meta{font-family:"STIX Two Math",serif!important;font-size:16px!important;fill:#163d55}.bt-formula math{font-family:"STIX Two Math",serif}\n'
(R/'dist/chapters/a_bst.css').write_text(css,encoding='utf-8')
s=(B/'render_d_recurrence.py').read_text(encoding='utf-8').replace('d_recurrence','a_bst').replace('rc-','bt-').replace('83','82').replace('authenticQuestionCount=3','authenticQuestionCount=2').replace('animationCount=14','animationCount=27').replace('animationWalkthroughCount=14','animationWalkthroughCount=27').replace('14 distinct mathematical models','27 exact tree models').replace('Recurrence Relations: Exact Solutions, Counting Models, and Boundary Conditions','Binary Search Trees: Correctness, Ordered Queries, and Exact Costs').replace('Discrete Mathematics · Week 4','Data Structures and Algorithms · Week 4').replace('four reviewed written university courses','four core written university courses plus a fifth reviewed course')
start=s.index("lab='");end=s.index('\nsource=',start)
lab='<section class="lab"><form id="bt-form"><label>Operation<select name="operation">'+''.join('<option>'+op+'</option>'for op in['search','insert','delete','rank','select','range'])+'</select></label><label>Insertion keys<input name="keys" value="40,20,70,10,30,60,80,25,65"></label><label>Query or zero-based rank<input name="q" type="number" value="27"></label><label>Lower endpoint<input name="a" type="number" value="25"></label><label>Upper endpoint<input name="b" type="number" value="70"></label><button type="submit">Build the exact tree trace</button></form><p id="bt-error" role="alert"></p><p>Use one through nine distinct comma-separated integer keys between minus 999 and 999. Select requires a rank from zero through node count minus one. Range uses both inclusive endpoints in increasing order. Query applies to search, delete and rank; insertion uses the complete supplied sequence. Every trace begins paused. Invalid input preserves the previous valid model. These are unique-key dictionary traces; counted multisets are separately explained in the lesson.</p><div id="bt-output"></div></section>'
s=s[:start]+'lab='+repr(lab)+s[end:];s=s.replace('<!-- LAB: recurrence -->','<!-- LAB: bst -->')
start=s.index('body=text(source);anchors=');end=s.index(';it=iter(anchors)',start)
anchors=['sources','representation','structure','bounds','search','insert','neighbors','successor','simple-delete','deep-delete','traversal','reconstruct','rank','range','multiplicity','path-cost','orders','shapes','expectation','construction','lca','rotation','hazards','summary','problems','review','laboratory','references']
s=s[:start]+'body=text(source);anchors='+repr(anchors)+s[end:]
s=s.replace('14 distinct mathematical models','21 exact tree models')
(B/'render_a_bst.py').write_text(s,encoding='utf-8');subprocess.run(['python','-X','utf8',str(B/'render_a_bst.py')],cwd=R,check=True)
save(E/'reading.json',dict(coreUniversities=['CMU','Princeton','UC Berkeley','MIT'],additionalReviewedUniversity='Stanford',nativeAcquisition=json.loads(Path('C:/Users/bheydari/AppData/Local/Temp/a-bst-sources/acquisition.json').read_text()),readScopes={'CMU':'All 22 pages, including solutions','Princeton':'All 31 slides and full official §3.2 web chapter','Berkeley':'Lecture 24 all 215 lines and Lecture 26 all 232 lines','MIT':'Lecture 5 all 8 pages','Stanford':'All written lecture sections and supplementary code, including 15 exercise prompts'},limits='Bounded candidate pool; original teaching and reconstructed problems, not reproduction of full copyrighted collections.'))
print('Built a_bst: 82 solutions, 80 full rules;',len(models),'models;',sum(len(m['frames'])for m in models),'checkpoints.')
