from pathlib import Path
import json,hashlib
B=Path(__file__).resolve().parent;R=B.parent;E=B/'a_amortized-evidence'
def save(p,x):p.write_text(json.dumps(x,indent=2)+'\n',encoding='utf-8')
m=json.loads((E/'mathematics.json').read_text());v=json.loads((E/'browser.json').read_text());assert m['status']==v['status']=='passed'and not v['geometry']['issues']
prior=json.loads((E/'prior-library.json').read_text())['chapters'];assert len(prior)==55
for c in prior:assert hashlib.sha256((R/'dist'/c['url']).read_bytes()).hexdigest()==c['sha256']
cs=[c for w in json.loads((R/'dist/lessons.json').read_text())for c in w['chapters']];assert len(cs)==56 and sum(c['questionCount']for c in cs)==3826
save(E/'retention.json',dict(status='passed',unchangedChapterPages=55,libraryCards=56,workedQuestionEntries=3826))
save(E/'lesson-and-retention.json',dict(status='quality_review_complete',totalSections=25,teachingSections=20,workedQuestions=87,finalRules=80,coreUniversities=4,universitiesRead=5,models=20,checkpoints=691,studentApproved=False))
g=json.loads((B/'chapter-gate.json').read_text());assert g['currentTopicId']=='a_amortized'
g['completedReviewDrafts']=[c for c in g['completedReviewDrafts']if c['topicId']!='a_amortized']+[dict(topicId='a_amortized',state='quality_review_complete',studentApproved=False,url='chapters/a_amortized.html',qualityAudit='research/a_amortized-quality-audit.md',evidence=['research/a_amortized-evidence/'+k+'.json'for k in['reading','mathematics','browser']],publicationState='pending_upload')]
g.update(currentTopicId='s_variance',state='in_progress',nextTopicRequiresExplicitApproval=False,activeWork='Evaluate written probability sources and author variance and covariance under standing continuous authorization.',reviewScope='Second moments, covariance, correlation, conditional variance, transformations, independence and inequalities.',sourceAuditPath='research/s_variance-source-audit.md',sourceAudit='research/s_variance-source-audit.md',qualityAuditPath='research/s_variance-quality-audit.md',qualityAudit='research/s_variance-quality-audit.md',lastCompletedReview='a_amortized: 87 worked problems, 80 final rules, five reviewed universities, 20 models / 691 checkpoints; 9334 independent inputs / 294906 checkpoints.',nextReview='Complete s_variance scientific and visual audits.',reviewEvidence=['research/a_amortized-evidence/'+k+'.json'for k in['reading','mathematics','browser']])
save(B/'chapter-gate.json',g)
N=B/'s_variance-evidence';N.mkdir(exist_ok=True);save(N/'prior-library.json',dict(chapters=[dict(topicId=c['topicId'],url=c['url'],questions=c['questionCount'],sha256=hashlib.sha256((R/'dist'/c['url']).read_bytes()).hexdigest())for c in cs]))
with(R/'WEEKLY_DELIVERY.md').open('a',encoding='utf-8')as f:f.write('\n\n## Amortized-analysis review draft\n\nCompleted a_amortized: twenty deep teaching sections, 87 worked problem entries, 80 final rules, four core university courses and one additional university actually read. Twenty specialized models / 691 exact checkpoints. Independent checks passed 9334 inputs / 294906 checkpoints / 10869 result contracts; real Edge passed geometry, fonts, native mathematics, control behavior, editable boundaries, mobile and print. All 55 previous chapter HTML files are unchanged. Library: 56 chapters / 3826 worked entries. No student approval is inferred. Publication is tracked separately. Continue with s_variance under standing continuous authorization.\n')
print('Completed amortized-analysis review; library 56 chapters / 3826 worked entries; next s_variance.')
