from pathlib import Path
import json,hashlib
B=Path(__file__).resolve().parent;R=B.parent;E=B/'s_variance-evidence'
def save(p,x):p.write_text(json.dumps(x,indent=2)+'\n',encoding='utf-8')
m=json.loads((E/'mathematics.json').read_text());v=json.loads((E/'browser.json').read_text());assert m['status']==v['status']=='passed'and not v['geometry']['issues']
prior=json.loads((E/'prior-library.json').read_text())['chapters'];assert len(prior)==56
for c in prior:assert hashlib.sha256((R/'dist'/c['url']).read_bytes()).hexdigest()==c['sha256'],c['topicId']
cs=[c for w in json.loads((R/'dist/lessons.json').read_text())for c in w['chapters']];assert len(cs)==57 and sum(c['questionCount']for c in cs)==3913
save(E/'retention.json',dict(status='passed',unchangedChapterPages=56,libraryCards=57,workedQuestionEntries=3913))
save(E/'lesson-and-retention.json',dict(status='quality_review_complete',totalSections=24,teachingSections=18,workedQuestions=87,finalRules=80,coreUniversities=4,universitiesRead=6,models=23,checkpoints=169,studentApproved=False))
g=json.loads((B/'chapter-gate.json').read_text());assert g['currentTopicId']=='s_variance'
g['completedReviewDrafts']=[c for c in g['completedReviewDrafts']if c['topicId']!='s_variance']+[dict(topicId='s_variance',state='quality_review_complete',studentApproved=False,url='chapters/s_variance.html',qualityAudit='research/s_variance-quality-audit.md',evidence=['research/s_variance-evidence/'+k+'.json'for k in['reading','mathematics','browser']],publicationState='pending_upload')]
g.update(currentTopicId='s_distributions',state='in_progress',nextTopicRequiresExplicitApproval=False,activeWork='Evaluate written university sources and author discrete distributions under standing continuous authorization.',reviewScope='Bernoulli, binomial, geometric, negative-binomial, hypergeometric, Poisson and discrete-uniform laws; parameter conventions, modeling, moments, limits and solved problems.',sourceAuditPath='research/s_distributions-source-audit.md',sourceAudit='research/s_distributions-source-audit.md',qualityAuditPath='research/s_distributions-quality-audit.md',qualityAudit='research/s_distributions-quality-audit.md',lastCompletedReview='s_variance: 87 worked entries, 80 final rules, six universities actually read, 23 models / 169 checkpoints; 414 independent enumeration cases and 162 editable calculator cases.',nextReview='Complete s_distributions source, scientific and visual audits.',reviewEvidence=['research/s_variance-evidence/'+k+'.json'for k in['reading','mathematics','browser']])
save(B/'chapter-gate.json',g)
N=B/'s_distributions-evidence';N.mkdir(exist_ok=True);save(N/'prior-library.json',dict(chapters=[dict(topicId=c['topicId'],url=c['url'],questions=c['questionCount'],sha256=hashlib.sha256((R/'dist'/c['url']).read_bytes()).hexdigest())for c in cs]))
with(R/'WEEKLY_DELIVERY.md').open('a',encoding='utf-8')as f:f.write('\n\n## Variance and covariance review draft\n\nCompleted s_variance: eighteen deep teaching sections, 87 worked entries (84 original/reconstructed, three authentic, two explicitly revisited), 80 final rules, four core university courses plus two genuinely read university extensions. Twenty-three specialized models / 169 checkpoints / 47 placements. Independent review passed 414 enumeration cases, 162 editable calculator cases and 690 static MathML fence checks; real Edge passed every checkpoint, geometry, fonts, motion/pause/resume, mobile and print. All 56 previous chapter pages are unchanged. Library: 57 chapters / 3913 worked entries. No student approval is inferred; publication is tracked separately. Continue sequential authoring with s_distributions under standing authorization.\n')
print('Variance review complete; 57 chapters / 3913 entries; next s_distributions.')
