from pathlib import Path
B=Path(__file__).parent
s=(B/'render_a_stackqueue.py').read_text(encoding='utf-8').replace('a_stackqueue','a_sort').replace('StackQueue','Sorting').replace('Stacks, Queues, and Applications','Comparison and Non-comparison Sorting').replace('Stacks and Queues','Sorting').replace('sq-','sort-').replace('data-sq','data-sort').replace('84','88').replace('81','86').replace('four primary','four primary and one complementary').replace('authenticQuestionCount=3','authenticQuestionCount=2').replace('<!-- LAB:stackqueue -->','<!-- LAB:sorting -->')
start=s.index("lab='''");end=s.index("\nsource=",start)
lab='''<section class="lab" id="sort-lab"><form id="sort-form"><label>Algorithm<select name="kind"><option value="insertion">Stable insertion</option><option value="selection">Selection</option><option value="bubble">Early-exit bubble</option><option value="merge">Stable top-down merge</option><option value="quick">Strict Lomuto quicksort</option><option value="three">Three-way quicksort</option><option value="heap">Floyd heapsort</option><option value="counting">Stable counting</option><option value="radix">Stable LSD radix</option><option value="bucket">Bucket with local insertion</option></select></label><label>Integer keys<input name="values" value="4,1,3,1,2" aria-describedby="sort-limits"></label><label>Radix base / bucket count<input name="base" type="number" min="2" max="10" value="5"></label><button type="submit">Compute the complete trace</button></form><p id="sort-lab-error" role="alert"></p><p id="sort-limits">Enter 1–10 integers from −999 to 999. Counting intervals may contain at most 24 keys. Radix uses a monotone shift of the minimum key, and a base from 2 to 10. Bucket keys must be integer percentages from 0 to 99. The displayed comparison convention is specified in the lesson; radix/counting distribution uses no key comparisons. An invalid submission preserves the last valid trace.</p><div id="sort-output"></div></section>'''
s=s[:start]+"lab="+repr(lab)+s[end:]
start=s.index("anchors=[");end=s.index(';it=iter(anchors)',start)
s=s[:start]+"anchors=['sources','contract','costs','selection','insertion','bubble-shell','merge-counts','merge-extensions','partition','random-quick','duplicates','heap','lower-bound','counting','radix','bucket-strings','hybrids','summary','problems','review','laboratory','references']"+s[end:]
# No shared geometry mutator: authored ports are already precise.
s=s.replace('<script src="diagram-layout.js"></script>','')
s=s.replace("Vert='‖'","Pr='Pr',Vert='‖'")
(B/'render_a_sort.py').write_text(s,encoding='utf-8')
