from pathlib import Path
B=Path(__file__).parent;p=B/'a_sort_browser_body.py.txt';s=p.read_text(encoding='utf-8');anchor=" fixtures=json.loads"
extra=''' report['teachingGeometry']=js("""(()=>{let ports=0,states=0;const issues=[];for(const p of SortingChapter.players){if(p.model.id==='editable')continue;const root=document.querySelector('[data-sort-model="'+p.model.id+'"]');for(let i=0;i<p.model.frames.length;i++){p.draw(i);states++;const svg=root.querySelector('svg');for(const path of svg.querySelectorAll('[data-source-entity]')){const first=path.getPointAtLength(0),last=path.getPointAtLength(path.getTotalLength());for(const [id,q] of [[path.dataset.sourceEntity,first],[path.dataset.targetEntity,last]]){const b=svg.querySelector('[data-entity="'+id+'"] [data-box]').getBBox();const on=q.x>=b.x-.5&&q.x<=b.x+b.width+.5&&q.y>=b.y-.5&&q.y<=b.y+b.height+.5&&Math.min(Math.abs(q.x-b.x),Math.abs(q.x-b.x-b.width),Math.abs(q.y-b.y),Math.abs(q.y-b.y-b.height))<.5;if(!on)issues.push({id:p.model.id,i,detached:id});ports++;}}if(p.model.kind!=='decision')for(const path of svg.querySelectorAll('[data-edge]')){const len=path.getTotalLength();for(const text of svg.querySelectorAll('text')){const b=text.getBBox();for(let t=2;t<len-2;t+=4){const q=path.getPointAtLength(t);if(q.x>b.x+1&&q.x<b.x+b.width-1&&q.y>b.y+1&&q.y<b.y+b.height-1){issues.push({id:p.model.id,i,crossesLabel:text.textContent});break;}}}}}p.draw(0);}return {states,connectedPorts:ports,issues:issues.slice(0,20),issueCount:issues.length};})()""")
 (R/'research/a_sort-browser-audit.json').write_text(json.dumps(report,indent=2)+'\\n',encoding='utf-8');assert report['teachingGeometry']['issueCount']==0,report['teachingGeometry']
'''
assert s.count(anchor)==1;s=s.replace(anchor,extra+anchor,1)
# Check precise copied motion and keep the explanation adjacent to a displayed comparison.
anchor=" old=js("
extra=''' comparison=js("(()=>{const p=SortingChapter.players.find(x=>x.model.id==='concept-12');const k=p.model.frames.findIndex(f=>f.operation==='compare');p.draw(k);const el=document.querySelector('[data-sort-model=concept-12]');el.querySelector('.sort-guide').open=true;return {test:el.querySelector('.sort-decision').textContent,active:el.querySelector('[aria-current=step]').textContent,regions:el.querySelectorAll('.sort-regions li').length};})()");assert 'Compare' in comparison['test'].capitalize() or 'compare' in comparison['test'];assert comparison['regions']==4;report['visibleComparison']=comparison
 copied=js("(()=>{const p=SortingChapter.players.find(x=>x.model.id==='concept-6'),k=p.model.frames.findIndex(f=>f.transfer);p.draw(k-1);p.draw(k,true);return document.querySelector('[data-sort-model=concept-6] .sort-stage').getAnimations({subtree:true}).length;})()");assert copied>0;report['copiedRecordAnimations']=copied
'''
assert s.count(anchor)==1;s=s.replace(anchor,extra+anchor,1);p.write_text(s,encoding='utf-8')
