from pathlib import Path
B=Path(__file__).resolve().parent;R=B.parent
p=R/'dist/chapters/g_arithmetic.js';s=p.read_text(encoding='utf-8')
s=s.replace("txt(380,311,'Low nibble z goes directly to correction adder.')", "txt(35,311,'Low nibble z follows the lower wire.')")
s=s.replace("b+=symbol(240,150,'nand'", "b+='<g transform=\"translate(0 35)\">';b+=symbol(240,150,'nand'")
s=s.replace("return svg(b,420,'nand-half-subtractor');}", "return svg(b+'</g>',460,'nand-half-subtractor');}")
s=s.replace("const frames=[],s={n,a,b,c,z},invariant=", "const reasons={full:'Each computed signal preserves a+b+c=sum+2carry. Generated carry and XOR-propagated carry cannot both be one.',ripple:'Only an established carry may enter the next column. Local counts conserve binary weight; the final extra carry remains separate from signed overflow.',subtract:'Complementing B and supplying initial carry one computes A minus B modulo the word width. Final carry means no unsigned borrow.',prefix:'A higher interval consumes the carry function of its adjacent lower interval. Ordered composition preserves every possible incoming carry.',select:'Both high candidates are independent of the actual low carry. Selection chooses the complete high sum and its carry, rather than recomputing that block.',compare:'A differing high bit outweighs the combined possible differences in every lower bit. Equal high bits permit continued inspection.',bcd:'Valid digit totals range from zero through nineteen. Decimal carry q detects the threshold ten; the second binary carry alone is insufficient.',csa:'Each column counts three equal-weight bits independently. Its sum remains in that column and its carry contributes twice that column weight.',multiply:'Every partial product has weight 2^(i+j). Shifted rows are accumulated as exact integers without discarding the reserved product width.',booth:'The digit is lower bit minus current bit. Its signed weighted row contributes to the exact product, including the minimum-negative boundary.',division:'The trial 2R+x is below twice the positive divisor, so one comparison and at most one subtraction preserve the prefix identity and remainder bound.',nand:'NAND inversion and tied inputs are evaluated in the original topology. The final outputs implement difference parity and the borrow of x minus y.'};\n const frames=[],s={n,a,b,c,z},invariant=")
s=s.replace("why:'Follow the displayed weight, width and control convention; unestablished signals are not guessed.'", "why:reasons[op]")
p.write_text(s,encoding='utf-8')
print('Moved circuit routes away from explanations and added operation-specific reasoning.')
