"""Finalize one reviewed draft and record prior explicit approval truthfully."""
from pathlib import Path
import json,re,hashlib,shutil
BASE=Path(__file__).resolve().parent;ROOT=BASE.parent
def read(p):return json.loads(p.read_text())
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
g=read(BASE/'chapter-gate.json')
g.update(currentTopicId='d_counting',state='awaiting_user_approval',approvedTopicId='g_combin',approvedLibraryReview=True,sourceAuditPath='research/d_counting-source-audit.md',qualityAuditPath='research/d_counting-quality-audit.md',sourceAudit='research/d_counting-source-audit.md',qualityAudit='research/d_counting-quality-audit.md',activeWork='Delivered the sole new English counting review draft: 88 worked questions, 80 examination rules, 15 subject-specific traces and 76 checkpoints.',reviewScope='Only the new d_counting chapter; prior 31 chapter visual revision explicitly approved in version 67.',lastCompletedReview='d_counting: independent question/model checks and actual desktop/mobile/print interaction checks passed; see its quality audit.',nextReview='Wait for explicit student approval of d_counting. Do not start d_inclusion or any other chapter.',proposedNextTopicId='d_inclusion',nextTopicId='d_inclusion',nextTopicRequiresExplicitApproval=True,reviewEvidence=['research/d_counting-verification.json','research/d_counting-browser-audit.json','research/d_counting-model-audit.json'])
write(BASE/'chapter-gate.json',g)
for name in ['library-approval.json','animation-approval.json']:
    p=BASE/name;a=read(p);a.setdefault('approvalByTopic',{})['g_combin']=dict(version=67,date='2026-10-05',approval='User explicitly approved the delivered whole-library visual and mathematical revision and authorized the next sole chapter.')
    a['approvedSiteVersion']=67;a['approvedSourceSHA']='3698444e52bdb9e04cb1eb879c9c8a35e869c377';write(p,a)
# The whole-library visual review is historical, approved evidence for the prior 31.
p=BASE/'subject-visual-review.json';a=read(p);a['approvedSiteVersion']=67
for c in a['chapters']:
    c['state']='student_approved';c['htmlSha256']=hashlib.sha256((ROOT/'dist/chapters'/(c['topicId']+'.html')).read_bytes()).hexdigest()
write(p,a);write(ROOT/'dist/evidence/subject-visual-review/review.json',a)
for name in ['research/exam-calibration/manifest.json','dist/evidence/exam-calibration/manifest.json']:
    p=ROOT/name;a=read(p)
    for c in a.get('chapters',[]):c['htmlSha256']=hashlib.sha256((ROOT/'dist/chapters'/(c['topicId']+'.html')).read_bytes()).hexdigest()
    write(p,a)
p=BASE/'animation-manifest.json';a=read(p)
for c in a['chapters']:
    c['visualRevisionState']='student_approved';c['htmlSha256']=hashlib.sha256((ROOT/'dist/chapters'/(c['topicId']+'.html')).read_bytes()).hexdigest()
a['chapters']=[c for c in a['chapters'] if c['topicId']!='d_counting']
models=read(ROOT/'dist/chapters/d_counting-models.json')
a['chapters'].append(dict(topicId='d_counting',placements=15,scenarios=15,sections={m['id']:[m['id']] for m in models['models']},questionCount=88,htmlSha256=hashlib.sha256((ROOT/'dist/chapters/d_counting.html').read_bytes()).hexdigest(),visualRevisionState='awaiting_user_approval',renderer='Dedicated counting SVG traces',dataUrl='chapters/d_counting-models.json',modelAuditPath='research/d_counting-model-audit.json',browserAuditPath='research/d_counting-browser-audit.json'))
a.update(state='31_approved_chapters_and_one_counting_review_draft',uniqueScenarios=221,checkpoints=1287,placements=184,scope='206 approved legacy subject-specific models plus 15 counting-specific draft models. Separate mathematical proofs remain authoritative.',legacyConstructionAssertions=4049,countingValidationAssertions=read(BASE/'d_counting-verification.json')['checks'],checkpointsPrint='Legacy players retain printable current or initial checkpoints; the counting chapter prints all 76 checkpoints.')
write(p,a)
p=ROOT/'dist/index.html';s=p.read_text();s=s.replace('The visual and mathematical revision of all 31 existing chapters is ready for review.','The visual and mathematical revision of all 31 existing chapters is student-approved. The new counting chapter is ready for your review.').replace('Choose a subject and review the revised chapters →','Open the approved library review →');p.write_text(s)
p=ROOT/'dist/subject-visual-review.html';s=p.read_text().replace('All 31 existing chapters · review draft','All 31 existing chapters · student-approved in version 67').replace('This revision awaits your explicit approval before the next new chapter begins.','The student explicitly approved this revision in version 67. The new counting chapter has its own separate review gate.');p.write_text(s)
p=ROOT/'dist/animation-review.html';s=p.read_text().replace('30 approved chapters and 1 new review draft · 206 distinct scenarios · 1211 exact checkpoints · 169 embedded walkthroughs.','31 approved chapters and 1 counting review draft · 221 distinct scenarios · 1287 exact checkpoints · 184 embedded walkthroughs.').replace('animated teaching in 30 existing chapters','animated teaching in 31 existing chapters')
if 'COUNTING REVIEW' not in s:s=s.replace('<h2>Approval</h2>','<!-- COUNTING REVIEW --><h2>Counting chapter: separate review draft</h2><p><a href="chapters/d_counting.html#models">Open 15 dedicated counting traces and 76 checkpoints →</a>. Choice-tree branches, representation fibers, gaps, star–bar decoding, rotation orbits and lattice paths have their own displays. The counting chapter remains a draft pending explicit approval.</p><h2>Approval</h2>')
p.write_text(s)
out=ROOT/'dist/evidence/d_counting';out.mkdir(exist_ok=True)
for source,name in [('d_counting-verification.json','verification.json'),('d_counting-browser-audit.json','browser.json'),('d_counting-model-audit.json','models.json'),('d_counting-reviewed-courses.json','courses.json')]:shutil.copy2(BASE/source,out/name)
p=ROOT/'WEEKLY_DELIVERY.md';s=p.read_text();heading='## Current delivery: English discrete counting chapter, October 5, 2026'
if heading not in s:s+='\n\n'+heading+'\n\nThe student explicitly approved Site version 67: the prior 31 chapters and their visual/mathematical revision. Their 1,747 question entries remain intact except the verified correction of MSc CS 1405 Q113 option 1 from 32 to 37. The new sole d_counting chapter is now a review draft awaiting explicit approval, with four genuinely reviewed written university courses from MIT, Berkeley, Stanford and CMU, 88 solved questions (80 new plus eight authentic revisits), 80 examination rules, and 15 dedicated models with 76 checkpoints. Read research/chapter-gate.json before any further chapter work. Do not start d_inclusion or another chapter before approval. No test is requested from the student before initial reading.\n\nSources, boundaries and access limits: research/d_counting-source-audit.md and research/d_counting-reviewed-courses.json. Main lesson: research/d_counting.en.md; questions: research/d_counting-questions.json; rules: research/d_counting-review.en.md. Build only this chapter with research/build_d_counting_models.py and research/render_d_counting.py. The counting renderer is independent of the older shared scene catalog and uses dist/chapters/d_counting-models.json, d_counting.js and d_counting.css. Do not erase its inventory when running a legacy all-scene rebuild. Combined inventory records 221 models and 1,287 checkpoints, while original 206-model evidence remains historical.\n\nObserved numerical and interaction evidence: research/d_counting-verification.json, d_counting-browser-audit.json and d_counting-model-audit.json. The real browser checks all 76 checkpoint text layouts, actual 390-pixel formula containment, loaded fonts, controls, reduced motion and printable full solutions/checkpoints. Source pool comparison is bounded to eight located candidates; no worldwide exhaustive ranking or universal examination-success guarantee is asserted.\n\nPublish the exact pushed source to the existing owner-private Site and mirror only changed files to GitHub study-planner-1406, preserving unrelated mirror deletions. The gate remains awaiting_user_approval after delivery.\n'
p.write_text(s)
print('Finalized the single review draft and prior approval records.')
