from pathlib import Path
import json,hashlib,shutil
B=Path(__file__).resolve().parent;R=B.parent
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def write(p,a):p.write_text(json.dumps(a,indent=2)+'\n',encoding='utf-8')
v=read(B/'d_pigeonhole-verification.json');b=read(B/'d_pigeonhole-browser-audit.json')
assert v['state']==b['state']=='passed'
assert v['retainedQuestions']==1917 and v['retainedChapters']==33
assert b['counts']['questions']==82 and b['counts']['rules']==80 and b['counts']['models']==18
assert len(b['labReferenceChecks'])==330 and all(x['actual']==x['expected'] for x in b['labReferenceChecks'])
assert all(b['invalidCalls']) and b['parserInvalid'] and b['print']['checkpoints']==78
assert not b['errors'] and not b['mobile']['mathOverflow'] and b['mobile']['badAnchors']==0 and b['realMotion']>0 and b['motionAnimations']==0
p=B/'d_pigeonhole-quality-audit.md';s=p.read_text(encoding='utf-8');start=s.index('## Verification in progress') if '## Verification in progress' in s else s.index('## Observed verification');end=s.index('## Authentic archive boundary',start)
s=s[:start]+f'''## Observed verification

The independent mathematical verifier passed {v['checks']:,} assertions. Every numerical bank answer is checked against a separately implemented finite reference, including stock-vector enumeration, occupancy optimization by convolution, exhaustive index-subset scans, original integer predicates and explicit construction checks. All 32,768 edge colorings of the complete six-vertex graph satisfy the stated Ramsey triangle conclusion. Simple undirected graphs on two through six vertices were checked for repeated degree. General proofs remain necessary beyond those finite ranges.

All 33 preceding chapter bodies and their 1,917 question entries are preserved; only the inclusion-exclusion header records the user's explicit approval. The new chapter has 82 fully solved questions and 80 examination rules. Original PDFs for both authentic questions and three locally cached university texts have checked SHA-256 fingerprints. Six written courses were genuinely reviewed, with five selected primary courses from four universities and Cornell as a complementary text.

Actual Edge browser verification passed for 18 distinct subject models and all 78 checkpoints. Text bounds and pairwise text overlaps were measured at each checkpoint. Restart, previous/next, seek, speed, play/pause and real moving elements were exercised. All 330 laboratory cases agree with independent Python references; seven invalid numerical inputs and an empty-entry parser input are rejected. The sequence lab additionally checks its dynamic program against exhaustive subsequence enumeration. Source Sans 3, Newsreader, STIX Two Math and JetBrains Mono actually loaded; {b['counts']['math']} native mathematical instances include the printable checkpoints.

At a 390-pixel viewport the body and document were 375 pixels wide. No mathematical expression overflow or underlined link was observed. Wide diagrams provide an internal horizontal pan, which was exercised. Reduced-motion mode created zero motion animations. Print mode opened every complete solution and exposed all 78 checkpoint drawings, hid controls and restored solution states afterwards. The chapter is reachable from the real application Library, with a review-draft label. No runtime or resource errors were observed. Screenshots of the actual rendered sequence, cancellation, colored-grid and prefix diagrams were inspected.

Machine-readable evidence: [mathematical verification](../evidence/d_pigeonhole/verification.json), [browser interactions](../evidence/d_pigeonhole/browser.json), [model contracts](../evidence/d_pigeonhole/models.json), and [reviewed courses](../evidence/d_pigeonhole/courses.json).

'''+s[end:];p.write_text(s,encoding='utf-8')
p=B/'d_pigeonhole-model-audit.json';a=read(p);a.update(state='passed',verificationPath='research/d_pigeonhole-verification.json',browserAuditPath='research/d_pigeonhole-browser-audit.json',observedAssertions=v['checks'],labReferenceCases=330,limitations='Finite references supplement the general written proofs and stated input bounds.');write(p,a)
models=read(R/'dist/chapters/d_pigeonhole-models.json');p=B/'animation-manifest.json';a=read(p)
for c in a['chapters']:
 if c['topicId']!='d_pigeonhole':c['visualRevisionState']='student_approved';c['htmlSha256']=hashlib.sha256((R/'dist/chapters'/(c['topicId']+'.html')).read_bytes()).hexdigest()
a['chapters']=[c for c in a['chapters'] if c['topicId']!='d_pigeonhole']
a['chapters'].append(dict(topicId='d_pigeonhole',placements=18,scenarios=18,sections=models['groups'],questionCount=82,htmlSha256=hashlib.sha256((R/'dist/chapters/d_pigeonhole.html').read_bytes()).hexdigest(),visualRevisionState='awaiting_user_approval',renderer='Dedicated mathematical witness SVGs and four editable exact laboratories',dataUrl='chapters/d_pigeonhole-models.json',modelAuditPath='research/d_pigeonhole-model-audit.json',browserAuditPath='research/d_pigeonhole-browser-audit.json'))
a.update(state='33_approved_chapters_and_one_pigeonhole_review_draft',uniqueScenarios=252,checkpoints=1421,placements=215,scope='234 approved preceding models and 18 new pigeonhole draft models. All existing chapter bodies are preserved.',pigeonholeValidationAssertions=v['checks'],checkpointsPrint='Earlier players retain their existing print behavior; pigeonhole prints all 78 checkpoints.')
assert len(a['chapters'])==34 and sum(c['questionCount'] for c in a['chapters'])==1999;write(p,a)
p=R/'dist/index.html';s=p.read_text(encoding='utf-8').replace('All 32 earlier chapters are student-approved. The new inclusion-exclusion chapter is ready for your review.','All 33 earlier chapters are student-approved. The new pigeonhole chapter is ready for your review.');p.write_text(s,encoding='utf-8')
p=R/'dist/animation-review.html';s=p.read_text(encoding='utf-8').replace('32 approved chapters and 1 inclusion-exclusion review draft · 234 distinct scenarios · 1343 exact checkpoints · 197 embedded walkthroughs.','33 approved chapters and 1 pigeonhole review draft · 252 distinct scenarios · 1421 exact checkpoints · 215 embedded walkthroughs.').replace('animated teaching in 32 existing chapters','animated teaching in 33 existing chapters').replace('Inclusion-exclusion chapter: separate review draft','Inclusion-exclusion chapter: student-approved in version 69').replace('This chapter remains a draft pending explicit student approval.','The inclusion-exclusion chapter was explicitly approved in version 69.')
if '<!-- PIGEONHOLE REVIEW -->' not in s:s=s.replace('<h2>Approval</h2>','<!-- PIGEONHOLE REVIEW --><h2>Pigeonhole chapter: separate review draft</h2><p><a href="chapters/d_pigeonhole.html">Open 18 dedicated mathematical displays and four editable laboratories →</a>. The 78 checkpoints cover physical stock, prefix witnesses, modular images, cancellation, complement pairs, divisibility chains, geometry, ending-length dependencies, actual colored graphs and information channels. This chapter awaits explicit student approval. <a href="reviews/d_pigeonhole-quality.html">Read observed verification evidence.</a></p><h2>Approval</h2>')
p.write_text(s,encoding='utf-8')
out=R/'dist/evidence/d_pigeonhole';out.mkdir(exist_ok=True)
for source,name in [('d_pigeonhole-verification.json','verification.json'),('d_pigeonhole-browser-audit.json','browser.json'),('d_pigeonhole-model-audit.json','models.json'),('d_pigeonhole-reviewed-courses.json','courses.json')]:shutil.copy2(B/source,out/name)
p=B/'chapter-gate.json';g=read(p);g.update(currentTopicId='d_pigeonhole',state='awaiting_user_approval',approvedTopicId='d_inclusion',nextTopicId='a_arrays',proposedNextTopicId='a_arrays',nextTopicRequiresExplicitApproval=True,sourceAuditPath='research/d_pigeonhole-source-audit.md',sourceAudit='research/d_pigeonhole-source-audit.md',qualityAuditPath='research/d_pigeonhole-quality-audit.md',qualityAudit='research/d_pigeonhole-quality-audit.md',activeWork='Delivered the sole pigeonhole review draft: 82 solved tasks, 80 examination rules, 18 dedicated traces and four editable laboratories.',reviewScope='Only d_pigeonhole; the preceding 33 chapters are approved.',lastCompletedReview=f'd_pigeonhole: {v["checks"]} mathematical assertions, 330 browser lab references, all 78 model checkpoints, fonts, mobile, real motion and print passed.',nextReview='Wait for explicit student approval of d_pigeonhole. Do not start a_arrays or another chapter.',reviewEvidence=['research/d_pigeonhole-verification.json','research/d_pigeonhole-browser-audit.json','research/d_pigeonhole-model-audit.json']);write(p,g)
p=R/'WEEKLY_DELIVERY.md';s=p.read_text(encoding='utf-8');heading='## Current delivery: English pigeonhole chapter, October 5, 2026'
if heading not in s:s+='\n\n'+heading+f'''

The user explicitly approved d_inclusion in Site version 69, source c958f2b5b8eae701ab686ba77051991cc1b24278. Only d_pigeonhole was written. It is now a complete review draft awaiting explicit student approval. Five genuinely reviewed primary courses from MIT (two), Oxford, Stanford and Toronto, plus a reviewed Cornell complementary text, were selected from nine located candidates. This bounded comparison is not a claim to have evaluated every course worldwide.

The English lesson has 17 substantial sections, 80 original or independently reconstructed course problems plus two original-PDF-checked authentic adaptations, 80 examination rules, 18 subject-specific animated models, 78 checkpoints and four editable laboratories. Both source and quality audit pages are reachable. Mathematics uses native MathML and STIX Two Math; code uses JetBrains Mono, headings Newsreader and prose Source Sans 3. Existing bodies and all 1,917 questions are retained across 33 approved chapters. The combined library has 34 chapters, 1,999 question entries, 252 models, 1,421 checkpoints and 215 placements.

The independent verifier passed {v['checks']} assertions. Actual browser checks covered 330 independent laboratory reference vectors, seven rejected numerical calls and an invalid list-parser input, every model checkpoint layout, moving elements and controls, reduced motion, loaded fonts, 390-pixel containment and all printable solutions/checkpoints. Original answers are independently derived rather than official keys; MSc CS 1405 Q116 is a newly checked worst-case-search bridge and PhD CS 1404 Q25 a parity-counting revisit. Source PDF fingerprints and exact reading ranges remain in evidence.

Read research/chapter-gate.json first. Do not start the next scheduled missing chapter a_arrays until explicit approval of this draft. Do not rerun start_d_pigeonhole.py: it records preceding approval once. Rebuild only this chapter with build_d_pigeonhole_models.py, prepare_d_pigeonhole.py and render_d_pigeonhole.py; preserve the dedicated models rather than using the legacy shared builder. Authoritative handoff files are d_pigeonhole.en.md, d_pigeonhole-questions.json, d_pigeonhole-review.en.md, source and quality audits, verification.json, browser-audit.json and model-audit.json. Publication uses the exact pushed source on the existing owner-private Site. Mirror only changed files to the GitHub study-planner-1406 branch, preserving unrelated deletions. Keep awaiting_user_approval after delivery.
'''
p.write_text(s,encoding='utf-8');print('Finalized one review draft; next chapter remains gated.')
