from pathlib import Path
import json
B=Path(__file__).parent;R=B.parent
p=B/'a_sort-quality-audit.md';s=p.read_text(encoding='utf-8').replace('887 stored checkpoints','1,186 stored checkpoints').replace('927 displayed recorded states','1,242 displayed recorded states').replace('across the 927 recorded states','across the 1,242 displayed recorded states')
s+='''

## Decision-led animation revision — 2026-10-06

The user requested more accurate and understandable animations. All 45 recorded sorting models were rebuilt with separate comparison and movement phases where appropriate. There are 402 explicitly presented comparison steps, each with a native MathML predicate, truth value and an explanation of its consequences. Algorithm guides mark the current operation; partition intervals have named roles and their declared inequalities were checked against every corresponding recorded key. Array indices stay at fixed slots, while original record identities move. Heap edges and slot positions remain fixed while labels move during exchanges. Construction and repair are distinguished from a claim that the whole prefix already has heap order.

Stable merge, counting scatter and digit distribution have boundary-connected transfer paths. A moving marker follows the actual authored connector while the destination record is revealed on arrival, avoiding a large record tile crossing unrelated rows. Radix buckets use a five-column grid and explicitly show FIFO order from top to bottom. Inversion diagrams show witness counts, rather than uncollected sorting-operation counters. The ten editable laboratories also separate key decisions and expose their predicates; their independently computed results still match all 54 fixtures.

The additional teaching audit passed 2,736 checks. It verifies that recorded comparison steps do not move records and advance the comparison count by exactly one, that the declared partition-region predicates hold, and that all 88 question stems and complete answers remain unchanged. Browser QA sweeps 1,242 displayed recorded states, checks 228 transfer endpoints against their actual source/destination rectangle boundaries, and checks that connectors do not cross text. Motion, copy markers, controls, reduced motion, print and mobile behavior passed. This is an improvement to the current sorting chapter; the preceding 36 chapter bodies were preserved.
''';p.write_text(s,encoding='utf-8')
p=B/'chapter-gate.json';g=json.loads(p.read_text());g['delivery']['checkpoints']=1186;g['reviewEvidence'].append('research/a_sort-teaching-audit.json') if 'research/a_sort-teaching-audit.json' not in g['reviewEvidence'] else None;g.update(activeWork='Decision-led visual revision of a_sort only. Await explicit approval; no next chapter started.',publicationState='pending_visual_revision');p.write_text(json.dumps(g,indent=2)+'\n')
p=R/'WEEKLY_DELIVERY.md';s=p.read_text(encoding='utf-8');s+='\n## Sorting visual revision — 2026-10-06\n\nAll 45 a_sort models now expose decisions, reasons and named regions. Array slots remain fixed; heap labels move on a fixed tree; copy markers follow authored transfer paths. 1,186 stored checkpoints, 402 explicit comparison steps and all 88 original problem bodies retained. Teaching and browser audits are adjacent. The chapter stays awaiting_user_approval, and no following chapter begins.\n';p.write_text(s,encoding='utf-8')
p=B/'ANIMATION_STANDARD.md';s=p.read_text(encoding='utf-8');s+='\n## Decision-led sorting standard (6 October 2026)\n\nSeparate decision checkpoints from record movement. Show the actual predicate, result, reason and algorithm operation. Keep positional indices fixed while record identities move. Name all region intervals and validate their predicates against saved data; an empty interval is valid. Distinguish reference/source views from output storage. Transfer markers follow boundary-connected, label-free routes. Do not animate heap position circles away from fixed tree edges. Allow enough playback time for each transition, honor pause and reduced motion, and provide printable checkpoints. Validate content retention, algorithm counts, visual geometry and the editable laboratory independently. Apply this teaching clarity in future relevant chapters with concept-specific layouts.\n';p.write_text(s,encoding='utf-8')
