from pathlib import Path
import json,shutil,re
B=Path(__file__).resolve().parent;R=B.parent
data=json.loads((R/'dist/chapters/a_select-models.json').read_text());models=len(data['models']);frames=sum(len(m['frames']) for m in data['models'])
p=B/'a_select-quality-audit.md';s=p.read_text(encoding='utf-8').replace('32 stored models and 352 checkpoints',f'{models} stored models and {frames} checkpoints')
s+='\n## Browser and literal-code result\n\nThe literal Python lesson code passed 6,015 order-statistic queries and 1,524 weighted-median cases including zero weights, plus an arbitrary-size integer-weight check. Finite rounding conditions were checked for 9,993 randomized-proof sizes and 9,860 deterministic-induction sizes. Pairwise extrema passed 1,092 independent cases.\n\nEdge browser review measured every one of the 33 stored models and 363 checkpoints. There were zero text-overlap, padding or SVG-bound issues, and 282 directed-edge endpoints met actual node boundaries. Native fractions, sums and indices rendered with STIX Two Math; prose, headings and code used their separate approved fonts. There were no blank mathematical expressions, underlined links, mobile document overflow or runtime errors. All eight editable modes passed independently specified examples; invalid input preserved the previous valid model.\n\nThe pause audit exposed a native Web Animations pending-pause frame drift. The shared raw player now explicitly holds its current animation time when pausing; the actual moving-record check froze and resumed correctly. This is a control fix; prior chapter HTML and model data were not rewritten. Step/back/restart/seek, reduced motion and printable checkpoints passed. The saved screenshots were visually inspected, including the completed group certificate, attached tournament tree, single-line equations and mobile boundary model.\n'
p.write_text(s,encoding='utf-8')
reading=[];scopes={'mit':'PDF pp. 4–5; page 5 rendered and visually checked','stanford':'PDF pp. 1–9','stanford-checks':'PDF p. 1; rendered and visually checked','cmu':'PDF pp. 1–14; page 8 separately read after output truncation','cmu-two':'PDF p. 1, problem 1; other problems screened','princeton':'PDF pp. 28–31 and 34–39','princeton-search':'§4.2 searching exposition, Q&A and relevant searching exercises','berkeley':'§2.4, printed pp. 64–66 / PDF pp. 10–12'}
for source in json.loads((B/'a_select-evidence/acquisition.json').read_text()):
 reading.append({**source,'reviewStatus':'reviewed_in_stated_scope' if source['id'] in scopes else 'not_selected_or_unavailable','readingScope':scopes.get(source['id'],'Screening/access only; no substantive full-reading claim'),'date':'2026-10-06'})
(B/'a_select-evidence/reading.json').write_text(json.dumps(reading,indent=2)+'\n',encoding='utf-8')
out=B/'a_select-evidence/screenshots';out.mkdir(exist_ok=True)
for name in ['title','groups','tournament','math-proof','two-arrays','mobile-binary','print-partition']:
 source=Path('C:/Users/bheydari/AppData/Local/Temp/a-select-visual-qa')/(name+'.png')
 if source.exists():shutil.copy2(source,out/source.name)
p=B/'chapter-gate.json';g=json.loads(p.read_text());assert g['currentTopicId']=='a_select'
g.update(state='awaiting_user_approval',activeWork='Only a_select completed as a review draft. Await explicit user approval; no next chapter is started.',lastCompletedReview=f'Searching, Selection, and Order Statistics: 89 complete worked problems, 80 rules, five reviewed university courses, {models} models, {frames} checkpoints, eight editable modes.',sourceAudit='research/a_select-source-audit.md',qualityAudit='research/a_select-quality-audit.md',reviewEvidence=['research/a_select-evidence/reading.json','research/a_select-evidence/mathematics.json','research/a_select-evidence/lesson-and-retention.json','research/a_select-evidence/browser.json'],publicationState='pending',publicationRecordPath='research/a_select-publication.json',delivery=dict(date='2026-10-06',topicId='a_select',status='complete_review_draft',url='chapters/a_select.html',questions=89,authenticQuestions=3,originalQuestions=86,examRules=80,visualModels=models,checkpoints=frames,editableLaboratories=8,retainedChapters=37,retainedQuestions=2257))
p.write_text(json.dumps(g,indent=2)+'\n',encoding='utf-8')
p=R/'WEEKLY_DELIVERY.md';s=p.read_text(encoding='utf-8');s+=f'\n## Searching and selection review draft — 2026-10-06\n\nOnly `a_select` is delivered: five genuinely reviewed university courses with bounded reading scopes, 89 complete solved problems, 80 examination rules, {models} concept-specific models / {frames} checkpoints and eight editable modes. Mathematical, literal-code, browser geometry, arrow-port, control, font, mobile and retention checks passed. All 37 preceding chapter HTML files and 2257 complete problem bodies are unchanged. A shared raw-animation control fix holds time exactly while pausing. The gate awaits explicit user approval; no next chapter has started. Source/GitHub push and private publication are recorded separately after verification.\n';p.write_text(s,encoding='utf-8')
(B/'a_select-publication.json').write_text(json.dumps(dict(topicId='a_select',state='pending',date='2026-10-06',sourceCommit=None,siteVersionId=None,deploymentId=None),indent=2)+'\n',encoding='utf-8')
print('Finalized one chapter review draft; no next chapter started.')
