"""Record finite evidence and expose an accurate student-facing visual review."""
from pathlib import Path
import json,hashlib,shutil,html,subprocess,re,collections
R=Path(__file__).resolve().parents[1];O=R/'research/library-visual-question-review';D=R/'dist'
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
write=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8')
animation=read(O/'animation-browser.json');moving=read(O/'moving-browser.json');problem=read(O/'problem-browser.json');pages=read(O/'page-browser.json');retention=read(O/'retention.json')
assert all(v['state']=='passed' for v in [animation,moving,problem,pages,retention])
assert len(pages['chapters'])==35 and retention['problems']==2085
models=read(O/'problem-models.json');decisions=read(O/'concept-review.json');inputs=read(O/'input.json');base='9fc830e7e98de7a6894672d623b15a88b8405122'
# No saved mathematical model state is changed by geometry repair.
unchanged=[]
for file in ['concept-animations.json','a_arrays-models.json','d_counting-models.json','d_inclusion-models.json','d_pigeonhole-models.json']:
 original=json.loads(subprocess.check_output(['git','show',base+':dist/chapters/'+file],cwd=R))
 assert read(D/'chapters'/file)==original,file
 unchanged.append(file)
for row in decisions['chapters']:
 for q in row['questions']:
  q['reviewState']='visual-placement-and-rendering-reviewed' if q['exactModel'] or q['conceptModels'] else 'existing-visual-or-written-derivation-retained'
  if q['exactModel']:q['decision']='Explicitly scoped arrays teaching illustration' if models[q['id']]['kind']=='supporting-array-concept' else 'Question-linked diagram, process or formula inspection; scope disclosed in the aid'
write(O/'concept-review.json',decisions)
summary=dict(state='awaiting_user_approval',chapters=35,problems=2085,existingAnimationModels=len(animation['scenes']),savedAnimationFrames=sum(r['frames'] for r in animation['scenes']),movingSamples=moving['samples'],questionLinkedAids=sum(m['kind']!='supporting-array-concept' for m in models.values()),arraysTeachingAids=sum(m['kind']=='supporting-array-concept' for m in models.values()),supportingConceptPlacements=sum(bool(q['conceptModels']) for r in decisions['chapters'] for q in r['questions']),supportingConceptModels=len(decisions['counts']),problemVisualFrames=sum(len(m['frames']) for m in models.values()),unchangedSavedModelFiles=unchanged,baselineCommit=base,evidenceFiles=['animation-browser.json','moving-browser.json','problem-browser.json','page-browser.json','retention.json','concept-review.json'],limitations='Visual-instruction revision. Source lessons and original complete problem bodies are retained; this is not a fresh proof audit of every mathematical assertion or a claim about every unsampled transient or editable input.')
write(O/'manifest.json',summary)
e=D/'evidence/library-visual-question-review';e.mkdir(parents=True,exist_ok=True)
for file in [*summary['evidenceFiles'],'manifest.json']:shutil.copy2(O/file,e/file)
table=[]
for row,original in zip(decisions['chapters'],inputs):
 topic=row['topicId'];p=D/'chapters'/f'{topic}.html';content=p.read_text(encoding='utf-8');title=html.unescape(re.sub('<[^>]*>','',re.search(r'<h1[^>]*>([\s\S]*?)</h1>',content)[1]))
 exact=sum(bool(q['exactModel']) and models[q['id']]['kind']!='supporting-array-concept' for q in row['questions']);teaching=sum(bool(q['conceptModels']) or bool(q['exactModel']) and models[q['id']]['kind']=='supporting-array-concept' for q in row['questions'])
 table.append(f'<tr><td><a href="chapters/{topic}.html">{html.escape(title)}</a></td><td>{original["questionCount"]}</td><td>{exact}</td><td>{teaching}</td></tr>')
 # A clear route to the latest report from every existing lesson.
 notice='<aside class="visual-reading-guide" data-library-visual-review><h2>Worked-solution visual instruction</h2><p>Open a problem’s complete solution to inspect its diagram or model. Question-linked data, derived witnesses and separate teaching examples are explicitly labeled. <a href="../library-visual-question-review.html">Read the current library-wide visual review →</a></p></aside>'
 if 'data-library-visual-review' not in content:content=content.replace('<article class="lesson">','<article class="lesson">'+notice,1)
 p.write_text(content,encoding='utf-8')
page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Library animation and worked-solution visual review</title><link rel="stylesheet" href="chapters/chapter.en.css"><link rel="stylesheet" href="chapters/exam-calibration.css"></head><body><main class="chapter"><p class="top-link"><a href="index.html#library">← Chapter library</a></p><header class="hero"><p class="eyebrow">5 October 2026 · visual revision awaiting your approval</p><h1>Library animation and worked-solution visual review</h1></header><article class="lesson">
<h2>How to use the revised problems</h2><p>Read the problem and its complete written solution. Where a visual process helps, the solution now contains an inspectable diagram or model. Use Previous step and Next step to follow one operation at a time. Play runs the stored steps; Restart restores the first step. The caption explains the currently displayed operation. All models start paused.</p><p>A question-linked aid uses its stated values, displayed mathematical objects or a clearly labeled derived witness. A supporting concept model uses a separate teaching example and states that its numerical values are not this problem’s answer. Symbolic arguments retain their complete written proofs when an additional model would not clarify them. Existing examination schematics and source links remain available.</p>
<h2>What changed</h2><ul><li>All 35 chapters use the shared boundary and padding review. Arrowheads are smaller, connections follow actual node boundaries, labels use measured glyph dimensions, and colliding annotations are separated.</li><li>Merge records and transposed entries use separate travel lanes where a straight path obscured other labels. Saved mathematical checkpoints are unchanged.</li><li>{summary['questionLinkedAids']} question-linked aids show exact row operations, Karnaugh covers, multiplexer inputs, gate-level equivalence miters, actual AND-tree arrival bounds, ripple carries, program object updates, array movements, probability masses and other relevant constructions.</li><li>{summary['arraysTeachingAids']} arrays/list teaching aids and {summary['supportingConceptPlacements']} supporting concept placements explain applicable methods with explicitly separate examples. These placements reuse {summary['supportingConceptModels']} different subject-specific concept models; they are not that many distinct new models.</li><li>The 2085 original problem statements, options, complete solution bodies and source labels remain intact. The revision adds visual teaching and operation-specific captions without replacing complete reasoning with a picture.</li></ul>
<h2>Open representative examples</h2><ul><li><a href="chapters/g_combin.html">Combinational circuits</a>: questions 37–48 show gate-level miters; questions 49–58 show the three actual arrival-sensitive AND trees; questions 59–68 show fixed-width ripple addition.</li><li><a href="chapters/g_kmap.html">Karnaugh maps</a>: question-linked ON/DC specifications and selected optimal covers.</li><li><a href="chapters/l_gauss.html">Gaussian elimination</a>: exact rational row operations with a visible coefficient/right-hand-side boundary.</li><li><a href="chapters/p_functions.html">Functions and parameter passing</a>: independent objects, aliases, persistent storage and helper composition.</li><li><a href="chapters/p_arrays.html">Array programming</a>: overlapping reads/writes, shifts, prefix sums and in-place dependencies.</li></ul>
<h2>Chapter-by-chapter coverage</h2><p>Question-linked aids include mathematical-object and derivation inspection. Supporting teaching models are counted separately. A zero in either column does not mean a chapter lacks its existing lesson figures or laboratories.</p><div class="table-scroll"><table><thead><tr><th>Chapter</th><th>Problems</th><th>Question-linked aids</th><th>Supporting examples</th></tr></thead><tbody>{''.join(table)}</tbody></table></div>
<h2>What was verified</h2><p>The actual browser rendered {summary['existingAnimationModels']} existing animation models at {summary['savedAnimationFrames']} saved checkpoints and checked {summary['movingSamples']} intermediate movement samples. The problem aids passed geometry checks at {summary['problemVisualFrames']} stored visual steps. Tests measured label bounds, text collisions, rectangular padding and annotated connector endpoints. All 35 chapter pages loaded their problem models, retained their problem counts, stayed within a 390-pixel mobile page width and exposed written solutions in print mode. Mathematical glyphs use STIX Two Math; algorithms retain JetBrains Mono.</p><p>Independent exact arithmetic checks cover the implemented row reductions, carry results, mux cofactors, miter truth values and replayed program contracts. Visual spot checks include the miter schematic, Karnaugh map, Gaussian matrix and aliasing diagram. These are finite checks. They do not certify every unsampled transient, every editable laboratory input or every mathematical assertion in the original library. This delivery reviews visual instruction; it does not claim a new exhaustive proof audit or guaranteed performance on future examinations.</p>
<h2>Evidence and approval</h2><p><a href="evidence/library-visual-question-review/manifest.json">Revision inventory</a> · <a href="evidence/library-visual-question-review/animation-browser.json">Saved animation geometry</a> · <a href="evidence/library-visual-question-review/moving-browser.json">Movement samples</a> · <a href="evidence/library-visual-question-review/problem-browser.json">Problem visual geometry</a> · <a href="evidence/library-visual-question-review/page-browser.json">Desktop, mobile and print pages</a> · <a href="evidence/library-visual-question-review/retention.json">Original problem retention</a></p><p>This library visual revision is ready for your approval. The next chapter remains paused at the approval gate.</p></article></main></body></html>'''
(D/'library-visual-question-review.html').write_text(page,encoding='utf-8')
p=D/'library-review.html';s=p.read_text(encoding='utf-8');notice='<aside class="visual-reading-guide"><h2>Current visual revision</h2><p><a href="library-visual-question-review.html">Open the current 35-chapter animation and worked-solution visual review →</a></p></aside>'
if 'library-visual-question-review.html' not in s:s=s.replace('<main class="chapter">','<main class="chapter">'+notice,1)
p.write_text(s,encoding='utf-8')
p=R/'research/chapter-gate.json';g=read(p);g.update(state='awaiting_user_approval',approvedTopicId='a_arrays',activeWork='35-chapter animation and worked-solution visual revision delivered for approval; no new chapter.',lastCompletedReview='Library geometry and problem visual instruction: 35 chapters; finite evidence in research/library-visual-question-review/manifest.json.',nextReview='Await explicit approval of this whole-library visual revision.',reviewEvidence=['research/library-visual-question-review/'+f for f in summary['evidenceFiles']]);write(p,g)
p=R/'research/animation-manifest.json';a=read(p);a['state']='35_existing_chapters_with_library_visual_revision_awaiting_approval'
for c in a['chapters']:c.update(htmlSha256=hashlib.sha256((D/'chapters'/f'{c["topicId"]}.html').read_bytes()).hexdigest(),visualRevisionState='awaiting_user_approval',libraryVisualReview='research/library-visual-question-review/manifest.json')
write(p,a)
p=R/'WEEKLY_DELIVERY.md';s=p.read_text(encoding='utf-8');marker='## Whole-library visual instruction: delivered for approval'
if marker not in s:s+='\n\n'+marker+'\n\n5 October 2026: All 35 chapter animation placements use measured boundary/padding geometry. All 2085 original worked-problem bodies are retained; visual teaching and inspected transitions were added where relevant. The record distinguishes '+str(summary['questionLinkedAids'])+' question-linked aids, '+str(summary['arraysTeachingAids'])+' separate arrays examples, and '+str(summary['supportingConceptPlacements'])+' supporting concept placements. Finite saved-state, intermediate-movement, question-model, desktop/mobile/print and retention checks passed. This is a visual-instruction review, not a new exhaustive proof audit. Evidence: research/library-visual-question-review/manifest.json. Report: dist/library-visual-question-review.html. Gate: awaiting_user_approval; no new chapter begun. Publication is verified separately.\n'
p.write_text(s,encoding='utf-8')
print(json.dumps(summary))
