from pathlib import Path
import json,subprocess,tarfile,hashlib,sys
R=Path(__file__).resolve().parents[1];B=R/'research';E=B/'p_strings-evidence'
def git(*args):return subprocess.check_output(['git',*args],cwd=R,text=True,encoding='utf-8').strip()
mode=sys.argv[1]
if mode=='prepare':
 browser=json.loads((E/'browser.json').read_text());math=json.loads((E/'mathematics.json').read_text());assert browser['status']==math['status']=='passed'
 data=json.loads((R/'dist/chapters/p_strings-models.json').read_text());(E/'models.json').write_text(json.dumps(dict(models=len(data['models']),checkpoints=sum(len(m['frames'])for m in data['models']),ids=[m['id']for m in data['models']],scope='Explicit ASCII byte algorithms, validated bounds, original-source overlap movement, matching, filtering and span parsing. Not an arbitrary C interpreter.'),indent=2)+'\n',encoding='utf-8')
 audit=B/'p_strings-quality-audit.md';s=audit.read_text(encoding='utf-8').replace('Status: verification in progress.','Status: local verification passed; publication tracked separately.').replace('will be recorded','are recorded').replace('will validate','validate').replace('Browser validation and final counts will be appended after those gates pass.','Browser validation passed for all 30 models and 179 stored checkpoints.');s+='\n\n## Completed verification\n\n18,945 checks passed, including 12,179 independent byte-operation runs over exhaustive short inputs and same-object movements, exact counting identities, 321 static mathematical instances, complete delimiters and prior-page retention. Browser inspection covered 49 mounted players (lesson and solution instances), all 179 distinct stored checkpoints, actual geometry pause/resume, seeking, restart, reduced motion, seven editable operation cases, six rejected inputs preserving the valid result, print checkpoints, mobile containment and library/week navigation. No runtime errors, text collisions, inadequate box padding or missing mathematical fences were found. All 45 previous HTML pages remain byte-for-byte unchanged and all 2920 previous question entries remain. The library now has 46 chapter cards and 3001 problem entries, including explicitly labelled bridge revisits rather than a unique-question count.\n';audit.write_text(s,encoding='utf-8')
 g=json.loads((B/'chapter-gate.json').read_text());assert g['currentTopicId']=='p_strings';g.update(state='awaiting_user_approval',lastCompletedReview='Strings and terminators in C17: 28 sections, 81 worked problems, 80 final rules, four core written university courses plus Stanford, 30 byte-memory models / 179 checkpoints, 18945 checks including 12179 independently compared operation runs.',sourceAudit='research/p_strings-source-audit.md',qualityAudit='research/p_strings-quality-audit.md',reviewEvidence=['research/p_strings-evidence/'+n+'.json'for n in ['reading','mathematics','models','browser','lesson-and-retention']],nextReview='Await explicit user approval of p_strings before writing any following chapter.',activeWork='p_strings complete as a review draft; publication being attempted. No following chapter started.',publicationState='pending',publishedVersion=None)
 (B/'chapter-gate.json').write_text(json.dumps(g,indent=2)+'\n',encoding='utf-8')
 with(R/'WEEKLY_DELIVERY.md').open('a',encoding='utf-8')as f:f.write('\n\n## Strings and terminators complete review draft — 8 October 2026\n\n28 sections, 80 original/reconstructed full solutions plus one original-PDF-rechecked MSc string-counting bridge, 80 examination rules and 30 specialized memory models with 179 checkpoints. Four core written courses are genuinely read; Stanford is supplementary and inaccessible CMU material is not counted as read. 18945 checks include 12179 independent byte-operation comparisons. Browser, motion, typography, mathematics, mobile, print and lab validation passed. Preserve 45 previous HTML pages and 2920 prior problem entries. Await explicit approval of p_strings; publication tracked separately.\n')
elif mode=='commit':
 stage=[]
 for row in subprocess.check_output(['git','status','--porcelain'],cwd=R,text=True,encoding='utf-8').splitlines():
  p=row[3:];assert p in ['WEEKLY_DELIVERY.md','dist/lessons.json','research/chapter-gate.json']or'p_strings'in p,('Unexpected change; preserve without staging',p);stage.append(p)
 subprocess.run(['git','add','--',*stage],cwd=R,check=True);subprocess.run(['git','diff','--cached','--check'],cwd=R,check=True);subprocess.run(['git','commit','-m','Add rigorous C17 strings chapter with worked problems and byte-memory laboratories'],cwd=R,check=True);print(git('rev-parse','HEAD'))
elif mode=='package':
 assert not git('status','--porcelain'),'Package committed clean content only';sha=git('rev-parse','HEAD');dest=Path('C:/Users/bheydari/AppData/Local/Temp/p-strings-deploy.tar.gz');files=[R/'.openai/hosting.json']+sorted(p for p in(R/'dist').rglob('*')if p.is_file())
 for p in files:assert p.resolve().is_relative_to(R.resolve())and not p.is_symlink()
 with tarfile.open(dest,'w:gz')as tf:
  for p in files:tf.add(p,arcname=p.relative_to(R).as_posix(),recursive=False)
 with tarfile.open(dest,'r:gz')as tf:
  members=tf.getmembers();assert len(members)==len(files)
  for m,p in zip(members,files):assert m.name==p.relative_to(R).as_posix()and tf.extractfile(m).read()==p.read_bytes()
 print(json.dumps(dict(project_id='appgprj_6ab5666f72b081918286c6b371c1eb1b',commit_sha=sha,archive=str(dest),files=len(files),archiveSha256=hashlib.sha256(dest.read_bytes()).hexdigest())))
