from pathlib import Path
import json
B=Path(__file__).resolve().parent
s=(B/'render_p_strings.py').read_text(encoding='utf-8').replace('p_strings','p_recursion').replace('st-','rc-').replace('Strings and Terminators: Representation, Contracts, and Algorithms in C17','Recursion: Contracts, Frames, Costs, and Backtracking').replace('byte-memory','recursive execution').replace('Strings and terminators','Recursion').replace('abstract-string counting bridge','recursive reverse-stride copying bridge')
start=s.index("lab='");end=s.index('\nsource=',start)
lab='''lab="""<section class="lab"><form id="rc-form"><label>Recursive algorithm<select name="operation">"""+''.join('<option value="'+x+'">'+x.capitalize()+'</option>'for x in ['factorial','around','fib','memo','gcd','digits','power','palindrome','binary','hanoi','subsets','stride','koch'])+"""</select></label><label>Size / disk count / order<input name="n" type="number" value="3" min="0" max="8"></label><label>First GCD input / power base<input name="a" type="number" value="2"></label><label>Second GCD input<input name="b" type="number" value="462"></label><label>Exponent<input name="exponent" type="number" value="13"></label><label>Digit input<input name="value" type="number" value="738"></label><label>ASCII palindrome content<input name="text" value="abccba"></label><label>Search target in [1,3,5,7,9,11,13]<input name="target" type="number" value="8"></label><button type="submit">Build the checked recursive execution</button></form><p id="rc-error" role="alert"></p><p>Only the selected algorithm's parameters apply. Sizes are zero through eight; Fibonacci trees use at most five, Hanoi and subsets at most four, and Koch order at most three. Digit input is zero through 99,999,999; GCD inputs are at most 10,000; power base is zero through three and exponent at most thirteen. Byte palindrome content has at most eight printable ASCII characters. All results start paused. Invalid inputs preserve the previous valid model. Calls include root and terminal invocations; counted operations are algorithm-specific arithmetic, comparisons, copied elements or legal moves. Koch checkpoints summarize completed construction orders rather than individual call frames.</p><div id="rc-output"></div></section>"""'''
s=s[:start]+lab+s[end:];s=s.replace('<!-- LAB: strings -->','<!-- LAB: recursion -->')
a=s.index('anchors=[');b=s.index(';it=iter(anchors)',a);s=s[:a]+"anchors=['sources','contracts','termination','proof','factorial','frames','output','state','linear','digits','intervals','binary','power','trees','fibonacci','memo','resources','tail','explicit-stack','structural','hanoi','subsets','backtracking','geometry','debugging','summary','problems','review','laboratory','references']"+s[b:]
s=s.replace(" return '<section class=\"exam-question\"", " visual=('<p class=\"visual-scope\">'+e(q['visualQualification'])+'</p>'+visual) if q.get('visualQualification') else visual\n return '<section class=\"exam-question\"")
(B/'render_p_recursion.py').write_text(s,encoding='utf-8')
p=B/'p_recursion-questions.json';qs=json.loads(p.read_text());[qs[i].pop('modelId',None)for i in[8,53]]
qs[22]['visualQualification']='The animation specializes the formula to six matching content bytes abccba; the proof covers general length.'
qs[72]['visualQualification']='The animation shows completed Koch replacement orders zero through three, rather than individual invocation frames.'
p.write_text(json.dumps(qs,indent=2)+'\n',encoding='utf-8')
