from pathlib import Path
B=Path(__file__).resolve().parent
s=(B/'render_i_uninformed.py').read_text(encoding='utf-8').replace('i_uninformed','p_strings').replace('us-','st-')
s=s.replace('import mathml','import mathml\nmathml.SYMBOLS.update(Sigma=chr(931),varepsilon=chr(949))',1)
s=s.replace('Authentic examination: iterative deepening','Authentic examination: abstract-string counting bridge')
s=s.replace("lab='<section", "lab='<section",1)
start=s.index("lab='<section");end=s.index('\nsource=',start)
lab='''<section class="lab"><form id="st-form"><label>Operation<select name="operation"><option value="copy">Whole-string copy</option><option value="ncpy">Bounded padded copy</option><option value="append" selected>Append selected content</option><option value="compare">Bounded unsigned comparison</option><option value="match">Find all overlapping matches</option><option value="scan">Scan source extent</option><option value="move">Move bytes inside destination</option><option value="insert">Insert first source byte</option><option value="delete">Delete content interval</option><option value="reverse">Reverse destination content</option><option value="compact">Remove first source byte</option><option value="tokens">Split on first source byte</option></select></label><label>Source / pattern / selected byte<input name="source" value="XY"></label><label>Initial destination / text<input name="destination" value="orbit"></label><label>Destination capacity<input name="capacity" type="number" min="1" max="16" value="10"></label><label>Copy, append or comparison limit<input name="limit" type="number" min="0" max="16" value="16"></label><label>Insertion or deletion position<input name="position" type="number" min="0" max="15" value="2"></label><label>Deleted content count<input name="remove" type="number" min="0" max="15" value="1"></label><label>Move source offset<input name="from" type="number" min="0" max="15" value="0"></label><label>Move destination offset<input name="to" type="number" min="0" max="15" value="1"></label><label>Move byte count<input name="count" type="number" min="0" max="16" value="3"></label><button type="submit">Build and inspect the byte trace</button></form><p id="st-error" role="alert"></p><p>Use at most fifteen entered printable ASCII bytes; \\0 inserts an embedded zero. A final source zero is added automatically. Destination capacity is between one and sixteen bytes. Only the selected operation's parameters apply. All traces start paused. Invalid inputs preserve the preceding valid result. Scan examines the displayed source extent; capacity controls the destination object. The laboratory's zero-filled unused destination cells are initialized model data, never a claim that automatic C arrays initialize themselves.</p><div id="st-output"></div></section>'''
s=s[:start]+'lab='+repr(lab)+s[end:]
s=s.replace('<!-- LAB: search -->','<!-- LAB: strings -->')
start=s.index(";anchors=");end=s.index(';it=iter(anchors)',start)
s=s[:start]+";anchors=['sources','representation','nulls','initialization','extent','scan','copy','bounded-copy','append','ownership','overlap','compare','spans','match','reverse','compact','tokens','input','formatting','unicode','tables','buffers','counting','summary','problems','review','laboratory','references']"+s[end:]
s=s.replace('Uninformed Search: BFS, DFS, Uniform Cost, and Iterative Deepening','Strings and Terminators: Representation, Contracts, and Algorithms in C17').replace('Artificial Intelligence · Week 3','Programming · Week 3').replace('Uninformed search chapter audit','Strings and terminators chapter audit').replace('Uninformed search chapter','Strings and terminators chapter').replace('exact-state models','byte-memory models')
(B/'render_p_strings.py').write_text(s,encoding='utf-8')
