from pathlib import Path
import json,hashlib
B=Path(__file__).resolve().parent;E=B/'i_uninformed-evidence';E.mkdir(exist_ok=True)
s='\n'.join((B/f).read_text(encoding='utf-8') for f in ['i_uninformed-problems.en.txt','i_uninformed-more-problems.en.txt']);qs=[];rules=[]
for block in s.split('@@ ')[1:]:
 header,body=block.split('\n',1);a=header.split('|');stem,tail=body.split('---SOLUTION---');sol,rule=tail.split('---RULE---');n=int(a[0]);q=dict(id='i-uninformed-original-'+str(n),title=a[1],origin=a[2],stem=stem.strip(),solution=sol.strip())
 if len(a)>3:q['modelId']=a[3].strip()
 qs.append(q);rules.append(str(n)+'. **'+a[1]+'.** '+rule.strip())
assert len(qs)==80
qs[40]['modelId']='finite-cycle-failure';qs[50]['modelId']='costly-dls'
(B/'i_uninformed-questions.json').write_text(json.dumps(qs,indent=2)+'\n',encoding='utf-8');(B/'i_uninformed-review.en.md').write_text('\n\n'.join(rules)+'\n',encoding='utf-8')
rp='Exams/MS/CE/1404/Daftarche-Soalat-Konkur-Arshad-Computer-1404 (konkurcomputer.ir).pdf';root=Path('C:/Users/bheydari/AppData/Local/Temp/exam-calibration-1406/source')
auth=[dict(id='MS_CE_1404_Q68',title='Iterative deepening versus breadth-first and depth-first search',booklet='MSc CE 1404',questionNumber=68,pdfPage=16,stem='Which statement about iterative deepening search (IDS) is correct in the standard tree-search comparison?',options=['The time complexity order of IDS is greater than that of BFS because IDS repeats its iterations.','The time complexity order of IDS is greater than that of DFS because IDS repeats its iterations.','The memory complexity order of IDS is like BFS, but unlike BFS, IDS is complete.','The memory complexity order of IDS is like DFS, but unlike DFS, IDS is complete.'],answer=4,modelId='ids-main',solution='Option 4 is the intended answer under the classical tree-search assumptions: finite branching, a goal at finite depth, and ordinary DFS without a mechanism that forces it to leave an infinite branch. IDS exhausts each finite depth limit and eventually reaches the shallowest goal depth. Its live depth-first frontier is linear in the depth bound for fixed branching factor, like DFS, whereas BFS stores an exponential-width frontier. Option 1 confuses repeated work with a larger asymptotic order: for fixed branching factor greater than one, exhaustive IDS and BFS both take exponential time in the shallowest goal depth, with a constant limiting overhead ratio. Option 2 is not a general comparison because DFS depends on its maximum reached depth and branch order. Option 3 also incorrectly suggests that standard BFS is incomplete. The qualification matters: DFS with global discovery on a finite graph is complete too; this examination item is not claiming the contrary.',repoPath=rp,sourceCommit='bdadf6e2c9cadc4772ae137a96a3da753c7cfd08',sourceSha256=hashlib.sha256((root/rp).read_bytes()).hexdigest(),answerStatus='independently_derived_not_official',verification='Original PDF page 16 visually inspected at enlarged resolution; Q68 options retained in printed order.')]
(B/'i_uninformed-authentic.json').write_text(json.dumps(auth,indent=2)+'\n',encoding='utf-8')
records=[dict(university='UC Berkeley',course='CS188 staff textbook',material='Section 1.3: Uninformed Search',read='Complete section text',role='core'),dict(university='Carnegie Mellon',course='15-281 Spring 2023, Stephanie Rosenthal',material='Course-linked Search Notes, uninformed-search sections; Lecture 2 activity solutions',read='Relevant node, algorithm and property sections; complete three-page activity text',role='core'),dict(university='MIT',course='6.034 Spring 2005, Leslie Kaelbling and Tomas Lozano-Perez',material='Chapter 2: Search, first part',read='All 21 PDF pages as extracted text',role='core'),dict(university='Edinburgh',course='INF2D, 2025-path lecture materials',material='Lecture 3 Search Strategies and Lecture 2 node/formulation sections',read='All 57 Lecture 3 pages as extracted text; relevant Lecture 2 sections',role='core',qualification='Individual 2025 lecturer not identified in PDF; current course team separately checked'),dict(university='Stanford',course='CS221 Summer 2012-2013, Chris Piech',material='Search homework, Chris Piech and Percy Liang',read='Complete assignment page',role='supplementary')]
(E/'reading.json').write_text(json.dumps(dict(reviewDate='2026-10-08',records=records,qualification='Accessible finite candidate pool, not every course worldwide. Original proofs and independently reconstructed problems; source-audit records limits.'),indent=2)+'\n',encoding='utf-8')
(E/'question-visual-decisions.json').write_text(json.dumps([dict(questionId=q['id'],modelId=q.get('modelId'),decision='Algorithm walkthrough or explicitly labelled counting specialization; read the question parameters before transferring numbers.' if q.get('modelId') else 'The full calculation or proof is primary; no unrelated generic visual attached.')for q in qs+auth],indent=2)+'\n',encoding='utf-8')
print('Prepared 80 original/reconstructed problems, 80 rules and one original-PDF-checked authentic item.')
