from pathlib import Path
import json,re,hashlib,fitz
B=Path(__file__).resolve().parent;R=B.parent;E=B/'l_det-evidence';C=Path('C:/Users/bheydari/AppData/Local/Temp/l-det-sources')
p=B/'l_det-problems.en.txt';s=p.read_text(encoding='utf-8')
s=s.replace("Cramer's rule with a negative determinant","Cramer's rule with signed numerators").replace("The title's potential sign concern is resolved explicitly: the coefficient determinant is positive here, while the second replacement determinant is negative.","The coefficient determinant is positive, while the second replacement determinant is negative.")
start=s.index('Take $B=',s.index('@@ 30|'));end=s.index('\n\n**Transfer rule.**',start)
s=s[:start]+r'''Take $B=\begin{bmatrix}1&1\\0&1\end{bmatrix}$, $D=I_2$, $C=\begin{bmatrix}1&0\\0&2\end{bmatrix}$, and $E=\begin{bmatrix}0&0\\1&0\end{bmatrix}$. Then $BD-EC=\begin{bmatrix}1&1\\-1&1\end{bmatrix}$ has determinant two. But $B^{-1}=\begin{bmatrix}1&-1\\0&1\end{bmatrix}$ gives $EB^{-1}C=\begin{bmatrix}0&0\\1&-2\end{bmatrix}$, so the actual block determinant is $\det B\det(I-EB^{-1}C)=3$. The discrepancy proves that the proposed scalar-looking formula is false. Moving factors through a matrix product requires commutation conditions that were not stated. The valid Schur formula retains both multiplication order and the invertibility assumption.''' +s[end:]
p.write_text(s,encoding='utf-8')
s+='\n'+(B/'l_det-more-problems.en.txt').read_text(encoding='utf-8')
qs=[];rules=[]
for block in s.split('@@ ')[1:]:
 header,body=block.split('\n',1);a=header.split('|');stem,sol=body.split('---SOLUTION---');n=int(a[0]);q=dict(id='l-det-original-'+str(n),title=a[1],origin=a[2],stem=stem.strip(),solution=sol.strip())
 if len(a)>3:q['modelId']=a[3]
 if n==37:q['modelId']='triangle-main'
 if n==42:q['modelId']='reflection-main'
 qs.append(q);transfer=sol.split('**Transfer rule.**')[1].strip();first=sol.strip().split('\n\n')[0];sentences=re.split(r'(?<=[.!?])\s+(?=[A-Z])',first)
 rules.append(f'{n}. **{a[1]}.** '+transfer+' **Worked check.** '+' '.join(sentences[:2]))
assert len(qs)==80 and [q['id']for q in qs]==['l-det-original-'+str(i)for i in range(1,81)]
calibrations=(B/'l_det-rule-checks.en.txt').read_text(encoding='utf-8').splitlines();assert len(calibrations)==80
rules=[str(i+1)+'. **'+q['title']+'.** '+q['solution'].split('**Transfer rule.**')[1].strip()+' **Condition and worked check.** '+calibrations[i] for i,q in enumerate(qs)]
(B/'l_det-questions.json').write_text(json.dumps(qs,indent=2)+'\n');(B/'l_det-review.en.md').write_text('\n\n'.join(rules)+'\n',encoding='utf-8')
commit='bdadf6e2c9cadc4772ae137a96a3da753c7cfd08';root=Path('C:/Users/bheydari/AppData/Local/Temp/exam-calibration-1406/source')
paths=['Exams/Phd/CS/1404/Q892A-PHD1404-[www.konkur.in].pdf','Exams/MS/CS/1405/Q257A-Arshad1405-[www.konkur.in].pdf']
auth=[dict(id='Phd_CS_1404_Q32',title='Symmetric positivity: determinant sign is insufficient',booklet='PhD CS 1404',questionNumber=32,pdfPage=8,modelId='positivity-main',stem=r'For $A=\begin{bmatrix}1&a&a\\a&1&a\\a&a&1\end{bmatrix}$ to be positive definite, what is the range of $a$?',options=[r'$-1<a<1$',r'$-\frac12<a<1$',r'$-\frac12<a<\frac12$',r'$0<a<1$'],answer=2,solution=r'''Write $A=(1-a)I+aJ$. The constant-vector line has factor $1+2a$, and its orthogonal sum-zero plane has factor $1-a$. Decompose any vector orthogonally into these two parts; the quadratic form is the sum of each squared length times its corresponding factor. Strict positivity requires both factors positive, so $-1/2<a<1$, which is option 2. At either endpoint a nonzero direction has zero form, so endpoints are excluded. The determinant is $(1-a)^2(1+2a)$, but its positivity alone would wrongly admit $a>1$, where the two-dimensional plane has a negative factor. Option 1 permits a negative constant-line factor, option 3 unnecessarily excludes valid values above one half, and option 4 unnecessarily excludes valid negative values. This authentic question calibrates the distinction between determinant positivity and quadratic-form positivity.'''),dict(id='MS_CS_1405_Q44',title='Triangular polynomial map and determinant consequence',booklet='MSc CS 1405',questionNumber=44,pdfPage=10,stem=r'On the real polynomial space $P_2$, let $T(f(x))=f(x)+(x+1)f\prime(x)$. Which set contains all eigenvalues of $T$?',options=[r'$\{2\}$',r'$\{1,2\}$',r'$\{1,2,3\}$',r'$\{1,2,4\}$'],answer=3,solution=r'''The ordered monomial basis is $1,x,x^2$. Its images are $1$, $1+2x$, and $2x+3x^2$. Therefore the coordinate matrix is $\begin{bmatrix}1&1&0\\0&2&2\\0&0&3\end{bmatrix}$. Its characteristic determinant is $(t-1)(t-2)(t-3)$, giving precisely eigenvalues one, two, and three, hence option 3. The printed question asks for eigenvalues; the further conclusion $\det T=6$ is our explicitly identified determinant consequence, not an added premise or changed question. It follows directly from triangularity and remains the same in every basis. Options 1 and 2 omit genuine roots, while option 4 replaces the actual degree-two factor three by four.''')]
for q,path in zip(auth,paths):
 q.update(repoPath=path,sourceCommit=commit,sourceSha256=hashlib.sha256((root/path).read_bytes()).hexdigest(),answerStatus='independently_derived_not_official',verification='Original PDF page visually inspected; all printed options retained in their original order; English adaptation checked.')
(B/'l_det-authentic.json').write_text(json.dumps(auth,indent=2)+'\n')
acq=json.loads((E/'acquisition.json').read_text());acq=[x for x in acq if x['id']!='cambridge'];path=C/'cambridge.pdf';acq.append(dict(id='cambridge',url='https://www.damtp.cam.ac.uk/user/sjc1/teaching/VandM/notes.pdf',pages=len(fitz.open(path)),sha256=hashlib.sha256(path.read_bytes()).hexdigest(),cachePath=str(path),transportNote='Public teaching PDF fetched with local certificate validation disabled after local CA failure; identified by PDF title, lecturer, course, term and saved hash.'))
(E/'acquisition.json').write_text(json.dumps(acq,indent=2)+'\n')
reading=[dict(university='Oxford',course='M1 Linear Algebra II',instructor='Richard Earl',term='Hilary 2026',pages=list(range(5,22)),role='Core: axioms, uniqueness, structured examples, adjugate and basis-invariant maps',corrections=['PDF page 16 contains a11 a22 a23 where the identity term requires a11 a22 a33, and a displayed matrix repeats a23 in position (3,2). Visually confirmed. Page 7 correctly says n >= 4; text extraction resembled > 4 and was not adopted as a source error.']),dict(university='Cambridge',course='Mathematical Tripos IA Vectors and Matrices',instructor='Stephen J. Cowley',term='Michaelmas 2010',pages=list(range(74,85))+[89,148],role='Core: geometric determinant, permutations, product proof, cofactors and inverse; no source reproduction',corrections=[]),dict(university='MIT',course='18.06SC Linear Algebra',instructor='Gilbert Strang',term='Fall 2011',documents={'properties':[1,2,3],'cofactors':[1,2,3],'cramer':[1,2,3,4]},role='Core: geometry, row-operation properties, tridiagonal recurrence, Cramer; independently corrected proof notation',corrections=['Cofactors summary page 1 prints a11 a23 a33 in one negative term; correct factor is a32. Visually confirmed.','Cramer summary page 1 uses Cj1 in a diagonal product where C1j is required and its final line includes an extra A in the inverse expression. Visually confirmed.','Unsigned geometric area uses absolute determinants; source page 4 area notation omits the absolute-value qualification.']),dict(university='UC Berkeley',course='Math 54',instructor='Alexander Paulin',term='Spring 2018',pages=[1,2,3,4],role='Core: all scanned pages visually read; row-operation example determinant -2 independently verified',corrections=[]),dict(university='Harvard',course='Math 21b',instructor='Oliver Knill',term='Spring 2023',pages=[1,2],decision='Not selected as a core: incorrect general formula includes an extra sign factor; retained only as rejected-candidate evidence',corrections=['PDF page 1 visually confirms extra (-1)^(n+1) inside Leibniz product and an unclosed triple-product parenthesis.']),dict(university='CMU',course='21-241 Summer I 2014',instructor='William Gunther',pages=[1,2,3],decision='Not selected: calendar determinant link points to linear-map notes instead.'),dict(university='ETH-hosted',course='110PMA207 notes',decision='Not counted as an ETH course: hosting does not verify institutional course provenance; only title/provenance screened.'),dict(university='Stanford SUMO',course='Student organization linear algebra notes',decision='Not counted as an instructor course: student notes provenance; chapter location screened, not claimed fully reviewed.')]
(E/'reading.json').write_text(json.dumps(reading,indent=2)+'\n')
decisions=[dict(questionId=q['id'],modelId=q.get('modelId'),decision='Exact stated data or labelled structural visualization.'if q.get('modelId')else'Complete algebra, counterexample, or formula is the primary representation; no unrelated generic animation.')for q in qs+auth]
(E/'question-visual-decisions.json').write_text(json.dumps(decisions,indent=2)+'\n')
print('Prepared 80 independently written solutions and final notes, plus two original-PDF-checked examination adaptations.')
