from pathlib import Path
B=Path(__file__).resolve().parent;R=B.parent
p=B/'build_concept_animations.py';s=p.read_text();s=s.replace('functions,arrays,kmap\n','functions,arrays,kmap,combin\n');p.write_text(s)
p=B/'animations/catalog.py';s=p.read_text()
if "'g_combin':" not in s:s=s.rstrip()[:-1]+",\n'g_combin':{'contract':['comb-priority'],'netlists':['comb-dag','comb-feedback'],'structure':['comb-arrival'],'cofactors':['comb-cofactor','comb-rom'],'mapping':['comb-nand','comb-active-low','comb-word'],'hdl':['comb-latch'],'verification':['comb-miter','comb-fault'],'timing':['comb-interval','comb-falsepath']}\n}\n"
p.write_text(s)
p=B/'qa_animations_browser.py';s=p.read_text().replace('scene.id.startsWith("kmap-custom-")','scene.id.startsWith("kmap-custom-")||scene.id.startsWith("combin-custom-")');p.write_text(s)
s=(B/'build_kmap_chapter.py').read_text();prefix=s[:s.index('figures={}')].replace('from kmap_math_layout import wrap','from combin_math_layout import wrap');tail=s[s.index('questions=json.loads'):]
tail=tail.replace('g_kmap','g_combin').replace('kmap-','combin-').replace('LAB:kmap','LAB:combin').replace('LAB:kmap','LAB:combin').replace("'kmap'","'combin'")
start=tail.index('lab="""');end=tail.index('source=(BASE/',start)
tail=tail[:start]+'''lab="""<section class="lab" id="combin-lab"><form id="combin-form"><label>Circuit family<select name="mode"><option value="shared">Shared multi-output circuit</option><option value="priority">Priority controller; A=E, B=R1, C=R0</option><option value="nand">Three-NAND mapping of A(B+C)</option></select></label><label>Candidate<select name="variant"><option value="correct">Correct reference implementation</option><option value="faulty">Deliberately faulty alternative</option></select></label><div class="bit-inputs"><label>A<select name="a"><option>0</option><option selected>1</option></select></label><label>B<select name="b"><option>0</option><option selected>1</option></select></label><label>C<select name="c"><option selected>0</option><option>1</option></select></label><label>D<select name="d"><option>0</option><option selected>1</option></select></label></div><button type="submit">Recompute complete table and restart trace</button></form><div id="combin-output" aria-live="polite"></div><section class="concept-animation" id="combin-player" data-loaded="true"></section></section>"""
'''+tail[end:]
tail=tail.replace("anchors=['sources','canonical','geometry','covers','care-sets','tabulation','implementation','problems','review','laboratory','references']","anchors=['sources','contract','netlists','structure','cofactors','mapping','hdl','verification','timing','case-studies','problems','review','laboratory','references']")
tail=tail.replace('==84','==82').replace('84 worked problems','82 worked problems').replace('questionCount=84,authenticQuestionCount=3,originalQuestionCount=81','questionCount=82,authenticQuestionCount=2,originalQuestionCount=80').replace('enumerate(questions,4)','enumerate(questions,3)').replace('Minterms, Maxterms, and Logic Minimization','Combinational Circuit Design').replace('Authentic canonical-form and hazard revisits','Authentic netlist and cofactor-design revisits').replace('Logic minimization chapter','Combinational circuit design chapter').replace('Logic minimization','Combinational circuit design').replace('logic-minimization','combinational-design')
tail=tail.replace('Priority controller; A=E, B=R1, C=R0','Priority controller').replace('Correct reference implementation','Correct implementation').replace('Deliberately faulty alternative','Faulty implementation')
tail=tail[:tail.index("print('Built sole")]+"print('Built sole combinational-design draft: 82 worked tasks, 80 rules, eight figures, fourteen models and an editable verification lab.')\n"
(B/'build_combin_chapter.py').write_text(prefix+(B/'combin_figures.pyfrag').read_text()+tail,encoding='utf-8')
css=(R/'dist/chapters/g_kmap.css').read_text().replace('kmap','combin')+'\n.bit-inputs{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.6rem} #combin-output{font-family:"Source Sans 3",sans-serif} #combin-output table td{font-family:"STIX Two Math",serif} .lesson :not(pre)>code{overflow-wrap:anywhere;word-break:break-word;white-space:normal}\n'
(R/'dist/chapters/g_combin.css').write_text(css)
p=R/'dist/chapters/g_combin.js';s=p.read_text();p.write_text(s.replace("mode==='shared'?{gates:5,depth:3}","mode==='shared'?{gates:4,depth:3}"))
print('Prepared single-chapter renderer, dedicated fonts and fourteen concept models.')
