from pathlib import Path
R=Path(__file__).resolve().parents[1];B=R/'research'
s=(B/'render_a_heap.py').read_text(encoding='utf-8').replace('a_heap','a_hash').replace('hp-','hs-').replace('#hp','#hs').replace('data-hp','data-hs')
s=s.replace("mathml.SYMBOLS.update(","mathml.SYMBOLS.update(ell='ℓ',gcd='gcd',exp='exp',ln='ln',Pr='Pr',")
s=s.replace("answer='<p><strong>Correct option: '+str(q['answer'])+'.</strong></p>'", "answer='<p><strong>'+e(q.get('answerLabel','Correct option:'))+' '+str(q['answer'])+'.</strong></p>'")
start=s.index("lab='<section");end=s.index('\n\nsource=',start)
lab='''<section class="lab"><form id="hs-form"><label>Operation<select name="operation"><option>open</option><option>chain</option><option>shift</option><option>rebuild</option><option>perfect</option><option>cuckoo</option><option>bloom</option><option>horner</option><option>robin</option></select></label><label>Capacity<input name="capacity" value="11"></label><label>Integer keys or character codes<input name="keys" value="10,21,32,43,9"></label><label>Probe policy<select name="policy"><option>linear</option><option>square</option><option>alternating</option><option>triangular</option><option>double</option></select></label><label>Fixed secondary step<input name="step" value="4"></label><label>After building<select name="command"><option>get</option><option>put</option><option>delete</option><option>none</option></select></label><label>Command target<input name="target" value="54"></label><label>New capacity for rebuilding<input name="newCapacity" value="13"></label><label>Polynomial base<input name="base" value="5"></label><label>Bloom bit-function count<input name="hashes" value="3"></label><button type="submit">Build the exact hashing trace</button></form><p id="hs-error" role="alert"></p><p>The compact laboratory accepts capacities two through thirteen and at most sixteen integer inputs between minus 999 and 999. Chaining uses at most eight inputs and eight buckets. Perfect placement requires distinct keys, at most three keys per bucket and four occupied buckets for readable second-level arrays. Rebuilding uses linear probing and enough new slots for every distinct key. Backward shifting requires a present deletion target and linear probing. Cuckoo placement uses distinct keys and declared candidate functions; bounded relocation failure is labeled. Robin Hood placement requires enough slots. Polynomial inputs are character codes; Bloom inputs use the explicit deterministic bit functions printed in the checkpoint. These mechanism samples do not simulate random hashing distributions. A probe route can exhaust before the physical table fills. Every trace starts paused, and invalid input preserves the preceding valid trace.</p><div id="hs-output"></div></section>'''
s=s[:start]+"lab="+repr(lab)+s[end:]
s=s.replace('<!-- LAB: heap -->','<!-- LAB: hash -->')
start=s.index("anchors=[");end=s.index(';it=iter(anchors)',start)
s=s[:start]+"anchors="+repr(['sources','contract','arithmetic','chaining','occupancy','birthday','universal','lookup','linear','tombstones','shifting','quadratic','double','ideal-probing','models','rebuilding','perfect','advanced','applications','exam-reasoning','summary','problems','review','laboratory','references'])+s[end:]
s=s.replace('Heaps and Priority Queues: Exact Structure, Repair Proofs, and Amortized Design','Hash Tables: Exact Probes, Collision Mathematics, and Correct Updates')
s=s.replace('four core written university courses plus a fifth reviewed course','four core written university courses plus two reviewed comparisons').replace('specialized exact heap models','specialized exact hashing models').replace('Heap and priority queue chapter audit','Hashing chapter audit').replace('Heap and priority queue chapter','Hashing chapter')
(B/'render_a_hash.py').write_text(s,encoding='utf-8')
print('Created isolated hash chapter renderer.')
