from pathlib import Path
import json,hashlib
B=Path(__file__).resolve().parent;E=B/'i_agents-evidence'
s='\n'.join((B/f).read_text(encoding='utf-8')for f in['i_agents-problems.en.txt','i_agents-more-problems.en.txt']);qs=[];rules=[]
for block in s.split('@@ ')[1:]:
 header,body=block.split('\n',1);a=header.split('|');stem,tail=body.split('---SOLUTION---');sol,rule=tail.split('---RULE---');n=int(a[0]);q=dict(id='i-agents-original-'+str(n),title=a[1],origin=a[2],stem=stem.strip(),solution=sol.strip())
 if len(a)>3:q['modelId']=a[3].strip()
 qs.append(q);rules.append(str(n)+'. **'+a[1]+'.** '+rule.strip())
assert len(qs)==80 and [q['id']for q in qs]==['i-agents-original-'+str(i)for i in range(1,81)]
(B/'i_agents-questions.json').write_text(json.dumps(qs,indent=2)+'\n',encoding='utf-8');(B/'i_agents-review.en.md').write_text('\n\n'.join(rules)+'\n',encoding='utf-8')
rp='Exams/MS/CE/1405/Q135A-Arshad1405-[www.konkur.in].pdf';root=Path('C:/Users/bheydari/AppData/Local/Temp/exam-calibration-1406/source');sha=hashlib.sha256((root/rp).read_bytes()).hexdigest()
auth=[dict(id='MS_CE_1405_Q71',title='Agent performance depends on its task environment',booklet='MSc CE 1405',questionNumber=71,pdfPage=15,stem='How well an agent can behave depends on which factor?',options=['The agent designer.','The agent sensors.','The nature of the environment.','The agent actuators.'],answer=3,solution='The intended best answer is option 3: the task environment determines which behaviour and information can achieve the performance criterion. Sensors and actuators are important components of the agent, but their adequacy is judged relative to that environment and task. A local dirt sensor can suffice for one cleaning objective and be insufficient for another requiring exact global dirt information. The designer is not a mathematical property of the task. The short original wording should not be strengthened into a claim that sensor and actuator quality never matter: rationality is evaluated relative to the information, action capabilities and performance criterion available in the specified environment. This is a conceptual best-choice item, not an exclusivity theorem.'),dict(id='MS_CE_1405_Q75',title='Learning-method selection is not determined only by data quantity',booklet='MSc CE 1405',questionNumber=75,pdfPage=15,stem='Any part of an agent program can be improved using machine learning. The kind of improvement and the methods used to make it do NOT depend on which of the following?',options=['The prior knowledge available to the agent.','It depends only on the amount of available data.','Which part of the agent is to be improved.','The data available and the feedback received about those data.'],answer=2,solution='Option 2 is the intended incorrect dependency statement. The word only is decisive: data quantity cannot by itself determine the type of improvement or learning method. Prior knowledge can justify a model structure or constrain hypotheses. The target component determines whether the output is a sensor model, transition distribution, utility estimate or direct policy. Available data and feedback distinguish, for example, labelled examples from reward-only interaction. Two tasks with the same number of observations can require very different methods when one supplies labels and the other supplies only delayed rewards. Options 1, 3 and 4 are genuine considerations; they need not each influence every possible special case to be relevant dependencies in general.')]
for q in auth:q.update(repoPath=rp,sourceCommit='bdadf6e2c9cadc4772ae137a96a3da753c7cfd08',sourceSha256=sha,answerStatus='independently_derived_not_official',verification='Original PDF page 15 visually inspected at enlarged resolution; options translated in printed order.')
(B/'i_agents-authentic.json').write_text(json.dumps(auth,indent=2)+'\n',encoding='utf-8')
reading=[dict(university='UC Berkeley',course='CS188 Fall 2023',instructors=['Igor Mordatch','Peyrin Kao'],author='Nikhil Sharma',material='Note 1',pdfPages=[1,2],read='Complete extracted text',role='core'),dict(university='Carnegie Mellon',course='15-281 Fall 2023',instructors=['Vincent Conitzer','Aditi Raghunathan'],material='Introduction and activity solutions',pdfPages=list(range(1,52)),activityPdfPages=[1,2],read='Complete extracted text',sharedProvenance='Lecture credits Berkeley',role='core'),dict(university='Edinburgh',course='INF2D, 2025-path written lectures',instructors='Individual 2025 lecturer not identified in PDF; current course team separately verified',material='Lectures 1 and 2',lecture1Pages=list(range(1,38)),lecture2Pages=list(range(1,32)),read='Complete extracted text; some source images unavailable',role='core'),dict(university='Stanford',course='CS221 Summer 2012-2013',instructor='Chris Piech',material='Markov Decisions handout',read='All sections; linked course page verifies author and term',role='core'),dict(host='Oxford',author='Michael Wooldridge',material='Second-edition Intelligent Agents Lecture 2',pdfPages=list(range(1,72)),read='Complete extracted text; author slides retain Liverpool URL',role='supplementary; not counted as a verified Oxford taught course')]
(E/'reading.json').write_text(json.dumps(dict(reviewDate='2026-10-08',records=reading,downloadLimitation='Local HTTPS connection refused; no document byte hashes claimed. Web full text used.',coursePoolAudit='research/i_agents-source-audit.md'),indent=2)+'\n',encoding='utf-8')
(E/'question-visual-decisions.json').write_text(json.dumps([dict(questionId=q['id'],modelId=q.get('modelId'),decision='Actual problem data or explicitly stated specialization.'if q.get('modelId')else'Complete calculation, proof or conceptual counterexample is primary; do not attach unrelated generic graphics.')for q in qs+auth],indent=2)+'\n',encoding='utf-8')
print('Prepared 80 full solutions, 80 final rules and two original-PDF-checked MSc adaptations.')
