from pathlib import Path
import json,subprocess,hashlib
R=Path(__file__).resolve().parents[1];B=R/'research';E=B/'l_spaces-evidence'
assert json.loads((E/'browser.json').read_text())['status']=='passed'
assert json.loads((E/'mathematics.json').read_text())['status']=='passed'
archive=Path('C:/Users/bheydari/AppData/Local/Temp/l-spaces-deploy.tar.gz')
receipt=dict(status='upload_blocked',projectId='appgprj_6ab5666f72b081918286c6b371c1eb1b',contentCommit='7f6d5669a290f552b22ba73760b6b17710a7a019',sourcePushed=True,archivePath=str(archive),archiveSha256=hashlib.sha256(archive.read_bytes()).hexdigest(),archiveFiles=366,githubBranch='study-planner-1406',githubContentCommit='18466e24164a78bff861f5d0de130b808e1d5902',lastConfirmedLiveVersion=80,newVersionConfirmed=False,uploadFailures=3,error='Native Sites archive upload failed to send its OpenAI file request to https://chatgpt.com/backend-api/files. No new version or deployment ID was returned.',preparationNote='Bundled workflow pushed and verified the content source, then its Windows package helper path failed. A local tar fallback was built and every member path and byte sequence validated.',localPreviewUrl='http://127.0.0.1:8093/chapters/l_spaces.html',nextAction='Retry the native archive-backed private publication of this exact content after upload service connectivity recovers. Preserve the archive and avoid claiming an online update until a succeeded deployment is verified.')
(B/'l_spaces-publication.json').write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf-8')
g=json.loads((B/'chapter-gate.json').read_text());g.update(state='awaiting_user_approval',publicationState='upload_blocked',publishedVersion=None,lastCompletedReview='Vector spaces: 29 sections, 82 complete solved problems, 80 condition-bearing final rules, four reviewed written courses from four universities, 23 concept models / 76 checkpoints, exact-rational rectangular generator laboratory and validated mathematical typography.',nextReview='Retry pending publication of l_spaces. Await explicit user approval before any following chapter.',activeWork='l_spaces complete and delivered through local preview and GitHub; private Site update is pending because native file upload transport failed. No following chapter has started.')
(B/'chapter-gate.json').write_text(json.dumps(g,indent=2)+'\n',encoding='utf-8')
with(R/'WEEKLY_DELIVERY.md').open('a',encoding='utf-8')as f:f.write('\n\n## Vector spaces draft delivered locally — 8 October 2026\n\nThe complete l_spaces review draft and evidence were pushed to GitHub branch study-planner-1406, content commit 18466e2. The Site source was pushed at 7f6d566. Four reviewed written university courses; 29 sections; 82 fully worked questions; 80 final rules; 23 specialized models / 76 checkpoints; 2,130 exact checks and 92 independently compared rectangular lab inputs. Fonts, mathematical fences, controls, print and mobile passed. All 42 preceding pages and 2,675 questions retained. Local preview: http://127.0.0.1:8093/chapters/l_spaces.html. Three archive upload attempts failed at the native OpenAI file transport. The last confirmed online Site is version 80; no new deployed version is claimed. Preserve the prepared archive and retry the same content publication when connectivity recovers. l_spaces remains a draft awaiting explicit approval; no following chapter has started.\n')
subprocess.run(['git','add','research/record_l_spaces_pending.py','research/l_spaces-publication.json','research/chapter-gate.json','WEEKLY_DELIVERY.md'],cwd=R,check=True)
subprocess.run(['git','commit','-m','Record completed vector-space draft and pending publication upload blocker'],cwd=R,check=True)
print('Recorded completed local delivery, publication blocker and explicit approval gate.')
