from pathlib import Path
import json,hashlib,subprocess
R=Path(__file__).resolve().parents[1];B=R/'research';archive=Path('C:/Users/bheydari/AppData/Local/Temp/i-uninformed-deploy.tar.gz')
receipt=dict(status='succeeded',projectId='appgprj_6ab5666f72b081918286c6b371c1eb1b',contentCommit='5145ee45f59cc57d57c79747a75e097090c3e4b8',sourcePushed=True,sourcePushVerification='Bundled workflow completed saveSource push and remote-HEAD checks before its Windows bash packager failed; a byte-verified Python archive fallback was supplied.',githubPushed=True,githubBranch='study-planner-1406',githubContentCommit='08126ca',archivePath=str(archive),archiveFiles=378,archiveSha256=hashlib.sha256(archive.read_bytes()).hexdigest(),savedArchiveContentHash='sha256:5fa0da567d487603941d2ec14b70f47d59d8226740c30aecfe13bd89a0836047',savedArchiveBytes=75448320,versionNumber=81,versionId='appgprj_6ab5666f72b081918286c6b371c1eb1b~appgver_6c1c3234a1948191905a03348e0b9d8f',deploymentId='appgdep_6ac7d4291a8881919637875a7b15438a',deploymentStatus='succeeded',deploymentUpdatedAt='2026-10-08T17:34:55.860258+00:00',sourceVerifiedBy='get_site_version: source.commit_sha matches contentCommit; archive file_count is 378',url='https://phd-cse-1406-plan.bheydari-as721rn.chatgpt.site/chapters/i_uninformed.html?v=81',audience='Existing owner-only custom access preserved',resolvedPriorPublications=['research/l_spaces-publication.json','research/i_agents-publication.json'],qualification='Earlier pending-publication receipts are historical; version 81 contains both preceding chapters and the current draft. No later chapter has begun.')
(B/'i_uninformed-publication.json').write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf-8')
g=json.loads((B/'chapter-gate.json').read_text());assert g['currentTopicId']=='i_uninformed';g.update(state='awaiting_user_approval',publicationState='succeeded',publishedVersion=81,pendingPriorPublication=None,activeWork='i_uninformed delivered online in version 81 and on GitHub. Await explicit approval before starting another chapter.',nextReview='Await explicit approval of i_uninformed. Version 81 also resolves the preceding l_spaces and i_agents publication backlog.');(B/'chapter-gate.json').write_text(json.dumps(g,indent=2)+'\n',encoding='utf-8')
with(R/'WEEKLY_DELIVERY.md').open('a',encoding='utf-8')as f:f.write('\n\n## Uninformed search online delivery — 8 October 2026\n\nPrivate Site version 81 successfully published from exact source commit 5145ee45f59cc57d57c79747a75e097090c3e4b8. Deployment appgdep_6ac7d4291a8881919637875a7b15438a succeeded, and get_site_version confirmed source provenance and 378 archive entries. GitHub content is mirrored at 08126ca on study-planner-1406. The archive also includes the previously pending l_spaces and i_agents chapters; their older failed-publication receipts are superseded by this successful delivery. i_uninformed remains a draft awaiting explicit student approval. No next chapter started.\n')
paths=['research/record_i_uninformed_publication.py','research/i_uninformed-publication.json','research/chapter-gate.json','WEEKLY_DELIVERY.md'];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','diff','--cached','--check'],cwd=R,check=True);subprocess.run(['git','commit','-m','Record verified version 81 publication and chapter approval gate'],cwd=R,check=True)
print('Recorded successful exact-source private publication and awaiting-user-approval gate.')
