from pathlib import Path
import hashlib,json,subprocess
R=Path(__file__).resolve().parents[1];B=R/'research';E=B/'i_agents-evidence'
assert json.loads((E/'browser.json').read_text())['status']=='passed'
assert json.loads((E/'mathematics.json').read_text())['status']=='passed'
archive=Path('C:/Users/bheydari/AppData/Local/Temp/i-agents-deploy.tar.gz')
receipt=dict(status='source_credential_transport_blocked',projectId='appgprj_6ab5666f72b081918286c6b371c1eb1b',contentCommit='8a45eb7964581856e9d78d324048bec0881d5bde',sourcePushed=False,githubPushed=True,githubBranch='study-planner-1406',githubContentCommit='c8f43b9',archivePath=str(archive),archiveFiles=372,archiveSha256=hashlib.sha256(archive.read_bytes()).hexdigest(),lastSuccessfullyReadLiveVersion=80,newVersionConfirmed=False,error='Sites get_site and create_source_repository_write_credential returned a transport HTTP request failure for https://chatgpt.com/backend-api/ps/mcp. The earlier credential expired at 2026-10-08T16:28:32.680Z. No expired credential was used, no new source push was attempted and no new version or deployment ID was returned.',localPreviewUrl='http://127.0.0.1:8093/chapters/i_agents.html',priorPendingPublication='research/l_spaces-publication.json',nextAction='When Sites transport recovers, refresh credentials, push the exact packaged content commit through the source workflow, and publish the validated archive to the existing private Site. Check the returned saved-version source and deployment success. This package includes the already approved l_spaces chapter. Do not claim an online update before those checks succeed.')
(B/'i_agents-publication.json').write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf-8')
g=json.loads((B/'chapter-gate.json').read_text());g.update(state='awaiting_user_approval',publicationState='source_credential_transport_blocked',publishedVersion=None,activeWork='i_agents complete and delivered through local preview and GitHub; private Site update pending because Sites transport prevents refreshing the expired source credential. No following chapter has started.',nextReview='Await explicit approval of i_agents before any following chapter. Retry the pending exact-content private publication when Sites connectivity recovers.')
(B/'chapter-gate.json').write_text(json.dumps(g,indent=2)+'\n',encoding='utf-8')
with(R/'WEEKLY_DELIVERY.md').open('a',encoding='utf-8')as f:f.write('\n\n## Intelligent agents delivered locally and to GitHub — 8 October 2026\n\nContent commit 8a45eb7 is mirrored on GitHub branch study-planner-1406 at c8f43b9. The complete interactive chapter is served at http://127.0.0.1:8093/chapters/i_agents.html (HTTP 200 checked). The clean content archive has 372 byte-verified entries. Sites transport failed both site reads and credential refresh at https://chatgpt.com/backend-api/ps/mcp; the preceding credential was expired, so it was not used. No new Site-source push, saved version or deployment is claimed. Version 80 was the last successful site read; current online state could not be refreshed. The prepared package includes approved l_spaces and draft i_agents. i_agents remains awaiting explicit user approval; no following chapter has started.\n')
subprocess.run(['git','add','research/record_i_agents_pending.py','research/i_agents-publication.json','research/chapter-gate.json','WEEKLY_DELIVERY.md'],cwd=R,check=True)
subprocess.run(['git','diff','--cached','--check'],cwd=R,check=True)
subprocess.run(['git','commit','-m','Record intelligent-agent local delivery and Sites credential transport blocker'],cwd=R,check=True)
print('Recorded completed draft, verified GitHub delivery and awaiting-user-approval gate.')
