from pathlib import Path
import json,hashlib,subprocess
R=Path(__file__).resolve().parents[1];B=R/'research';archive=Path('C:/Users/bheydari/AppData/Local/Temp/p-strings-deploy.tar.gz')
receipt=dict(status='succeeded',projectId='appgprj_6ab5666f72b081918286c6b371c1eb1b',contentCommit='cf44482c5281b5280541e69b95514876e38cf607',sourcePushed=True,sourcePushVerification='Bundled workflow source push preceded the Windows package-helper failure. A byte-verified Python archive fallback was supplied; native save and get_site_version verified the exact pushed source commit.',githubPushed=True,githubBranch='study-planner-1406',githubContentCommit='5cffe5c',archivePath=str(archive),archiveFiles=384,archiveSha256=hashlib.sha256(archive.read_bytes()).hexdigest(),savedArchiveContentHash='sha256:069ae41f1610873b2de96788ece38ab40de49204888e6f1844814f8a6bf220fc',savedArchiveBytes=77312000,versionNumber=82,versionId='appgprj_6ab5666f72b081918286c6b371c1eb1b~appgver_3b56a52fb318819197059c553d779333',deploymentId='appgdep_6ac7dd9a413081918b3e2a7364ae4aa1',deploymentStatus='succeeded',deploymentUpdatedAt='2026-10-08T18:15:14.905229+00:00',sourceVerifiedBy='get_site_version: source.commit_sha matches contentCommit; archive file_count is 384',url='https://phd-cse-1406-plan.bheydari-as721rn.chatgpt.site/chapters/p_strings.html?v=82',audience='Existing owner-only custom access preserved',qualification='p_strings is a review draft awaiting explicit approval. No subsequent chapter has begun.')
(B/'p_strings-publication.json').write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf-8')
g=json.loads((B/'chapter-gate.json').read_text());assert g['currentTopicId']=='p_strings';g.update(state='awaiting_user_approval',publicationState='succeeded',publishedVersion=82,activeWork='p_strings delivered online in version 82 and on GitHub. Await explicit user approval before starting another chapter.',nextReview='Await explicit approval of p_strings before starting any following chapter.');(B/'chapter-gate.json').write_text(json.dumps(g,indent=2)+'\n',encoding='utf-8')
with(R/'WEEKLY_DELIVERY.md').open('a',encoding='utf-8')as f:f.write('\n\n## Strings and terminators online delivery — 8 October 2026\n\nPrivate Site version 82 successfully published from exact source commit cf44482c5281b5280541e69b95514876e38cf607. Deployment appgdep_6ac7dd9a413081918b3e2a7364ae4aa1 succeeded; get_site_version verified source provenance and 384 archive entries. GitHub chapter content is mirrored at 5cffe5c on study-planner-1406. The current p_strings chapter remains a draft awaiting explicit student approval. No next chapter started.\n')
paths=['research/record_p_strings_publication.py','research/p_strings-publication.json','research/chapter-gate.json','WEEKLY_DELIVERY.md'];subprocess.run(['git','add','--',*paths],cwd=R,check=True);subprocess.run(['git','diff','--cached','--check'],cwd=R,check=True);subprocess.run(['git','commit','-m','Record verified version 82 strings publication and approval gate'],cwd=R,check=True)
print('Recorded verified version 82 and awaiting-user-approval gate.')
