from pathlib import Path
import json
B=Path(__file__).resolve().parent;R=B.parent
receipt=json.loads(Path('C:/Users/bheydari/AppData/Local/Temp/d-generating-reviewed.tar.receipt.json').read_text())
r=dict(status='published_private',projectId=receipt['project_id'],sourceCommit=receipt['commit_sha'],archiveSha256=receipt['archiveSha256'],archiveEntries=434,versionId='appgprj_6ab5666f72b081918286c6b371c1eb1b~appgver_67af0986d7348191a0cbbadbdccc78b8',deploymentId='appgdep_6aca6c2cbf7c81919a3b7ec687b7f008',deploymentStatus='succeeded',url='https://phd-cse-1406-plan.bheydari-as721rn.chatgpt.site',githubBranch='study-planner-1406',githubContentCommit='086e3ba',chaptersAdded=['g_arithmetic','g_mux','d_recurrence','d_generating'],libraryChapters=51,questions=3411,sourcePushEvidence='Bundled source workflow passed push, remote-SHA and clean-tree verification; subsequently failed only at Windows shell packaging. Independently byte-verified exact archive supplied to native private publication.',verificationLimit='Native private save/deploy returned succeeded. Follow-up site/version reads currently failed transport; no numeric version number or native tar hash is invented.',supersedes=['research/g_mux-publication-pending.json','research/player-behavior-repair/publication-pending.json'])
(B/'d_generating-publication.json').write_text(json.dumps(r,indent=2)+'\n',encoding='utf-8')
g=json.loads((B/'chapter-gate.json').read_text());g['pendingPriorPublication']=None;g['latestPublication']=r
for q in g.get('completedReviewDrafts',[]):
 if q['topicId']in r['chaptersAdded']:q.update(publicationState='published_private',publicationRecord='research/d_generating-publication.json')
(B/'chapter-gate.json').write_text(json.dumps(g,indent=2)+'\n',encoding='utf-8')
with(R/'WEEKLY_DELIVERY.md').open('a',encoding='utf-8')as f:f.write('\n\n## Four new review drafts privately published — 10 October 2026\n\nNative private deployment appgdep_6aca6c2cbf7c81919a3b7ec687b7f008 succeeded from source 164f1769a25642ec05e9d1bd4341bfb12b45f18e, exact 434-file archive. It includes arithmetic circuits, selectors/encoders/decoders, recurrence relations and generating functions, plus the earlier pending simulation behavior fixes. GitHub content commit 086e3ba. Library: 51 chapters and 3411 worked questions. Follow-up site/version reads failed transport, so the numeric Site version remains unverified. Work continues on a_bst under standing authorization; unapproved notes remain review drafts. See research/d_generating-publication.json.\n')
print('Recorded successful native private publication and preserved follow-up read limitations.')
