from pathlib import Path
import gzip,hashlib,json,subprocess
R=Path(__file__).resolve().parents[1];E=R/'research/recent-animation-redesign';receipt=json.loads((E/'publication.json').read_text());v=receipt['version_number'];archive=Path(receipt['archive'])
compressed=archive.read_bytes();assert hashlib.sha256(compressed).hexdigest()==receipt['archiveSha256'];raw=gzip.decompress(compressed)
# Native storage records its tar representation separately from the local gzip/PAX
# representation. Do not assert that different tar encodings have identical hashes.
receipt['localTarSha256']=hashlib.sha256(raw).hexdigest();receipt['localTarBytes']=len(raw);receipt['provenanceVerification']='Local packaged file bytes verified before upload; native saved source SHA and file count verified. Native stored tar hash recorded separately.';(E/'publication.json').write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf-8')
p=R/'research/chapter-gate.json';g=json.loads(p.read_text());assert g['state']=='awaiting_user_approval';g.update(publicationState='succeeded',publishedVersion=v,currentChapterPublishedVersion=83,currentChapterPublicationPath='research/p_recursion-publication.json',publicationRecordPath='research/recent-animation-redesign/publication.json',recentAnimationPublicationPath='research/recent-animation-redesign/publication.json',recentAnimationRevisionStatus='published',activeWork='Simulation redesign published in version '+str(v)+' and on GitHub: ten chapters, 251 models, 1802 checkpoints. No following chapter begun; p_recursion chapter gate still awaits explicit approval.');p.write_text(json.dumps(g,indent=2)+'\n',encoding='utf-8')
p=E/'manifest.json';m=json.loads(p.read_text());m.update(status='published',publishedVersion=v,publicationRecord='publication.json');p.write_text(json.dumps(m,indent=2)+'\n',encoding='utf-8')
with(E/'DELIVERY.en.md').open('a',encoding='utf-8')as f:f.write('\n## Publication\n\nVersion '+str(v)+' succeeded. Published source: '+receipt['commit_sha']+'. The saved source SHA and 397-file archive count were verified. Every local packaged file was byte-verified before upload; the native tar hash and local gzip/PAX tar hash are recorded separately. GitHub content commit: '+receipt['githubContentCommit']+' on study-planner-1406.\n')
with(R/'WEEKLY_DELIVERY.md').open('a',encoding='utf-8')as f:f.write('\nPublication confirmed: recent simulation revision is online in version '+str(v)+' from '+receipt['commit_sha']+', with 397 archived files. GitHub branch study-planner-1406 contains the source, per-model audits and screenshots. Chapter gate remains awaiting approval of p_recursion.\n')
subprocess.run(['git','add','--','research/recent-animation-redesign/publication.json','research/recent-animation-redesign/manifest.json','research/recent-animation-redesign/DELIVERY.en.md','research/record_recent_publication.py','research/chapter-gate.json','WEEKLY_DELIVERY.md'],cwd=R,check=True);subprocess.run(['git','diff','--cached','--check'],cwd=R,check=True);subprocess.run(['git','commit','-m','Record successful version 84 simulation revision publication'],cwd=R,check=True)
print(json.dumps({'version':v,'localArchiveHashVerified':True,'nativeSourceAndFileCountVerified':True}))
