from pathlib import Path
R=Path(__file__).resolve().parents[1];p=R/'dist/chapters/p_strings.js';s=p.read_text()
s=s.replace('snapshot:{source:src.slice()', 'snapshot:{operation:op,source:src.slice()')
s=s.replace("function cellPos(row,i){return {x:70+(i%8)*108,y:(row==='source'?170:440)+Math.floor(i/8)*100};}","function cellPos(row,i,single=false){return {x:70+(i%8)*108,y:(single?170:row==='source'?170:440)+Math.floor(i/8)*100};}")
s=s.replace("const st=f.snapshot;let body=", "const st=f.snapshot,single=['move','delete','reverse','scan'].includes(st.operation);let body=")
s=s.replace("['destination',st.destination,'Destination / text / working buffer']]){body+=", "['destination',st.destination,'Destination / text / working buffer']]){if(single&&row!==(st.operation==='scan'?'source':'destination'))continue;body+=")
s=s.replace("(row==='source'?90:360)","(single?90:row==='source'?90:360)")
s=s.replace('cellPos(row,i)','cellPos(row,i,single)').replace('cellPos(head.row,head.index)','cellPos(head.row,head.index,single)')
s=s.replace("const both=st.read&&st.write&&st.read.row===st.write.row&&st.read.index===st.write.index;", "const both=st.read&&st.write&&st.read.row===st.write.row&&st.read.index===st.write.index,label=name==='write'&&['match','compare'].includes(st.operation)?'read B':name;")
s=s.replace("(both?name[0].toUpperCase():name)","(both?label[0].toUpperCase():label)")
s=s.replace("y=\"700\" class=\"st-label\"", "y=\"'+(single?430:700)+'\" class=\"st-label\"")
s=s.replace("viewBox=\"0 0 1000 760\"", "viewBox=\"0 0 1000 '+(single?490:760)+'\"")
s=s.replace("frames:r.frames.map(f=>({...f,svg:svg(f)}))", "frames:r.frames.map((f,i)=>{const prev=i?r.frames[i-1].snapshot:null;f.teaching.currentState=clone(f.snapshot);f.teaching.changes=prev?Object.keys(f.snapshot).filter(k=>JSON.stringify(prev[k])!==JSON.stringify(f.snapshot[k])).map(k=>({field:k,before:prev[k],after:f.snapshot[k]})):[];for(const head of [f.snapshot.read,f.snapshot.write])if(head)f.teaching.checks.push({expression:head.row+' byte index '+head.index+' is inside its '+f.snapshot[head.row].length+'-byte object; displayed value is '+f.snapshot[head.row][head.index]+'.',result:'verified'});return {...f,svg:svg(f)};})")
p.write_text(s,encoding='utf-8')
print('Added actual before/after state and read-only comparison labels; single-object traces use compact diagrams.')
