from pathlib import Path
R=Path(__file__).resolve().parents[1];p=R/'dist/chapters/d_recurrence.js';s=p.read_text(encoding='utf-8')
start=s.index(" else if(s.operation==='derangements'){b+=");end=s.index("\n else if(s.operation==='partitions'){b+=",start)
new=r''' else if(s.operation==='derangements'){b+=text(34,42,'Size '+z.step+': two reversible cases after choosing the image of one','rc-prose');function cycle(mapping,ox,cy){const n=mapping.length,pts=Array.from({length:n},(_,i)=>[ox+94*Math.cos(-Math.PI/2+2*Math.PI*i/n),cy+58*Math.sin(-Math.PI/2+2*Math.PI*i/n)]);for(let i=0;i<n;i++){const a=pts[i],v=pts[mapping[i]-1],dx=v[0]-a[0],dy=v[1]-a[1],d=Math.hypot(dx,dy);if(!d)continue;const from=[a[0]+19*dx/d,a[1]+19*dy/d],to=[v[0]-20*dx/d,v[1]-20*dy/d];b+=line([from,to],C.active,true);}pts.forEach(([x,y],i)=>{b+=`<circle cx="${x}" cy="${y}" r="17" fill="${i===0?'#f3e8d7':C.light}" stroke="${C.active}"/>`+text(x,y+6,i+1,'rc-node','middle');});}if(z.step>=2){let two=Array.from({length:z.step},(_,i)=>i+2);two[0]=2;two[1]=1;if(z.step>=4){for(let i=2;i<z.step;i++)two[i]=i===z.step-1?3:i+2;cycle(two,200,185);}else if(z.step===2)cycle(two,200,185);else b+=text(200,180,'No valid leftover derangement','rc-prose','middle');if(z.step>=3){let long=Array.from({length:z.step},(_,i)=>i===z.step-1?1:i+2);cycle(long,555,185);}else b+=text(555,180,'No longer cycle at size two','rc-prose','middle');b+=text(200,90,'Two-cycle sample','rc-prose','middle')+text(555,90,'Longer-cycle sample','rc-prose','middle');}else b+=text(380,180,z.step===0?'One empty permutation':'No derangement on one element','rc-prose','middle');b+=text(380,286,'All image choices: '+(z.two??0)+' + '+(z.long??0)+' = '+z.value,'rc-math','middle')+text(380,322,'Drawings are one representative per feasible case, not all permutations.','rc-prose','middle');}'''
s=s[:start]+new+s[end:]
start=s.index(" else if(s.operation==='ferrers'){b+=");end=s.index("\n else if(s.operation==='catalan'){",start)
new=r''' else if(s.operation==='ferrers'){b+=text(34,44,'Partition '+z.parts.join(' + ')+': '+z.case,'rc-prose');const cell=32;z.parts.forEach((p,row)=>{for(let j=0;j<p;j++)b+=rect(55+j*cell,105+row*48,26,34,(z.case.startsWith('Subtract')?j===0:row===2)?'#f3e8d7':C.light);});const reduced=z.case.startsWith('Subtract')?z.parts.map(x=>x-1):z.parts.slice(0,-1);b+=line([[325,172],[408,172]],C.active,true);reduced.forEach((p,row)=>{for(let j=0;j<p;j++)b+=rect(445+j*cell,105+row*48,26,34);});b+=text(55,86,'Original','rc-prose')+text(445,86,'Reduced: '+reduced.join(' + '),'rc-prose')+text(34,305,'The operation is reversible; the complete original count is '+r.count,'rc-prose');}'''
s=s[:start]+new+s[end:];p.write_text(s,encoding='utf-8')
p=R/'research/d_recurrence.en.md';s=p.read_text(encoding='utf-8').replace('## 26. Modular recurrences: cycles, transients, and parity','<!-- SIM: matrix -->\n\n## 26. Modular recurrences: cycles, transients, and parity');p.write_text(s,encoding='utf-8')
print('Added real derangement cycle samples, transformed Ferrers diagrams and matrix state lesson.')
