from pathlib import Path
import re,json
B=Path(__file__).resolve().parent;R=B.parent
s=(B/'render_s_expectation.py').read_text(encoding='utf-8')
s=s.replace('s_expectation','l_det').replace('exp-','det-').replace('data-exp','data-det').replace('Expectation, Linearity, Indicators, and Moments','Determinants, Orientation, and Structured Computation').replace('Expectation chapter audit','Determinants chapter audit').replace('Probability and Statistics','Linear Algebra').replace('Authentic examination: indicator expectation and algorithm cost','Authentic examinations: positivity and a triangular polynomial map').replace('four core university courses and one additional lecture check','four core written courses from four universities')
s=s.replace('mathml.SYMBOLS.update(Pr=', 'mathml.SYMBOLS.update(gamma=chr(947));mathml.SYMBOLS.update(Pr=')
s=s.replace('enumerate(qs,len(auth)+1)','enumerate(qs,1)')
s=s.replace("'<h3>Question '+str(n)","'<h3>'+('Authentic Question ' if auth else 'Question ')+str(n)")
start=s.index('lab=');end=s.index('\nsource=',start)
lab='''<section class="lab"><form id="det-form"><label>Mode<select name="kind"><option value="eliminate">Exact row elimination</option><option value="area">Oriented area</option></select></label><label>Matrix<input name="matrix" value="2,1;3,4"></label><button type="submit">Compute and inspect every step</button></form><p id="det-error" role="alert"></p><p>Exact elimination accepts square integer matrices of order 2–4, with entries from −20 to 20. Separate columns with commas and rows with semicolons. Fractions generated by elimination remain exact. Area mode uses order two and entries from −4 to 4, with a fixed coordinate scale and explicitly labelled derived swap/collapse configurations. Invalid input preserves the preceding result. Every animation starts paused. No floating-point singularity threshold is used.</p><div id="det-output"></div></section>'''
s=s[:start]+'lab='+repr(lab)+s[end:];s=s.replace('<!-- LAB: expectation -->','<!-- LAB: determinant -->')
start=s.index('anchors=');end=s.index(';it=iter(anchors)',start)
anchors=['sources','definition','area','permutations','axioms','multilinearity','ledger','products','invertibility','cofactors','adjugate','cramer','parameters','blocks','update','vandermonde','recurrence','gram','transformations','characteristic','positivity','derivatives','computation','workflow','summary','problems','review','laboratory','references']
s=s[:start]+'anchors='+repr(anchors)+s[end:];s=s.replace('math-layout.js"','math-layout.js?v=79"').replace('math-layout.js\"','math-layout.js?v=79\"')
(B/'render_l_det_impl.py').write_text(s,encoding='utf-8')
css=(R/'dist/chapters/s_expectation.css').read_text(encoding='utf-8').replace('exp-','det-').replace('#exp','#det')
css+='''
.det-math { font-family: "STIX Two Math", serif; font-size: 24px; }
.det-label { font-family: "Source Sans 3", sans-serif; font-size: 21px; }
#det-form input[name=matrix] { min-width: 12em; max-width: 100%; }
.det-stage { overflow: auto; }
'''
(R/'dist/chapters/l_det.css').write_text(css,encoding='utf-8')
exec(compile(s,'render_l_det_impl.py','exec'))
