from pathlib import Path
import json,re,subprocess
B=Path(__file__).resolve().parent;R=B.parent
js=R/'dist/chapters/s_discrete.js'
data=json.loads(subprocess.check_output(['node','-e',"process.stdout.write(JSON.stringify(require(process.argv[1]).fixtures()))",str(js)],text=True,encoding='utf-8'))
(R/'dist/chapters/s_discrete-models.json').write_text(json.dumps(data,indent=2)+'\n',encoding='utf-8')
s=(B/'render_s_descriptive.py').read_text(encoding='utf-8')
s=s.replace('s_descriptive','s_discrete').replace('stat-','disc-').replace('data-stat','data-disc').replace('#stat','#disc')
s=s.replace("mathml.SYMBOLS.update(Phi='Φ',inf='inf')","mathml.SYMBOLS.update(Phi='Φ',inf='inf',downarrow='↓',uparrow='↑')")
s=s.replace('==82','==83').replace('questionCount=82','questionCount=83').replace('authenticQuestionCount=2','authenticQuestionCount=3').replace('82 questions','83 questions')
s=s.replace('Authentic population-moment and normal-standardization bridges','Authentic examination questions: count models and conditioning')
s=s.replace('Descriptive Statistics and Exploratory Data Analysis','Discrete Random Variables and Common Distributions').replace('Descriptive statistics chapter','Discrete random variables chapter').replace('Descriptive statistics','Discrete random variables')
s=s.replace('five reviewed university courses · 82 worked problems','four core university courses and one bounded additional review · 83 worked problems')
start=s.index('lab="""');end=s.index('\nsource=',start)
lab='''<section class="lab"><form id="disc-form"><label>Model<select name="kind"><option value="cdf">CDF from a finite law</option><option value="interval">Four endpoint intervals</option><option value="quantile">Generalized inverse quantile</option><option value="square">Squared-value transformation</option><option value="binomial">Binomial recurrence</option><option value="geometric">First-success waiting</option><option value="poisson">Poisson recurrence</option><option value="hypergeometric">Without-replacement sampling</option></select></label><label>Atom values<input name="values" value="-2,1,4" aria-describedby="disc-limits"></label><label>Corresponding masses<input name="masses" value="0.2,0.5,0.3" aria-describedby="disc-limits"></label><label>n / lower bound / population N<input name="n" value="4" aria-describedby="disc-limits"></label><label>p / quantile level / lambda / sample size<input name="p" value="0.25" aria-describedby="disc-limits"></label><label>Upper bound / marked population K<input name="upper" value="5" aria-describedby="disc-limits"></label><button type="submit">Compute the teaching trace</button></form><p id="disc-error" role="alert"></p><p id="disc-limits">CDF, interval, quantile and square modes use 1–8 atom values and equally long nonnegative mass lists summing to one. Duplicate atom values merge; unnormalized weights are rejected. Interval mode uses the lower and upper bounds. Quantile mode uses a probability level in (0,1]. Binomial uses integer n from 0 to 12 and p in [0,1]. Geometric uses p in (0,1]. Poisson uses lambda in [0,10]. Hypergeometric uses integer population N from 1 to 20, marked count K from 0 to N, and sample size from 0 to N. Named-family modes ignore the value and mass lists after basic input syntax checks. Every infinite-law prefix retains an explicit omitted tail. Invalid input preserves the previous model. Display arithmetic is rounded; the underlying state retains double precision and the audits separately check exact rational fixtures.</p><div id="disc-output"></div></section>'''
s=s[:start]+'lab='+repr(lab)+s[end:]
s=s.replace("replace('<!-- INCLUDE:problems -->',bank)","replace('<!-- INCLUDE: problems -->',bank)").replace("replace('<!-- INCLUDE:review -->'","replace('<!-- INCLUDE: review -->'").replace('<!-- LAB:statistics -->','<!-- LAB: discrete -->').replace("'<!-- SIM:'+k+' -->'","'<!-- SIM: '+k+' -->'")
start=s.index("anchors=[");end=s.index(';it=iter(anchors)',start)
s=s[:start]+"anchors="+repr(['sources','variables','support','pmf','cdf','intervals','quantiles','transformations','dependence','bernoulli','binomial','tails','unequal','hypergeometric','geometric','stopping','poisson','conditioning','convolution','computation','selection','summary','problems','review','laboratory','references'])+s[end:]
# Record model specializations instead of implying a numeric picture proves a symbolic theorem.
s=s.replace("visual=trace(q['modelId']) if q.get('modelId') else ''", "visual=(trace(q['modelId']) if q.get('modelId') else '')+''.join(trace(id) for id in q.get('additionalModelIds',[]))\n if q.get('modelId')=='bin-three-third':visual='<p class=\"visual-scope\">Worked specialization: n = 3 and success probability 1/3. The symbolic argument above applies to all stated n; the diagram does not replace that proof.</p>'+visual")
s=s.replace("s=s.replace(r'\\bigl','').replace(r'\\bigr','')","s=s.replace(r'\\bigl','').replace(r'\\bigr','').replace(r'\\mathbin{\\oplus}',r'\\oplus ')")
(B/'render_s_discrete.py').write_text(s,encoding='utf-8')
print('Prepared renderer and',len(data['models']),'distinct subject-specific models,',sum(len(m['frames']) for m in data['models']),'checkpoints.')
