"""Replace exact operation snippets; fail if a future implementation has drifted."""
from pathlib import Path
p=Path(__file__).parent/'a_sort_lab.js';s=p.read_text(encoding='utf-8')
changes=[
("if(A[j].key<A[m].key)m=j;add(`Scan ${j}; current minimum index ${m}.`);","add(`Compare suffix key at ${j} with minimum at ${m}.`,undefined,{test:[A[j].key,'<',A[m].key],testResult:A[j].key<A[m].key,operation:'compare',reason:'A strict improvement updates the minimum; equality keeps the earlier candidate.',activeLine:1});if(A[j].key<A[m].key)m=j;add(`Scan ${j}; current minimum index ${m}.`);"),
("add(`Compare predecessor ${j-1} with held key.`,rows());","add(`Compare predecessor ${j-1} with held key.`,rows(),{test:[A[j-1].key,'>',x.key],testResult:A[j-1].key>x.key,operation:'compare',reason:'Shift only a strictly larger predecessor. Equality preserves the earlier record order.',activeLine:2});"),
("C++;if(A[j].key>A[j+1].key){swap(j,j+1);moved=true;}","C++;add(`Compare adjacent positions ${j} and ${j+1}.`,undefined,{test:[A[j].key,'>',A[j+1].key],testResult:A[j].key>A[j+1].key,operation:'compare',reason:'Only a strictly inverted adjacent pair is exchanged.',activeLine:1});if(A[j].key>A[j+1].key){swap(j,j+1);moved=true;}"),
("C++;out.push(L[i].key<=R[j].key?L[i++]:R[j++]);W++;", "C++;add('Compare the two current run heads.',rows(),{test:[L[i].key,'≤',R[j].key],testResult:L[i].key<=R[j].key,operation:'compare',reason:'A tie chooses the left run. This is the step that preserves cross-run stability.',activeLine:2});out.push(L[i].key<=R[j].key?L[i++]:R[j++]);W++;"),
("C++;if(A[j].key<pivot){swap(b,j);b++;}","C++;add(`Compare scanned position ${j} with the pivot.`,undefined,{test:[A[j].key,'<',pivot],testResult:A[j].key<pivot,operation:'compare',reason:'A smaller key joins the left region; the pivot stays outside the scan.',activeLine:2});if(A[j].key<pivot){swap(b,j);b++;}"),
("while(i<gt){C++;if(A[i].key<pivot)","while(i<gt){C++;add('Classify the first unknown key.',undefined,{test:[A[i].key,A[i].key<pivot?'<':A[i].key>pivot?'>':'=',pivot],testResult:true,operation:'compare',reason:'A right exchange introduces a new unknown key at the same scan index; inspect it before advancing.',activeLine:2});if(A[i].key<pivot)"),
("C++;snap(`Choose larger child ${j}; compare with parent ${i}.`,end);", "C++;add(`Choose larger child ${j}; compare with parent ${i}.`,[row('Array',A)],{layout:'heap',heapSize:end,test:[A[i].key,'<',A[j].key],testResult:A[i].key<A[j].key,operation:'compare',reason:'Exchange only if the parent is smaller than its larger child.',activeLine:2});"),
("bins[k].push(r);W++;add(`Pass ${t+1}: append ${r.id} to FIFO bucket ${k}.`,rows());", "bins[k].push(r);W++;add(`Pass ${t+1}: append ${r.id} to FIFO bucket ${k}.`,rows(),{distributedId:r.id,bucketIndex:k,operation:'distribute',reason:kind==='radix'?`Shifted key ${r.key-low}; place ${exp}; base ${B}; extracted digit ${k}. Append at the rear to retain earlier tie order.`:'The range selects a bucket; local ordering still needs to be established.',activeLine:kind==='radix'?2:1});")]
for before,after in changes:
 assert s.count(before)==1,(before,s.count(before));s=s.replace(before,after)
before="f.formulaHtml=formula(f.metrics);f.svg=picture(f);frames.push(f);"
after="f.teaching={operation:f.operation||'checkpoint',why:f.reason||caption,guide:teachingGuides[kind]||[],activeLine:f.activeLine||0,regions:[],decision:f.testResult===undefined?'':String(f.testResult),testHtml:f.test?'<math xmlns=\"http://www.w3.org/1998/Math/MathML\"><mrow><mn>'+f.test[0]+'</mn><mo>'+esc(f.test[1])+'</mo><mn>'+f.test[2]+'</mn></mrow></math>':''};f.formulaHtml=formula(f.metrics);f.svg=picture(f);frames.push(f);"
assert s.count(before)==1;s=s.replace(before,after);p.write_text(s,encoding='utf-8')
