from pathlib import Path
R=Path(__file__).resolve().parents[1];p=R/'dist/chapters/g_mux.js';s=p.read_text(encoding='utf-8')
# Priority models now search one declared request at a time rather than reveal a precomputed winner early.
anchor="const reasons={mux:"
before="""if(['priority','rotate'].includes(s.operation)){const order=s.operation==='rotate'?r.order:Array.from({length:2**s.n},(_,j)=>s.order==='low'?j:2**s.n-1-j);const k=r.winner===null?order.length:order.indexOf(r.winner)+1;labels=['Read requests and the declared search order',...order.slice(0,k).map(i=>'Inspect request index '+i+' = '+bit(s.requests,i)),r.winner===null?'Confirm that no request exists':'Encode the resolved winning index'];}const reasons={mux:"""
s=s.replace(anchor,before)
s=s.replace('const p={phase};const visible=',"const p={phase};if(['priority','rotate'].includes(s.operation)){const order=s.operation==='rotate'?r.order:Array.from({length:2**s.n},(_,j)=>s.order==='low'?j:2**s.n-1-j);const count=r.winner===null?order.length:order.indexOf(r.winner)+1;p.scanned=Math.min(phase,count);p.decided=phase>=count;p.encoded=phase===labels.length-1;}const visible=")
s=s.replace("p.phase>1?(i===r.winner?'grant':'blocked'):'pending'", "p.decided?(i===r.winner?'grant':(bit(s.requests,i)?'blocked':'absent')):(j<p.scanned?'absent':'pending')")
s=s.replace("p.phase>1?'valid = '","p.encoded?'valid = '")
s=s.replace("snapshot:{phase,operation:s.operation,inputs:copy(s),result:visible?copy(r):null}", "snapshot:{step:phase+1,inputAddress:!['priority','rotate','bus','cascade'].includes(s.operation)?s.address:'not used',requestWord:['priority','rotate'].includes(s.operation)?bin(s.requests,2**s.n):'not used',selectedIndex:visible?(r.winner??r.address??'none'):'not resolved',output:visible?(r.output??r.code??r.value??r.pattern??'see output vector'):'not evaluated',inputs:copy(s),result:visible?copy(r):null}")
# Add a true gate schematic of the 2:4 enabled decoder.
start=s.index('function decoderDiagram(')
gate=r'''function gateDecoderDiagram(s,r,p){let b=text(30,34,'Enabled 2:4 decoder: shared inversions and four AND minterms')+text(30,72,'Junction dots mark connected buses; unmarked wire crossings are not connections.');const bus=[160,260,360,460,560],values=[bit(s.address,1),1-bit(s.address,1),bit(s.address,0),1-bit(s.address,0),s.enable],names=['a1','¬a1','a0','¬a0','e'];for(let i=0;i<5;i++)b+=text(bus[i]-28,117,names[i]+' = '+values[i],'mx-math')+wire([[bus[i],145],[bus[i],580]],p.phase>0);for(const x of[160,360])b+=wire([[x,145],[x+32,145]])+`<path d="M${x+32},127 L${x+65},145 L${x+32},163 Z" fill="#edf4f7" stroke="#426f82" stroke-width="2"/><circle cx="${x+71}" cy="145" r="6" fill="white" stroke="#426f82" stroke-width="2"/>`+wire([[x+77,145],[x+100,145]]);for(let i=0;i<4;i++){const y=190+i*100,x1=bit(i,1)?160:260,x0=bit(i,0)?360:460;for(const[x,dy]of[[560,13],[x1,36],[x0,59]])b+=wire([[x,y+dy],[650,y+dy]],p.phase>0)+`<circle cx="${x}" cy="${y+dy}" r="3.5" fill="#426f82"/>`;b+=`<path d="M650,${y} L686,${y} A36,36 0 0 1 686,${y+72} L650,${y+72} Z" fill="${p.phase>1&&r.logical[i]?'#d8eee9':'#f5f8fa'}" stroke="#426f82" stroke-width="2"/>`+wire([[722,y+36],[840,y+36]],p.phase>1&&r.logical[i]===1)+text(860,y+42,'D'+i+' = '+(p.phase>1?r.logical[i]:'?'),'mx-math');}b+=text(30,625,'Every gate combines enable with the two literals of one complete address minterm.');return svg(b,660);}
'''
s=s[:start]+gate+s[start:]
s=s.replace("if(['decoder','demux'].includes(s.operation))return decoderDiagram", "if(s.operation==='decoder'&&s.diagram==='gates')return gateDecoderDiagram(s,r,p);if(['decoder','demux'].includes(s.operation))return decoderDiagram")
p.write_text(s,encoding='utf-8')
p=R/'research/build_g_mux.py';b=p.read_text(encoding='utf-8');b=b.replace("specs=[('mux-basic'","specs=[('decoder-gates','Four enabled address minterms at gate level',dict(operation='decoder',n=2,address=2,enable=1,diagram='gates'),'decoder'),('mux-basic'");b=b.replace('16 exact circuit/selection models','17 exact circuit/selection models').replace('animationCount=16','animationCount=17').replace('animationWalkthroughCount=16','animationWalkthroughCount=17');b=b.replace("title='", "title='")
p.write_text(b,encoding='utf-8')
p=R/'research/prepare_g_mux_qa.py';q=p.read_text(encoding='utf-8').replace("players']>16","players']>17");q=q.replace("('priority-high',2,'priority.png')","('priority-high',3,'priority.png')");q=q.replace("report['counts']=js", "report['counts']=js");p.write_text(q,encoding='utf-8')
print('Sequential priority decisions, explicit output readouts, and a genuine enabled decoder gate schematic added.')
