const fs=require('fs'),assert=require('assert');require('../dist/chapters/a_select.js');const M=globalThis.SelectionModels;
const report={selectionQueries:0,partitionStates:0,boundaryQueries:0,twoArrayQueries:0,weightedQueries:0,groupCertificates:0,tournamentQueries:0,storedFrames:0};
function* arrays(n,alphabet){if(!n){yield [];return;}for(const a of arrays(n-1,alphabet))for(const v of alphabet)yield [...a,v];}
function region(f){const s=f.snapshot;if(!s.records||s.lt===undefined)return;const a=s.records.map(r=>r.v),{lo,hi,lt,i,gt,pivot:p}=s;
 // A side-choice frame updates lo/hi but retains the just-completed partition's cursors.
 if(f.teaching.operation.startsWith('Keep only'))return;
 assert(lo<=lt&&lt<=i&&i<=gt&&gt<=hi);
 assert(a.slice(lo,lt).every(x=>x<p));assert(a.slice(lt,i).every(x=>x===p));assert(a.slice(gt,hi).every(x=>x>p));assert(new Set(s.records.map(r=>r.id)).size===s.records.length);report.partitionStates++;
}
for(let n=1;n<=6;n++)for(const a of arrays(n,[0,1,2]))for(let k=1;k<=n;k++){const sorted=[...a].sort((a,b)=>a-b);for(const policy of ['middle','deterministic']){const m=M.quick(a,k,{policy});assert.equal(m.result,sorted[k-1]);m.frames.forEach(region);report.selectionQueries++;}assert.equal(M.det(a,k),sorted[k-1]);}
const sorted=[];for(let n=0;n<=5;n++)for(const a of arrays(n,[0,1,2]))if(a.every((x,j)=>!j||a[j-1]<=x))sorted.push(a);
for(const a of sorted)for(let x=-1;x<=3;x++)for(const upper of [false,true]){const m=M.bound(a,x,upper);let i=a.findIndex(v=>upper?v>x:v>=x);if(i<0)i=a.length;assert.equal(m.result,i);for(const f of m.frames){const s=f.snapshot;assert(0<=s.lo&&s.lo<=s.hi&&s.hi<=a.length);assert(a.slice(0,s.lo).every(v=>upper?v<=x:v<x));assert(a.slice(s.hi).every(v=>upper?v>x:v>=x));}report.boundaryQueries++;}
for(const a of sorted.filter(x=>x.length<=3))for(const b of sorted.filter(x=>x.length<=3))for(let k=1;k<=a.length+b.length;k++){const union=[...a,...b].sort((a,b)=>a-b);assert.equal(M.two(a,b,k).result,union[k-1]);report.twoArrayQueries++;}
for(let n=1;n<=4;n++)for(const a of arrays(n,[0,1,2]))for(const weights of arrays(n,[1,2])){const pairs=a.map((v,j)=>({v,w:weights[j]})).sort((a,b)=>a.v-b.v),total=weights.reduce((a,b)=>a+b),threshold=total/2;let sum=0,expected;for(const r of pairs){sum+=r.w;if(sum>=threshold){expected=r.v;break;}}const m=M.weighted(a,weights);assert.equal(m.result,expected);const l=pairs.filter(r=>r.v<m.result).reduce((s,r)=>s+r.w,0),h=pairs.filter(r=>r.v>m.result).reduce((s,r)=>s+r.w,0);assert(l<=threshold&&h<=threshold);report.weightedQueries++;}
for(let n=1;n<=25;n++){const a=Array.from({length:n},(_,j)=>(j*17+3)%31),m=M.groups(a),med=[];for(let j=0;j<n;j+=5){const g=a.slice(j,j+5).sort((a,b)=>a-b);med.push(g[Math.floor((g.length-1)/2)]);}med.sort((a,b)=>a-b);assert.equal(m.result.pivot,med[Math.floor((med.length-1)/2)]);const bound=Math.max(0,3*(Math.ceil(n/10)-2));assert(m.result.less+m.result.equal>=bound);assert(m.result.greater+m.result.equal>=bound);report.groupCertificates++;}
for(let n=2;n<=10;n++)for(let shift=0;shift<n;shift++){const a=Array.from({length:n},(_,j)=>(j+shift)%n),m=M.tournament(a);assert.equal(m.result.maximum,n-1);assert.equal(m.result.second,n-2);assert.equal(m.result.tournamentComparisons,n-1);assert(m.result.totalComparisons<=n+Math.ceil(Math.log2(n))-2);report.tournamentQueries++;}
const stored=JSON.parse(fs.readFileSync('dist/chapters/a_select-models.json','utf8'));for(const m of stored.models)for(const f of m.frames){assert(f.svg&&f.teaching?.why&&f.teaching.currentState);region(f);report.storedFrames++;}
report.pairedExtremaQueries=0;for(let n=1;n<=6;n++)for(const a of arrays(n,[0,1,2])){const m=M.minmax(a);assert.equal(m.result.minimum,Math.min(...a));assert.equal(m.result.maximum,Math.max(...a));assert.equal(m.result.comparisons,Math.ceil(3*n/2)-2);report.pairedExtremaQueries++;}
fs.writeFileSync('research/a_select-evidence/mathematics.json',JSON.stringify({status:'passed',scope:'Finite exhaustive output checks against sorted or cumulative-mass reference oracles; every three-way state checked against the region invariant. This is not a universal testing guarantee.',...report},null,2)+'\n');console.log(JSON.stringify(report));
