"""Explicit multi-step challenge questions; no randomized question templates."""
DATA={
'd_logic':[
('Count two-sided logical specifications',r'For four Boolean atoms, $G=p\\land q$ and $H=p\\lor r$. How many functions$F(p,q,r,s)$ satisfy both$G\\Rightarrow F$ and$F\\Rightarrow H$ on every row?', ['16','64','256','4096'],'C',r'First check compatibility: every row with$G=1$ has$p=1$ and therefore$H=1$. Among sixteen rows,$G$ is true on four, while$H$ is true on twelve. Thus four outputs are forced1, four forced0, and eight free. The count is$2^8=256$. Free rows are the difference of the two true sets, not the full$H$ set. The otherwise unused atom$s$ doubles each relevant row count and cannot be discarded when counting tables.'),
('Mix row and column constraints',r'On a labeled three-object domain, how many relations satisfy both$\\forall x\\exists yR(x,y)$ and$\\exists y\\forall xR(x,y)$?', ['169','192','343','512'],'A',r'A full column already supplies an outgoing witness in every row, so the second condition implies the first. Count only matrices with at least one full column. Three single-column events each leave six bits free and contribute64; three two-column intersections each leave three bits free and contribute8; the all-column intersection contributes1. Inclusion-exclusion gives$3(64)-3(8)+1=169$. Multiplying counts of the two conditions would incorrectly treat them as independent constraints.'),
],
'd_sets':[
('Two strict inclusions',r'For a four-element universe, how many ordered triples satisfy$A\\subset B\\subset C$?', ['65','81','110','256'],'C',r'For nonstrict chains, each element is in none, only$C$, in$B,C$, or in all three: four choices, hence256 triples. The failure$A=B$ removes one membership state and has$3^4=81$ triples; so does$B=C$. Their intersection has all three sets equal and$2^4=16$ triples. Subtract failures and restore their overlap:256-81-81+16=110. Properness is a global requirement that at least one element occupies each of two distinct difference states.'),
('Nonempty disjoint subsets',r'How many ordered pairs of disjoint nonempty subsets of a five-element universe exist?', ['120','180','211','243'],'B',r'With disjointness, each element lies in neither set, only$A$, or only$B$, so there are$3^5=243$ pairs before nonemptiness. Pairs with$A$ empty number$2^5=32$, and the same is true for$B$. The pair with both empty was subtracted twice and must be restored. Total243-32-32+1=180. Division by two is inappropriate because the pair is ordered.'),
],
'd_proof':[
('A universal prime claim',r'Which$n$ is a counterexample to “$n^2+n+41$ is prime for every integer$n\\ge0$”?', ['0','1','2','40'],'D',r'At$n=40$, the value is1600+40+41=1681=$41^2$, a composite. It satisfies the nonnegative-domain premise and falsifies the conclusion. At0,1,2 the values41,43,47 are prime and do not disprove the claim. The argument needs one verified composite, not a characterization of every earlier input. Recognizing that substituting one less than the constant yields its square constructs the counterexample rather than guessing.'),
('An inequality with domain-sensitive division',r'For real$x>0$, which statement about$x+1/x$ is correct?', ['Its minimum is0.','Its minimum is2, attained only at$x=1$.','It is always strictly greater than2.','It has the same lower bound for all nonzero real$x$.'],'B',r'Compute$x+1/x-2=(x-1)^2/x$. The numerator is nonnegative and the denominator positive, proving the lower bound2. Equality forces$x-1=0$, and$x=1$ is admissible. Strictness fails at that witness. If negative$x$ were admitted, dividing by$x$ would reverse the sign argument and the expression could be negative without this lower bound. The domain and equality case are both part of the conclusion.'),
],
'd_induction':[
('Weighted binomial sum',r'What is$\\sum_{j=0}^{6}j^2\\binom6j$?', ['192','480','672','768'],'C',r'Write$j^2=j(j-1)+j$. A subset with one distinguished member is counted by$n2^{n-1}$; one with two ordered distinct distinguished members is$n(n-1)2^{n-2}$. For$n=6$, these counts are192 and480. Their sum is672. The endpoint$j=0$ contributes zero; the two-member part cannot count the repeated-member case, which is why the additional one-member count is necessary. Pascal induction provides another proof of the two identities.'),
('Two-step recurrence and bases',r'A proof step derives$P(k+2)$ from$P(k)$ for every$k\\ge0$. Which conclusion is justified from only$P(0)$?', ['All$P(n)$ for$n\\ge0$.','Exactly all even-index$P(n)$ are established by this rule.','Exactly all odd-index$P(n)$ are established.','No later index is established.'],'B',r'The dependency edges add2 and preserve parity. Starting0 yields2,4,6 and all later even indices by ordinary induction on half the index. There is no predecessor path to1 or any odd index. To cover all nonnegative integers, also establish$P(1)$ and propagate its odd chain. Strong induction cannot fill the missing base without a separately valid rule; changing the name of the proof method does not change reachability.'),
],
'a_model':[
('Growing arithmetic objects',r'Begin with integer$x=2$ and square it six times exactly. How many bits are needed for the final positive integer?', ['6','32','64','65'],'D',r'After$k$ squarings,$x=2^{2^k}$. At$k=6$, the final value is$2^{64}$, whose unsigned representation needs65 bits because the top bit is position64. Six source-level multiplications do not imply six constant-time word operations on a64-bit machine; the final value already exceeds its unsigned maximum. This separates operation count, operand growth and representability.'),
('Capacity measured in input bits',r'A table allocates$100W$ fixed-size cells for a binary-encoded20-bit positive capacity$W$. What largest cell count is possible?', ['2000','1048575','104857500','104857600'],'C',r'The greatest20-bit value is$2^{20}-1=1048575$. Multiplying by100 gives104857500 cells. The20-bit encoding length does not mean the capacity is20. Using$2^{20}$ instead would choose a value needing21 bits. Allocation is pseudo-polynomial in numeric$W$ and can be exponential in its length even before the cells are initialized.'),
],
'a_asym':[
('Oscillation across growth classes',r'For positive integer$n$, let$f(n)=n^{2+\\sin(\\ln n)}$ and$g(n)=n^2$. Which statement holds?', [r'$f\\in\\Theta(g)$',r'$f\\in O(g)$ but not$\\Omega(g)$',r'$f\\in\\Omega(g)$ but not$O(g)$','Neither big-oh nor big-omega relation holds.'],'D',r'The ratio is$n^{\\sin(\\ln n)}$. Near logarithmic phases$\\pi/2+2k\\pi$, it grows like$n$ and is unbounded. Near$3\\pi/2+2k\\pi$, it behaves like$1/n$ and tends to zero. Integer indices can be chosen by rounding the corresponding exponentials; their logarithmic error tends to zero. Thus no uniform upper constant or positive lower constant works. A ratio lacking a limit does not always cause incomparability, but these two subsequences do.'),
('A floor inside an exponent',r'For$n\\ge1$, what is the relation between$f(n)=2^{\\lfloor\\log_2 n\\rfloor}$ and$n$?', [r'$f\\in\\Theta(n)$, but$f/n$ need not converge.',r'$f\\in o(n)$',r'$f\\in\\omega(n)$',r'$f/n\\to1$'],'A',r'If$2^k\\le n<2^{k+1}$, then$f=2^k$, so$n/2<f\\le n$. These constant bounds establish tight linear growth. At powers of two the ratio is1, while near the top of each interval it tends to1/2. Hence there is no limit1 or any single ratio limit. Rounding the logarithm changes a bounded factor without creating a strict growth relation.'),
],
'a_loop':[
('Three-factor integer region',r'Count body executions over all positive integer triples$(i,j,k)$ satisfying$ijk\\le n$. What is the tight order?', [r'$\\Theta(n\\log n)$',r'$\\Theta(n\\log^2n)$',r'$\\Theta(n^2)$',r'$\\Theta(n^3)$'],'B',r'The exact count is$\\sum_{i=1}^n\\sum_{j=1}^{\\lfloor n/i\\rfloor}\\lfloor n/(ij)\\rfloor$. Dropping floors and enlarging the inner range gives upper bound$nH_n^2=O(n\\log^2n)$. For a lower bound, restrict$i,j$ to at most$n^{1/3}$. Their product is at most$n^{2/3}$, so for sufficiently large$n$ the floor is at least$n/(2ij)$. Summing this restricted square yields a constant times$nH_{\\lfloor n^{1/3}\\rfloor}^2$, matching the upper order. The feasible product region is not a cube of side$n$.'),
('A branch-defined triangular region',r'For$i=1,\\ldots,n$, start$j=1$ and execute the body while$j\\le n$ and$i+j\\le n$, incrementing$j$ each time. What is the exact count?', [r'$n(n+1)/2$',r'$n(n-1)/2$',r'$n^2$',r'$n-1$'],'B',r'For a fixed$i$, admissible$j$ values are1 through$n-i$, giving$n-i$ visits including zero visits at$i=n$. Sum these counts to obtain$(n-1)+\\cdots+1+0=n(n-1)/2$. The inclusive sum constraint still excludes the diagonal case$i=j=n$, and independent-loop multiplication ignores the stopping condition. Evaluating the region directly resolves both tight order and exact endpoints.'),
],
's_axioms':[
('Three-event feasibility',r'Three events each have probability0.5 and every pair intersection has probability0.3. What is the exact feasible interval for triple-intersection probability$t$?', ['[0,0.3]','[0.1,0.3]','[0.2,0.5]','Only0.125.'],'B',r'The triple atom has mass$t$, each pair-only atom has$0.3-t$, each single-only atom has$0.5-0.3-0.3+t=t-0.1$, and the outside atom has$1-1.5+0.9-t=0.4-t$. All eight masses must be nonnegative, yielding$t\\ge0.1$ and$t\\le0.3$. These masses sum to1 and construct a law for every$t$ in that interval, proving sufficiency as well as necessity. The independence guess0.125 does not reproduce the supplied pair masses.'),
('Mixed discrete and continuous mass',r'A law puts probability1/4 exactly at0 and distributes the remaining3/4 uniformly on$[0,1]$. What is$P(X\\le1/2)$?', ['1/4','3/8','1/2','5/8'],'D',r'The point atom at0 belongs to the event and contributes1/4. The continuous component contributes$(3/4)(1/2)=3/8$. Their sum is5/8. The singleton0 has mass1/4 under this mixed law, even though the uniform component assigns it zero. Treating the whole distribution as uniform or forgetting the atom loses the mixture contract.'),
],
's_counting':[
('Lower and upper bounds together',r'How many integer solutions satisfy$x_1+x_2+x_3+x_4=12$ with$1\\le x_i\\le5$?', ['65','80','85','165'],'C',r'Shift$y_i=x_i-1$ to nonnegative variables summing to8 with upper bound4. Unrestricted count is$\\binom{11}3=165$. A violation$y_i\\ge5$ leaves sum3 and count$\\binom63=20$; there are four possible violating variables. Two violations need sum at least10 and are impossible. Thus165-4(20)=85. Applying upper-bound exclusion before accounting for the lower-bound shift can use the wrong forbidden threshold.'),
('Uniform sequences versus multisets',r'Three independent fair binary digits are sampled. What is the probability that the induced multiset contains two zeros and one one?', ['1/4','3/8','1/2','2/3'],'B',r'There are eight equally likely ordered strings. The desired multiset has three realizations:001,010,100, so probability is3/8. The four possible multisets are not uniformly distributed: the all-zero and all-one multisets each have one realization, while the two mixed multisets each have three. Dividing by the number of multisets therefore changes the sampling law.'),
],
'l_vectors':[
('Projection onto a nonorthogonal span',r'Let$u=(1,1,0)$,$w=(1,0,1)$ and$v=(0,1,1)$. What is the Euclidean projection of$v$ onto$\\operatorname{span}(u,w)$?', [r'$(1,1,1)$',r'$(2/3,1/3,1/3)$',r'$(0,1/2,1/2)$',r'$(1/2,1/2,1/2)$'],'B',r'Write the projection$cu+dw$ and impose residual orthogonality to both directions. Dot products give$2c+d=1$ and$c+2d=1$, hence$c=d=1/3$. The projection is$(2/3,1/3,1/3)$. Its residual$(-2/3,2/3,2/3)$ is orthogonal to both$u,w$. Adding separate one-direction projections fails because the directions are not orthogonal; the Gram system accounts for their interaction.'),
('Minimum norm on an affine intersection',r'Among real$(x,y,z)$ satisfying$x+y=1$ and$y+z=1$, what is the minimum squared Euclidean norm?', ['1/3','2/3','1','2'],'B',r'The constraints give$x=z=1-y$. Squared norm is$2(1-y)^2+y^2=3(y-2/3)^2+2/3$. It is minimized uniquely at$y=2/3$, giving$x=z=1/3$ and squared norm2/3. Completing the square proves global optimality without an unproved critical-point argument. The requested quantity is squared norm, so taking an additional square root would answer a different question.'),
],
'l_matrices':[
('Powers of a triangular nilpotent perturbation',r'$A=I+N$ is3 by3, where$N_{12}=N_{23}=1$ and all other entries of$N$ are zero. What is$(A^{10})_{13}$?', ['10','20','45','100'],'C',r'$N^2$ has its only nonzero entry1 at(1,3), and$N^3=0$. Since$I$ commutes with$N$, the binomial expansion terminates: $A^{10}=I+10N+\\binom{10}2N^2$. The requested entry is45. Ordinary entrywise exponentiation would miss the path through the intermediate coordinate. This binomial use is legal because the factors here commute, not because arbitrary matrices do.'),
('Inverse of a triangular block',r'A block matrix has rows of blocks$(I,B)$ and$(0,I)$ with compatible square identity blocks. What is the top-right block of its inverse?', [r'$B$',r'$-B$',r'$B^{-1}$',r'$0$'],'B',r'Multiply the proposed inverse with blocks$(I,-B),(0,I)$ in both orders. The top-right product is$-B+B=0$, while diagonal blocks remain identities. No inverse of$B$ is needed; it may even be singular or rectangular under compatible block sizes. This is the square-zero perturbation identity applied to a block matrix and avoids an unjustified cancellation of$B$.'),
],
'p_types':[
('Complement after integer promotion','Assume8-bit `uint8_t`,32-bit two’s-complement `int` and32-bit `unsigned int`. For `uint8_t x=128; unsigned int y=~x;`, what are$y$ and `(uint8_t)~x`?', ['(127,127)','(4294967167,127)','(4294967167,255)','(128,127)'],'B',r'The narrow unsigned$x$ is promoted to signed `int` because all its values fit. Bitwise complement of128 in that specified representation is$-129$. Assignment to unsigned converts it modulo$2^{32}$, giving4294967167. The separate conversion to8-bit unsigned gives$-129\\bmod256=127$. Complement is performed at the promoted width; applying an8-bit complement first would incorrectly predict$y=127$.'),
('Conditional type changes an unselected value','Assume32-bit `int` and `unsigned int`. For `int a=-1; unsigned int b=1;`, what is the value of `(1 ? a : b) < 0` in C17?', ['0','1','Undefined behavior.','It depends on which branch is selected at runtime.'],'A',r'The conditional operator’s common result type is unsigned because its arithmetic branches have equal-rank signed and unsigned types. The selected value$a$ is converted to unsigned even though the$b$ branch is not evaluated, producing the unsigned maximum. In the comparison, zero is converted to unsigned and the result is false. Short-circuit selection controls evaluation, but it does not remove the unselected branch from type determination.'),
],
'p_flow':[
('Continue and break priorities','Compute final$(s,i)$ for `int s=0,i; for(i=1;i<=10;i++){if(i%3==0)continue; if(i==8)break; s+=i;}`.', ['(19,8)','(27,9)','(19,9)','(55,11)'],'A','Indices3 and6 are skipped by continue. Indices1,2,4,5,7 add to19. At8, the continue condition is false, then break exits before adding8 and before the for update, so final$i$ remains8. Values9 and10 are never reached. Reversing the order of tests or moving the addition changes the state trace; exact execution checkpoints decide both components.'),
('Reach a target in an unsigned orbit',r'An8-bit unsigned variable starts at0 and repeatedly adds6 modulo256. What is the first positive update count at which it reaches64?', ['32','64','96','128'],'C',r'Solve$6t\\equiv64\\pmod{256}$. Divide by the gcd2 to obtain$3t\\equiv32\\pmod{128}$. The inverse of3 modulo128 is43, so$t\\equiv1376\\equiv96\\pmod{128}$. This residue is the least positive solution. The orbit period is128, while32 and64 updates give residues192 and128. A target test can terminate even though the counter does not increase monotonically.'),
],
'g_number':[
('A fixed-point multiplication with rounding',r'A signed8-bit two’s-complement fixed-point format has two fractional bits. Raw inputs are$-6$ and5. Multiply their values and round the stored result to nearest, ties to even. What real value is stored?', ['-1.75','-1.875','-2.0','-7.5'],'C',r'The inputs mean$-6/4=-1.5$ and$5/4=1.25$, whose exact product is$-1.875$. At the target scale4, the desired raw result is$-7.5$. It is halfway between$-7$ and$-8$; ties-to-even selects$-8$, yielding$-2.0$. The exact product is not representable at quarter-unit spacing. Truncation toward zero would yield$-1.75$, a different rounding rule.'),
('Nearest-even binary quantization',r'Quantize1.625 to an unsigned fixed-point format with two fractional bits, nearest-even rounding and enough integer range. What is the result?', ['1.25','1.5','1.625','1.75'],'B',r'Scale by4 to get raw target6.5, halfway between6 and7. The even raw integer is6, so the stored value is6/4=1.5. Rounding ties upward would choose1.75 instead. The tie rule applies to the retained integer significand or raw field, not to the parity of the decimal printed value.'),
],
'g_boolean':[
('Count monotone three-input functions',r'How many Boolean functions of three inputs are nondecreasing in every input?', ['8','16','20','256'],'C',r'A monotone function is determined by the antichain of its minimal true subsets in the three-element subset lattice. Count antichains: one empty antichain, eight single-member choices, nine incomparable pairs, and two incomparable triples. The pairs consist of three pairs of singletons, three pairs of two-element sets, and three singleton/complement-pair choices. The triples are all three singletons or all three two-element sets. Total1+8+9+2=20; no larger antichain exists. The empty and bottom-containing cases include both constant functions.'),
('Self-dual care constraints',r'A self-dual function on three inputs has$F(000)=0$ and$F(111)=1$ fixed. No other rows are specified. How many completions exist?', ['4','8','16','64'],'B',r'The eight rows form four complement pairs. The given values constrain the same pair consistently, leaving three independent pairs. Choose one bit in each remaining pair and force its complement in the partner row, giving$2^3=8$. Treating the two given rows as two independent pair constraints would give4; treating all six remaining rows as independent ignores self-duality.'),
],
'g_gates':[
('A quantified static hazard window',r'$F=ab\\lor\\neg a c$ has$b=c=1$ and$a$ falls at0ns. The$ab$ output falls at2ns and$\\neg a c$ rises at5ns. An OR with equal1ns transport delay follows them. What is its low-pulse width?', ['1ns','2ns','3ns','4ns'],'C',r'The OR inputs are both zero from2ns to5ns, a three-nanosecond interval. Equal transport delay shifts the falling output event to3ns and the rising event to6ns without changing pulse width. A steady-state truth table predicts output1 before and after but misses the transient. An inertial model rejecting pulses shorter than4ns could suppress it, which is a different stated timing model.'),
('Noise-margin bottleneck',r'A driver guarantees$V_{OL}\\le0.2$V and$V_{OH}\\ge2.4$V. A receiver accepts lows through0.7V and highs from2.0V. What is the smaller guaranteed noise margin?', ['0.2V','0.4V','0.5V','0.7V'],'B',r'Low margin is$0.7-0.2=0.5$V and high margin is$2.4-2.0=0.4$V. The smaller is0.4V. The driver output bounds and receiver thresholds have different roles; subtracting two driver levels would not give either noise margin. Both margins are positive, so the idealized voltage-level compatibility check passes.'),
],
'd_relations':[
('Divisor-poset cover count',r'The divisor lattice of$72=2^3 3^2$ is represented by a Hasse diagram. How many vertices and cover edges does it have?', ['(12,17)','(12,24)','(6,17)','(12,29)'],'A',r'Vertices correspond to exponent pairs$0\\le i\\le3$, $0\\le j\\le2$, giving4 times3=12. Covers increment exactly one exponent by1. There are3 horizontal increments in each of three rows, giving9, and2 vertical increments in each of four columns, giving8. Total17. Counting all comparable pairs would include transitive edges omitted from a Hasse diagram.'),
('Height of a product order',r'In the same divisor lattice, what is the longest-chain length measured in vertices?', ['3','4','5','6'],'D',r'The exponent rank$i+j$ starts at0 and ends at5. Every strict cover raises it by1, so a chain can have at most six vertices. The chain1,2,4,8,24,72 attains that bound. Width instead concerns incomparable sets and is not this serial depth. Measuring edges would give5 rather than the requested vertex count.'),
],
'd_functions':[
('All idempotent maps on four points',r'How many functions on a four-element labeled set satisfy$f\\circ f=f$?', ['24','36','41','64'],'C',r'Classify by nonempty image size$r$. Image points must be fixed, and each other point may map to any image point. Counts are$\\binom4r r^{4-r}$. For$r=1,2,3,4$ they are4,24,12,1, totaling41. A nonempty domain cannot have empty image. All functions number256, while permutations satisfying this idempotent condition include only the identity.'),
('Count split inverse pairs',r'$A$ has two labeled elements and$B$ has three. How many ordered function pairs$f:A\\to B,g:B\\to A$ satisfy$g\\circ f=\\mathrm{id}_A$?', ['6','8','12','18'],'C',r'The identity composite forces$f$ injective, giving3 times2=6 choices. For each chosen$f$, the values of$g$ on its two image points are forced. The remaining point of$B$ may map to either of the two$A$ values, giving two choices. Total12. This counts the pair jointly; selecting arbitrary$f,g$ independently would include pairs violating the identity.'),
],
'd_invariants':[
('Count a specific iterative powering trace',r'An iterative power algorithm starts$y=1,b=a,e=13$. While$e>0$, multiply$y$ by$b$ if$e$ is odd, then always square$b$, then set$e=\\lfloor e/2\\rfloor$. How many multiplications execute?', ['5','6','7','8'],'C',r'The exponent states are13,6,3,1, four iterations. Every iteration squares$b$, contributing four multiplications. Odd states13,3,1 also multiply$y$, adding three. Total7. The last square is executed even though its result is unused after$e$ becomes0. A recursive algorithm stopping at exponent1 can perform only5 multiplications; exact counts depend on the specified control flow, not just the shared mathematical method.'),
('A modular linear invariant',r'States are pairs modulo5. The only move adds$(1,2)$ to a pair. Starting$(0,0)$, which target is unreachable?', ['(1,2)','(2,4)','(3,4)','(4,3)'],'C',r'The quantity$2x-y$ modulo5 is invariant because a move changes it by$2-2=0$. The first, second and fourth targets give residue0, and they occur after1,2,4 moves. For(3,4), the residue is2, so it is excluded. Here the reachable orbit has five states and the explicit move construction verifies sufficiency for the other listed targets; invariant agreement alone would not prove sufficiency in a more general system.'),
],
'd_number':[
('Congruence solutions in an interval',r'How many integers$0\\le x\\le100$ solve$6x\\equiv8\\pmod{14}$?', ['7','13','14','15'],'C',r'Reduce the congruence to$x\\equiv6\\pmod7$. The interval solutions are$x=6+7t$ with integer$t\\ge0$ and$t\\le\\lfloor(100-6)/7\\rfloor=13$. Thus there are14 values. The two-residues-per14 statement is compatible but does not by itself count a partially filled final interval. Apply floor endpoints after finding the reduced progression.'),
('Compatible shared-modulus reconstruction',r'What is the least nonnegative$x$ satisfying$x\\equiv5\\pmod{12}$ and$x\\equiv11\\pmod{18}$?', ['11','17','29','35'],'C',r'The gcd6 compatibility test passes because5 and11 have equal residues modulo6. Put$x=5+12t$; then$12t\\equiv6\\pmod{18}$. Divide6 to get$2t\\equiv1\\pmod3$, so$t\\equiv2\\pmod3$. Therefore$x\\equiv29\\pmod{36}$ and29 is the least nonnegative solution. The lcm36, not product216, is the fundamental period.'),
],
'a_recurrence':[
('A slowly shrinking argument',r'For integer$n>1$, $T(n)=T(n-\\lceil\\sqrt n\\rceil)+1$, with constant base cost for$n\\le1$. What is its tight order?', [r'$\\Theta(\\log n)$',r'$\\Theta(\\sqrt n)$',r'$\\Theta(n)$',r'$\\Theta(n\\log n)$'],'B',r'Each step removes order$\\sqrt n$ items, and the potential$\\sqrt n$ decreases by a positive constant order: rationalize $\\sqrt n-\\sqrt{n-\\lceil\\sqrt n\\rceil}$ as the decrement divided by the sum of roots. Away from the fixed small cutoff this difference is bounded above and below by constants. Hence order$\\sqrt n$ steps are necessary and sufficient. The final small states add only a constant. Neither subtract-one unrolling nor equal-fraction master cases model this shrink rule.'),
('Work with a repeated state',r'A program recursively calls the identical size-$n/2$ subproblem twice, then does$n$ work. If the second call reuses the first result instead of recomputing, what is the resulting work order?', [r'$\\Theta(\\log n)$',r'$\\Theta(n)$',r'$\\Theta(n\\log n)$',r'$\\Theta(n^2)$'],'B',r'Without reuse the execution tree follows$2T(n/2)+n$ and costs$n\\log n$. With one actual child computation per size, the recurrence is$T(n/2)+n$ and its tolls form$n+n/2+n/4+\\cdots=\\Theta(n)$. The specification requires identical subproblems and reusable results; equal sizes alone do not prove that the child instances are identical.'),
],
'a_divide':[
('A finite-field Fourier evaluation',r'Work modulo17 with length-four root$\\omega=4$. For$a=[1,2,0,0]$ and forward positive exponents, what is$Y$?', ['[3,9,16,10]','[3,10,16,9]','[1,2,0,0]','[3,8,15,9]'],'A',r'Powers of4 modulo17 are1,4,16,13; the square is$-1$ and the fourth power is1, so its order is4. Each evaluation is$1+2\\omega^k$, producing3,9,33 modulo17=16, and27 modulo17=10. Reversing the exponent sign exchanges the second and fourth values. The inverse normalization uses$4^{-1}=13$ modulo17, not real division by4.'),
('Exact modular recovery range',r'An integer coefficient is known only to lie in$[-10,10]$, and its residue modulo17 is7. Is its exact value uniquely determined?', ['Yes, it must be7.','Yes, it must be-10.','No, both7 and-10 fit.','No value in the range fits.'],'C',r'Values7 and$7-17=-10$ share the residue and both lie in the allowed interval. Unique centered recovery needs a modulus greater than the full coefficient-range width20, or additional information excluding one candidate. Exact modular arithmetic prevents rounding error but does not by itself prevent integer aliasing. More CRT moduli can enlarge the combined modulus enough to distinguish the possibilities.'),
]
}

if __name__=='__main__':
 import re
 from pathlib import Path
 for t,qs in DATA.items():
  p=Path(__file__).with_name(t+'.md');s=p.read_text(encoding='utf-8')
  before,after=s.split('## Applicable formulas and examination notes',1)
  before=before.split('<!-- CHALLENGE-BANK -->')[0].rstrip()+'\n\n'
  n=len(re.findall(r'^### (?:Question|Problem) \d+',before,re.M))
  before+='<!-- CHALLENGE-BANK -->\n\n'
  for i,(title,prompt,options,answer,solution) in enumerate(qs,n+1):
   # JSON-style double backslashes in this explicit data become single TeX commands.
   clean=lambda v:v.replace('\\\\','\\')
   before+=f'### Question {i}. Challenge: {title}\n\n'+clean(prompt)+'\n\n'
   before+='\n\n'.join('**'+a+'.** '+clean(v) for a,v in zip('ABCD',options))
   before+='\n\n**Answer: '+answer+'.**\n\n'+clean(solution)+'\n\n'
  p.write_text((before+'## Applicable formulas and examination notes'+after).rstrip()+'\n',encoding='utf-8')
 print('Added 44 multi-step challenge questions across 22 chapters.')
