from author import chapter
chapter('d_sets',r'''
### Solve a cardinality question by recovering disjoint atoms

For two finite sets, the disjoint pieces are the intersection, the part only in the first set, the part only in the second, and the outside. If their sizes are respectively $t,a-t,b-t,N-a-b+t$, every one must be nonnegative. Thus a proposed intersection must satisfy $\max(0,a+b-N)\le t\le\min(a,b)$. This feasibility check comes before substitution into a formula.

For three sets, start with the triple intersection, subtract it from the pair intersections, and only then obtain the single-only regions. A pair intersection includes the triple intersection unless explicitly stated otherwise. The union is

$$|A\cup B\cup C|=|A|+|B|+|C|-|A\cap B|-|A\cap C|-|B\cap C|+|A\cap B\cap C|.$$

Exactly one membership has size the sum of singleton sizes minus twice the sum of pair intersections plus three times the triple intersection. Exactly two memberships has size the sum of pair intersections minus three times the triple intersection. These coefficients follow by charging an object that occurs in one, two or three sets; they are not independent formulas to memorize without a region model.

### Count sets of sets by translating the constraint

If $A\subseteq S\subseteq B$ and $A\subseteq B$, each element of $B\setminus A$ is independently optional: there are $2^{|B|-|A|}$ choices. A size restriction $|S|=k$ instead gives $\binom{|B|-|A|}{k-|A|}$. If the premise $A\subseteq B$ fails, the answer is zero; negative exponents cannot repair an inconsistent constraint.

For a fixed ordered pair $(A,B)$ of subsets of an $n$-element universe, each element has four membership states. A local rule eliminates forbidden states: $A\subseteq B$ leaves three, $A\cap B=\varnothing$ leaves three, and both together leave two. A rule requiring at least one element in a particular state needs subtraction of the configurations avoiding that state. Thus a proper inclusion has $3^n-2^n$ pairs, not $3^n-1$.

### Algebraic identities are truth-table identities

Set $a=[x\in A]$, $b=[x\in B]$, $c=[x\in C]$. Union, intersection, complement and symmetric difference become OR, AND, NOT and XOR. Equality of sets means equality on all admissible membership patterns. An implication between containments restricts which patterns are admissible; cancellation of a common union or intersection is generally invalid. A single legal pattern falsifying an identity is sufficient.
''',[
('Three overlapping groups',r'In a universe of 100 objects, $|A|=50$, $|B|=45$, $|C|=40$, pair intersections are 20, 18 and 15, and the triple intersection is 8. How many objects belong to exactly one set?', ['40','45','53','61'],'C',r'The sum of singleton counts is 135 and the sum of pair intersections is 53. Exactly-one membership therefore counts $135-2(53)+3(8)=53$. Alternatively the exclusive regions are $50-20-18+8=20$, $45-20-15+8=18$ and $40-18-15+8=15$; their sum is 53. The union is 90 and exactly-two membership is 29, so $53+29+8=90$ checks the partition. The choices 40, 45 and 61 do not satisfy these disjoint-region equations.'),
('Exactly two memberships','Use the data in Question 1. How many objects belong to exactly two sets?', ['21','29','37','53'],'B',r'The pair-only regions are $20-8=12$, $18-8=10$ and $15-8=7$. Their sum is 29. Summing the inclusive pair intersections produces 53 and counts each triple member three times; subtracting the triple count only once produces 45, also wrong. Exactly-two means three disjoint pair-only regions, not the union of inclusive intersections.'),
('Choose an intermediate set',r'$A\subseteq B$, $|A|=3$, $|B|=8$. How many $S$ satisfy $A\subseteq S\subseteq B$ and $|S|=5$?', ['10','20','32','56'],'A',r'The three compulsory elements are already in $A$. Select exactly two of the five elements in $B\setminus A$, giving $\binom52=10$. The answer 32 counts all intermediate sizes. The answer 56 chooses five elements from eight without making the three elements of $A$ compulsory. Ordered selection of the optional two would overcount each resulting set twice.'),
('Strict inclusion pairs',r'How many ordered pairs of subsets $(A,B)$ of a four-element labeled universe satisfy $A\subset B$?', ['65','80','81','256'],'A',r'For nonstrict inclusion each element is in neither set, only $B$, or both; hence $3^4=81$. Equality allows only neither or both, giving $2^4=16$. Subtract all equal pairs, not just the empty pair: $81-16=65$. The unrestricted pair count 256 allows the forbidden only-$A$ state. Strict inclusion does not mean that either individual set is nonempty.'),
('Disjoint pairs covering everything',r'For an $n$-element universe $U$, how many ordered pairs satisfy $A\cap B=\varnothing$ and $A\cup B=U$?', [r'$2^n$',r'$3^n$',r'$4^n$',r'$2^{n-1}$'],'A',r'Every element must belong to exactly one of $A$ and $B$. Its two independent choices give $2^n$. The three-choice formula allows an element in neither and fails the coverage rule. Dividing by two would forget that the pair is ordered; exchanging the two sets generally changes the counted object. For the empty universe the one pair $(\varnothing,\varnothing)$ confirms the formula.'),
('Power-set intersection',r'If $|A|=5$, $|B|=6$ and $|A\cap B|=3$, what is $|\mathcal P(A)\cap\mathcal P(B)|$?', ['3','8','32','64'],'B',r'A set belongs to both power sets exactly when it is a subset of both underlying sets, equivalently a subset of $A\cap B$. There are $2^3=8$ such sets. The number 3 counts shared elements, not shared subsets; 32 and 64 count the full power sets. The empty subset is one of the eight and must not be excluded.'),
('Nested empty objects',r'What is $|\mathcal P(\mathcal P(\varnothing))|$?', ['0','1','2','4'],'C',r'The empty set has no elements. Its power set is the singleton whose only element is the empty set. Taking a power set again produces exactly the empty subset and that singleton itself, so the size is $2^1=2$. The distinction between zero elements and one element that happens to be empty controls both stages.'),
('A conditional cancellation',r'Which hypothesis guarantees that $A\cup C=B\cup C$ implies $A=B$?', [r'$A\subseteq C$',r'$A\cap C=B\cap C=\varnothing$',r'$C\ne\varnothing$',r'$A\cap B=\varnothing$'],'B',r'Outside $C$, union equality already forces equal membership in $A$ and $B$. Under the disjointness hypothesis neither set has members inside $C$, so their membership agrees everywhere. If $A\subseteq C$, different subsets of $C$ have the same union with $C$. Nonemptiness is irrelevant; even disjoint $A$ and $B$ can be hidden inside $C$. Cancellation is justified by recovering the hidden region, not by ordinary arithmetic.'),
('Symmetric-difference size',r'$|A|=17$, $|B|=12$ and $|A\cup B|=22$. Find $|A\oplus B|$, where $\oplus$ denotes symmetric difference.', ['5','15','22','29'],'B',r'Inclusion-exclusion first gives $|A\cap B|=17+12-22=7$. Symmetric difference discards the intersection from both sets: $17+12-2(7)=15$. The answer 5 is a difference of sizes and loses overlap information. The answer 22 is the union, which still contains the seven shared elements. The answer 29 counts each shared element twice.'),
('Product difference',r'Which identity holds for arbitrary sets $A,B,C,D$?', [r'$(A\times B)\setminus(C\times D)=(A\setminus C)\times(B\setminus D)$',r'$(A\times B)\setminus(C\times D)=((A\setminus C)\times B)\cup(A\times(B\setminus D))$',r'$\mathcal P(A\cup B)=\mathcal P(A)\cup\mathcal P(B)$',r'$A\setminus(B\cup C)=(A\setminus B)\cup(A\setminus C)$'],'B',r'An ordered pair is excluded from $C\times D$ when its first coordinate is outside $C$ OR its second is outside $D$. Intersect that condition with membership in $A\times B$ to obtain option B. Option A requires both failures and loses pairs with only one failing coordinate. A subset can mix elements from $A$ and $B$, refuting C. De Morgan changes the union in option D to an intersection.'),
],[(
'Intersection feasibility',r'For sizes $a,b$ in a universe of size $N$, require $\max(0,a+b-N)\le t\le\min(a,b)$ before using $t=|A\cap B|$. For $a=8,b=7,N=10$, the intersection is at least 5; a proposed value 4 makes the outside region negative. Bounds on an intersection are simultaneous constraints.'),
('Exactly-one versus exactly-two',r'For three sets with pair-sum $s_2$ and triple size $t$, exactly-one is $s_1-2s_2+3t$ and exactly-two is $s_2-3t$. An element in all three contributes three to each sum of pairs. If a question supplies pair-only counts instead, do not subtract the triple again.'),
('Union and outside',r'Compute the union by inclusion-exclusion and subtract it from the specified universe for “none.” For Question 1, the union is 90 and none is 10. Summing complements independently counts the same outside object repeatedly; the complement of a union is an intersection of complements.'),
('Optional elements',r'$A\subseteq S\subseteq B$ gives $2^{|B|-|A|}$ only if $A\subseteq B$. A required size $k$ changes it to $\binom{|B|-|A|}{k-|A|}$. Interpret an out-of-range binomial choice as zero. Compulsory elements must be removed before selecting optional ones.'),
('Local membership states',r'Ordered subset pairs use four states per element. Inclusion or disjointness removes one state and gives $3^n$; coverage together with disjointness leaves two and gives $2^n$. Proper inclusion subtracts $2^n$ equal pairs from $3^n$. Pair order is part of the sample object.'),
('Power-set operators',r'$\mathcal P(A)\cap\mathcal P(B)=\mathcal P(A\cap B)$ because a subset must satisfy both containments. The union counterpart fails for mixed subsets. With $A=\{1\},B=\{2\}$, the subset $\{1,2\}$ exposes that failure.'),
('Nested size growth',r'If $|A|=n$, then $|\mathcal P(A)|=2^n$ and $|\mathcal P(\mathcal P(A))|=2^{2^n}$. Distinguish membership from inclusion: $\varnothing\subseteq A$ always, but $\varnothing\in A$ requires an empty object actually listed as an element.'),
('Symmetric difference',r'$|A\oplus B|=|A|+|B|-2|A\cap B|$. For multiple sets, membership means an odd number of occurrences. Associativity follows from parity, while union is not parity. Two identical copies cancel under symmetric difference and do not cancel under union.'),
('Products and empty factors',r'$|A\times B|=|A||B|$ for finite sets. A product is empty if either factor is empty; therefore equality of products does not let you cancel an arbitrary empty factor. Coordinate order remains significant even when the cardinalities agree.'),
('A counterexample is a membership pattern',r'To refute $A\setminus(B\cup C)=(A\setminus B)\cup(A\setminus C)$, choose an element in $A\cap B$ but outside $C$. It belongs to the right side and not the left. This one pattern is a complete disproof and identifies the correct intersection replacement.'),
])
chapter('d_proof',r'''
### Convert a claim into the exact proof obligation

An implication fails only when its premise is true and conclusion false. Consequently, a proposed counterexample must satisfy the premise; an object that violates the premise proves nothing. The contrapositive of $P\Rightarrow Q$ is $\neg Q\Rightarrow\neg P$. For a compound antecedent $P\land R$, the negative is $\neg P\lor\neg R$, not a conjunction. A biconditional requires two independently justified implications.

Existence means producing an admissible witness. Uniqueness means comparing any two possible witnesses and proving equality. For $ax=b$ over the reals, a unique solution requires $a\ne0$; if $a=0$, the equation has all real solutions when $b=0$ and none otherwise. Dividing by $a$ before splitting these cases silently assumes precisely the fact to be tested.

### Let algebra expose the equality and domain conditions

For real $x,y$, $(x-y)^2\ge0$ gives $x^2+y^2\ge2xy$, with equality exactly when $x=y$. Squaring a comparison is reversible only after sign conditions make the square function monotone on the permitted interval. The statement $x^2>y^2\Rightarrow x>y$ is false: $x=-3,y=2$ refutes it. Cancellation of a zero factor is another lost branch: from $x(x-1)=0$, either factor may vanish.

Integer proofs often reduce a quantified assertion to a finite remainder table. Every integer, including negative integers, has exactly one remainder in $\{0,1,\ldots,m-1\}$ under Euclidean division by positive $m$. A residue argument is exhaustive only when all these classes are handled. Observing many positive examples is not a proof over all integers.
''',[
('Negate the whole implication',r'Which statement is the contrapositive of “If $x>0$ and $y>0$, then $xy>0$”?', [r'If $xy\le0$, then $x\le0$ and $y\le0$.',r'If $xy\le0$, then $x\le0$ or $y\le0$.',r'If $xy>0$, then $x>0$ and $y>0$.',r'If $x\le0$ or $y\le0$, then $xy\le0$.'],'B',r'Negate the conclusion to obtain $xy\le0$. Negate the whole antecedent using De Morgan: $\neg(x>0\land y>0)$ is $x\le0\lor y\le0$. This produces B. Option A is stronger and false when $x=-1,y=1$. Options C and D are converse and inverse, respectively, and both fail for two negative inputs. Equivalence applies to the full grouped antecedent.'),
('Valid counterexample',r'Which pair disproves “For all real $x,y$, if $x^2>y^2$ then $x>y$”?', [r'$(1,2)$',r'$(3,2)$',r'$(-3,2)$',r'$(2,2)$'],'C',r'For $x=-3,y=2$, the premise is $9>4$ and the conclusion is $-3>2$, which is false. Option A has a false premise, B satisfies the implication, and D also has a false premise. A counterexample must hit the one failing truth row; it is not enough for the conclusion alone to fail.'),
('A residue proof',r'For integer $n$, which condition is equivalent to $3\mid(n^2-1)$?', [r'$3\mid n$',r'$3\nmid n$',r'$n$ is odd',r'$n>0$'],'B',r'The three residues of $n$ modulo 3 are 0,1,2. Their squares are 0,1,1, so $n^2-1$ has residue 2,0,0. Exactly the nonmultiples of 3 satisfy the divisibility claim. This proof handles negative integers too. Oddness and positivity are unrelated to the residue condition; for example 2 satisfies it and 3 does not.'),
('Existence and uniqueness parameter',r'Over the real numbers, for which parameters $a$ does $ax=1$ have exactly one solution?', [r'All real $a$',r'$a=0$',r'$a\ne0$',r'$a>0$ only'],'C',r'If $a\ne0$, the witness $x=1/a$ satisfies the equation. If two solutions $x,y$ exist, $a(x-y)=0$ and nonzero $a$ implies $x=y$. If $a=0$, the equation becomes $0=1$ and has no solution. Negative nonzero values are just as valid as positive ones; D unnecessarily restricts the parameter.'),
('A rationality implication',r'For real numbers $a,b$, which assertion is always true?', ['The sum of two irrational numbers is irrational.','The product of two irrational numbers is irrational.','A nonzero rational times an irrational is irrational.','A rational divided by an irrational is always irrational.'],'C',r'Let $r$ be nonzero rational and $u$ irrational. If $ru$ were rational, division by the nonzero rational $r$ would make $u$ rational, a contradiction. The nonzero condition is essential. Two irrationals can sum to zero or multiply to an integer. Option D fails when its rational numerator is zero. Rationality closure must be paired with legal division.'),
('Equality case of an inequality',r'For real $x,y$, when does $x^2+y^2=2xy$ hold?', [r'$x=-y$',r'$x=y$',r'$xy=0$',r'$x,y\ge0$'],'B',r'Transfer all terms to one side: $x^2-2xy+y^2=(x-y)^2=0$. A real square is zero exactly when its base is zero, giving $x=y$. Equal negative values work too. Opposite values work only at zero, and nonnegativity alone does not force equality. The equality condition comes from the precise nonnegative term used in the proof.'),
('Cancellation with a lost case',r'A purported proof cancels $x$ in $x^2=x$ and concludes $x=1$. Which set is the actual real solution set?', [r'$\{1\}$',r'$\{0\}$',r'$\{0,1\}$',r'$\mathbb R$'],'C',r'Rearrange without division: $x^2-x=x(x-1)=0$. The real zero-product property gives $x=0$ or $x=1$. Both substitute correctly into the original equation. Cancellation was legal only on the branch $x\ne0$ and omitted the other branch. D mistakes a particular equation for an identity.'),
('Construct a witness after the input',r'For every real $x$, there exists real $y$ such that $x+y=0$. Which witness construction proves the claim?', [r'$y=0$ for every $x$',r'$y=-x$',r'$x=0$ for every $y$',r'A single fixed $y$ chosen before $x$'],'B',r'Given an arbitrary $x$, choose $y=-x$; then $x+y=0$ by additive inverses. The witness is allowed to depend on the universally chosen input because the existential quantifier follows it. A fixed $y$ cannot work for both $x=0$ and $x=1$. Changing which variable is arbitrary changes the claim rather than proving it.'),
('Prime construction trap',r'For $N=p_1p_2\cdots p_k+1$, where the $p_i$ are positive primes, which conclusion always follows?', [r'$N$ is prime.',r'No prime divisor of $N$ equals any $p_i$.',r'$N$ is smaller than every $p_i$.',r'$N$ has no prime divisor.'],'B',r'Each $p_i$ divides the product, so $N$ has remainder 1 on division by $p_i$. Thus none divides $N$. Since $N>1$, some prime divisor exists, but $N$ itself need not be prime; $2\cdot3\cdot5\cdot7\cdot11\cdot13+1=30031=59\cdot509$. The proof needs a new prime divisor, not the false assertion that the constructed integer is always prime.'),
('Exactly one means two obligations',r'A proof of “there exists exactly one $x$ with $P(x)$” establishes only that $P(a)$ is true. What is missing?', ['A second witness distinct from the first.',r'A proof that every $x$ satisfying $P(x)$ equals $a$.',r'A proof that every $x$ fails $P(x)$.','No further argument.'],'B',r'The verified witness supplies existence. Uniqueness still requires taking any arbitrary satisfying $x$ and deducing $x=a$. Producing another distinct witness would refute uniqueness rather than establish it. A proof that every input fails contradicts existence. Keeping the arbitrary candidate separate from the constructed witness prevents circular uniqueness arguments.'),
],[(
'Implication failure',r'A counterexample to $P\Rightarrow Q$ must satisfy $P\land\neg Q$. For $x^2>y^2\Rightarrow x>y$, use $(-3,2)$, not $(1,2)$. A false premise makes the implication true and cannot be used to reject it.'),
('Contrapositive grouping',r'For $(P\land R)\Rightarrow Q$, start from $\neg Q$ and target $\neg P\lor\neg R$. For $(P\lor R)\Rightarrow Q$, target $\neg P\land\neg R$. Negate the grouped expression before choosing a proof tactic.'),
('Biconditional obligations',r'To prove $P\Leftrightarrow Q$, prove $P\Rightarrow Q$ and $Q\Rightarrow P$. Showing two examples where both are true establishes neither universal direction. A divisibility equivalence can often be tested and proved by an exhaustive residue table.'),
('Zero-factor branch',r'Before dividing by a variable expression $g(x)$, split $g(x)=0$ and $g(x)\ne0$. In $x^2=x$, the zero branch is a real solution. Cancellation can simplify a branch but cannot erase it from the answer set.'),
('Squaring a comparison',r'Squaring preserves order for nonnegative operands. Without that premise, $-3<2$ yet $9>4$. Solve or prove a squared inequality by tracking signs or by factoring, rather than assuming the squaring step is reversible.'),
('Equality from the proof',r'In $x^2+y^2\ge2xy$, equality holds precisely when $(x-y)^2=0$. The source of nonnegativity identifies the equality condition. For a sum of nonnegative terms, equality requires every term to vanish, not only their product.'),
('Unique linear witness',r'For $ax=b$, nonzero $a$ yields exactly one real solution. If $a=0$, $b=0$ yields all reals and $b\ne0$ yields none. Parameter questions demand this split before substitution of $b/a$.'),
('Rational closure conditions',r'If $r\ne0$ is rational and $u$ irrational, $ru$ is irrational because a rational result would imply $u=(ru)/r$ rational. Remove the nonzero condition and the proof fails at $r=0$. Sums or products of two irrational numbers have no automatic irrationality guarantee.'),
('Euclidean residues include negatives',r'For modulus 3, every integer has remainder 0,1 or2. Hence $3\mid n^2-1$ exactly when the remainder is 1 or2. A residue proof does not need separate positive and negative cases once the division convention is specified.'),
('Constructed integer versus prime divisor',r'For a product of listed primes plus one, prove that none of the listed primes divides it. The constructed integer can be composite. Extract a prime divisor to contradict completeness of the list; primality of the whole integer is unnecessary and generally false.'),
])
chapter('d_induction',r'''
### Recognize the increment, not only the final closed form

For a sum $S_n=\sum_{j=1}^n f(j)$, the induction step is $S_{k+1}=S_k+f(k+1)$. To test a proposed closed form $F(n)$, compute $F(k+1)-F(k)$ and compare it with $f(k+1)$; also check the first allowed index. The increment and the base together determine the whole sequence. A formula may pass the increment test and still have the wrong additive constant.

For example, $F(n)=n(n+1)(2n+1)/6$ has difference $(n+1)^2$ and $F(0)=0$, proving the sum-of-squares identity. Weighted geometric sums can be checked the same way: for $r\ne1$,

$$\sum_{j=1}^n jr^j=\frac{r-(n+1)r^{n+1}+nr^{n+2}}{(1-r)^2}.$$

The missing case $r=1$ is the arithmetic sum, not a division by zero. Such parameter cases are part of the theorem's statement.

### Bases are a reachability problem

A step $P(k)\Rightarrow P(k+d)$ stays in one residue class modulo $d$. To cover every integer from a starting point, establish a base in every required residue class. A step using the two preceding values needs two consecutive initial values unless a separately proved start supplies the missing dependency. “Strong induction” does not automatically grant statements below the stated starting index.

For postage using nonnegative counts of four-unit and five-unit pieces, 12,13,14,15 are consecutive representable bases. Adding four then covers every integer at least12. Since11 is impossible,12 is the least all-future threshold. Proving isolated larger values would not establish the consecutive interval needed by this step.

### Inequality induction needs a closing inequality

To prove $2^n\ge n^2$ eventually, multiplying the hypothesis by2 yields $2^{k+1}\ge2k^2$. One must separately show $2k^2\ge(k+1)^2$, equivalent to $k^2-2k-1\ge0$. This holds for integer $k\ge3$, and the chosen base $n=4$ closes the proof. Writing the desired next bound without this comparison merely repeats the goal.
''',[
('A weighted geometric sum',r'Find $\sum_{j=1}^{5}j2^j$.', ['258','260','320','192'],'A',r'The terms are $2,8,24,64,160$, which sum to258. Alternatively the formula at $r=2$ simplifies to $(n-1)2^{n+1}+2$, yielding $4\cdot64+2=258$. The constant2 is fixed by the base case. The option260 has an incorrect constant,320 incorrectly multiplies the last power by the arithmetic sum, and192 does not count the weights correctly.'),
('Closed-form difference test',r'A proposed formula $S_n=n(n+1)(2n+1)/6$ has what increment $S_{n+1}-S_n$?', [r'$n^2$',r'$(n+1)^2$',r'$2n+1$',r'$n(n+1)$'],'B',r'Factor the shared $(n+1)/6$. The remaining difference is $(n+2)(2n+3)-n(2n+1)=6(n+1)$. The product is therefore $(n+1)^2$. This matches adding the next square to a sum ending at $n$. The expression $2n+1$ is the increment of $n^2$, not of the cumulative sum of squares.'),
('Step size three',r'Only the rule $P(k)\Rightarrow P(k+3)$ is available for $k\ge2$. Which base set suffices to establish $P(n)$ for every $n\ge2$?', [r'$P(2)$ only',r'$P(2),P(3)$',r'$P(2),P(3),P(4)$',r'$P(2),P(5),P(8)$'],'C',r'The starting integers2,3,4 represent all three residue classes modulo3. Repeated use of the step covers respectively2,5,8,...;3,6,9,...;4,7,10,.... OptionD establishes only the first of those chains. Two bases leave one class uncovered. The rule has no operation that transfers a proof between residue classes.'),
('An eventual exponential inequality',r'What is the smallest $N\ge1$ such that $2^n\ge n^2$ for every integer $n\ge N$?', ['1','2','3','4'],'D',r'At $n=3$, $8<9$, so every candidate threshold at most3 fails. At4 the inequality is equality. If it holds at $k\ge4$, then $2^{k+1}\ge2k^2\ge(k+1)^2$ since $k^2-2k-1>0$. Thus4 is sufficient and necessary. Checking1 and2 alone misses the failure at3; an eventual claim requires all later values.'),
('Consecutive postage bases',r'Nonnegative combinations of4 and5 represent every integer from what least threshold onward?', ['10','11','12','16'],'C',r'Values12,13,14,15 are $3\cdot4$, $2\cdot4+5$, $4+2\cdot5$, and $3\cdot5$. For any $n\ge16$, subtract4 and use induction. Value11 is not representable: possible numbers of five-unit pieces are0,1,2, leaving11,6,1, none divisible by4. Therefore12 is the least threshold. The four consecutive bases match the four-step recurrence.'),
('A binary-string recurrence',r'Let $b_n$ count length-$n$ binary strings without adjacent ones, with $b_0=1,b_1=2$. What is $b_5$?', ['8','13','16','21'],'B',r'Partition strings by their start:0 followed by a valid length-$n-1$ string, or10 followed by a valid length-$n-2$ string. These cases are disjoint and exhaustive, yielding $b_n=b_{n-1}+b_{n-2}$. The next values are3,5,8,13. OptionA is $b_4$ andD is $b_6$. The two bases include the one empty string, not zero empty strings.'),
('Divisibility by a step',r'For every integer $n\ge0$, which divisor always divides $5^n-1$?', ['3','4','5','8'],'B',r'At0 the expression is0, divisible by4. If $5^k-1=4q$, then $5^{k+1}-1=5(5^k-1)+4=4(5q+1)$. This is a direct induction certificate. At $n=1$, the value4 refutes divisors3,5 and8. The factorization of the increment exposes the required constant remainder.'),
('A false induction with a true-looking base',r'The statement $n^2\le2^n$ is checked at1 and2. A claimed step replaces $2k^2$ by $(k+1)^2$ for all $k\ge1$. What first fails?', ['The base at1.',r'The necessary inequality at $k=2$, since8 is less than9.','Every base case.','The use of ordinary induction itself.'],'B',r'The bases1 and2 satisfy the statement, but at the step from2 to3 the hypothesis yields only $2^3\ge2(2^2)=8$. The desired next square is9. The needed comparison $2k^2\ge(k+1)^2$ fails for $k=2$. Ordinary induction is valid; this particular closing inequality is not. The actual statement is false at3, agreeing with the identified gap.'),
('Hockey-stick boundary',r'Find $\sum_{j=3}^{8}\binom j3$.', ['56','70','126','210'],'C',r'Pascal gives $\binom j3=\binom{j+1}4-\binom j4$. Summing telescopes to $\binom94-\binom34=126$. The lower term is zero because three objects cannot supply four. The direct terms1,4,10,20,35,56 also sum to126. The upper index is one larger than the last summation index.'),
('Telescoping induction',r'What is $\sum_{j=1}^{n}1/(j(j+1))$ for integer $n\ge1$?', [r'$1/n$',r'$n/(n+1)$',r'$n/2$',r'$1/(n+1)$'],'B',r'Write each term as $1/j-1/(j+1)$. Every intermediate reciprocal cancels and the result is $1-1/(n+1)=n/(n+1)$. The base $n=1$ gives1/2. For an induction check, add $1/((k+1)(k+2))$ to $k/(k+1)$ and combine to $(k+1)/(k+2)$. OptionD retains only the discarded final reciprocal.'),
],[(
'Increment check',r'For a sum ending at $n$, verify $F(n+1)-F(n)=f(n+1)$ and one base value. These two conditions prove the candidate closed form by induction. Testing only the increment misses an arbitrary additive constant.'),
('Weighted powers',r'For $r\ne1$, use $\sum_{j=1}^n jr^j=[r-(n+1)r^{n+1}+nr^{n+2}]/(1-r)^2$. For $r=2$, this becomes $(n-1)2^{n+1}+2$. At $r=1$, use $n(n+1)/2$; substituting into the fractional formula is undefined.'),
('Residue-class coverage',r'A step adding $d$ requires bases covering every required residue modulo $d$. Adding3 from bases2,3,4 covers all integers at least2. Adding3 from2,5,8 does not: these bases are in one residue class.'),
('Predecessor dependencies',r'If the step uses $P(k)$ and $P(k-1)$, prove two consecutive starts and specify where the step begins. For $b_n=b_{n-1}+b_{n-2}$, values $b_0,b_1$ determine every later value. Strong induction grants only predecessors within the stated domain.'),
('Exponential inequality slack',r'After doubling a quadratic hypothesis, check $2k^2\ge(k+1)^2$. The step is safe for integer $k\ge3$, but the target $2^n\ge n^2$ fails at3, so the all-future proof starts at4. Step validity and base validity are distinct checks.'),
('Consecutive representation bases',r'For pieces4 and5, establish12 through15 and then add4. To establish the least threshold, also prove11 impossible. A construction proves sufficiency; the immediately preceding obstruction proves minimality.'),
('Divisibility increment',r'For $a^n-1$ modulo $a-1$, rewrite $a^{k+1}-1=a(a^k-1)+(a-1)$. Both terms are divisible by $a-1$. The base at0 is0, and this identity avoids an unsupported “powers preserve the property” assertion.'),
('Hockey-stick endpoints',r'$\sum_{j=r}^{n}\binom jr=\binom{n+1}{r+1}$. The upper index increases by1 and so does the lower index. Derive it by Pascal telescoping; starting the sum later subtracts the omitted lower boundary term.'),
('Telescoping boundary terms',r'$1/[j(j+1)]=1/j-1/(j+1)$. From1 through$n$, only1 and $-1/(n+1)$ survive. A different lower limit changes the first survivor. A limit of1 does not mean the finite sum equals1.'),
('Strengthen a weak hypothesis',r'If a recursive step needs properties of every prefix or every smaller input, state those quantified properties in the induction claim. The auxiliary claim must have its own base and preservation proof; merely asserting the desired next-stage information is circular.'),
])
