from author import chapter
chapter('p_types',r'''
### Type the operands before evaluating the expression

The language for the following questions is C17. Machine widths are specified whenever needed. Integer promotions occur before the usual arithmetic conversions. With32-bit `int` and `unsigned int`, comparing `-1` to `1u` first converts the negative integer to the corresponding unsigned value, making the comparison false. This rule is not shared by every programming language and cannot be replaced by mathematical integer ordering.

For division of two integer operands, compute the truncated integer quotient before assigning to a floating object. `double z = 3/2;` stores1.0, while `double z = (double)3/2;` stores1.5. Casting the already computed quotient cannot restore its discarded fractional part. C17 signed division truncates toward zero and its remainder satisfies `a == (a/b)*b + a%b` for defined operands.

### Distinguish storage width, promotion width and assignment conversion

On an8-bit unsigned-character model, `unsigned char x = 250; x += 10;` computes the promoted sum260 in an `int` that can represent it, then converts the assignment back modulo256 to4. Unsigned arithmetic has modular semantics, but a narrow unsigned operand may be promoted to a signed `int` first. Therefore not every intermediate expression inherits the storage width of its variable.

### Classify behavior before predicting an output

Unsigned wraparound is defined. Overflow of a signed arithmetic result is undefined, so an exam answer must not invent a wrapped numeric result. A C17 expression with unsequenced modification and access to the same scalar, such as `i++ + i`, is undefined. Precedence determines parsing, while sequencing determines which evaluations may legally interact. Short-circuit logical operators specify evaluation order and can suppress an otherwise invalid operation.

For an IEEE binary64 exercise, exact integer representation extends through $2^{53}$. At larger magnitudes, neighboring integers need not be distinct after conversion. This is a specified numeric model for those questions, not a guarantee that every C implementation uses binary64 for `double`.
''',[
('Integer division before assignment','In C17, what value is stored by `double z = 3 / 2;`?', ['1.0','1.5','2.0','Undefined behavior.'],'A','Both operands have integer type, so integer division computes1. Assignment then converts that integer to the floating value1.0. The destination type does not retroactively change evaluation of the right-hand expression. To obtain1.5, convert an operand before division or use a floating literal.'),
('Cast location','In C17, which expression has value1.5?', ['`(double)(3/2)`','`(double)3/2`','`3/(int)2.0`','`(int)(3.0/2)`'],'B','InB, one operand is converted before division and the other is converted by the arithmetic rules, producing a floating quotient. A converts an integer quotient already truncated to1. C has integer operands after its cast, andD explicitly converts a floating quotient back to an integer. Trace the typed intermediate result at each operator.'),
('Signed and unsigned comparison','Assume32-bit `int` and `unsigned int`. What is the value of `-1 < 1u` in C17?', ['0','1','Implementation-defined under these assumptions.','Undefined behavior.'],'A',r'The equal-rank unsigned operand forces conversion of$-1$ to unsigned, yielding $2^{32}-1$. This is greater than1, so the comparison is false and has integer value0. The conversion itself is defined. A mathematical comparison of the original values ignores the type conversion step.'),
('Narrow assignment wrap','Assume8-bit `unsigned char` and an `int` that represents0 through260. After `unsigned char x=250; x+=10;`, what is$x$?', ['4','10','250','260'],'A',r'The compound assignment performs the addition after promotion, yielding260, then converts to the unsigned-character range modulo256. The stored result is4. The intermediate need not wrap at8 bits, but the final conversion does.260 cannot be stored in the specified8-bit destination.'),
('Negative remainder','In C17, what is `-7 % 3`?', ['-1','1','2','Undefined behavior.'],'A','The quotient `-7/3` truncates toward zero to-2. Use the defining identity: remainder is `-7 - (-2)*3 = -1`. A nonnegative Euclidean remainder would be2, but C signed remainder follows truncating division. Neither division by a nonzero3 nor this quotient overflows.'),
('Parsing a bitwise test','In C17, how is `x & 1 == 0` parsed?', ['`(x & 1) == 0`','`x & (1 == 0)`','`(x == 1) & 0`','It is syntactically invalid.'],'B','Equality binds more tightly than bitwise AND, so the comparison `1 == 0` is evaluated as a subexpression and yields0. The whole value is therefore `x & 0`, zero for an integer$x$. To test whether the low bit is zero, write explicit parentheses around `x & 1`. Parsing and the intended English condition are separate.'),
('A signed shift boundary','Assume a32-bit signed `int` with maximum2147483647. What is the C17 classification of `1 << 31`?', ['Defined and equal to-2147483648.','Defined and equal to2147483648.','Undefined behavior.','Always zero.'],'C',r'The left operand is a signed nonnegative `int`. Its multiplication by $2^{31}$ is not representable in that signed type, so the signed-left-shift rule does not define this expression. The shift count itself is within the width, but representability still fails. Using `1u` would ask a different, defined unsigned question.'),
('Unsequenced access','In C17, with initially `int i=1`, what is the classification of `i++ + i`?', ['Always2.','Always3.','Unspecified but always2 or3.','Undefined behavior.'],'D','The modification from the postfix increment is unsequenced relative to the other read of the same scalar used to compute the sum. This violates the C17 sequencing rule and produces undefined behavior. Evaluating the left operand first by intuition does not supply a sequencing guarantee for the addition operator.'),
('Short-circuit suppression','Initially `int x=0, y=2;`. Evaluate `x && ++y` in C17. What are the expression value and final$y$?', ['(0,2)','(0,3)','(1,2)','(1,3)'],'A','Logical AND first evaluates$x$. Since it is zero, the result is already false and the right operand is not evaluated. Thus$y$ remains2 and the expression value is0. This is a specified sequencing and suppression rule; replacing logical AND with bitwise AND would evaluate both operands.'),
('Array storage','Assume `sizeof(int)==4` and `sizeof(int*)==8`. For a local `int a[10];`, what is `sizeof a`?', ['4','8','10','40'],'D','The operand of `sizeof` retains the array type in this case instead of undergoing ordinary array-to-pointer conversion. Ten elements of four bytes give40 bytes. Eight would be the size of a pointer variable, including an array parameter after its type adjustment, which is not this local declaration.'),
('An unparenthesized macro','For `#define SQ(x) x*x`, what is the C value of `SQ(1+2)`?', ['5','6','9','Undefined behavior.'],'A','Text substitution yields `1+2*1+2`. Multiplication binds before addition, so the value is5. The macro should parenthesize each substituted operand and the full expression. Even a parenthesized square macro can repeat evaluation when its argument has side effects, so syntactic repair alone does not make every argument safe.'),
('Binary64 spacing',r'Assume IEEE754 binary64 rounding to nearest, ties to even. Let$x=2^{53}$ exactly. What is the result of comparing the floating sum$x+1$ with$x$?', ['The sum is greater.','The sum equals$x$.','The sum is smaller.','Every implementation must raise an exception.'],'B',r'At this magnitude adjacent representable values differ by2. The exact integer $2^{53}+1$ is halfway between$x$ and$x+2$. Ties-to-even rounds it to$x$, so the equality comparison is true. This is a rounding effect on a defined specified format, not signed integer overflow and not a universal rule for all floating formats.'),
],[(
'Promotion before conversion',r'Determine literal types, apply integer promotions, then apply usual arithmetic conversions. Under32-bit equal-rank signed/unsigned comparison, $-1$ becomes $2^{32}-1$. A destination type does not control intermediate operators.'),
('Cast timing','`(double)(a/b)` preserves integer-division truncation already performed; `(double)a/b` requests floating division. For3 and2, the results are1.0 and1.5. Place the cast before the operator whose semantics must change.'),
('Unsigned assignment modulus',r'Converting an integer to an unsigned destination of$b$ bits gives its residue modulo$2^b$. For8 bits,260 becomes4 and$-1$ becomes255. Intermediate promotion can occur at a wider signed width; distinguish calculation from final storage.'),
('C remainder identity','For defined signed C17 division, quotient truncates toward zero and remainder satisfies `a == (a/b)*b + a%b`. Thus `-7%3` is-1. A nonnegative modular representative belongs to a different arithmetic convention.'),
('Bit-test parentheses','Write `(x & mask) == 0` when testing masked bits. `x & mask == 0` parses the equality first. Also distinguish bitwise operators, which operate on bit patterns, from logical operators, which produce0 or1 and may short-circuit.'),
('Shift legality','Check the promoted left operand, count range and signed representability separately. For32-bit `int`, `1 << 31` is undefined inC17 while `1u << 31` is defined. Right-shifting a negative signed value has implementation-defined semantics in this language version.'),
('Undefined is not unspecified','Signed overflow and unsequenced modification/access cannot be assigned a finite set of predicted outputs by the language. Unspecified evaluation order can still be defined when operands do not conflict. Classify before tracing.'),
('Short-circuit protection','For `a && b`, a false left operand suppresses$b$; for `a || b`, a true left operand suppresses$b$. This can guard a pointer access or division. Swapping operand order can remove the protection even if a pure Boolean identity holds mathematically.'),
('Array versus pointer sizeof','A local fixed array preserves its complete type under `sizeof`; an adjusted array parameter is a pointer. Ten four-byte integers occupy40 bytes, while the pointer size is separately specified. Storage size is independent of the displayed numeric values.'),
('Macro expansion','Expand replacement text before parsing. `SQ(1+2)` under an unparenthesized macro yields5, not9. Parenthesizing parameters repairs precedence but does not prevent an argument like `i++` from appearing twice.'),
('Floating integer precision',r'Binary64 represents every integer through$2^{53}$ exactly, but not every larger integer. Under nearest-even, $2^{53}+1$ rounds to$2^{53}$. Equality tests at this boundary need a format and rounding assumption.'),
('Defined overflow checks','For signed positive$b$, ensure `a <= MAX-b` before evaluating `a+b`. Checking overflow after the signed operation is too late. Division also requires a nonzero divisor and must exclude the minimum-signed divided by-1 overflow case.'),
])
chapter('p_flow',r'''
### Expand execution into control checkpoints

A for-loop executes initialization once, then alternates guard, body and update. A `continue` in its body jumps to the update, whereas a `continue` in an equivalent-looking while-loop jumps directly to the guard. To preserve semantics in a for-to-while translation, every continue path must still execute the intended update. A `break` exits the nearest loop or switch; it does not automatically exit an enclosing loop.

A switch performs one initial dispatch to a matching label and then ordinary sequential execution. Encountering `default` later through fallthrough does not mean the original value failed every case. Case labels do not create automatic jumps after each statement. Compute the exact entered point and follow the statements until a transfer exits.

### Trace side effects in guards at the correct time

For `while (i++ < 3)` starting at0, successful tests compare0,1,2; the failing test compares3, but still increments$i$ to4. The body runs three times while the final state is4. Distinguish the value used in the comparison from the new value stored by postfix increment. A posttest loop runs its body at least once if control enters it, even when its first guard is false.

### Machine arithmetic changes termination

An unsigned$b$-bit update adding$d$ follows residues modulo$2^b$. Its cycle length is $2^b/\gcd(d,2^b)$, and only residues congruent to the start modulo that gcd are reachable. A mathematical increasing sequence can therefore become a finite modular cycle. A signed overflow path is instead undefined; it must not be treated as the same wrapped state graph.

For total correctness, supply an invariant giving the output property and a decreasing nonnegative integer or other well-founded ranking giving termination. A constant invariant such as “the variables are integers” may be preserved but does not explain the result or why execution stops.
''',[
('Independent conditionals','Initially `int x=1;`. Execute `if(x==1) x=2; if(x==2) x=3;`. What is final$x$?', ['1','2','3','Undefined behavior.'],'C','The first condition is true and changes$x$ to2. The second statement is independent and tests the updated value, so it changes$x$ to3. Replacing the second `if` with `else if` would make the statements one selection chain and change the outcome. Read the actual syntax, not an imagined priority chain.'),
('Dangling else','Initially `int a=0,b=0,x=0;`. Execute `if(a) if(b) x=1; else x=2;`. What is final$x$?', ['0','1','2','Undefined behavior.'],'A','The else binds to the nearest unmatched if, namely `if(b)`. Because the outer condition$a$ is false, its entire nested statement is skipped. No assignment to$x$ occurs. Formatting without braces does not change the binding rule; pairing the else with the outer if would incorrectly predict2.'),
('Switch fallthrough','Initially `int x=2,y=0;`. Execute `switch(x){case 1:y+=1; case 2:y+=2; default:y+=4;}`. What is$y$?', ['2','4','6','7'],'C','Dispatch enters case2, adds2, then falls through to the default-labeled statement and adds4. The result is6. Case1 is before the entry point and is not executed. Default is a label, not an implicit else branch that prevents fallthrough. A break after case2 would give a different result.'),
('Continue in a for-loop','Compute$s$ after `int s=0; for(int i=0;i<5;i++){if(i==2) continue; s+=i;}`.', ['7','8','10','The loop never terminates.'],'B','The accumulated indices are0,1,3,4, totaling8. At$i=2$, continue skips the remaining body but still executes the for update, moving$i$ to3. The sum10 includes the skipped index. An incorrect while translation that puts its update after the continue path could stall.'),
('A modifying guard','Initially `int i=0,c=0;`. Execute `while(i++<3) c++;`. What are final$(i,c)$?', ['(3,3)','(4,3)','(4,4)','(3,4)'],'B','The tests use old$i$ values0,1,2,3. The first three succeed and increment$c$; the fourth fails, but its postfix increment still changes$i$ from3 to4. Thus final$i$ is4 and$c$ is3. A failed comparison does not undo side effects performed while evaluating its operand.'),
('Posttest minimum execution','Initially `int i=5,c=0;`. Execute `do {c++;} while(i<3);`. What is$c$?', ['0','1','3','5'],'B','Control enters the body before evaluating the condition, so$c$ becomes1. The first test is false and ends the loop. A while-loop with the same condition would execute zero times. The initial numeric value5 affects the guard but does not specify a number of body repetitions.'),
('Break scope','Execute `int c=0; for(int i=0;i<3;i++){for(int j=0;j<4;j++){if(j==2) break; c++;}}`. What is$c$?', ['2','3','6','12'],'C',r'For each outer$i$, the inner iterations$j=0,1$ increment$c$, then$j=2$ breaks only the inner loop. The outer loop continues for all three indices. Total increments are$3\cdot2=6$. An outer-loop exit would need another transfer or condition; the inner break does not imply it.'),
('Return exits the function','A function loops through indices0 through9, increments$c$, and immediately returns$c$ when the index equals3. Starting$c=0$, what value is returned?', ['3','4','9','10'],'B','Indices0,1,2,3 each execute the increment before the return check. Thus$c$ is4 when the function exits. Return ends the whole function and no later iterations execute. The answer3 would correspond to checking before the increment or using different index endpoints.'),
('Unsigned cycle reachability','Assume8-bit unsigned storage and defined promoted additions. Starting$x=0$, repeatedly assign$x=x+64$ back to that storage. Which value is never reached?', ['0','64','128','1'],'D',r'The reachable cycle is0,64,128,192,0. Equivalently $\gcd(64,256)=64$, so only residues congruent to0 modulo64 can appear.1 is outside that class. A loop waiting for$x=1$ never terminates under this model; “the counter increases” is not a valid unsigned termination proof.'),
('A sum invariant','A loop begins with$i=0,s=0$ and repeats `s+=i; i++;` while$i<n$. Which invariant holds at each guard checkpoint?', [r'$s=i(i-1)/2$',r'$s=i(i+1)/2$',r'$s=n(n-1)/2$',r'$s=i^2$'],'A',r'Before the iteration with index$i$, exactly the values0 through$i-1$ have been accumulated, so $s=i(i-1)/2$. Adding$i$ gives $i(i+1)/2$, which equals the same invariant expression after incrementing the index to$i+1$. At termination$i=n$, it yields the final sum. The other formulas use the wrong checkpoint or assume the postcondition throughout.'),
('Euclid trace','Starting positive$a=48,b=18$, repeatedly replace$(a,b)$ by$(b,a%b)$ while$b!=0$. How many updates occur?', ['2','3','4','18'],'B','The states are(48,18), then(18,12), then(12,6), then(6,0). There are three updates before the guard fails. The second component strictly decreases while positive and the gcd is invariant, so termination and the answer6 are independently explained. Counting the initial state as an update gives the wrong endpoint count.'),
('A correct ranking',r'For a loop with invariant$0\le i\le n$ and update$i=i+1$ whenever$i<n$, which integer ranking proves termination?', [r'$i$',r'$n-i$',r'$n+i$',r'$0$'],'B',r'$n-i$ is nonnegative at the checkpoint and decreases by exactly1 per iteration. It cannot descend infinitely through nonnegative integers. The counter$i$ increases and is not a decreasing ranking; the constant0 provides no progress. The invariant supplies the ranking domain needed by the proof.'),
],[(
'If chains are syntax','Independent if statements test the latest state; an else-if chain chooses at most one branch. In the update1 to2 to3 example, independent statements yield3, while a chain can yield2. Do not infer the grouping from indentation.'),
('Else binding','An else attaches to the nearest unmatched if. For a false outer guard, an inner else is skipped with its enclosing statement. Braces make the intended binding explicit and remove this common parsing distractor.'),
('Switch dispatch and fallthrough','Switch selects an entry label once; later labels do not redispatch. Starting at case2 and falling into default executes both bodies. Count until a break, return or other actual transfer occurs.'),
('Continue destination','In a for-loop, continue goes to the update and then guard. In a while-loop, it goes directly to the guard. A semantics-preserving translation must route all continue paths through the equivalent update.'),
('Guard side effects','A failed guard still evaluates its operands. `while(i++<3)` starting0 ends with$i=4$ after three bodies. The old value determines the comparison; the new value remains stored after failure.'),
('Do-while entry','A do-while body executes once before its first guard if entered normally. For initial$i=5$ and test$i<3$, it still executes once. A pretest loop with the same condition executes zero times.'),
('Break and return','Break exits the nearest enclosing loop or switch. Return exits the entire function. A break inside a switch nested in a loop need not end the loop, and a break inside an inner loop need not end the outer one.'),
('Half-open count',r'For$i=a,a+d,\ldots<b$ with$d>0$, exact body count is $\max(0,\lceil(b-a)/d\rceil)$. Inclusive upper bounds use a floor formula with one added. A count formula assumes arithmetic progresses without overflow.'),
('Unsigned orbit',r'An unsigned$b$-bit increment$d$ has period $2^b/\gcd(d,2^b)$. Reachable residues share the starting residue modulo the gcd. For8 bits and step64, the period is4 and the target1 from start0 is unreachable.'),
('Invariant checkpoint',r'Before adding$i$, the prefix sum of0 through$i-1$ is$i(i-1)/2$. After adding$i$ but before incrementing, it is$i(i+1)/2$. Locate the assertion exactly; a correct formula at one checkpoint can be wrong at another.'),
('Euclid progress','For nonnegative remainder arithmetic and positive$b$, the next second operand is strictly smaller than$b$. The gcd remains invariant. Together these properties establish termination and the returned gcd; neither alone proves total correctness.'),
('Partial versus total correctness','An invariant plus a false exit guard can establish the postcondition if the loop terminates. A nonnegative decreasing ranking establishes termination. A preserved weak property such as “all variables are integers” supplies neither the intended result nor progress.'),
])
