from author import chapter
chapter('a_model',r'''
### Translate the representation into a numerical input length

For a positive integer $N$, unsigned binary length is $L=\lfloor\log_2N\rfloor+1$. Therefore $2^{L-1}\le N<2^L$. A loop running $N$ times can take exponentially many steps in $L$, even though it is linear in the numeric value. Unary encoding instead has length proportional to $N$; the same loop then has linear complexity in its input length. Pseudo-polynomial complexity is a statement about this mismatch, not a statement that every numeric loop is slow.

If an array contains $n$ values each represented in $b$ bits, payload length is $nb$ bits. Reading a value is constant time only in a model where it fits in a word and that word is an accessible primitive. Reading an arbitrarily long integer is not a constant-time primitive in a bit model. Multiplying two $b$-bit integers by the ordinary digit algorithm performs quadratic bit work, even though a language presents multiplication as one expression.

### Separate addressability, payload and operation support

A memory with $M$ individually addressable positions needs at least $\lceil\log_2M\rceil$ address bits. Representing every integer from0 through$M$ needs $\lceil\log_2(M+1)\rceil$ value bits, which can differ at a power of two. Neither statement grants constant-cost arithmetic on an object occupying many words. A word-RAM assumption specifies a word width, allowed operations and memory access costs together.

### Derive information and output lower bounds

A binary comparison decision tree of height $h$ has at most $2^h$ leaves. Distinguishing $K$ possible outcomes requires $h\ge\lceil\log_2K\rceil$. Sorting distinct labeled keys requires $K=n!$, but selecting one of$n$ possible positions uses a different outcome count. An explicit output of$m$ words costs at least proportional to$m$ writes. Returning a pointer to an already stored object does not write the object again; output representation changes the lower-bound argument.
''',[
('A power-of-two boundary',r'How many bits represent the positive integer1024 in ordinary unsigned binary without leading zeros?', ['9','10','11','1024'],'C',r'The highest set bit represents $2^{10}$, and its position counts from zero. The representation has that bit plus ten lower positions, hence11 bits. The floor-log formula gives $\lfloor\log_2 1024\rfloor+1=11$. Ten bits represent at most1023. The address space of1024 positions is a different question and needs ten address bits.'),
('Address versus length',r'A memory has1024 positions indexed0 through1023. Which pair gives the minimum index bits and the bits needed to store its length1024?', ['(10,10)','(10,11)','(11,10)','(11,11)'],'B',r'The1024 possible indices fit in ten bits. The length is the numeric value1024 and needs eleven bits. The two quantities differ precisely because the length lies one above the largest index. Assigning the same bit count to both confuses number of available values with the largest represented value.'),
('Binary numeric iteration',r'An algorithm performs exactly $N$ constant-cost iterations on a positive $L$-bit integer $N$. Its worst-case count as a function of $L$ is which?', [r'$\Theta(L)$',r'$\Theta(L^2)$',r'$\Theta(2^L)$',r'$\Theta(\log L)$'],'C',r'The greatest $L$-bit value is $2^L-1$, and the least is $2^{L-1}$. Thus even the minimum for that length is exponential in $L$. Counting iterations gives tight order $2^L$. This classification assumes the problem grants constant-cost loop operations; adding bit-cost arithmetic cannot make it linear in $L$.'),
('Array payload',r'An array has200 signed values stored in fixed16-bit slots. Ignore headers and padding. What is its payload in bytes?', ['200','400','1600','3200'],'B',r'The payload is $200\cdot16=3200$ bits. Divide by eight bits per byte to obtain400 bytes. Choice3200 reports bits as bytes. Choice200 assumes one byte per value. The calculation counts physical fixed-width storage, not the number of decimal digits printed for each value.'),
('Matrix input parameter',r'For an $n\times n$ matrix of fixed-width entries, scanning every entry once takes what order in the number $M$ of entries?', [r'$\Theta(\sqrt M)$',r'$\Theta(M)$',r'$\Theta(M^2)$',r'$\Theta(\log M)$'],'B',r'There are $M=n^2$ entries and one visit per entry, giving $\Theta(n^2)=\Theta(M)$. A quadratic statement in the side length is linear in the entry count. ChoiceC substitutes $M$ for $n$ without translating the parameter definition. Complexity labels are meaningless unless the input-size variable is defined.'),
('Bit-cost multiplication',r'The ordinary schoolbook method multiplies two $b$-bit integers. Under a bit-operation model, what is its asymptotic worst-case work?', [r'$\Theta(1)$',r'$\Theta(b)$',r'$\Theta(b^2)$',r'$\Theta(2^b)$'],'C',r'Each of$b$ multiplier bits contributes a shifted partial product involving up to$b$ multiplicand bits. Ordinary accumulation also fits within quadratic bit work, yielding $\Theta(b^2)$ for this method. A source-level multiplication operator is not a constant-time bit primitive. Faster multiplication algorithms change the algorithm; they do not change this schoolbook count.'),
('Decision-tree capacity',r'A binary comparison tree must distinguish70 possible answers. What minimum worst-case depth follows solely from leaf capacity?', ['6','7','35','70'],'B',r'Six levels provide at most64 leaves, insufficient for70 distinguishable answers. Seven levels provide128, so the necessary lower bound is $\lceil\log_2 70\rceil=7$. Capacity alone does not construct an algorithm attaining it under every comparison restriction. The linear options mistake one outcome per comparison for exponential branching.'),
('Sorting a small distinct input',r'What comparison lower bound follows for sorting five distinct keys?', ['5','6','7','10'],'C',r'There are $5!=120$ possible relative orders. A binary comparison tree needs at least120 leaves, so its height is at least $\lceil\log_2 120\rceil=7$. Six levels distinguish only64 orders. Ten is the number of unordered key pairs, which is not the information-theoretic lower bound and need not all be compared.'),
('Sparse versus dense reading',r'A simple graph has $n$ vertices and $m$ edges. Ignoring vertex-label bit lengths, which pair describes scanning an adjacency matrix and adjacency lists respectively?', [r'$\Theta(n),\Theta(m)$',r'$\Theta(n^2),\Theta(n+m)$',r'$\Theta(m),\Theta(n^2)$',r'$\Theta(n+m),\Theta(nm)$'],'B',r'The matrix stores $n^2$ cells whether edges exist or not. Lists require visiting$n$ list headers and a total proportional to$m$ edge entries, twice$m$ for an undirected graph. That constant does not change the order. The vertex-header cost matters even for an edgeless graph, so $\Theta(m)$ alone is incomplete.'),
('Explicit output size',r'An algorithm emits all ordered pairs of distinct elements from an $n$-element input, each pair as an explicit constant-size record. What worst-case output lower bound follows?', [r'$\Omega(n)$',r'$\Omega(n\log n)$',r'$\Omega(n^2)$',r'$\Omega(\log n)$'],'C',r'There are $n(n-1)$ ordered pairs. Each record requires at least one fixed-cost emission under the stated model, so the output alone imposes $\Omega(n^2)$ for $n\ge2$. If pairs were represented implicitly by a generator, this lower bound would apply to fully consuming the generator, not constructing its handle. The explicit-output premise is essential.'),
],[(
'Binary length',r'For $N\ge1$, use $\lfloor\log_2N\rfloor+1$. At powers of two, include the leading bit:1024 needs11 bits. Zero requires a separately specified encoding convention, so do not apply the logarithm formula to zero.'),
('Address range',r'$M$ indexed positions0 through$M-1$ need $\lceil\log_2M\rceil$ address bits. A stored count ranging0 through$M$ needs $\lceil\log_2(M+1)\rceil$. The distinction appears at powers of two and often supplies an off-by-one distractor.'),
('Numeric versus encoded time',r'If $N$ has $L$ binary bits, a count proportional to$N$ is $\Theta(2^L)$ in the worst case for fixed length. A unary representation has length $\Theta(N)$ instead. Always identify the encoding before classifying a numeric bound as polynomial.'),
('Payload accounting',r'$n$ fixed$b$-bit values occupy $nb$ bits before overhead. For20016-bit values, this is400 bytes. Word alignment, headers and padding must be included only when specified; printed numeric magnitude is not storage width.'),
('Bit versus word arithmetic',r'Ordinary multiplication of two$b$-bit values costs $\Theta(b^2)$ bit operations. In a word model, multiplication of values fitting supported words may count as one primitive. Unbounded integers spanning multiple words invalidate that shortcut.'),
('Matrix parameter conversion',r'For side length$n$, entry count is $M=n^2$. A full scan is quadratic in$n$ and linear in$M$. Translate the function when changing parameters instead of carrying its old exponent to the new variable.'),
('Comparison leaf bound',r'Binary comparisons require $h\ge\lceil\log_2K\rceil$ for$K$ distinguishable outputs. Sorting distinct keys uses $K=n!$; an arbitrary query may use a smaller outcome space. A leaf-count lower bound need not be achievable by every allowed comparison family.'),
('Representation-specific graph reading',r'Adjacency matrices have $\Theta(n^2)$ cells; adjacency lists have $\Theta(n+m)$ words with fixed labels. Even if$m=0$, reading all vertex headers costs linear time. The same graph does not force the same input length under both representations.'),
('Output lower bounds',r'Explicitly emitting$n(n-1)$ constant-size pairs costs $\Omega(n^2)$. An implicit pointer or lazy iterator is a different output contract. Compare algorithms only after making their output obligations identical.'),
('An adversarial unseen position',r'To determine whether an arbitrary unsorted array contains a designated value, a negative answer may require reading all$n$ positions: an unread position could contain it. This proves a linear worst-case access bound, while a positive answer can finish earlier.'),
])
chapter('a_asym',r'''
### Decide the relation before comparing growth

For eventually positive $g$, $f\in O(g)$ means one constant upper bound on $f/g$ beyond some threshold. $f\in\Omega(g)$ means an eventual positive lower bound; $\Theta$ requires both. Little-oh requires $f/g\to0$, a strictly stronger conclusion than boundedness. A positive finite ratio limit proves $\Theta$, but the absence of a limit does not refute $\Theta$: a ratio oscillating between1 and3 is still bounded above and below.

### Transform exponents and logarithms exactly

For fixed positive bases with logarithms defined, $a^{\log_b n}=n^{\log_b a}$. This is an exact identity obtained by taking natural logarithms. In contrast, $a^{\log_b^2n}$ has exponent proportional to $(\ln n)^2$ and grows faster than every fixed polynomial. Constants inside an exponent are not multiplicative constants outside it: $2^{2n}/2^n=2^n$ is unbounded.

For fixed integer$r$, $\binom nr=\Theta(n^r)$ because the numerator is a product of$r$ linear factors and$r!$ is constant. If$r$ grows with$n$, this reasoning fails. In particular, central binomial coefficients are exponential up to a polynomial factor; the fixed-index theorem must not be silently generalized.

### Cancellation and several variables need their own analysis

Knowing $f,g\in\Theta(n^2)$ does not determine $f-g$: cancellation can leave zero, a linear term or an oscillatory residual. For two independent parameters, a proposed $O(n)$ bound on $n+m$ fails on the path $m=n^2$. Conversely, $n+m\in\Theta(\max(n,m))$ follows from the two inequalities $\max(n,m)\le n+m\le2\max(n,m)$. Choose parameter paths to refute a uniform claim.
''',[
('A strict growth relation',r'For $f(n)=n\log_2n$ and $g(n)=n^{1.1}$, which strongest listed relation holds?', [r'$f\in\Theta(g)$',r'$f\in o(g)$',r'$f\in\omega(g)$','The functions are incomparable.'],'B',r'The ratio is $\log_2 n/n^{0.1}$, which tends to zero because every fixed positive power dominates a logarithm. Thus little-oh holds and also implies big-oh. A finite crossover is not relevant to an eventual limit. The exponent gap0.1 is positive and fixed; a gap tending to zero would require a different calculation.'),
('An exponent identity',r'For $n>0$, what is $4^{\log_2n}$?', [r'$n$',r'$n^2$',r'$n^4$',r'$4\log_2n$'],'B',r'Write4 as $2^2$: $(2^2)^{\log_2 n}=2^{2\log_2 n}=n^2$. Equivalently use $a^{\log_b n}=n^{\log_b a}$. Multiplying the exponent does not multiply the final function by4. The identity is exact, so its asymptotic consequence follows immediately.'),
('An oscillating tight bound',r'Let $f(n)=n(2+(-1)^n)$ for positive integers$n$. Which statement is correct?', [r'$f\in\Theta(n)$ but $f/n$ has no limit.',r'$f\in o(n)$',r'$f\notin O(n)$',r'$f/n\to2$'],'A',r'The factor is1 on odd$n$ and3 on even$n$, hence $n\le f(n)\le3n$ for every$n$. This proves tight order without a ratio limit. Odd and even subsequences give limits1 and3, so no full limit exists. A ratio method is a sufficient tool when a limit exists, not a necessary definition of tight order.'),
('A cancellation residual',r'What is the tight order of $(n+1)^3-n^3$?', [r'$\Theta(n)$',r'$\Theta(n^2)$',r'$\Theta(n^3)$',r'$\Theta(1)$'],'B',r'Expand before comparing: $(n+1)^3-n^3=3n^2+3n+1$. The cubic terms cancel and the quadratic term dominates. For $n\ge1$ it is between $3n^2$ and $7n^2$. Subtracting the labels $\Theta(n^3)$ from each other is not an algebraic operation on the actual functions.'),
('Factorial logarithm',r'What is the tight order of $\log_2(n!)$?', [r'$\Theta(\log n)$',r'$\Theta(n)$',r'$\Theta(n\log n)$',r'$\Theta(n^2)$'],'C',r'Upper bound each of$n$ factors by$n$, obtaining $n!\le n^n$. For the lower bound, at least roughly$n/2$ factors are at least$n/2$, so $\log(n!)\ge(n/2)\log(n/2)$ up to integer rounding. Both bounds are order$n\log n$. No exact Stirling constant is needed to establish this order.'),
('Fixed-index combination',r'For fixed $r=4$, what is the tight order of $\binom n4$ as $n\to\infty$?', [r'$\Theta(n)$',r'$\Theta(n^2)$',r'$\Theta(n^4)$',r'$\Theta(4^n)$'],'C',r'The exact expression is $n(n-1)(n-2)(n-3)/24$. Dividing by$n^4$ gives a ratio tending to1/24. Thus the order is$n^4$. The fixed lower index is essential; treating$r$ as a growing input would invalidate the constant-factor product argument.'),
('Independent parameters',r'For independently unbounded positive$n,m$, which uniform tight bound holds for$n+m$?', [r'$\Theta(n)$',r'$\Theta(m)$',r'$\Theta(\max(n,m))$',r'$\Theta(nm)$'],'C',r'The maximum is at most the sum, and the sum is at most twice the maximum. These bounds use constants independent of both parameters. Taking$m=n^2$ refutes a uniform linear bound in$n$, and taking$n=m^2$ refutes the corresponding bound in$m$. Taking$n=m$ refutes tight order$nm$.'),
('Exponential constants',r'Which comparison is true?', [r'$2^{2n}\in\Theta(2^n)$',r'$2^{2n}\in\omega(2^n)$',r'$2^{2n}\in o(2^n)$',r'$2^{2n}\in O(n^2)$'],'B',r'The ratio $2^{2n}/2^n=2^n$ tends to infinity, which is precisely the strict lower-growth relation inB. The constant2 multiplies$n$ inside an exponent and cannot be discarded as a multiplicative constant on the function. Every exponential here also outgrows fixed$n^2$.'),
('Superpolynomial but subexponential',r'For $f(n)=n^{\log_2n}$, which assertion is correct?', [r'$f\in\Theta(n^2)$',r'$f\in O(n^{100})$',r'$n^k\in o(f)$ for every fixed$k$, and $f\in o(2^n)$.',r'$f\in\Theta(2^n)$'],'C',r'Taking natural logarithms gives $\ln f=(\ln n)^2/\ln2$. Compared with $\ln(n^k)=k\ln n$, the difference tends to infinity; hence every fixed polynomial is smaller. Compared with $\ln(2^n)=n\ln2$, the difference tends to negative infinity, so the ratio to$2^n$ tends to zero. Comparing logarithms establishes ratio behavior only after examining their difference.'),
('Big-oh is not equality',r'If a positive runtime belongs to $O(n^2)$, which further statement must hold?', [r'It belongs to $\Theta(n^2)$.',r'It belongs to $O(n^3)$.',r'It belongs to $\Omega(n^2)$.',r'It belongs to $o(n^2)$.'],'B',r'For $n\ge1$, $n^2\le n^3$, so transitivity gives the weaker cubic upper bound. A linear runtime is a counterexample toA andC. A quadratic runtime is a counterexample toD. An upper bound states a permitted ceiling, not automatically the exact rate or a strict relation.'),
],[(
'Ratio outcomes',r'For eventually positive$g$, a ratio limit0 gives little-oh; a positive finite limit gives tight order; infinity gives little-omega. Failure of a limit leaves the question open: bounded positive oscillation can still give tight order.'),
('Polynomial versus logarithm',r'For fixed $\epsilon>0$, $(\log n)^k/n^\epsilon\to0$ for fixed$k$. Thus $n\log n\in o(n^{1.1})$. A varying exponent or logarithm power is not covered by the fixed-parameter theorem.'),
('Move exponents correctly',r'$a^{\log_b n}=n^{\log_b a}$ for fixed valid bases. Thus $4^{\log_2n}=n^2$. Squaring the logarithm in the exponent instead yields superpolynomial growth; parentheses determine which expression is being compared.'),
('Exponential ratios',r'Compare $a^{cn}$ with $a^n$ by the ratio $a^{(c-1)n}$ for fixed$a>1$. When$c>1$, the ratio diverges. A coefficient inside an exponent is not a dispensable outside constant.'),
('Factorial logarithms',r'Use $\log(n!)=\sum_{j=1}^n\log j$ and upper/lower blocks to establish $\Theta(n\log n)$. This does not imply $n!\in\Theta(n^n)$: exponentiating a tight-order logarithm does not preserve multiplicative tight order.'),
('Fixed binomial index',r'$\binom nr\in\Theta(n^r)$ only when$r$ is a fixed nonnegative integer. For$r=4$, expand four linear factors and divide by24. If$r$ grows with$n$, analyze its factorials instead of treating$r!$ as constant.'),
('Subtract actual functions',r'Expand $(n+1)^3-n^3$ before selecting its dominant term; the answer is quadratic. Bounds on each operand alone do not specify the difference. A difference can even be zero or change sign.'),
('Independent variables',r'$n+m\in\Theta(\max(n,m))$ uniformly, with constants1 and2. To reject a single-variable guess, choose a legal path such as$m=n^2$. A relation imposed between parameters can change the answer and must be stated.'),
('Quantified bound witnesses',r'To prove big-oh, give a constant$c$ and threshold$n_0$ working for every larger input. To refute it, show that every proposed$c,n_0$ admits a violating larger input. A few measured values establish neither statement.'),
('Hierarchy through log differences',r'For $n^{\log_2n}$, compare $\ln f$ with the log of a candidate using their difference, not just their ratio. The difference with a fixed polynomial log diverges upward; the difference with$n\ln2$ diverges downward. This gives strict ratio conclusions.'),
])
chapter('a_loop',r'''
### Derive the integer index region

Write one summation term for each outer iteration before estimating. A triangular nest with inner index1 through$i$ performs $\sum_{i=1}^n i=n(n+1)/2$ body visits. Three strictly increasing indices choose a three-element subset and perform $\binom n3$ visits. Inclusive equality changes the combinatorial object and the exact formula.

If the inner loop visits multiples of$i$ up to$n$, the count is $\lfloor n/i\rfloor$. Summing gives $\sum_{i=1}^n\lfloor n/i\rfloor$, bounded above by$nH_n$ and below by$nH_n-n$, hence order$n\log n$. In contrast, an outer counter doubling while the inner runs up to that counter produces $1+2+4+\cdots$, order$n$; multiplying maximum iterations of both loops gives a loose and misleading bound.

### Count guards and updates separately

A normally terminating pretest loop with$k$ body executions tests its guard$k+1$ times. A break can remove the final failed test, and a continue in a for-loop still executes the update expression. Header operations therefore require a control-flow trace; “body count plus one” is not universally valid after abrupt exits.

### Nonconstant body cost and input dependence

An inner operation copying$i$ entries contributes$i$ work each time it is executed. If there are$i$ inner visits at outer$i$, its contribution is$i^2$, and summation becomes cubic rather than quadratic. For search with early exit, best-case and worst-case counts require separate input witnesses. An inversion-based shifting procedure costs exactly one shift per inversion, but its comparison count can include unsuccessful comparisons as well.
''',[
('Triangular count',r'For $i=1,\ldots,20$, an inner loop executes for $j=1,\ldots,i$. How many body executions occur?', ['190','200','210','400'],'C',r'The exact count is $1+2+\cdots+20=20\cdot21/2=210$. Option190 counts strict pairs with$j<i$. Option400 replaces every inner bound by20 and overcounts. The outer loop is inclusive at20, so neither boundary may be dropped before counting.'),
('Strict triples',r'The body executes for every $1\le i<j<k\le10$. How many executions occur?', ['45','120','165','1000'],'B',r'Each execution corresponds bijectively to a three-element subset of ten indices listed in increasing order. The count is $\binom{10}3=120$. Multiplying ten choices per index ignores strict ordering and distinctness. Option45 counts pairs, not triples; a count allowing equality is a different index region.'),
('Exact multiples',r'For $i=1,\ldots,6$, visit $j=i,2i,\ldots$ while $j\le6$. What is the total?', ['12','14','18','21'],'B',r'The six inner counts are $\lfloor6/i\rfloor=6,3,2,1,1,1$. Their sum is14. The harmonic expression $6H_6$ is an upper approximation, not the exact integer count. The last three outer values each still have their first multiple; dropping them loses three visits.'),
('Geometric outer, dependent inner',r'For $i=1,2,4,\ldots,n$ with $n=2^k$, run an inner body exactly$i$ times. What is the exact total?', [r'$n\log_2 n$',r'$n$',r'$2n-1$',r'$n^2$'],'C',r'The count is $\sum_{r=0}^k2^r=2^{k+1}-1=2n-1$. Maximum inner count$n$ multiplied by the number of outer iterations is only an upper bound and is not tight. Each geometric term must retain its own value; the final term dominates a bounded-ratio sum.'),
('Doubling from every start',r'For each integer$i$ from1 through$n$, initialize$j=i$ and repeatedly double$j$ while$j\le n$. What is the total tight order?', [r'$\Theta(\log n)$',r'$\Theta(n)$',r'$\Theta(n\log n)$',r'$\Theta(n^2)$'],'B',r'Reverse the counting: at doubling level$r$, exactly $\lfloor n/2^r\rfloor$ starting values remain legal. Sum these counts over$r\ge0$. The first level gives$n$ as a lower bound, and the infinite geometric upper bound gives at most$2n$. Many starts near$n$ execute only once, so multiplying every start by the longest chain is loose.'),
('Square-root region',r'For each $i=1,\ldots,n$, count positive$j$ while $j^2\le i$. What is the total tight order?', [r'$\Theta(n)$',r'$\Theta(n\log n)$',r'$\Theta(n^{3/2})$',r'$\Theta(n^2)$'],'C',r'At outer$i$, there are $\lfloor\sqrt i\rfloor$ visits. Their sum is at most$n\sqrt n$. For at least roughly half the outer indices, $i\ge n/2$, so each contributes order$\sqrt n$, giving a matching lower bound. The square in the condition produces a square-root count, not a quadratic count.'),
('Guard tests',r'In a pretest while-loop without break or return, the body executes seven times and then the guard becomes false. How many guard evaluations occur?', ['6','7','8','14'],'C',r'Each of the seven executions is preceded by a successful guard test. An eighth test detects termination. There is no extra body execution after that failed test. Seven counts only successful tests; fourteen wrongly assigns one failed test to every iteration. A break would change the premise and can eliminate the final failed test.'),
('A nonconstant body',r'For $i=1,\ldots,n$, repeat$i$ times a procedure costing exactly$i$ word operations. What is the total tight order?', [r'$\Theta(n)$',r'$\Theta(n^2)$',r'$\Theta(n^3)$',r'$\Theta(n^4)$'],'C',r'Outer$i$ contributes $i\cdot i=i^2$ operations. Therefore total work is $\sum_{i=1}^n i^2=n(n+1)(2n+1)/6$, cubic in$n$. The quadratic body-visit count applies only if each visit costs a constant. The procedure cost and its invocation count must both appear in the summand.'),
('Squaring counter',r'A loop begins at integer$j=2$, executes while$j\le n$, and updates$j=j^2$. Ignoring arithmetic cost and overflow, what is its body count order for large$n$?', [r'$\Theta(\log n)$',r'$\Theta(\log\log n)$',r'$\Theta(\sqrt n)$','It never terminates.'],'B',r'After$t$ updates, $j=2^{2^t}$. The guard is true while $2^t\le\log_2 n$, so the number of legal$t$ values is order$\log\log n$. Starting at0 or1 would instead stall forever, but the specified start2 avoids those fixed points. Counting bit arithmetic would require an additional model.'),
('Input-dependent shifts',r'Insertion-style sorting shifts an earlier entry whenever it exceeds the key being inserted. For $[4,1,3,2]$, how many shifts occur?', ['3','4','5','6'],'B',r'The strict inversions are $(4,1),(4,3),(4,2),(3,2)$, four pairs. Inserting1 shifts4 once; inserting3 shifts4 once; inserting2 shifts4 and3, twice. The total is4. Comparisons can also include a failing comparison and are not identical to this shift count. Equal keys would not create a strict inversion.'),
],[(
'Inclusive arithmetic sum',r'$\sum_{i=1}^n i=n(n+1)/2$; strict$j<i$ gives$n(n-1)/2$. At$n=20$, these are210 and190. Endpoint conventions often account for the entire difference between two candidate answers.'),
('Strict ordered indices',r'$1\le i_1<\cdots<i_r\le n$ yields $\binom nr$ body visits. Increasing order selects one representation per subset. Nondecreasing indices allow repeated values and require a different combination formula.'),
('Multiples and floors',r'Visits$i,2i,\ldots\le n$ number $\lfloor n/i\rfloor$. Sum the floors for an exact count; use $nH_n-n\le\sum\lfloor n/i\rfloor\le nH_n$ for tight asymptotic order. Replacing floors by fractions does not give an exact integer answer.'),
('Reverse the count',r'For doubling chains starting at every$i$, count legal starts per level: $\sum_{r\ge0}\lfloor n/2^r\rfloor$. This lies between$n$ and$2n$. Reversing the sum exposes why the longest-chain bound overestimates total work.'),
('Geometric dependent inner work',r'If outer bounds are1,2,4,...,$n$ and the inner cost equals the bound, the total is$2n-1$ for power-of-two$n$. The independent-loop multiplication rule does not apply to these dependent inner lengths.'),
('Root constraints',r'For $j^p\le i$ with fixed positive$p$, the count per$i$ is $\lfloor i^{1/p}\rfloor$ and the total is $\Theta(n^{1+1/p})$. Establish a lower bound from the final half of outer indices; an upper estimate alone is insufficient.'),
('Headers are distinct events',r'A normally terminating pretest loop tests its guard one more time than body execution. A break exits without the final false guard; a for-loop continue still reaches the update. Count the actual path before applying an endpoint shortcut.'),
('Weighted invocation counts',r'If$i$ calls each cost$i$, the contribution is$i^2$, not$i$. Sum the full operation cost: the resulting square sum is cubic. A procedure call is not a unit-cost event unless the question explicitly supplies that model.'),
('Supermultiplicative counters',r'Starting at2 and squaring yields $2^{2^t}$, so iteration count is doubly logarithmic. Starting at0 or1 never progresses. Finite-width overflow and the cost of large-integer squaring are separate issues that can invalidate the idealized count.'),
('Shifts and inversions',r'In insertion-style movement, every strict inversion induces one shift. For$[4,1,3,2]$, the shift count is4. Include unsuccessful comparisons separately when asked for comparisons, and specify whether equality causes movement.'),
])
