from author import chapter
chapter('g_number',r'''
### Decode the representation before doing arithmetic

For an unsigned$b$-bit word, the value is$\sum_{i=0}^{b-1}x_i2^i$. For two's complement, the most significant bit has weight$-2^{b-1}$ instead. Thus an8-bit word11110110 has unsigned value246 and signed two's-complement value$246-256=-10$. The same physical word can represent different values under different encoding contracts.

Signed addition overflow is detected when equal-sign operands produce an opposite-sign result in a fixed-width two's-complement adder. A carry out alone detects unsigned overflow, not signed overflow. For8 bits,127+1 produces10000000 with no final unsigned carry but with signed overflow;255+1 produces00000000 with unsigned carry but does not represent addition of two positive signed operands.

### Treat binary fractions and fixed point as scaled integers

A binary fraction$0.x_1x_2\ldots$ has weights$2^{-1},2^{-2},\ldots$. A rational$p/q$ in lowest terms terminates in binary exactly when$q$ is a power of two. For a fixed-point word with$f$ fractional bits, the represented value is the decoded integer divided by$2^f$. Addition preserves the scale; multiplication of raw integers doubles the fractional-bit scale and must be rescaled with a specified rounding rule.

### Floating encodings have several regimes

For a specified binary floating format, normal values use an implicit leading1 and exponent field minus bias. Subnormals use no implicit1 and the minimum normal exponent. All-zero exponent and fraction represent signed zero; all-one exponent selects infinities or NaNs depending on the fraction. A decoded bit pattern is therefore not always a finite number. Endianness determines byte order in memory, while bit significance in the value remains unchanged.
''',[
('Base conversion',r'What is the decimal value of hexadecimal$2D$?', ['29','35','45','52'],'C',r'The digitD represents13. Positional evaluation gives $2\cdot16+13=45$. Reading the letter as a decimal digit or interpreting the string as two decimal characters does not respect the base. A check is binary0010 1101, which has weights32+8+4+1=45.'),
('A binary fraction',r'What is the decimal value of binary$101.101$?', ['5.125','5.5','5.625','5.75'],'C',r'The integer part is4+1=5. The fractional positions contribute1/2,0/4 and1/8, totaling5/8. Thus the value is5.625. Treating the fractional digits as101/1000 would incorrectly use decimal rather than binary place values.'),
('Minimum unsigned width',r'What minimum unsigned width can represent every integer from0 through300?', ['8','9','10','300'],'B',r'Eight bits provide256 values and maximum255, insufficient. Nine bits provide512 values and maximum511, sufficient. The exact formula is $\lceil\log_2(301)\rceil=9$. The plus-one counts zero as one of the required values.'),
('Decode two’s complement','Interpret the8-bit word `11110110` as two’s complement. What is its value?', ['-9','-10','-118','246'],'B',r'The unsigned value is246. Since the sign bit is1, subtract256 to obtain$-10$. Alternatively invert to00001001 and add1 to obtain magnitude10. The answer246 uses the unsigned interpretation; sign-magnitude and ones-complement use different negative encodings.'),
('Signed overflow versus carry','In an8-bit two’s-complement adder, add `01111111` and `00000001`. Which flags apply?', ['No signed overflow and no carry out.','Signed overflow but no carry out.','Carry out but no signed overflow.','Both flags.'],'B','The bit sum is10000000, with no ninth-bit carry. Interpreted signed, the mathematical sum128 is outside the range-128 through127, and two positive inputs produced a negative decoded result. Thus signed overflow occurs. Carry-out is an unsigned-range flag and does not detect this signed case.'),
('Sign extension','What16-bit word preserves the value of the8-bit two’s-complement word `11110110`?', ['`0000000011110110`','`1111111111110110`','`0000000000001010`','`1000000011110110`'],'B','Copy the sign bit into all eight new leading positions. The resulting unsigned value is65526, which decodes as65526-65536=-10. Zero extension instead gives positive246 and changes the signed value. Sign extension follows from the negative leading weight in two’s complement.'),
('Fixed-point scale',r'An unsigned8-bit fixed-point format has four fractional bits. What real value is represented by raw integer40?', ['2.5','4','10','40'],'A',r'The scale is$2^4=16$. Divide the raw integer by16, giving40/16=2.5. Four fractional bits means sixteen representable steps per unit, not a division by4 or by ten. The spacing is1/16 and the largest value is255/16.'),
('Binary termination',r'Which reduced rational number has a finite binary expansion?', ['1/10','3/20','7/16','2/15'],'C',r'The reduced denominator16 is a power of two, so7/16 has a terminating expansion, namely0.0111. Denominators10,20 and15 retain an odd prime factor after reduction and cannot divide a power of two. Termination in decimal does not imply termination in binary.'),
('Reflected Gray encoding','For the4-bit binary word `1011`, what is its reflected Gray code?', ['`1110`','`1010`','`0111`','`1101`'],'A','Gray encoding is the XOR of the binary word and its one-bit right shift:1011 XOR0101 gives1110. The leading bit is copied; each later Gray bit XORs neighboring binary bits. Gray code minimizes neighboring-code changes but is not a positional arithmetic representation.'),
('BCD validity','Which4-bit word is invalid as one8421 BCD digit?', ['`0011`','`1001`','`1010`','`0000`'],'C','BCD digit codes represent decimal0 through9.1010 has ordinary binary value10 and lies among the six unused4-bit patterns.1001 represents9 and is valid. A whole decimal number uses one nibble per decimal digit, which differs from encoding the whole number directly in base2.'),
('Little-endian bytes','A32-bit word has hexadecimal value `12345678`. What bytes appear at increasing addresses in little-endian storage?', ['`12 34 56 78`','`78 56 34 12`','`87 65 43 21`','`21 43 65 87`'],'B','Little-endian places the least significant byte78 first, followed by56,34,12. It reverses byte order relative to the written most-significant-first hexadecimal word, not the order of bits within each byte and not the digits within a byte. The numeric value remains the same once the representation is interpreted correctly.'),
('A small normal floating format',r'A toy binary format has one sign bit, three exponent bits with bias3 and four fraction bits. A normal code has sign0, exponent100 and fraction0100. What is its value?', ['1.25','2.5','4.25','10'],'B',r'The exponent field is4, so the unbiased exponent is1. The significand is$1.0100_2=1.25$. The value is$1.25\cdot2^1=2.5$. Forgetting the hidden leading1 or using the raw exponent without bias produces a different result. The question explicitly says normal, so subnormal decoding does not apply.'),
],[(
'Position weights',r'In base$r$, multiply each digit by its power of$r$, with negative powers after the point. Hexadecimal2D is45 and binary101.101 is5.625. Digit validity must be checked before evaluation.'),
('Width bounds',r'Unsigned$b$ bits cover0 through$2^b-1$; two’s complement covers$-2^{b-1}$ through$2^{b-1}-1$. To include unsigned maximum$M$, require $b\ge\lceil\log_2(M+1)\rceil$. The signed interval is asymmetric.'),
('Signed decoding',r'For a two’s-complement word with sign1, subtract$2^b$ from its unsigned value.11110110 is246 unsigned but-10 signed. Do not decode the same word by a sign-magnitude rule unless the format explicitly changes.'),
('Negation boundary',r'Invert bits and add1 to negate a two’s-complement value modulo$2^b$. The minimum signed value negates to the same bit pattern and has no positive counterpart in that width. This is a representability boundary, not an ordinary equality of mathematical integers.'),
('Two overflow flags','Signed overflow occurs when same-sign inputs yield an opposite-sign result. Unsigned overflow is a carry beyond the width.127+1 in8 bits illustrates signed overflow without carry. The flags answer different questions.'),
('Extension rules','Sign-extend two’s complement by copying its sign bit; zero-extend unsigned words. Extending11110110 with zeros changes its signed interpretation from-10 to246. A representation-preserving conversion must follow the original value contract.'),
('Fixed-point scaling',r'With$f$ fractional bits, divide the raw decoded integer by$2^f$. Multiplying two such words produces a raw product with$2f$ fractional bits; rescale before storing back and specify rounding and overflow. Integer multiplication alone does not preserve the original scale.'),
('Terminating fractions',r'A reduced denominator gives a finite binary expansion exactly when it divides a power of two.7/16 terminates;1/10 repeats. Always reduce the fraction first, because removable odd factors do not obstruct termination.'),
('Gray transformations','Encode reflected Gray as `b XOR (b >> 1)`. Decode by cumulative XOR from the leading bit. Adjacent reflected Gray codes differ in one bit, but adding codewords as ordinary binary does not preserve represented numeric addition.'),
('BCD correction','8421 BCD has valid digit codes0000 through1001. A digit sum exceeding9 requires decimal correction, not just ordinary4-bit truncation. Distinguish a BCD carry between decimal digits from a binary carry between bit positions.'),
('Endianness','Little-endian changes byte placement, not bit significance inside a byte.12345678 appears as78 56 34 12 at increasing addresses. Byte swapping and reversing every bit are different operations.'),
('Floating regimes',r'For a normal field use$(-1)^s(1.f)2^{E-\mathrm{bias}}$. An all-zero exponent uses subnormal or zero rules; an all-one exponent selects infinity or NaN. A decoder must classify the regime before applying the normal formula.'),
])
chapter('g_boolean',r'''
### A Boolean expression is a truth table under a stated variable order

An$n$-input function has$2^n$ input rows and$2^{2^n}$ possible output tables. A minterm selects one row with a positive literal for a1 input and a complemented literal for a0 input. A maxterm rejects one row with the opposite polarity rule. With variable order$a,b,c$ and$a$ most significant, row101 has minterm$a\neg b c$ and maxterm$\neg a\lor b\lor\neg c$.

### Cofactors reduce dimensionality

Set$a=0$ and$a=1$ to obtain$F_0,F_1$. Shannon decomposition is $F=\neg a F_0\lor aF_1$. If the cofactors agree, the function does not depend on$a$. Boolean difference is$F_0\oplus F_1$, describing sensitivity to an$a$ transition while other inputs are fixed. Existential elimination is$F_0\lor F_1$ and universal elimination is$F_0\land F_1$; these operations answer different questions from ordinary substitution.

### Use algebraic identities only inside their semantics

Absorption$a\lor ab=a$ follows from the two$a$ cases. The consensus identity$ab\lor\neg a c\lor bc=ab\lor\neg a c$ says that$bc$ does not change the steady-state truth table; it does not say that the extra term has no timing benefit. XOR uses parity: repeated terms cancel and AND distributes over XOR, but ordinary OR does not behave as arithmetic addition modulo2.

To form the algebraic normal form, determine coefficients over the two-element field. For two inputs, the constant coefficient is$F(0,0)$, linear coefficients compare their one-input rows to the constant, and the product coefficient is the XOR of all four output rows. Care-set equivalence is equality only on specified rows; unconstrained outputs are independent bits when counting legal completions.
''',[
('Count function tables',r'How many Boolean functions of three labeled inputs exist?', ['8','64','128','256'],'D',r'Three inputs have eight distinct assignments. Each row chooses its output bit independently, so there are$2^8=256$ tables. Eight counts rows, not functions. Expression syntax can describe the same function in many ways and is not what this count measures.'),
('Canonical maxterm polarity','With variable order$a,b,c$, which maxterm is false exactly at input101?', [r'$a\lor\neg b\lor c$',r'$\neg a\lor b\lor\neg c$',r'$a\land\neg b\land c$',r'$\neg a\land b\land\neg c$'],'B',r'A maxterm is an OR of literals each false at the target row. At101, choose$\neg a$, $b$ and$\neg c$. Their disjunction is false there and true on every other row. OptionC is the corresponding minterm, true at101, not a maxterm false there.'),
('Absorption and distribution',r'Simplify $(a\lor b)\land(a\lor\neg b)$.', [r'$a$',r'$b$',r'$a\lor b$',r'$0$'],'A',r'Distribute in the Boolean lattice: $(a\lor b)(a\lor\neg b)=a\lor(b\land\neg b)=a$. A cofactor check gives0 when$a=0$ and1 when$a=1$, independent of$b$. Treating OR as ordinary addition would not preserve this identity.'),
('Consensus term',r'Which term is redundant in the steady-state SOP$ab\lor\neg a c\lor bc$?', [r'$ab$',r'$\neg a c$',r'$bc$',r'All terms.'],'C',r'If$bc=1$, both$b$ and$c$ are1. For$a=1$, the$ab$ term is1; for$a=0$, the$\neg a c$ term is1. Thus every row covered by$bc$ is already covered by another term. Removing either main term loses rows not covered by the other terms. Timing hazards are a separate implementation question.'),
('XOR cancellation',r'Simplify $a\oplus b\oplus a\oplus1$.', [r'$b$',r'$\neg b$',r'$a\lor b$',r'$0$'],'B',r'XOR is associative and each duplicated$a$ cancels to0. The remaining$b\oplus1$ is$\neg b$. OR would not permit this cancellation; the identity uses parity arithmetic. Neither the result nor its dependence includes$a$.'),
('Shannon reconstruction',r'The$a$-cofactors are$F_0=b$ and$F_1=c$. Which expression represents$F$?', [r'$ab\lor\neg a c$',r'$\neg a b\lor ac$',r'$b\lor c$',r'$bc$'],'B',r'Shannon attaches the0 cofactor to$\neg a$ and the1 cofactor to$a$. Thus$F=\neg a b\lor ac$. OptionA exchanges the control polarity and chooses the wrong data input in each$a$ case. C andD discard the selector and cannot reproduce both arbitrary cofactors.'),
('Sensitivity',r'For$F=\neg a b\lor ac$, what is the Boolean difference with respect to$a$?', [r'$b\lor c$',r'$bc$',r'$b\oplus c$',r'$a$'],'C',r'The two cofactors are$b$ and$c$, so their XOR is$b\oplus c$. Changing$a$ affects the output exactly when those two possible data values differ. OR would incorrectly mark sensitivity when$b=c=1$, where both cofactor outputs are identical.'),
('Existential elimination',r'For$F=ab\lor\neg a c$, what is$\exists a\,F$?', [r'$b\land c$',r'$b\lor c$',r'$b\oplus c$',r'$F$'],'B',r'The cofactor at0 is$c$ and at1 is$b$. Some$a$ value makes$F$ true exactly when at least one cofactor is true, giving$b\lor c$. AND is universal elimination and would require both choices of$a$ to work. XOR instead asks whether the choices differ.'),
('Algebraic normal form',r'Which XOR-polynomial represents$a\lor b$?', [r'$a\oplus b$',r'$a\oplus b\oplus ab$',r'$ab$',r'$1\oplus ab$'],'B',r'At00 the output is0, at01 and10 it is1, and at11 the expression$1\oplus1\oplus1$ is1. The product term repairs XOR at the both-one row. OptionA is exclusive OR and fails there; C is AND and misses the single-one rows.'),
('Don’t-care completions',r'A four-input function has five unconstrained output rows and every other row fixed consistently. How many complete tables satisfy the specification?', ['5','16','32','2048'],'C',r'Each of the five unspecified outputs is an independent bit, producing$2^5=32$ completions. The remaining eleven fixed rows add no choices. Eleven is not the free-row count, so2048 exponentiates the wrong set. Consistency of all fixed requirements is assumed; a contradictory fixed row would give zero.'),
('Monotonicity through cofactors',r'For a Boolean function$F$, which condition is equivalent to being nondecreasing in input$a$?', [r'$F_0=F_1$ only',r'$F_0\Rightarrow F_1$ for every assignment of other inputs',r'$F_1\Rightarrow F_0$',r'$F_0\oplus F_1=1$ everywhere'],'B',r'Changing$a$ from0 to1 must never change the output from1 to0. That is exactly the implication from the0 cofactor to the1 cofactor pointwise. Equal cofactors are sufficient but unnecessarily strong. The reverse implication describes nonincreasing behavior. Always unequal cofactors can include prohibited falling transitions.'),
('Self-dual tables',r'How many self-dual Boolean functions of three inputs satisfy $F(\neg x)=\neg F(x)$?', ['4','8','16','128'],'C',r'The eight input rows form four complementary pairs. Choose one output bit per pair freely; the partner output is then its complement. Thus there are$2^4=16$ functions. No row equals its own bitwise complement for a positive input count, so no impossible self-pair occurs.'),
],[(
'Rows versus functions',r'$n$ inputs give$2^n$ rows and$2^{2^n}$ functions. A constraint on$r$ otherwise independent outputs reduces the free bit count accordingly. Count tables rather than syntactic expressions.'),
('Canonical polarity',r'A minterm matches a row: positive for1, negative for0. A maxterm rejects a row: negative for1, positive for0. For101, the minterm is$a\neg b c$ and the maxterm is$\neg a\lor b\lor\neg c$.'),
('Absorption',r'Use$a\lor ab=a$ and$(a\lor b)(a\lor\neg b)=a$. Verify by the two$a$ cases if a longer expression hides the pattern. Boolean distributivity has two dual forms and is not ordinary numeric multiplication over addition.'),
('Consensus',r'In$ab\lor\neg a c\lor bc$, the$bc$ term is truth-table redundant. It can still cover a transient static hazard in a two-level realization. Functional equivalence does not prove equal delay or hazard behavior.'),
('XOR field arithmetic',r'Repeated XOR terms cancel, and$a\lor b=a\oplus b\oplus ab$. The product term matters at11. Negation is XOR with1, not deletion of a literal.'),
('Shannon polarity',r'$F=\neg aF_0\lor aF_1$. Write the cofactor subscripts beside their control literals before mapping a selector. Equal cofactors remove dependence on$a$; different cofactors do not necessarily make$a$ monotone.'),
('Boolean difference',r'$\partial_aF=F_0\oplus F_1$ identifies settings where changing$a$ changes$F$. This is a Boolean sensitivity function, not a real derivative or the OR of both cofactors.'),
('Quantified elimination',r'Existential elimination uses$F_0\lor F_1$; universal elimination uses$F_0\land F_1$. A single input witness is enough for the first, while both values must work for the second. Cofactor substitution itself is neither operation.'),
('Algebraic normal form','All coefficients are Boolean and the sum operation is XOR. The constant coefficient is the all-zero output. For two inputs, the product coefficient is the XOR of all four table values; check the11 row after determining the linear coefficients.'),
('Care-set equivalence',r'Two circuits meet a partial specification if they agree on every cared-about row. Five independent don’t-care outputs admit32 completions. An implementation that differs on a care row fails even if it is simpler or agrees on most inputs.'),
('Unateness test',r'Nondecreasing in$a$ means$F_0\Rightarrow F_1$; nonincreasing means$F_1\Rightarrow F_0$. Equal cofactors satisfy both and mean independence. A syntactic complemented occurrence is not by itself a semantic monotonicity proof.'),
('Self-dual pair count',r'For$n\ge1$, complementary input rows form$2^{n-1}$ pairs, so self-dual tables number$2^{2^{n-1}}$. One output per pair is free and the other forced opposite. Complementing only an output is not the self-dual condition.'),
])
chapter('g_gates',r'''
### Separate Boolean equivalence from circuit cost

A NAND-only realization derives NOT as NAND of a signal with itself, AND as NAND followed by inversion, and OR by De Morgan using inverted inputs. Tying two inputs together is one two-input gate under this library convention; it is not free unless the cost model says so. A NAND implementation of XOR uses four shared gates; realizing separate expanded SOP terms without sharing can cost more.

For a two-level SOP, map product terms into first-level NANDs and combine their inverted outputs with a final NAND. A two-level POS maps dually into NORs. Gate fan-in constraints can add intermediate gates. Inverting gates are not associative: a cascade of NAND gates generally does not implement a larger NAND without a polarity correction.

### Derive timing from actual sensitized paths

Latest stable arrival through a gate is bounded by its maximum input arrival plus propagation delay. Earliest possible output contamination uses the earliest relevant input change plus contamination delay, with controlling-value and sensitization conditions checked. A topological timing calculation is not a proof that every longest graph path is sensitizable.

For$F=ab\lor\neg a c$ with$b=c=1$, a transition in$a$ exchanges the two product terms. Unequal path delays can temporarily make both zero even though the steady-state output is1. The consensus term$bc$ keeps a continuous1 coverage under the standard single-input, two-level static-hazard assumptions. This guarantee does not cover arbitrary simultaneous input changes or every multilevel dynamic hazard.

### Physical formulas require their activity convention

In the elementary RC model, charging a load$C$ through resistance$R$ toward a step voltage reaches fraction$1-e^{-t/(RC)}$. Reaching half the final value takes$RC\ln2$. Charging from an ideal supply uses$CV^2$ energy, half stored in the capacitor and half dissipated in the resistor. Average dynamic supply power is$\alpha CV^2f$ when$\alpha$ counts zero-to-one charging events per clock cycle; a different activity definition changes the prefactor.
''',[
('NAND truth condition',r'When is a three-input NAND output zero?', ['Whenever any input is zero.','Only when all three inputs are one.','Whenever an odd number of inputs are one.','Only when all inputs are zero.'],'B','NAND negates the AND of all its inputs. The underlying AND equals1 only on111, so the NAND is0 only there. A zero input is a controlling input for AND and forces the NAND output to1. The odd-parity rule describes a different gate.'),
('NAND-only OR',r'Two-input NAND gates are allowed and inputs may be tied. How many gates does the direct De Morgan construction of$a\lor b$ use?', ['1','2','3','4'],'C',r'Invert$a$ with NAND$(a,a)$ and invert$b$ with NAND$(b,b)$. A third NAND of these inverted signals yields$\neg(\neg a\land\neg b)=a\lor b$. This counts the stated construction, not a minimum over an enriched library with free input complements. Omitting an inverter changes one literal polarity.'),
('A NAND cascade error',r'Let$u=\neg(ab)$ and$y=\neg(uc)$. Which expression is$y$?', [r'$\neg(abc)$',r'$ab\lor\neg c$',r'$ab\lor c$',r'$a\oplus b\oplus c$'],'B',r'Apply De Morgan to the final NAND: $y=\neg u\lor\neg c=ab\lor\neg c$. Setting$c=0$ makes the output1, and setting$c=1$ yields$ab$. A simple cascade therefore does not implement a three-input NAND; a missing polarity-restoring inversion explains the difference.'),
('XOR shared NAND network',r'The standard shared implementation computes$t=\operatorname{NAND}(a,b)$,$u=\operatorname{NAND}(a,t)$,$v=\operatorname{NAND}(b,t)$,$y=\operatorname{NAND}(u,v)$. What is$y$?', [r'$a\land b$',r'$a\lor b$',r'$a\oplus b$',r'$\neg(a\oplus b)$'],'C','For00, the intermediate values are$t=u=v=1$, giving$y=0$. For01 or10, exactly one of$u,v$ is0, giving$y=1$. For11,$t=0$ and$u=v=1$, giving0. These four values identify XOR. The intermediate$t$ is shared, and duplicating its computation changes the gate count.'),
('Functional completeness','With no external constants or complemented inputs, which two-input gate alone is functionally complete?', ['AND','OR','XOR','NOR'],'D','NOR constructs NOT by tied inputs. It then constructs OR by following a NOR with inversion and AND through De Morgan with inverted inputs, giving a complete basis of AND, OR and NOT. AND and OR cannot express negation; XOR alone generates affine parity functions and cannot express arbitrary conjunction.'),
('Static CMOS transistor count','In the ideal complementary static-CMOS model, how many transistors implement a three-input NAND without extra buffers?', ['3','4','6','8'],'C','The pull-down network has three series nMOS devices, conducting only when every input is high. The dual pull-up network has three parallel pMOS devices, conducting when any input is low. Total count is six. The answer counts one complementary gate, not a cascade of two-input gates or a buffered cell.'),
('Latest arrival calculation','A two-input gate has propagation delay3ns. Its input stable-arrival times are2ns and7ns. Using the conservative max-input timing rule, what is the latest output stable time?', ['5ns','7ns','10ns','12ns'],'C',r'The output cannot be guaranteed stable until the last relevant input is stable and the gate’s propagation bound has elapsed. Compute$\max(2,7)+3=10$ns. Summing the two input arrival times counts parallel histories as serial work. Sensitization can tighten a particular case, but the stated conservative rule gives10.'),
('Serial contamination delay','Two gates on a sensitized serial path have contamination delays1ns and2ns. What path lower bound follows for an output change after the initiating input change?', ['1ns','2ns','3ns','0ns'],'C','An input change must traverse the first gate before it can initiate a change in the second. The two lower bounds add to3ns on the stated sensitized serial path. Parallel alternatives could give earlier changes, so the question restricts the path being analyzed. Contamination delay is an earliest-change lower bound, not a latest-stability guarantee.'),
('A static-one hazard repair',r'For$F=ab\lor\neg a c$, what extra product term removes the classic single-$a$ static-one hazard in the two-level model?', [r'$ac$',r'$\neg b\neg c$',r'$bc$',r'$a\neg a$'],'C',r'The hazard case has$b=c=1$ while$a$ changes. The consensus term$bc$ stays1 throughout the transition and prevents a temporary output fall. It adds no new steady-state true rows because each such row was already covered by$ab$ or$\neg a c$. The other candidate terms do not provide constant coverage during both polarities of$a$.'),
('RC half-voltage time',r'A first-order node charges with time constant$RC=10$ns. When does it reach half its final voltage?', ['5ns',r'$10\ln2$ns','10ns','20ns'],'B',r'Solve$1-e^{-t/(RC)}=1/2$. Then$e^{-t/(RC)}=1/2$, so$t=RC\ln2=10\ln2$ns, about6.93ns. Half voltage is not reached at half a time constant because the charging trajectory is exponential.'),
('Dynamic power ratio',r'In$P=\alpha CV^2f$, voltage doubles and frequency halves while$\alpha,C$ stay fixed. What is the power ratio?', ['1/2','1','2','4'],'C',r'Voltage contributes a factor$2^2=4$, and frequency contributes1/2. Their product is2. A linear voltage assumption would incorrectly predict no change. This compares dynamic charging power under a fixed activity convention; leakage and short-circuit power are not included by this elementary formula.'),
('Stored versus supplied energy',r'An initially uncharged capacitor$C$ is charged to$V$ through a resistor from an ideal constant supply. What energy remains stored?', [r'$CV^2$',r'$CV^2/2$',r'$2CV^2$',r'$CV/2$'],'B',r'Stored energy is$\int_0^{CV}(q/C)\,dq=CV^2/2$. The supply delivers$V\int i\,dt=CV^2$; the other half is dissipated during ideal resistive charging. Confusing stored energy with supply energy introduces the factor-two error. The answer$CV/2$ has the wrong physical dimension for energy.'),
],[(
'Controlling inputs','For AND and NAND, any0 fixes the underlying AND to0; the NAND output is therefore1. For OR and NOR, any1 fixes the OR to1; the NOR output is0. Parity gates have no single controlling input in the same sense.'),
('Mapping polarity',r'SOP naturally maps into NAND-NAND; POS into NOR-NOR. Write the inversion at each intermediate wire before counting gates. Complemented inputs are free only if the specified library provides them at no extra cost.'),
('Inverting gates are not associative',r'$\operatorname{NAND}(\operatorname{NAND}(a,b),c)=ab\lor\neg c$. It is not a three-input NAND. Cascaded decompositions must restore the internal polarity where required.'),
('Shared XOR cost','The standard four-NAND XOR reuses the first NAND output twice. Fanout is not an extra logical gate under this count, but buffering may add physical cost in a different model. Count unique instances, not repeated occurrences of a shared subexpression.'),
('Completeness assumptions','NAND and NOR construct negation with tied inputs and form complete libraries. XOR alone generates affine functions. Constants, complemented external inputs and fan-in restrictions are part of the library and can change the completeness question.'),
('Static CMOS dual networks','An$n$-input NAND uses$n$ series nMOS and$n$ parallel pMOS devices, total$2n$, in the ideal unbuffered model. NOR reverses series and parallel roles. Compound gates need the dual pull-up graph, not merely the same graph with device names changed.'),
('Arrival recurrence',r'Conservative latest output arrival is$\max_i a_i+t_{pd}$. Serial path delays add; parallel input arrival times take a maximum. A longest graph path may be unsensitizable, so distinguish structural bounds from attainable transition timings.'),
('Contamination versus propagation','Contamination bounds the earliest possible change; propagation bounds latest guaranteed stabilization. Summing contamination delays is a path-specific lower bound under a sensitized serial model. It does not guarantee the output has settled at that time.'),
('Static hazard consensus',r'For$ab\lor\neg a c$, add$bc$ to maintain coverage while$a$ changes and$b=c=1$. This is a single-input static-one guarantee in a two-level model. It does not eliminate every functional hazard from multiple changing inputs.'),
('RC threshold',r'At voltage fraction$q$, first-order charging takes$-RC\ln(1-q)$. Half voltage takes$RC\ln2$. A specified threshold and model are needed before using an RC delay as a gate timing number.'),
('Activity convention',r'$P=\alpha CV^2f$ assumes$\alpha$ counts charging events per cycle. Doubling voltage and halving frequency doubles this power. If activity counts every edge instead, a factor-of-two convention change may be necessary.'),
('Energy distinction',r'Charging from0 to$V$ supplies$CV^2$, stores$CV^2/2$ and dissipates$CV^2/2$ in the simple resistive model. During discharge the stored half is dissipated. A full charging/discharging cycle therefore uses the full supply-energy expression.'),
])
