from author import chapter
chapter('d_relations',r'''
### Count independent local relation choices

For$n$ labeled objects, a relation is an$n\times n$ Boolean matrix. There are$2^{n^2}$ arbitrary relations. Reflexivity fixes all diagonal entries to1 and leaves$n(n-1)$ free bits. Symmetry ties each off-diagonal pair and leaves$n(n+1)/2$ independent bits. Combining reflexivity with symmetry leaves only$n(n-1)/2$ free bits. Antisymmetry forbids only the both-directions state for distinct objects, so every unordered off-diagonal pair has three choices; each diagonal remains independently optional. The antisymmetric count is therefore$2^n3^{n(n-1)/2}$. Asymmetry additionally forbids every diagonal and has count$3^{n(n-1)/2}$.

Transitivity couples several pairs, so these local-choice products do not count transitive relations. Equivalence relations instead correspond to partitions; their count is the Bell number, with a fixed number of classes counted by a Stirling number of the second kind. A class of size$k$ contributes$k^2$ ordered pairs to the relation. Summing class sizes does not count relation edges.

### Use Boolean multiplication for composition

With the convention $(x,z)\in S\circ R$ when there exists$y$ with$xRy$ and$ySz$, the matrix entries use OR of AND-products. Multiple witnesses do not create multiplicity in a relation. The transitive closure includes paths of positive length; the reflexive-transitive closure additionally includes zero-length paths, hence the full diagonal. A cycle can make diagonal pairs appear even in the positive-length closure.

### Read a Hasse diagram without confusing four extrema

Minimal means no strictly smaller element; least means below every element. Multiple minimal elements can exist but a least element is unique. For a pair, an upper bound must dominate both; a least upper bound must also lie below every common upper bound. If two incomparable minimal upper bounds exist, there is no join. Hasse edges show covers, omitting loops and transitive edges; reachability reconstructs the order. In the divisor order of a positive integer, meet is gcd and join is lcm, both still divisors of the ambient integer.
''',[
('Reflexive relation count',r'How many reflexive relations exist on three labeled objects?', ['8','32','64','512'],'C',r'The three diagonal positions are forced1. Six off-diagonal positions remain independently free, yielding$2^6=64$.512 counts all nine bits free. Reflexivity does not restrict off-diagonal direction pairs or impose symmetry.'),
('Reflexive symmetric count',r'How many relations on four labeled objects are both reflexive and symmetric?', ['16','64','128','1024'],'B',r'Reflexivity fixes the four diagonal bits. There are$\binom42=6$ unordered distinct pairs, each choosing either both directions or neither. Hence$2^6=64$. Counting twelve ordered off-diagonal bits independently would violate symmetry.'),
('Antisymmetric count',r'How many antisymmetric relations exist on three labeled objects?', ['27','64','216','512'],'C',r'Each of the three diagonal positions is free, giving$2^3$. Each of three unordered distinct pairs has options neither direction, forward only or backward only, giving$3^3$. The product is$8\cdot27=216$. Removing all diagonal choices would count asymmetric rather than antisymmetric relations.'),
('Symmetric and antisymmetric',r'How many relations on four labeled objects are simultaneously symmetric and antisymmetric?', ['1','4','16','64'],'C',r'For distinct objects, symmetry would require both directions whenever one is present, but antisymmetry forbids both. Thus no off-diagonal pair can occur. Each of four diagonal pairs remains optional, yielding$2^4=16$. If reflexivity were added, all four would be forced and only the identity relation would remain.'),
('Equivalence edges',r'An equivalence relation has three classes of sizes2,3 and4. How many ordered pairs does it contain?', ['9','18','29','81'],'C',r'Every class relates all of its elements to every element of that same class, including itself. The total is$2^2+3^2+4^2=4+9+16=29$.81 would relate all nine objects across classes as well. Counting unordered pairs omits directions and diagonal loops.'),
('Two-class partitions',r'How many equivalence relations on four labeled objects have exactly two classes?', ['6','7','8','15'],'B',r'Choose a nonempty proper subset to be one class: there are$2^4-2=14$ choices. Each partition is counted twice, once by either class, so divide by2 to obtain7. The total Bell number15 counts every possible class count, not just two classes.'),
('Composition direction',r'Let$R=\{(1,2),(2,3)\}$ and$S=\{(2,1),(3,2)\}$. Under the stated convention, what is$S\circ R$?', [r'$\{(1,1),(2,2)\}$',r'$\{(2,2),(3,3)\}$',r'$\{(1,3)\}$',r'$\varnothing$'],'A',r'Follow an$R$ edge first and then an$S$ edge. The path1 to2 to1 gives(1,1), and2 to3 to2 gives(2,2). No$R$ edge begins at3. The second option is the reversed composition. Writing the witness condition before following edges prevents a convention-dependent reversal.'),
('Positive-length closure of a cycle',r'On$\{1,2,3\}$, let$R=\{(1,2),(2,3),(3,1)\}$. How many pairs lie in its transitive closure?', ['3','6','9','12'],'C',r'From each starting vertex, one step reaches the next, two reach the remaining vertex, and three return to the start. Thus every ordered pair is reachable by a positive-length path, including every diagonal pair. There are$3^2=9$ pairs. A transitive closure need not be irreflexive when the original graph has a cycle.'),
('Asymmetric versus antisymmetric',r'Which relation on$\{1,2\}$ is antisymmetric but not asymmetric?', [r'$\{(1,1)\}$',r'$\{(1,2)\}$',r'$\varnothing$',r'$\{(1,2),(2,1)\}$'],'A',r'A permits a diagonal loop, allowed by antisymmetry because its two endpoints are equal. Asymmetry forbids every diagonal pair. B andC are asymmetric; D violates antisymmetry through a distinct bidirectional pair. The two property names differ in their diagonal requirement, not just in wording.'),
('Minimal versus least',r'In the divisor order on$\{2,3,6\}$, which statement is correct?', ['2 is least.','3 is least.','There are two minimal elements and no least element.','There are no minimal elements.'],'C',r'Neither2 nor3 has a strictly smaller element in this set, so both are minimal. But2 does not divide3 and3 does not divide2; neither is below every element.6 is greatest. Removing the divisor1 from the ambient set removed the least element without removing all minimal elements.'),
('Meet and join',r'In the divisor lattice of60, what are the meet and join of12 and20?', ['(4,60)','(2,60)','(4,240)','(12,20)'],'A',r'The greatest common divisor is4, the largest common lower bound in divisibility. The least common multiple is60, the least common upper bound. Both belong to the divisor set of60. Ordinary numeric minimum and maximum do not define the meet and join for this order.'),
('Linear extensions',r'A poset has four labeled elements with only the strict requirements$a<b$ and$c<d$. How many linear extensions does it have?', ['4','6','8','12'],'B',r'Choose which two of the four positions hold the$a,b$ chain; their internal order is forced. The remaining two positions hold$c,d$ in their forced order. This gives$\binom42=6$. Counting all$4!$ orders and dividing by the two independent pair-order factors4 gives the same result.'),
('Scheduling layers',r'A finite poset has longest chain length5 and tasks take one unit with unlimited processors. What is the minimum number of precedence-respecting time slots?', ['1','4','5','The width.'],'C',r'Every five-element chain needs five distinct successive slots, giving a lower bound. Assign each element a level equal to the longest chain ending there; comparable elements have strictly increasing levels. These five levels provide a feasible schedule, attaining the bound. Width describes simultaneous incomparability, not the required serial depth.'),
('Chain partition duality',r'A finite poset has largest antichain size4. What does Dilworth’s theorem guarantee?', ['Every chain has length4.','A partition into four chains exists, and fewer cannot suffice.','Exactly four maximal elements exist.','Exactly four linear extensions exist.'],'B',r'An antichain of four requires four different chains in any chain partition, because a chain cannot contain two incomparable members. Dilworth supplies a matching partition into four chains. Neither the longest chain nor the number of maximal elements or linear extensions is determined by width alone.'),
],[(
'Relation bit counts',r'Arbitrary$n$-object relations number$2^{n^2}$; reflexive ones number$2^{n(n-1)}$. Diagonal requirements fix$n$ bits, not an entire row. Other properties can couple the remaining bits.'),
('Symmetry count',r'Symmetric relations number$2^{n(n+1)/2}$; adding reflexivity reduces this to$2^{n(n-1)/2}$. Choose one bit per unordered off-diagonal pair, and handle each diagonal independently.'),
('Antisymmetric count',r'Antisymmetric relations number$2^n3^{n(n-1)/2}$. Asymmetric relations number$3^{n(n-1)/2}$. The factor$2^n$ is exactly the optional diagonal; transitivity is not included in either product.'),
('Equivalence blocks',r'A class of size$k$ contributes$k^2$ ordered pairs. For class sizes2,3,4 the relation has29 pairs. Counting partitions gives equivalence relations; counting partitions with exactly$r$ blocks gives a Stirling number, not the Bell total.'),
('Two-block formula',r'For$n\ge1$, two-class partitions number$(2^n-2)/2=2^{n-1}-1$. Exclude empty and full subsets, then remove the double count from selecting either class. Ordered labeled classes would omit the final division.'),
('Composition direction',r'Write$(x,z)\in S\circ R$ iff some$y$ satisfies$xRy$ and$ySz$. Follow$R$ then$S$. Boolean matrix multiplication uses OR of AND, so two witnesses still produce one pair.'),
('Closure diagonals',r'Transitive closure uses positive-length paths; cycles can create diagonal pairs. Reflexive-transitive closure explicitly adds zero-length paths. A three-cycle reaches all nine pairs, even without original loops.'),
('Property counterexamples',r'To refute transitivity, find$xRy,yRz$ with missing$xRz$. To refute antisymmetry, find distinct objects related both ways. A loop alone refutes asymmetry, not antisymmetry.'),
('Hasse reconstruction','Hasse edges are covers, with reflexive and transitive pairs omitted from the drawing. Use reachability to recover comparisons. A missing direct edge does not mean two elements are incomparable.'),
('Extrema distinctions','Minimal means no smaller member; least means below every member. In divisors2,3,6, the two minimal elements are2 and3 but no least exists. Greatest and maximal have the dual distinction.'),
('Bounds and joins','A join is below every common upper bound, not merely one minimal-looking upper bound. In a divisor lattice meet is gcd and join is lcm. Two incomparable minimal upper bounds imply no least upper bound.'),
('Linear extensions',r'Two independent chains of lengths$r,s$ have$\binom{r+s}r$ interleavings when no extra comparisons exist. Additional precedence edges remove legal interleavings; do not reuse the unconstrained binomial formula blindly.'),
('Height and scheduling','With unit tasks and unlimited processors, required slots equal longest-chain length. The level construction attains the chain lower bound. Processor limits or nonunit durations change the model.'),
('Width and chain partitions','Dilworth equates maximum antichain size with minimum chain-partition count for finite posets. Height instead equals minimum antichain-layer count. These dual quantities answer different scheduling and decomposition questions.'),
])
chapter('d_functions',r'''
### Count fibers before assigning inverse choices

A function from an$n$-element domain to an$m$-element codomain selects one of$m$ outputs independently for every input, giving$m^n$. Injectivity requires distinct outputs and gives$m!/(m-n)!$ if$n\le m$. Surjectivity requires nonempty fibers and is counted by inclusion-exclusion: $\sum_{j=0}^m(-1)^j\binom mj(m-j)^n$. A codomain label outside the image is a failure of surjectivity even if every domain element has a legal output.

For an onto function with fiber sizes$s_1,\ldots,s_m$, a right inverse chooses one representative in every fiber, giving$\prod s_i$ choices. A left inverse of an injection must undo its image points, while its values outside the image are free choices in the original domain. These counts require careful empty-set cases; a nonempty set has no function into the empty set.

### Composition preserves some facts in only one direction

If$g\circ f$ is injective, $f$ is injective; $g$ need only be injective on the image of$f$. If$g\circ f$ is surjective, $g$ is surjective; $f$ need not fill the whole intermediate set. Full injectivity of both factors is sufficient for injective composition, and full surjectivity of both is sufficient for surjective composition. The converse does not follow in the unused part of the intermediate space.

### Images merge fibers; preimages do not

Preimages preserve unions, intersections and relative complements under the stated total-function types. Images preserve unions but can merge intersections: two disjoint domain subsets may share an output. The round trip$f^{-1}(f(S))$ contains$S$ and adds every other domain point in fibers touched by$S$. Equality means$S$ is a union of whole fibers. Global equality for every$S$ is equivalent to injectivity.

### Infinite counting needs explicit maps

Finite equality of domain and codomain sizes makes injectivity equivalent to surjectivity, but infinite examples break that equivalence. On the nonnegative integers, $n\mapsto n+1$ is injective and not onto. Cantor’s diagonal set$D=\{x:x\notin f(x)\}$ cannot equal$f(d)$ for any$d$ and proves no surjection from a set onto its power set. This is a structural argument, not a finite truth-table count.
''',[
('Unrestricted functions',r'How many functions map a four-element labeled domain to a three-element labeled codomain?', ['12','24','36','81'],'D',r'Each of four domain elements selects one of three outputs independently, giving$3^4=81$. Functions may repeat outputs.36 would count onto functions, and24 suggests a permutation rule without matching domain and codomain sizes. Every domain point must have one output, not an optional output.'),
('Injections',r'How many injections map a three-element domain into a five-element codomain?', ['15','60','125','243'],'B',r'Select distinct output choices successively:5 choices, then4, then3, giving60. Equivalently choose an image subset in$\binom53=10$ ways and biject the three inputs to it in$3!=6$ ways.125 permits collisions and counts all functions.'),
('Surjections onto two values',r'How many surjections map a five-element domain onto a two-element codomain?', ['16','30','31','32'],'B',r'All maps number$2^5=32$. Exactly two are not onto: the constant map to either codomain element. Subtract both to obtain30. Removing only one constant gives31 and violates the symmetry between codomain labels.'),
('Exactly three image values',r'How many functions from four labeled inputs to five labeled outputs have image size exactly3?', ['120','240','360','625'],'C',r'Choose the three used outputs in$\binom53=10$ ways. Onto maps from four inputs to those three number36 by inclusion-exclusion. Their product is360. Each function has one uniquely determined image set, so this multiplication does not overcount.'),
('Right inverse choices',r'An onto function has three fibers of sizes2,3,4. How many right inverses does it have?', ['9','12','24','29'],'C',r'A right inverse selects one preimage for each codomain element. The independent choices are2,3,4, giving24. The sum9 counts total domain points but not complete representative selections.29 counts ordered pairs within fibers and belongs to an equivalence-relation question instead.'),
('Left inverse choices',r'An injection maps a three-element domain into a five-element codomain. How many left inverses from the codomain back to the domain exist?', ['3','6','9','15'],'C',r'On the three image points the left inverse is forced to return their original inputs. On each of the two remaining codomain points, any of three domain values can be chosen. The count is$3^2=9$. The unused points are not constrained by$h\circ f=\mathrm{id}$.'),
('Injective composition',r'If$g\circ f$ is injective, which conclusion must follow?', [r'$f$ is injective.',r'$g$ is injective on its whole domain.',r'$f$ is onto.',r'$g$ is onto.'],'A',r'If$f(x)=f(y)$, applying$g$ gives equal composite outputs. Composite injectivity forces$x=y$, proving$f$ injective. The behavior of$g$ away from$f$’s image is unconstrained. A one-point image inside a larger intermediate set can hide collisions of$g$ outside that image.'),
('Surjective composition',r'If$g\circ f$ is onto its codomain, which conclusion must follow?', [r'$f$ is onto its codomain.',r'$g$ is onto its codomain.',r'$f$ is injective.',r'$g$ is injective.'],'B',r'Every final output is$g(f(x))$ for some input$x$, so it has a preimage under$g$. Thus$g$ is onto. The subset$f$ reaches may already contain one witness for every final output, so$f$ need not fill the intermediate codomain. Neither condition prohibits collisions.'),
('Preimage algebra',r'Which equality holds for every total function$f$ and codomain subsets$B,C$?', [r'$f^{-1}(B\cap C)=f^{-1}(B)\cap f^{-1}(C)$',r'$f(S\cap T)=f(S)\cap f(T)$ for all$S,T$',r'$f^{-1}(f(S))=S$ for every$S$',r'$f(f^{-1}(B))=B$ for every$B$'],'A',r'An input belongs to the left side exactly when its one output belongs to both$B$ and$C$, so it belongs to both preimages. Images can merge separate points, refutingB andC without injectivity. The final round trip equals$B\cap\operatorname{im}f$, not all$B$ unless those outputs are reached.'),
('Fiber saturation',r'$f(1)=f(2)=a$ and$f(3)=b$. What is$f^{-1}(f(\{1\}))$?', [r'$\{1\}$',r'$\{1,2\}$',r'$\{a\}$',r'$\{1,2,3\}$'],'B',r'The image of$\{1\}$ is$\{a\}$. Its preimage contains every input with output$a$, namely1 and2. The round trip fills the entire touched fiber. A tests injectivity where it fails; C is in the codomain rather than the required domain; D adds a point with a different output.'),
('Involutions on four objects',r'How many permutations$f$ on four labeled objects satisfy$f\circ f=\mathrm{id}$?', ['4','8','10','24'],'C',r'Every cycle must have length1 or2. There is one identity, six choices of a single transposition, and three ways to pair all four objects into two disjoint transpositions. Total$1+6+3=10$. All24 permutations include3-cycles and4-cycles, which do not square to identity.'),
('Idempotent maps with two fixed points',r'On a four-element labeled set, how many functions satisfy$f\circ f=f$ and have image size2?', ['12','24','36','48'],'B',r'Every image point of an idempotent map is fixed: if$y=f(x)$, then$f(y)=f(f(x))=f(x)=y$. Choose the two image/fixed points in6 ways. Each of the other two points independently maps to either one, giving4 choices. Total24. The image points themselves are not free assignments.'),
('Empty-set typing',r'For nonempty$A$, which function set contains exactly one member?', [r'Functions$A\to\varnothing$.',r'Functions$\varnothing\to A$.',r'Bijections$A\to\varnothing$.',r'Surjections$\varnothing\to A$.'],'B',r'The empty function has no input obligations and is the unique function from the empty domain to any codomain. No total function maps a nonempty domain into an empty codomain because an input would lack an output. The empty function cannot be onto nonempty$A$.'),
('Infinite injection without surjection',r'On$\mathbb N_0$, which description applies to$f(n)=n+1$?', ['Bijective.','Injective but not surjective.','Surjective but not injective.','Neither.'],'B',r'Equality of outputs$n+1=m+1$ forces$n=m$, so injectivity holds. The codomain element0 has no preimage, so surjectivity fails. Equal infinite domain and codomain sets do not supply the finite pigeonhole equivalence between these properties.'),
('Function-space size',r'For finite$A,B,C$ with sizes2,3,4, how many functions$(A\times B)\to C$ exist?', ['24','64','729','4096'],'D',r'The product domain has six elements, and each chooses one of four outputs, so the count is$4^6=4096$. Currying gives a bijection with maps$A\to C^B$, whose codomain has$4^3=64$ members and count$64^2=4096$. The count24 multiplies sizes rather than counting function tables.'),
('Cantor’s diagonal contradiction',r'For$f:A\to\mathcal P(A)$, define$D=\{x\in A:x\notin f(x)\}$. Why can$D$ not be$f(d)$ for any$d\in A$?', [r'It would force$d\in D\Leftrightarrow d\notin D$.',r'Every subset of$A$ is empty.',r'$f$ must be injective.',r'$A$ must be finite.'],'A',r'If$D=f(d)$, substituting$d$ into the defining membership rule gives$d\in D$ exactly when$d\notin f(d)$, hence exactly when$d\notin D$. Either truth value contradicts itself. No finiteness assumption or injectivity is used. This proves the diagonal subset is missing from every proposed image.'),
],[(
'Function counts',r'Total maps give$m^n$; injections give$m!/(m-n)!$ for$n\le m$; bijections of equal finite size give$n!$. State whether maps are total, partial or onto. Partial maps add a distinguished “undefined” option and number$(m+1)^n$.'),
('Onto and image size',r'Count onto maps by missing-output inclusion-exclusion. For image size$r$, choose$r$ outputs and multiply by the onto count into them. Four inputs and five outputs with image size3 give$\binom53\cdot36=360$.'),
('Right inverses',r'For an onto finite map, right inverse count is the product of fiber sizes. Fibers2,3,4 give24 choices. A missing fiber gives no right inverse, because its output has no representative.'),
('Left inverses',r'For an injection from$n>0$ points into$m$, the image values of a left inverse are forced and the$m-n$ others each have$n$ choices: $n^{m-n}$. Empty-domain cases require direct typing rather than casual use of$0^0$.'),
('Composition implications',r'Composite injective implies first map injective; composite onto implies second map onto. The reverse component conclusions fail on unused intermediate points. Restrict the second map to the first image before making a stronger assertion.'),
('Cancellation sides',r'An injective postcomposition permits canceling the post-map from$g\circ f_1=g\circ f_2$. An onto precomposition permits canceling the pre-map. Swapping these hypotheses changes which values the equality actually tests.'),
('Preimage preservation',r'Preimages preserve unions, intersections and codomain-relative complements for total functions. This uses one output per input, not invertibility. The notation$f^{-1}(B)$ is a set operation even when no inverse function exists.'),
('Image loss',r'Images preserve unions but can enlarge intersections through collisions. For$1,2$ in one fiber, images of the disjoint singletons intersect. Images preserve all intersections exactly when the function is injective.'),
('Saturation round trip',r'$f^{-1}(f(S))$ is the union of fibers touched by$S$ and equals$S$ precisely when$S$ is already fiber-saturated. The codomain round trip is$f(f^{-1}(B))=B\cap\operatorname{im}f$.'),
('Involution versus idempotence',r'An involution has$f^2=\mathrm{id}$ and consists of fixed points and swaps. An idempotent has$f^2=f$ and fixes every image point. With a chosen$r$-point image on$n$ points, idempotent count is$\binom nr r^{n-r}$ for$r\ge1$.'),
('Empty function',r'There is one map from the empty domain to any codomain. There is no map from a nonempty domain to the empty codomain. A map is onto an empty codomain only when the domain is empty as well.'),
('Infinite finite-rule failure',r'On nonnegative integers,$n\mapsto n+1$ is an injection missing0. A surjection can likewise merge points in an infinite domain. Use explicit fibers or missing outputs rather than finite cardinality cancellation.'),
('Currying',r'Maps$(A\times B)\to C$ correspond to maps$A\to C^B$. Finite size becomes$|C|^{|A||B|}=(|C|^{|B|})^{|A|}$. This rearranges a function representation, not an ordinary Cartesian product of codomains.'),
('Diagonal exclusion',r'For$D=\{x:x\notin f(x)\}$, assume$D=f(d)$ and test membership of$d$. The contradiction proves no surjection onto the power set. It does not assume every proper subset is smaller in cardinality.'),
])
