from author import chapter
chapter('d_invariants',r'''
### Construct a conservation law from one transition

If a move changes an integer quantity$Q$ by a multiple of$m$, the residue$Q\bmod m$ is preserved. Toggling two bits changes the number of ones by$-2,0$ or2, preserving parity. A target with different parity is impossible; matching parity alone need not prove reachability because there may be additional constraints. A conservation law proves a necessary condition unless sufficiency is independently established.

For a checkerboard domino covering, every tile covers one square of each color. Removing two same-color corners from an8 by8 board leaves unequal color counts and is impossible to tile. Counting total area as even is a weaker invariant that fails to detect this obstruction.

### Choose the exact loop checkpoint

For a prefix-sum loop with checkpoint before processing entry$i$, the invariant is$s=\sum_{j=0}^{i-1}a_j$. The empty prefix gives$s=0$ at$i=0$. Assignment uses old-state values: `s = s + a[i]; i = i + 1;` preserves the relationship because the right-hand prefix grows by exactly the term just added. At exit$i=n$, the invariant turns into the required full sum. A sum invariant alone does not establish termination; a bound on$i$ and a ranking$n-i$ supply that separate proof.

### Count recursive structure through constructors

A full binary tree has either one leaf or an internal root with two full children. If each child satisfies$L=I+1$, the parent satisfies$L=L_1+L_2=(I_1+1)+(I_2+1)=I+1$. For a full$k$-ary tree the same accounting yields$L=(k-1)I+1$. A tree allowing one-child internal nodes does not satisfy this leaf formula; the constructor premise controls the identity.

For exponentiation by squaring, establish the invariant$yb^e=a^n$ for iterative state$y,b,e$. If$e$ is odd, move one factor$b$ into$y$ before halving the remaining exponent; then square$b$. Whether the final unused square is executed affects an exact multiplication count. The proof of the returned value and the count of executed operators are distinct tasks.
''',[
('Parity obstruction','A move toggles exactly two distinct bits in a five-bit word. Starting00000, which target is impossible?', ['11000','10100','11110','01000'],'D',r'The number of ones changes by an even amount under every move, so its parity remains even. The target01000 has one1 and odd parity, making it impossible. Each other target has even parity and is actually reachable here by pairing its set positions into toggles. The invariant excludes the target without enumerating all move sequences.'),
('Checkerboard covering','From an8 by8 board, remove its two diagonally opposite corner squares. Can the remainder be tiled by1 by2 dominoes?', ['Yes, because62 is even.','No, because the color counts differ.','Yes, because the corners are far apart.','No, because its area is odd.'],'B','Opposite corners of an even-by-even board have the same checkerboard color. Removing both leaves30 squares of that color and32 of the other. Every domino covers exactly one of each, so equality of color counts is necessary and violated. Even remaining area62 is insufficient; D also reports the wrong parity.'),
('Safety without inductiveness',r'Integer states start at$x=0$ and transition$x\mapsto x+2$. The property$x\ne1$ holds on every reachable state. Why does it fail as an inductive invariant over all integer states?', [r'It fails initially.',r'The state$x=-1$ satisfies it but transitions to1.',r'Every reachable state violates it.',r'The transition decreases$x$.'],'B',r'The initial state0 satisfies the property, and reachable states are nonnegative even integers. But inductive preservation quantifies over every state satisfying the proposed assertion, including unreachable$-1$. Its successor1 violates the assertion. Strengthening to$x\ge0$ and$x$ even supplies a closed inductive set.'),
('Prefix checkpoint',r'Before processing index$i$, a loop has summed array entries0 through$i-1$. For$a=[2,5,-1,4]$ and$i=3$, what is the sum variable?', ['5','6','10','11'],'B',r'The processed prefix contains2,5,-1, summing to6. The element at index3 is not yet included. Including4 would give10, the post-processing value. This difference is the exact control-point distinction encoded by the invariant; an array value and the sum of its prefix are different quantities.'),
('Binary-tree identity',r'A full binary tree has17 internal nodes. How many leaves does it have?', ['16','17','18','34'],'C',r'Full means each internal node has exactly two children. The identity$L=I+1$ gives18 leaves. An edge count verifies it: total edges$2I$ equals total nodes minus1,$I+L-1$, so$L=I+1$. If one-child nodes were permitted, the formula would not follow.'),
('Full ternary tree',r'A full ternary tree has10 internal nodes. How many leaves are there?', ['11','20','21','30'],'C',r'Every internal node has exactly three children, so$3I=I+L-1$. Rearranging gives$L=2I+1=21$. Thirty counts edges, not leaves. The plus-one originates in the tree identity that edge count is node count minus one.'),
('Structural concatenation',r'Lists$A,B$ have lengths4 and7. A structurally recursive append copies every node of$A$ and reuses$B$. How many new list nodes are allocated?', ['4','7','11','28'],'A',r'The empty-$A$ base returns$B$ without allocation. Each constructor of$A$ allocates one new node and recurses on its tail, so exactly four new nodes are created. The resulting list length is11, but the seven nodes of$B$ are shared rather than copied. Allocation count follows the implementation contract, not just output length.'),
('Accumulator invariant',r'An iterative reverse has processed the prefix$[1,2,3]$ and still has$[4,5]$ remaining. What is its front-consing accumulator?', ['[1,2,3]','[3,2,1]','[5,4]','[5,4,3,2,1]'],'B',r'Each processed element is pushed to the front, so successive accumulator states are[],[1],[2,1],[3,2,1]. The invariant relates the accumulator to the reverse of the processed prefix, not to the whole input yet. The final complete reverse appears only after the remaining two elements have been processed.'),
('Exponentiation operation count',r'Recursive powering has bases$p(0)=1,p(1)=a$. For$n>1$, compute$p(\lfloor n/2\rfloor)$ once, square it, and multiply by$a$ if$n$ is odd. How many multiplications compute$p(13)$?', ['3','5','6','7'],'B',r'The nonbase exponents are13,6,3, each contributing one square. Odd13 and3 contribute one additional multiplication each, for$3+2=5$. The base1 returns$a$ without multiplication. With a different base or an iterative implementation performing a final unused square, the exact count changes; those are different algorithms.'),
('Lexicographic ranking',r'A process decreases$j$ when$j>0$. When$j=0$ and$i>0$, it decreases$i$ and resets$j$ to an arbitrary finite nonnegative value. Both indices are nonnegative. Which ranking proves termination?', [r'$i+j$',r'Lexicographic$(i,j)$ with$i$ primary.',r'$j$ only.',r'$i-j$'],'B',r'When$j$ decreases, the primary component$i$ stays fixed and the lexicographic pair decreases. On reset,$i$ strictly decreases, so the pair decreases regardless of the new$j$. The sum can increase during reset. Nonnegative lexicographic pairs are well founded, so there is no infinite descent under these rules.'),
('A well-founded codomain',r'Which quantity alone is insufficient to prove termination even if it strictly decreases and stays positive?', ['A positive integer.','A positive real number.','A nonnegative integer.','A finite ordered state rank.'],'B',r'The positive real sequence1,1/2,1/4,... decreases strictly forever without reaching zero. Integer rankings cannot have such an infinite bounded-below descent. Therefore real-valued strict progress needs an extra discrete gap or another termination argument; positivity alone is insufficient.'),
('Finite checking limit','An invariant checker exhaustively validates every input up to size8 for an unbounded algorithm. What conclusion follows?', ['The property holds for all sizes.','The tested instances pass, but an unbounded proof is still required.','The algorithm must terminate on all inputs.','Every alternative invariant is false.'],'B','Exhaustive testing certifies only the finite domain actually enumerated, assuming the checker itself is correct. A counterexample might first occur at size9 or later. An induction proof or another general argument is needed for unbounded validity. Finite checks are useful error detectors but do not supply missing quantified proof steps.'),
],[(
'Residue invariance',r'Compute$Q_{next}-Q_{old}$ and show it is divisible by$m$. Toggling two bits preserves one-count parity. A matching residue is only necessary unless a separate construction proves every matching state reachable.'),
('Color accounting','A domino covers one square of each checkerboard color. Removing two same-color corners leaves30 versus32 squares, ruling out a covering. Even area is a weaker condition and cannot replace the color invariant.'),
('Reachable versus inductive',r'A safety property can hold on all reachable states yet fail closure on unreachable states satisfying it. For$x\ne1$ under$x+2$, unreachable$-1$ breaks preservation. Strengthen with parity and nonnegativity instead of assuming reachability during the induction step.'),
('Invariant obligations',r'Check initialization, one-step preservation and exit implication separately. Prefix sums use$s=\sum_{j<i}a_j$ at the guard. A property true after the body may not hold before the body, so specify the checkpoint.'),
('Termination obligation',r'For a bounded prefix loop, use$n-i$ as a decreasing nonnegative integer. The sum identity proves the result if exit occurs; the ranking proves exit. Total correctness needs both, plus defined memory accesses and arithmetic.'),
('Assignment old-state meaning','In `x=x+y; y=x-y;`, the second right-hand expression reads the updated$x$, not its original value. For simultaneous mathematical updates, preserve old values explicitly. Incorrect substitution order can destroy a claimed invariant.'),
('Full-tree count',r'For full$k$-ary trees,$L=(k-1)I+1$ and edge count is$kI$. Full binary gives$L=I+1$. The constructor requirement excludes unary internal nodes; arbitrary binary trees have different leaf bounds.'),
('Recursive allocation','Appending a singly linked list by copying its first argument allocates one node per element in that argument and shares the second. Result length and new storage count differ. Complexity depends on the sharing and copying contract.'),
('Generalized accumulator',r'Reverse-with-accumulator correctness is$\operatorname{revAcc}(L,A)=\operatorname{concat}(\operatorname{reverse}(L),A)$ under list concatenation. Generalizing to arbitrary$A$ supports the recursive step; proving only the empty-accumulator case can leave an unusably weak induction hypothesis.'),
('Powering count',r'With bases0 and1 returning directly, powering$n\ge1$ uses$\lfloor\log_2n\rfloor$ squares and$\operatorname{popcount}(n)-1$ extra multiplications.13 therefore costs5. Other base and final-square conventions change exact counts while preserving asymptotic logarithmic depth.'),
('Lexicographic descent','Nonnegative pair$(i,j)$ with$i$ primary decreases when$j$ drops or$i$ drops with arbitrary finite reset of$j$. The sum need not decrease. The ranking codomain and ordering are essential parts of the argument.'),
('Testing boundary','Finite exhaustive checks establish the enumerated cases and can expose errors in a proof. They do not justify an all-input induction step or certify unbounded numerical stability. Record the exact tested domain beside the result.'),
])
chapter('d_number',r'''
### Solve linear congruences with a gcd before canceling

For$ax\equiv b\pmod m$ with$m>0$, set$d=\gcd(a,m)$. There are no solutions if$d$ does not divide$b$. Otherwise divide$a,b,m$ by$d$; the reduced coefficient is invertible modulo$m/d$. One solution modulo$m/d$ lifts to exactly$d$ distinct residues modulo$m$, spaced$m/d$ apart. Canceling$a$ while keeping the old modulus is generally false.

For example,$6x\equiv8\pmod{14}$ reduces to$3x\equiv4\pmod7$. The inverse of3 is5, so$x\equiv20\equiv6\pmod7$, giving$x=6,13$ modulo14. The gcd predicts both solvability and the exact number of answers before any inverse is calculated.

### Compatibility precedes Chinese-remainder construction

The system$x\equiv a\pmod m$, $x\equiv b\pmod n$ is solvable exactly when$a\equiv b\pmod{\gcd(m,n)}$. If solvable, it has one residue class modulo$\operatorname{lcm}(m,n)$, not necessarily modulo$mn$. Coprime moduli make every pair compatible and give the familiar product modulus. Substitution$x=a+mt$ reduces the construction to a linear congruence in$t$.

### Prime exponents are a reusable accounting language

If$N=\prod p_i^{e_i}$, divisor count is$\prod(e_i+1)$ and divisor sum is$\prod(1+p_i+\cdots+p_i^{e_i})$. Gcd takes minimum exponents and lcm maximum exponents. In$n!$, the exponent of prime$p$ is $\sum_{j\ge1}\lfloor n/p^j\rfloor$; later terms count numbers contributing more than one factor$p$. Totient is$N\prod_{p\mid N}(1-1/p)$, based on exclusion of multiples of distinct prime divisors.

### Reduce exponents only for units under the theorem used

Euler gives$a^{\phi(m)}\equiv1\pmod m$ when$\gcd(a,m)=1$. For nonunits, residues can have a transient before cycling, so reducing an exponent modulo$\phi(m)$ can fail. An inverse exists exactly for units. Repeated squaring computes powers without an invalid theorem assumption; order gives the exact unit period and divides the totient.
''',[
('Euclidean remainder of a negative integer',r'Under$-17=5q+r$ with$0\le r<5$, what are$q,r$?', ['(-3,-2)','(-4,3)','(-3,2)','(-4,2)'],'B',r'Euclidean remainder must be nonnegative. Taking$q=-4$ yields$-20+3=-17$, so$r=3$. The pair(-3,-2) follows truncating division but violates the required remainder interval. The equation and interval together uniquely determine the pair.'),
('Gcd and lcm',r'For$a=72$ and$b=90$, what are their gcd and lcm?', ['(9,720)','(18,360)','(18,180)','(36,180)'],'B',r'Prime exponents are$72=2^3 3^2$ and$90=2\cdot3^2\cdot5$. Minima give$2\cdot3^2=18$; maxima give$2^3\cdot3^2\cdot5=360$. The identity$\gcd(a,b)\operatorname{lcm}(a,b)=ab$ checks$18\cdot360=6480$. Option A underestimates the common power of three. Option C omits a factor of two from the lcm. Option D gives a supposed gcd that does not divide 90.'),
('Linear congruence count',r'How many residues modulo14 solve$6x\equiv8\pmod{14}$?', ['0','1','2','6'],'C',r'The gcd of6 and14 is2, which divides8, so exactly two residues solve it. Reducing gives$3x\equiv4\pmod7$, hence$x\equiv6\pmod7$ and the lifted residues6,13. Substitution gives36 and78, both congruent to8 modulo14.'),
('Inconsistent linear congruence',r'How many residues modulo14 solve$6x\equiv5\pmod{14}$?', ['0','1','2','7'],'A',r'Every multiple of6 is even, and subtracting a multiple of14 preserves parity. It cannot become congruent to odd5. Equivalently the gcd2 does not divide5, so the linear-congruence solvability criterion fails. Trying to invert6 modulo14 is itself invalid because it is not a unit.'),
('A modular inverse',r'What is the inverse of7 modulo26?', ['3','7','15','19'],'C',r'$7\cdot15=105=4\cdot26+1$, so15 is an inverse. The gcd is1, guaranteeing a unique inverse residue. The other candidates yield remainders21,23 and3. A Bézout computation would supply the same coefficient without searching all residues.'),
('Cancellation changes modulus',r'From$6x\equiv6y\pmod{15}$, which strongest listed congruence must follow?', [r'$x\equiv y\pmod{15}$',r'$x\equiv y\pmod5$',r'$x\equiv y\pmod3$',r'$x=y$ as integers.'],'B',r'The condition is$15\mid6(x-y)$. Divide the gcd3 to obtain$5\mid2(x-y)$. Since2 is invertible modulo5, this is$x\equiv y\pmod5$. The old modulus15 cannot be retained: $x=0,y=5$ is a counterexample. The modulus is divided by the common gcd, not by the entire coefficient.'),
('Coprime Chinese remainders',r'Find the residue modulo15 satisfying$x\equiv2\pmod3$ and$x\equiv3\pmod5$.', ['2','3','8','13'],'C',r'Candidates congruent to3 modulo5 are3,8,13. Only8 has remainder2 modulo3. The moduli are coprime, so this is the unique residue modulo15. Substitution$x=3+5t$ gives$2t\equiv2\pmod3$, hence$t\equiv1$.'),
('Noncoprime compatibility',r'Which system is inconsistent?', [r'$x\equiv1\pmod4, x\equiv3\pmod6$',r'$x\equiv0\pmod4, x\equiv2\pmod6$',r'$x\equiv1\pmod4, x\equiv2\pmod6$',r'$x\equiv3\pmod4, x\equiv5\pmod6$'],'C',r'The gcd of4 and6 is2. The residues must therefore agree in parity. OptionC requests both odd and even$x$, impossible. The other residue pairs have matching parity and are compatible. Their solution period is lcm12 rather than the product24.'),
('Totient',r'What is$\phi(60)$?', ['12','16','20','24'],'B',r'The distinct prime divisors are2,3,5. Apply $60(1-1/2)(1-1/3)(1-1/5)=60\cdot(1/2)(2/3)(4/5)=16$. Repeated powers of a prime do not add repeated product factors. Totient counts unit residue classes, not all proper divisors.'),
('Exponent reduction for a unit',r'What is$7^{100}\bmod13$?', ['1','3','9','12'],'C',r'Since7 is a unit modulo13, reduce100 modulo12 to4. Compute$7^2\equiv49\equiv10$ and$7^4\equiv100\equiv9$. Euler’s theorem applies because13 is prime and does not divide7. Reducing the base or exponent before checking that condition can fail for nonunits.'),
('A nonunit exponent trap',r'What is$2^4\bmod8$?', ['0','1','2','4'],'A',r'The exact power16 is divisible by8, giving0. Although$\phi(8)=4$, reducing exponent4 to0 would give1 and is invalid because$\gcd(2,8)=2$. Nonunit powers here eventually reach0 rather than follow the unit-group period from exponent zero.'),
('Divisor count',r'How many positive divisors does$360$ have?', ['18','20','24','36'],'C',r'$360=2^3 3^2 5^1$. Choose each divisor exponent independently from0 through its corresponding exponent, giving$(3+1)(2+1)(1+1)=24$. Summing exponents counts factor multiplicities, not combinations of divisor exponents. The divisor1 and360 itself are included.'),
('Factorial valuation',r'What is the exponent of2 in$10!$?', ['5','7','8','10'],'C',r'Legendre’s sum is $\lfloor10/2\rfloor+\lfloor10/4\rfloor+\lfloor10/8\rfloor=5+2+1=8$. The first term counts all even factors, and later terms add the extra twos in multiples of4 and8. Counting only even numbers undercounts repeated factors.'),
('Bézout and integer equations',r'For which integer$c$ can$12x+18y=c$ have integer solutions?', ['Every integer$c$.','Exactly multiples of3.','Exactly multiples of6.','Exactly positive multiples of12.'],'C',r'The gcd is6, so every left-hand value is divisible by6. Bézout gives$6=-12+18$, and multiplying that solution by any integer$t$ produces every$c=6t$. Positive and negative coefficients are permitted. Restricting$x,y$ to nonnegative integers would add constraints not present here.'),
('Number of units',r'How many invertible residue classes exist modulo18?', ['3','6','9','12'],'B',r'$\phi(18)=18(1-1/2)(1-1/3)=6$. They are1,5,7,11,13,17. Invertibility is equivalent to gcd1 with the modulus. Nonzero residues such as2 and3 can still lack inverses, so counting all seventeen nonzero classes would be wrong.'),
('Multiplicative order',r'What is the multiplicative order of2 modulo7?', ['2','3','6','7'],'B',r'The powers are2,4,1 modulo7, so the first positive exponent returning1 is3. The order divides$\phi(7)=6$ but need not equal it. Euler gives an exponent that works, while order asks for the least positive such exponent.'),
],[(
'Euclidean interval',r'For positive$m$, divide$n=qm+r$ with$0\le r<m$. Negative$n$ may require a quotient below truncation-toward-zero. For$-17$ and5 the answer is$q=-4,r=3$.'),
('Gcd and lcm exponents',r'Gcd takes minimum prime exponents and lcm maximum exponents. For nonzero integers, their positive product is$|ab|$. Handle the zero pair by the chapter’s stated gcd convention before using an lcm formula with division.'),
('Linear solvability',r'$ax\equiv b\pmod m$ is solvable iff$d=\gcd(a,m)$ divides$b$. If so, there are$d$ residues modulo$m$. Reduce by$d$ and lift by multiples of$m/d$; do not search for an inverse of a nonunit.'),
('Cancellation modulus',r'$ax\equiv ay\pmod m$ yields$x\equiv y\pmod{m/\gcd(a,m)}$. For$a=6,m=15$, the reduced modulus is5. Keeping15 assumes an inverse that does not exist.'),
('Inverse check',r'A modular inverse exists exactly when gcd is1. Verify a candidate by multiplying and obtaining residue1. Bézout supplies the inverse coefficient, which may be negative before conversion to the canonical residue.'),
('CRT compatibility',r'Two residue requirements agree iff their residues agree modulo the gcd of their moduli. Compatible solutions repeat modulo the lcm. Coprimality is sufficient for automatic compatibility but is not necessary for a particular system.'),
('Diophantine family',r'For$ax+by=c$ and$d=\gcd(a,b)$ dividing$c$, a particular solution generates$x=x_0+(b/d)t$, $y=y_0-(a/d)t$. Nonnegative restrictions become an interval of allowed$t$ values and may remove all integer solutions.'),
('Totient factors',r'$\phi(N)=N\prod_{p\mid N}(1-1/p)$ uses each distinct prime once.60 gives16. The result counts residues coprime to$N$, including1, not a count of divisors or arbitrary nonzero residues.'),
('Safe power reduction',r'Euler exponent reduction requires gcd1. For$7^{100}$ modulo13, reduce100 to4 and get9. For$2^4$ modulo8, reducing exponent to0 gives a false answer. Use repeated squaring when group conditions are absent.'),
('Order versus totient',r'The unit order is the least positive exponent returning1 and divides the totient.2 modulo7 has order3 although the totient is6. A proper divisor must be checked to establish minimality.'),
('Divisor formulas',r'If$N=\prod p_i^{e_i}$, count divisors with$\prod(e_i+1)$ and sum them with$\prod(1+p_i+\cdots+p_i^{e_i})$. Include zero exponents in each choice. Square divisors restrict every selected exponent to be even.'),
('Factorial prime valuation',r'$v_p(n!)=\sum_{j\ge1}\lfloor n/p^j\rfloor$. For$p=2,n=10$, the terms5,2,1 sum to8. Trailing decimal zeros use the minimum of2- and5-valuations; counting only multiples of5 can miss powers of25.'),
('Wilson direction',r'For prime$p$, $(p-1)!\equiv-1\pmod p$; conversely this condition characterizes primes among integers greater than1. Pair units with inverses in the proof and handle the self-inverse residues separately. A Fermat congruence for one base is not an equivalent primality test.'),
('RSA mathematical scope',r'For distinct primes$p,q$, choose exponent$e$ invertible modulo$\phi(pq)$ and its inverse$d$. Correctness on units follows from Euler and on nonunits from separate prime-modulus cases. This arithmetic teaching does not certify a cryptographic implementation’s security.'),
])
