from author import chapter
chapter('s_axioms',r'''
### Recover all four atomic probabilities

Given $P(A)=a$, $P(B)=b$ and $P(A\cap B)=t$, the four disjoint masses are $t,a-t,b-t,1-a-b+t$. Nonnegativity yields $\max(0,a+b-1)\le t\le\min(a,b)$. This inequality is both necessary and sufficient: if it holds, the four numbers define a valid law on four atoms. Thus feasibility questions can be solved without guessing independence.

The union is $a+b-t$, exactly one is $a+b-2t$, neither is $1-a-b+t$, and $A$ without$B$ is$a-t$. These are distinct events. A diagram of the four regions determines the coefficient of$t$ and is safer than memorizing ambiguous phrases such as “either.” When the question says “either but not both,” it means symmetric difference.

### A count ratio requires equally likely elementary outcomes

If a fair die's outcomes are grouped into parity, the two groups are equally likely because each contains three equally likely faces. Grouping into “one” versus “not one” creates masses1/6 and5/6, not1/2 each. For a nonuniform finite law, sum the masses of favorable elementary outcomes. A probability density at a point is not its point probability.

### Infinite sums and limiting events

For a countable discrete law $p_k=c/2^k$ for$k\ge1$, normalization uses the convergent geometric series and gives$c=1$. For a uniform point on$[0,1]$, an interval's mass is its length while every singleton has probability zero. Countable unions of null singletons remain null, but the uncountable union of every singleton is the whole interval. Countable additivity deliberately does not extend to arbitrary uncountable sums.

For increasing measurable events, $P(\bigcup A_n)=\lim P(A_n)$; for decreasing ones, $P(\bigcap A_n)=\lim P(A_n)$ in a probability space. A moving interval sequence can have empty intersection even when each individual interval has positive mass. “Infinitely often” is an intersection of tail unions, while “eventually always” is a union of tail intersections.
''',[
('Recover a union',r'$P(A)=0.6$, $P(B)=0.5$ and $P(A\cap B)=0.2$. Find $P(A\cup B)$.', ['0.3','0.7','0.9','1.1'],'C',r'Count each singleton probability once and subtract the overlap counted twice: $0.6+0.5-0.2=0.9$. The outside mass is0.1, confirming feasibility. The sum1.1 is not a valid union probability because the events overlap. Difference0.3 instead counts $B\setminus A$, and0.7 counts exactly one event.'),
('Exactly one versus at least one',r'With the data in Question 1, what is the probability of exactly one of$A,B$?', ['0.2','0.7','0.9','0.1'],'B',r'The exclusive masses are $0.6-0.2=0.4$ and $0.5-0.2=0.3$. They are disjoint, so their sum is0.7. The union probability0.9 still includes the0.2 intersection. The outside probability0.1 means neither, and0.2 means both. Translate the phrase into disjoint regions before using numbers.'),
('Sharp intersection range',r'If $P(A)=0.7$ and $P(B)=0.6$, which is the exact feasible range for$P(A\cap B)$?', ['[0,0.6]','[0.3,0.6]','[0.42,0.6]','[0.3,0.7]'],'B',r'The union cannot exceed1, requiring $t\ge0.7+0.6-1=0.3$. The intersection cannot exceed either event, requiring $t\le0.6$. Every$t$ in this range gives nonnegative four-region masses and is realizable. The value0.42 assumes independence, which is not supplied. A allows a negative outside mass for small$t$.'),
('An inconsistent table',r'Which triple $(P(A),P(B),P(A\cap B))$ is impossible?', ['(0.8,0.7,0.6)','(0.3,0.5,0.1)','(0.8,0.7,0.4)','(0.3,0.5,0.3)'],'C',r'ForC, the union would be $0.8+0.7-0.4=1.1$ and the outside mass would be$-0.1$. The necessary lower intersection bound is0.5. All other triples satisfy both the lower bound and the upper minimum bound. Feasibility needs all four disjoint masses nonnegative; checking only that every given number lies in[0,1] is insufficient.'),
('Nonuniform elementary outcomes',r'A law on outcomes1,2,3,4 assigns probability proportional to the outcome number. What is the probability of an even outcome?', ['1/2','3/5','2/5','1/4'],'B',r'The normalization denominator is $1+2+3+4=10$. The even outcomes carry mass $(2+4)/10=3/5$. Counting two favorable labels out of four gives1/2 only for a uniform law. Neither the number of labels nor the name of the event changes the assigned masses.'),
('A grouped experiment',r'A fair die is recorded as “one” or “not one.” What is the probability of “one”?', ['1/2','1/6','1/3','5/6'],'B',r'The elementary outcomes are the six equally likely faces. Exactly one maps to the first recorded label, so its mass is1/6. Grouping changes the labels but does not reassign equal probability to the two groups. The complementary label has five preimages and probability5/6.'),
('Normalize an infinite discrete law',r'For $k=1,2,\ldots$, $P(\{k\})=c/2^k$. What is$c$?', ['1/2','1','2','No finite value.'],'B',r'The geometric sum from$k=1$ is $1/2+1/4+\cdots=1$. Total mass is therefore$c$, which must equal1. Starting the sum at zero would give2 and a different normalization. Nonnegative masses and a sum of1 define the discrete probability law.'),
('A tail probability',r'Under the law of Question 7, what is $P(\{4,5,6,\ldots\})$?', ['1/16','1/8','1/4','1/2'],'B',r'The tail begins with1/16 and has ratio1/2. Its sum is $(1/16)/(1-1/2)=1/8$. OptionA counts only the first point. The equivalent complement computation subtracts $1/2+1/4+1/8=7/8$ from1, giving the same result.'),
('Uniform continuous length',r'$X$ is uniform on$[0,1]$. What is $P(1/4<X\le3/4)$?', ['0','1/4','1/2','3/4'],'C',r'The interval length is $3/4-1/4=1/2$. Each endpoint has probability zero, so open or closed endpoints do not change this value. Zero is the mass of one specified point, not of an interval containing uncountably many points. Counting endpoints as separate positive atoms would be inconsistent with the uniform continuous law.'),
('A decreasing sequence',r'For uniform$X$ on$[0,1]$, let $A_n=\{0<X<1/n\}$. What is $P(\bigcap_{n=1}^{\infty}A_n)$?', ['0','1','1/2','It does not exist.'],'A',r'No positive real number is less than1/n for every$n$, and zero is excluded. The intersection is empty and has mass zero. Alternatively the sequence decreases and $P(A_n)=1/n\to0$, so continuity from above gives zero. Every individual event having positive probability does not force a positive intersection probability.'),
('A union bound',r'For events $E_1,E_2,E_3$ with probabilities0.1,0.2,0.25 and no overlap data, which upper bound on their union is guaranteed?', ['0.05','0.25','0.55','Exactly0.55.'],'C',r'Finite subadditivity gives $P(E_1\cup E_2\cup E_3)\le0.1+0.2+0.25=0.55$. This is an upper bound, not an equality; nested events could have union0.25. It is sharp if the three events are disjoint, which is feasible since the total is below1. The largest individual mass is a lower bound on the union, not an upper bound.'),
('Finite information partitions',r'A sigma-algebra on a finite sample space is generated by a partition into three nonempty atoms. How many events does it contain?', ['3','6','8','9'],'C',r'Every measurable event is a union of partition atoms, and every choice of included atoms gives one event. Three independent yes/no choices yield $2^3=8$. The empty event and the full space are included. Counting only the three atoms omits their unions and violates closure of the event family.'),
],[(
'Four-region reconstruction',r'Use$t,a-t,b-t,1-a-b+t$ for both, first-only, second-only and neither. With$a=0.6,b=0.5,t=0.2$, these are0.2,0.4,0.3,0.1. Their sum and nonnegativity are independent checks on every computed answer.'),
('Sharp feasibility',r'$\max(0,a+b-1)\le t\le\min(a,b)$ is necessary and sufficient for two-event data. For$a=0.7,b=0.6$, the range is[0.3,0.6]. The product$ab$ is just an independence value, not the universal lower bound.'),
('Exactly one',r'$P(A\oplus B)=a+b-2t$. Subtract overlap twice because both original masses counted it. The union subtracts it once. “Either” is ambiguous unless the question explicitly specifies inclusive or exclusive meaning.'),
('Difference and complement',r'$P(A\setminus B)=a-t$ and $P((A\cup B)^c)=1-a-b+t$. Negating “both” gives the complement of the intersection, whereas negating “at least one” gives the complement of the union.'),
('Nonuniform mass sums',r'Use $\sum_{\omega\in E}p_\omega$ for a nonuniform law. For probabilities proportional to1,2,3,4, the even event is6/10. Favorable count divided by total count is valid only when elementary outcomes are equally likely.'),
('Coarse recording',r'Grouped labels inherit the total masses of their preimages. Recording one die face versus all other faces produces1/6 and5/6. Two possible labels do not imply equal probability.'),
('Infinite normalization and tails',r'For $p_k=2^{-k}$ starting at1, total mass is1 and the tail from$m$ is$2^{1-m}$. Verify the starting index; starting at0 doubles the sum. A tail probability includes all its points, not only its first term.'),
('Continuous endpoints',r'For uniform length on$[0,1]$, point masses are zero and interval probabilities equal length. A countable set of specified points is null. The union of uncountably many null singletons can have mass1; countable additivity does not justify an uncountable sum.'),
('Monotone limits',r'Increasing events use a union and decreasing events an intersection. For$(0,1/n)$, the intersection is empty and its mass is the limit0. Positive masses at every finite stage do not imply a positive limiting mass.'),
('Union bounds versus equality',r'$P(\bigcup E_i)\le\sum P(E_i)$ always for a finite or countable family. Equality requires that overlaps contribute no mass. If the sum exceeds1, replace the numerical upper bound by1; do not report a probability greater than1.'),
('Finite sigma-algebras',r'A partition into$k$ nonempty atoms generates $2^k$ events, each a union of whole atoms. Distinct subsets of sample points are not all observable if they split an atom. Count atoms, not individual elementary labels, for the event-family size.'),
('Infinitely often',r'$\limsup E_n=\bigcap_m\bigcup_{n\ge m}E_n$ means infinitely many occurrences; $\liminf E_n=\bigcup_m\bigcap_{n\ge m}E_n$ means eventual permanent occurrence. If$\sum P(E_n)$ converges, tail union bounds give $P(\limsup E_n)=0$, with no independence assumption.'),
])
chapter('s_counting',r'''
### Choose the object before the formula

An ordered sample of$r$ distinct objects from$n$ has $n!/(n-r)!$ outcomes. Forgetting order gives $\binom nr$ because every unordered subset has exactly$r!$ orderings. If repetition is allowed, ordered sequences have$n^r$ outcomes, while unordered multisets have $\binom{n+r-1}r$. These are different sample spaces; a uniformly drawn sequence does not induce a uniform law on multisets.

### Allocate with lower and upper bounds

Nonnegative integer solutions of $x_1+\cdots+x_k=N$ number $\binom{N+k-1}{k-1}$. Lower bounds$x_i\ge a_i$ are removed by shifting to$y_i=x_i-a_i$. Upper bounds need exclusion. If every$x_i\le b$, inclusion-exclusion gives

$$\sum_{j=0}^k(-1)^j\binom kj\binom{N-j(b+1)+k-1}{k-1},$$

with a term zero when its adjusted sum is negative. The shift is$b+1$, because violation begins at$b+1$, not$b$.

### Count occupancy and adjacency without duplicating objects

Distributing$n$ distinct objects to$k$ labeled boxes gives$k^n$ assignments. Requiring every box nonempty gives $\sum_{j=0}^k(-1)^j\binom kj(k-j)^n$. For unlabeled nonempty boxes, divide this surjection count by$k!$ because permuting nonempty box labels acts freely. Empty boxes or repeated geometric symmetries can destroy that constant-orbit assumption.

For binary strings of length$n$ with$r$ isolated ones, position the zeros first. They create$n-r+1$ gaps; choose$r$ distinct gaps, giving $\binom{n-r+1}r$. For adjacent specified objects in a permutation, merge them into a block and multiply by internal block order. Dividing by rotations is safe for arrangements of distinct objects, but repeated symbols can create shorter rotational orbits.
''',[
('Ordered without replacement',r'How many ordered length-three samples of distinct objects can be formed from seven labeled objects?', ['21','35','210','343'],'C',r'There are7 choices for the first object,6 for the second and5 for the third, giving210. The35 count forgets order;343 allows repetition. Each three-element subset has six different orders, so $\binom73\cdot3!=35\cdot6=210$ checks the result.'),
('Multiset permutations',r'How many different strings can be formed by permuting the letters of BANANA?', ['20','60','120','720'],'B',r'There are six positions, three indistinguishableAs, two indistinguishableNs and oneB. Divide $6!$ by $3!2!$, obtaining60. Dividing by the number of repeated letter types is insufficient; internal permutations within each group generate the same string.720 treats every copy as distinguishable.'),
('Positive allocations',r'How many positive integer solutions satisfy $x+y+z=10$?', ['28','36','45','66'],'B',r'Shift $u=x-1,v=y-1,w=z-1$ to get nonnegative solutions with sum7. Stars and bars gives $\binom{7+2}2=36$. Using66 counts nonnegative solutions of the original sum and permits zeros. The shift subtracts one from each of three variables, not only once from the total.'),
('Upper bounds',r'How many nonnegative integer solutions satisfy $x+y+z=7$ with each variable at most3?', ['6','12','15','36'],'A',r'Unrestricted solutions number $\binom92=36$. A violation$x\ge4$ shifts that variable by4 and leaves sum3, giving $\binom52=10$; three variables contribute30. Two simultaneous violations need at least8 and are impossible. Thus the count is $36-30=6$. The bounded generating polynomial gives the same value; the stated upper bound3 excludes values starting at4.'),
('Onto assignments',r'How many functions from four labeled objects to three labeled boxes use every box?', ['12','24','36','81'],'C',r'Use inclusion-exclusion: $3^4-\binom31 2^4+\binom32 1^4=81-48+3=36$. Alternatively the occupancy must be2,1,1: choose the doubled box in3 ways, its two objects in6 ways, and assign the remaining objects in2 ways, again36. The box labels matter.'),
('Unlabeled nonempty groups',r'How many partitions of four labeled objects into three nonempty unlabeled groups exist?', ['3','6','12','36'],'B',r'Every partition has one doubleton and two singleton groups. Choose the doubleton in $\binom42=6$ ways. Equivalently divide the36 onto assignments to three labeled boxes by $3!=6$. Because all boxes are nonempty and distinct by their members, each unlabeled partition has exactly six labelings.'),
('No adjacent ones',r'How many binary strings of length eight contain exactly three ones, no two adjacent?', ['20','35','56','64'],'A',r'There are five zeros and hence six gaps, including both ends. Put one1 in each of three selected gaps, yielding $\binom63=20$. The answer56 chooses arbitrary three positions and permits adjacency. The gap method also proves impossibility when the number of ones exceeds the number of available gaps.'),
('A probability by combinations',r'A committee of three is drawn uniformly from five women and four men. What is the probability of exactly two women?', ['5/21','10/21','1/2','2/3'],'B',r'The denominator is $\binom93=84$ equally likely committees. Favorable committees number $\binom52\binom41=10\cdot4=40$. The probability is40/84=10/21. Independent sequential selection probabilities require updating the remaining counts; a committee combination count avoids order duplication.'),
('Specified adjacency',r'Five distinct objects are uniformly permuted. What is the probability that two specified objects are adjacent?', ['1/5','2/5','1/2','4/5'],'B',r'Merge the specified pair into a block, leaving four distinct units with $4!$ orders. The pair has two internal orders, so the favorable count is $2\cdot4!$. Divide by $5!$ to obtain2/5. If the internal order were fixed, the probability would be1/5; the question permits both.'),
('Circular distinct objects',r'How many circular orders of six distinct objects exist when rotations are identified but reflections remain different?', ['60','120','360','720'],'B',r'Fix one object as an anchor; arrange the other five clockwise, giving $5!=120$. Equivalently every orbit of linear listings has six rotations because all objects are distinct. Identifying reflections as well would divide by another2 and give60, which is not the stated convention.'),
('A guaranteed collision',r'What smallest number of objects guarantees that some one of seven boxes contains at least four objects?', ['22','23','28','29'],'A',r'Without a four-object box, each box contains at most3, so at most $7\cdot3=21$ objects can be placed. The22nd forces the desired occupancy. The21-object placement with exactly3 per box shows sharpness. Seven times four is sufficient but not the smallest guaranteed count.'),
('Repeated unordered selection',r'How many multisets of size four can be chosen from three types?', ['12','15','27','81'],'B',r'A multiset is determined by nonnegative type counts summing to4. Stars and bars gives $\binom{4+3-1}{3-1}=\binom62=15$. The81 count is for ordered selections with repetition. Each multiset has a different number of sequence realizations when multiplicities differ, so a uniform sequence does not make these fifteen multisets equally likely.'),
],[(
'Order and replacement',r'Ordered distinct samples use $n!/(n-r)!$; unordered distinct samples use $\binom nr$; ordered repeated selections use$n^r$. For7 objects and3 distinct picks, these first two counts are210 and35. State the counted object before selecting a formula.'),
('Identical copies',r'Fixed multiplicities$n_1,\ldots,n_k$ among$N$ positions give $N!/\prod n_i!$. BANANA gives $6!/(3!2!)=60$. Divide by the factorial of each multiplicity, not merely by the number of repeated letters.'),
('Positive versus nonnegative',r'For positive$k$ variables summing to$N$, subtract1 from every variable and use $\binom{N-1}{k-1}$. Nonnegative variables use $\binom{N+k-1}{k-1}$. Inconsistent lower bounds give zero rather than a negative factorial.'),
('Upper-bound shift',r'For$x_i\le b$, a bad variable begins at$b+1$. Shift by$b+1$ in inclusion-exclusion. For three variables summing to7 with bound3, unrestricted36 minus three bad counts of10 gives6; two bad variables are impossible.'),
('Surjections',r'Onto maps from$n$ labeled objects to$k$ labeled boxes number $\sum_{j=0}^k(-1)^j\binom kj(k-j)^n$. For$n=4,k=3$, the answer is36. Missing a box is an event, and missing-box events overlap.'),
('Unlabeled boxes',r'For exactly$k$ nonempty groups of labeled objects, divide the onto count by$k!$. All groups being nonempty ensures each partition has exactly$k!$ labelings. Allowing empty boxes introduces stabilizers and invalidates a blind division.'),
('Isolated positions',r'Binary strings with$r$ nonadjacent ones have $\binom{n-r+1}r$ arrangements. There are$n-r+1$ gaps among the zeros. Select distinct gaps; allowing several ones in one gap violates isolation.'),
('Uniform committees',r'For$r$ selected from groups of sizes$a,b$, exactly$j$ from the first group has count $\binom aj\binom b{r-j}$ out of $\binom{a+b}r$. The ratio is justified by uniform sampling of subsets, not by an unstated independent model.'),
('Adjacency blocks',r'Two specified distinct objects adjacent in$n$ permutations have $2(n-1)!$ favorable orders, probability$2/n$. If their order is fixed, remove the factor2. A chain of overlapping adjacency constraints may not behave like independent blocks.'),
('Circular symmetry',r'Distinct objects modulo rotation give $(n-1)!$ orders. Keeping versus identifying reflections is a separate convention. With repeated symbols, rotational orbits can have different sizes, so dividing every linear count by$n$ can fail.'),
('Pigeonhole threshold',r'To force at least$r$ objects in one of$k$ boxes, the sharp unrestricted threshold is $k(r-1)+1$. Construct the balanced counterexample with$r-1$ per box to prove that one fewer is insufficient.'),
('Multisets are not uniform sequence outcomes',r'Multisets of size$r$ from$k$ types number $\binom{k+r-1}r$. A multiset with counts$n_i$ has $r!/\prod n_i!$ sequence realizations. Different multiplicities yield different induced probabilities when sequences are drawn uniformly.'),
])
