from author import chapter
chapter('a_recurrence',r'''
### Account for a whole level before summing the tree

For$T(n)=aT(n/b)+f(n)$ on$n=b^h$, depth$i$ has$a^i$ nodes, each of size$n/b^i$. Its toll is$a^if(n/b^i)$. The leaf contribution is$a^hT(1)=n^{\log_ba}T(1)$. Every proposed total must include both internal work and leaves. If$f$ is stated only as an upper bound, the equation may not determine a tight internal-work rate, although a leaf lower bound can remain decisive.

For the balanced critical recurrence with$a=b$, toll$n(\log n)^q$ and a positive constant base cutoff, reindex levels by distance from the leaves. Total internal work has order$n\sum_{j=1}^{h}j^q$. This yields$n\log^{q+1}n$ when$q>-1$, $n\log\log n$ when$q=-1$, and$n$ when$q<-1$, after adding the linear leaves. The logarithmic denominator must be defined only above the stated cutoff; evaluating a toll$n/\log n$ at1 is invalid.

### Change variables when arguments are not linear fractions

For$T(n)=T(\sqrt n)+1$, let$n=2^{2^k}$ and set$U(k)=T(2^{2^k})$. Then$U(k)=U(k-1)+1$, so$T(n)$ is order$\log\log n$. For$T(n)=2T(\sqrt n)+\log_2n$, instead set$m=\log_2n$ and$U(m)=T(2^m)$; the equation becomes$U(m)=2U(m/2)+m$. Its solution is$\Theta(m\log m)$, giving$\Theta(\log n\log\log n)$. Translate back to the original variable at the end.

### Unequal split exponents and resources

For$T(n)=T(n/3)+T(2n/3)+n$ with admissible rounding and positive base cost, the Akra–Bazzi exponent$p$ satisfies $(1/3)^p+(2/3)^p=1$, giving$p=1$. The integral correction from the linear toll is logarithmic, so the result is$n\log n$. Work sums child costs; parallel span can instead take their maximum. Storage of a depth-first implementation counts simultaneously live data, not every node ever created.
''',[
('Leaf-dominated recurrence',r'For$n=2^k$, $T(n)=4T(n/2)+n$ with$T(1)=1$. What is its tight order?', [r'$\Theta(n)$',r'$\Theta(n\log n)$',r'$\Theta(n^2)$',r'$\Theta(n^3)$'],'C',r'The leaf exponent is$\log_24=2$. At depth$i$, toll is$4^i(n/2^i)=n2^i$, which grows geometrically toward the leaves. Its sum is quadratic and the$n^2$ leaves give a matching lower bound. Comparing only the root’s linear toll misses most of the work.'),
('Balanced critical toll',r'$T(n)=2T(n/2)+n\log_2n$ on powers of two, with$T(1)=1$. What is the tight order?', [r'$\Theta(n\log n)$',r'$\Theta(n\log^2n)$',r'$\Theta(n^2)$',r'$\Theta(\log^2n)$'],'B',r'Write$h=\log_2n$. Level$i$ contributes$n(h-i)$. Sum$i=0$ through$h-1$ to obtain$n h(h+1)/2$, then add$n$ leaf work. The result is order$n\log^2n$. The logarithm is not a polynomial gap allowing classical case3.'),
('Critical reciprocal log',r'For powers of two above cutoff2, $T(n)=2T(n/2)+n/\log_2n$, with positive constant base cost at2. What is the order?', [r'$\Theta(n)$',r'$\Theta(n\log\log n)$',r'$\Theta(n\log n)$',r'$\Theta(n/\log n)$'],'B',r'Let$h=\log_2n$. Level tolls are$n/(h-i)$ until the cutoff. Their sum is a linear factor times a harmonic sum of order$\log h$. Leaves add linear work, so total is$\Theta(n\log\log n)$. The cutoff makes every denominator nonzero.'),
('Convergent critical tail',r'With the same cutoff convention, $T(n)=2T(n/2)+n/(\log_2n)^2$. What is the order?', [r'$\Theta(n)$',r'$\Theta(n\log\log n)$',r'$\Theta(n\log n)$',r'$\Theta(n^2)$'],'A',r'After reindexing, the level sum is$n\sum_{j=2}^{h}1/j^2$, bounded above and below by positive constants times$n$. The leaf contribution is also linear. A logarithmic saving in the toll does not reduce below the cost of the linear number of leaves.'),
('A decreasing-by-one chain',r'$T(n)=T(n-1)+n$ with$T(0)=0$. What is$T(10)$?', ['45','50','55','100'],'C',r'Unroll to the exact sum$10+9+\cdots+1=55$. The base contributes zero. Applying a divide-and-conquer master formula to$n-1$ is invalid because the shrink factor is not a fixed$b>1$. The sum determines both the exact value and quadratic asymptotic order.'),
('Unequal mass-conserving split',r'$T(n)=T(n/3)+T(2n/3)+n$ with conventional rounding and constant positive base costs. What is the tight order?', [r'$\Theta(n)$',r'$\Theta(n\log n)$',r'$\Theta(n^{\log_32})$',r'$\Theta(n^2)$'],'B',r'The exponent equation $(1/3)^p+(2/3)^p=1$ has$p=1$. The integral term is$\int_1^n u/u^2\,du=\log n$, so Akra–Bazzi gives$n(1+\log n)$. Ordinary equal-subproblem master parameters do not describe the unequal split. Rounding must meet the theorem’s admissible perturbation conditions.'),
('Shrinking total mass',r'$T(n)=T(n/3)+T(n/4)+n$ with constant positive bases and admissible rounding. What is the tight order?', [r'$\Theta(n)$',r'$\Theta(n\log n)$',r'$\Theta(n^2)$',r'$\Theta(\log n)$'],'A',r'The total child size is$(7/12)n$, so successive total linear tolls decrease geometrically up to rounding effects. The root already costs$n$, giving a linear lower bound. A substitution with sufficient constant slack proves the matching upper bound. Two recursive calls alone do not imply$n\log n$ work.'),
('Square-root recursion',r'$T(n)=T(\sqrt n)+1$, with a fixed base for$n\le2$ and idealized arguments$n=2^{2^k}$. What is the tight order?', [r'$\Theta(\log n)$',r'$\Theta(\log\log n)$',r'$\Theta(\sqrt n)$',r'$\Theta(1)$'],'B',r'Each square root halves$\log_2n$, so$k$ successive roots reach the cutoff when$n=2^{2^k}$. Since$k=\log_2\log_2n$, the one-per-level cost is doubly logarithmic. Treating the root as division by a constant applies the wrong recurrence family.'),
('Transformed critical recurrence',r'$T(n)=2T(\sqrt n)+\log_2n$ with fixed small bases on a compatible domain. What is the tight order?', [r'$\Theta(\log n)$',r'$\Theta(\log n\log\log n)$',r'$\Theta(n\log n)$',r'$\Theta(\log^2n)$'],'B',r'Let$m=\log_2n$ and$U(m)=T(2^m)$. The equation becomes$U(m)=2U(m/2)+m$, giving$\Theta(m\log m)$. Substituting back yields the listed expression. Leaving the answer in$m$ or writing$n\log n$ without reversing the variable change loses the original input scale.'),
('Exact balanced count',r'$T(n)=2T(n/2)+n$ on powers of two with$T(1)=1$. What is$T(8)$?', ['16','24','32','64'],'C',r'There are three internal levels, each costing8, plus eight unit-cost leaves. Thus$T(8)=8\cdot3+8=32$. Equivalently values are$T(2)=4,T(4)=12,T(8)=32$.24 omits the leaf cost. Exact counts retain bases that asymptotic notation may hide.'),
('Repeated characteristic root',r'$a_n=2a_{n-1}-a_{n-2}$ with$a_0=1,a_1=3$. What is$a_n$?', [r'$2^n$',r'$1+2n$',r'$n^2+1$',r'$3^n$'],'B',r'The characteristic polynomial is$(r-1)^2$, so the general form is$A+Bn$. The first base gives$A=1$ and the second$B=2$. Another direct proof observes that first differences satisfy$a_n-a_{n-1}=a_{n-1}-a_{n-2}$ and remain2. A repeated root requires the polynomial factor$n$.'),
('Resonant forcing',r'$a_n=2a_{n-1}+2^n$ with$a_0=0$. What is$a_n$?', [r'$2^n$',r'$n2^n$',r'$2^{n+1}$',r'$n^2$'],'B',r'Divide by$2^n$ and set$b_n=a_n/2^n$. Then$b_n=b_{n-1}+1$ with$b_0=0$, giving$b_n=n$. Multiply back to get$n2^n$. The forcing term resonates with the homogeneous factor2, so a constant multiple of$2^n$ alone cannot satisfy the equation.'),
('Memoized overlapping states',r'A recursive program computes$F_n$ from$F_{n-1},F_{n-2}$ with constant local work. Memoization stores each$F_k$ once. What is total arithmetic work through$F_n$ under unit-cost arithmetic?', [r'$\Theta(2^n)$',r'$\Theta(n)$',r'$\Theta(\log n)$',r'$\Theta(n^2)$'],'B',r'There are$n+1$ distinct indexed states and each nonbase state requires a constant number of table lookups and arithmetic operations. Memoization counts the state DAG, not every occurrence in the expanded recursion tree. With bit-cost arithmetic on growing Fibonacci integers, the unit-cost conclusion would need revision.'),
('Work versus span',r'A parallel algorithm has$W(n)=2W(n/2)+n$ and$S(n)=S(n/2)+n$, with constant positive bases. What are their orders?', [r'Both$\Theta(n\log n)$.',r'$W=\Theta(n\log n),S=\Theta(n)$.',r'$W=\Theta(n),S=\Theta(\log n)$.',r'Both$\Theta(\log n)$.'],'B',r'Work adds both child subcomputations and has a linear toll at every level, giving$n\log n$. Span takes one longest child chain; its tolls are$n+n/2+n/4+\cdots$, summing to linear$n$. Parallelism does not make a serial linear combine constant time.'),
('Insufficient toll information',r'$T(n)=2T(n/2)+f(n)$ with$f(n)\in O(n^2)$, $f(n)\ge0$, positive constant bases. Which is guaranteed without a lower bound on$f$?', [r'$T\in\Theta(n^2)$',r'$T\in O(n^2)$ and$T\in\Omega(n)$.',r'$T\in\Theta(n\log n)$',r'$T\in O(\log n)$'],'B',r'Using the maximum permitted quadratic toll gives a quadratic upper bound, while the$n$ positive-cost leaves give a linear lower bound. The choice$f=0$ gives linear cost, whereas$f=n^2$ gives quadratic cost, so no single tight rate is forced. Replacing an$O$ statement by a$\Theta$ toll changes the assumptions.'),
('Depth-first auxiliary storage',r'A balanced depth-first recursive algorithm allocates$c n$ temporary words at size$n$, retains them during both child calls, and frees them on return. Child sizes halve. What is peak extra storage?', [r'$\Theta(\log n)$',r'$\Theta(n)$',r'$\Theta(n\log n)$',r'$\Theta(n^2)$'],'B',r'Only one child path is active at a time, with simultaneously live arrays totaling$cn+cn/2+cn/4+\cdots<2cn$, plus logarithmic stack metadata. The root allocation gives a linear lower bound. Summing allocations across every tree node counts lifetime allocation volume rather than peak storage.'),
],[(
'Whole-level toll',r'For$aT(n/b)+f(n)$, level$i$ costs$a^if(n/b^i)$ and leaves cost$n^{\log_ba}T(1)$. Count both. A root-only comparison misses leaf-dominated and critical cases.'),
('Master comparison',r'For $T(n)=aT(n/b)+f(n)$ with $a\ge1$, $b>1$, nonnegative toll and positive constant bases, put $p=\log_ba$. If $f(n)=O(n^{p-\epsilon})$ for some fixed $\epsilon>0$, the answer is $\Theta(n^p)$. If $f(n)=\Theta(n^p)$, the answer is $\Theta(n^p\log n)$. If $f(n)=\Omega(n^{p+\epsilon})$ and $af(n/b)\le cf(n)$ for some fixed $c<1$ eventually, the answer is $\Theta(f(n))$. A logarithmic gap is not the polynomial gap required in the strict cases. For $a=b=2$ and quadratic toll, the regularity ratio is one half; the result is $\Theta(n^2)$.'),
('Critical positive log powers',r'For $T(n)=aT(n/b)+\Theta(n^p\log^q n)$ with $p=\log_ba$ and $q>-1$, the answer is $\Theta(n^p\log^{q+1}n)$ under the standard balanced cutoff model. Reindex levels from the leaves to derive the power sum. In particular, $2T(n/2)+n\log n$ has order $\Theta(n\log^2n)$; comparing only the root toll misses one logarithmic factor.'),
('Critical negative powers',r'For the same critical recurrence, $q=-1$ gives $\Theta(n^p\log\log n)$; for $q<-1$, the level series converges and positive-cost leaves give $\Theta(n^p)$. Thus $2T(n/2)+n/\log n$ and $2T(n/2)+n/\log^2n$ have different orders. Use a fixed base cutoff above one, avoiding division by $\log1=0$. These are tight growth rates, not exact identities for the count.'),
('Additive chains',r'$T(n)=T(n-1)+n$ unrolls to$n(n+1)/2$ with zero base. A step$n-d$ stays in residue classes modulo$d$ and needs bases covering them. The equal-split master theorem does not apply.'),
('Unequal splitting',r'For $T(x)=\sum_i a_iT(b_ix+h_i(x))+g(x)$, first solve $\sum_i a_i b_i^p=1$, with positive $a_i$ and fractions $0<b_i<1$. Subject to the theorem’s regularity and perturbation conditions, the bound is $\Theta(x^p(1+\int_1^x g(u)/u^{p+1}\,du))$. For thirds and two-thirds, $p=1$; a linear toll gives the integral $\log x$ and therefore $\Theta(x\log x)$. Floor and ceiling errors are bounded perturbations, but the subproblem sizes must still decrease beyond a fixed base cutoff. Averaging the fractions before applying an equal-split theorem changes the recurrence.'),
('Shrinking mass',r'If total child fraction is less than1 and local work is linear, a geometric mass bound often gives linear total work. For fractions1/3 and1/4, the ratio is7/12. Rounding slack must still be handled in a proof.'),
('Square-root transform',r'For a one-child square-root recursion, log size halves and depth is$\Theta(\log\log n)$. For two children with log toll, transform to$m=\log n$ and solve$U(m)=2U(m/2)+m$. Substitute$m$ back in the final result.'),
('Exact bases',r'For$T(n)=2T(n/2)+n,T(1)=1$, exact cost is$n\log_2n+n$ on powers of two. Dropping leaf work changes exact values such as$T(8)=32$, even though asymptotic order remains unchanged.'),
('Repeated roots',r'A characteristic root$r$ of multiplicity$s$ contributes$(A_0+\cdots+A_{s-1}n^{s-1})r^n$. For a double root1, use$A+Bn$. Bases determine coefficients and cannot be replaced by a growth-rate guess.'),
('Resonant forcing',r'For$a_n=2a_{n-1}+2^n$, normalization by$2^n$ yields an arithmetic sequence and gives$n2^n$ with zero base. A forcing term sharing a homogeneous root requires additional polynomial factors.'),
('Tree versus state DAG','Memoized recursion pays once per distinct state, plus dependency-processing work. Fibonacci has linear states under unit arithmetic. Repeated appearances in an expanded tree are not separate executions after cache hits.'),
('Work versus span',r'Work sums parallel children; span follows the maximum child path plus the actual combine span. With a serial linear combine, balanced work is$n\log n$ while span is$n$. Speedup assumptions cannot remove a serial dependency.'),
('Peak live storage','Depth-first retained allocations$n,n/2,n/4,...$ yield linear peak storage. Parallel children or different allocation lifetimes can change the recurrence. Total allocations over time are not peak memory.'),
('Upper toll uncertainty',r'An$O(n^2)$ nonnegative toll supplies a quadratic upper bound, not necessarily quadratic tight order. Positive leaves supply a separate lower bound. Give the strongest justified interval of growth rates rather than silently strengthening the toll.'),
('Substitution slack',r'When substituting an upper-bound guess, leave enough constant or lower-order slack to absorb the toll and rounding. Prove bases separately. Writing$T(n)\le cn\log n$ on both sides without closing the remaining inequality is not an induction proof.'),
])
chapter('a_divide',r'''
### Convert a combine operation into a numerical contract

Merging sorted arrays of lengths$p,q$ needs at most$p+q-1$ key comparisons when both are nonempty. Remaining items are copied without comparing after one side is exhausted. For strict inversion counting, emitting a right item smaller than the current left item creates one inversion with every remaining left item. Equality must not trigger that count.

For maximum-subarray summaries, each child returns total$T$, best nonempty prefix$P$, suffix$S$ and interval$B$. Concatenating left$X$ and right$Y$ gives total$T_X+T_Y$, prefix$\max(P_X,T_X+P_Y)$, suffix$\max(S_Y,T_Y+S_X)$ and best$\max(B_X,B_Y,S_X+P_Y)$. The crossing term is a suffix plus a prefix, not the sum of child best intervals. A nonempty contract returns the largest negative singleton for an all-negative array; an empty-allowed contract returns zero.

### Compare arithmetic algorithms in the same model

Ordinary recursive digit multiplication uses four half-size products, giving quadratic work. Karatsuba computes three, giving exponent$\log_23$. Strassen changes eight block multiplications to seven, giving exponent$\log_27$. These exponents assume linear digit additions for Karatsuba and quadratic matrix-block additions for Strassen. Constant-cost whole-number arithmetic or an incompatible representation asks a different question.

For unequal digit lengths, align low-part widths before applying reconstruction; for odd widths, use the actual low width$m$ in the shifts$B^m,B^{2m}$. Matrix blocks need their multiplication order preserved because they do not generally commute. Padding can increase operation counts even though it does not change the asymptotic exponent for bounded-factor padding.

### Fourier size and sign conventions determine the answer

Coefficient lengths$r,s$ have linear convolution length$r+s-1$. A power-of-two transform must choose$N\ge r+s-1$ to avoid wraparound. Without enough padding, cyclic convolution aliases high-degree coefficients into lower positions. Under a forward transform using$\omega^{jk}$, the inverse uses$\omega^{-jk}/N$. Omitting the normalization multiplies recovered coefficients by$N$; using the wrong sign permutes their phase structure.
''',[
('Merge comparison bound',r'Two sorted nonempty arrays have lengths4 and6. What is the worst-case number of key comparisons for the usual two-pointer merge?', ['6','9','10','24'],'B',r'The worst case keeps both arrays nonempty until only one item remains, using$4+6-1=9$ comparisons. Every comparison emits one item, and the last item requires only copying. The output still has ten writes under an explicit-output contract; key comparisons and writes are different counts.'),
('Strict cross inversions',r'Merge left$[2,4,7]$ with right$[1,4,6]$. How many strict cross inversions exist?', ['4','5','6','9'],'B',r'Right1 is smaller than all three left items and contributes3. Right4 is smaller only than left7 and contributes1; equality with left4 is not an inversion. Right6 is also smaller only than7 and contributes1. Total5. Counting only the first equal-key comparison can incorrectly lose the later7-versus4 inversion.'),
('Four-summary combine',r'Left summary$(T,P,S,B)=(6,6,8,8)$ and right summary$(-3,1,5,5)$ use nonempty subarrays. What is the combined summary?', ['(3,7,5,9)','(3,6,8,8)','(3,7,13,13)','(3,1,5,8)'],'A',r'Total is3. Prefix is$\max(6,6+1)=7$. Suffix is$\max(5,-3+8)=5$. Best interval is$\max(8,5,8+1)=9$. The crossing best uses the left suffix and right prefix, not the two child best intervals. Compute each field separately; different fields can have different winning witnesses.'),
('All-negative contract',r'For array$[-8,-3,-5]$, what is the maximum nonempty subarray sum?', ['-16','-8','-3','0'],'C',r'Adding any other negative entry makes a selected interval sum smaller. The best nonempty interval is the singleton$[-3]$, giving$-3$. Zero is valid only when an empty interval is allowed. The word nonempty determines initialization and invalidates the common zero-initialized maximum shortcut.'),
('Sufficient child information',r'Why is returning only each child’s best subarray sum insufficient for a correct divide-and-conquer combine?', ['The arrays must be sorted.','A crossing optimum needs left suffix and right prefix information.','The recursive calls must overlap.','Every child best must be negative.'],'B',r'The optimal parent interval can cross the split and then consists of a suffix of the left child followed by a prefix of the right. A child’s best internal interval may touch neither boundary. Therefore its value cannot reconstruct the required crossing candidate. This information gap motivates the four-field summary and is independent of whether inputs are positive or negative.'),
('Closest-pair strip',r'Recursive halves each have minimum distance at least$\delta>0$. Which cross pair can improve$\delta$?', ['Any pair regardless of its horizontal coordinates.',r'Only pairs with both endpoints within$\delta$ of the divider.',r'Only pairs in the left half.',r'Only pairs already compared recursively.'],'B',r'If a cross pair has distance below$\delta$, its horizontal separation is below$\delta$. Each endpoint’s horizontal distance from the divider is at most that separation, so both lie in the strip. This is a necessary filter, not proof that every strip pair improves the minimum. Same-half pairs have already been bounded by the recursive result.'),
('Packing successor bound','In the standard closest-pair strip sorted by vertical coordinate, the half-specific packing argument permits comparison with at most how many later points per point?', ['3','6','7','All remaining points.'],'C',r'The relevant height-$\delta$ window has four small cells per half, each of diameter below$\delta$ under consistent boundary treatment. At most one point from each recursive half lies in each half-specific cell. There are at most eight points including the current point, hence seven successors. The same-half separation premise is essential; it does not constrain cross-half closeness.'),
('Karatsuba exponent',r'Three half-size digit multiplications and linear combine work give which tight order?', [r'$\Theta(n)$',r'$\Theta(n\log n)$',r'$\Theta(n^{\log_23})$',r'$\Theta(n^2)$'],'C',r'The recurrence is$T(n)=3T(n/2)+\Theta(n)$. The leaf exponent$\log_23$ exceeds1, so recursive multiplication dominates and the total has that power. Four half-size products would give exponent2. The stated digit model charges linear addition and shifting work rather than treating arbitrarily long integers as unit words.'),
('Karatsuba reconstruction',r'With decimal low width1, let$x=23,y=45$. The high product is8, low product15, and difference product$(2-3)(4-5)=1$. What is the mixed coefficient?', ['7','15','22','24'],'C',r'The mixed coefficient is$z_2+z_0-z_d=8+15-1=22$. Reconstruction gives$8\cdot100+22\cdot10+15=1035$, equal to23 times45. Adding rather than subtracting the difference product gives24 and an incorrect product. The low width1 determines both decimal shifts.'),
('Strassen exponent',r'Seven half-size block products and quadratic block-addition work give which tight order?', [r'$\Theta(n^2)$',r'$\Theta(n^2\log n)$',r'$\Theta(n^{\log_27})$',r'$\Theta(n^3)$'],'C',r'The recurrence$7T(n/2)+\Theta(n^2)$ has leaf exponent$\log_27>2$, so the answer is$n^{\log_27}$. The ordinary eight-product block algorithm gives cubic work. The number of added matrices affects constants and storage but not this exponent under the stated dense scalar-operation model.'),
('Zero-padding length',r'Polynomial coefficient arrays have lengths5 and4. What is the minimum power-of-two transform length avoiding cyclic aliasing?', ['4','5','8','16'],'C',r'The linear convolution has length$5+4-1=8$, corresponding to maximum degree7. The minimum power of two at least8 is8. Using16 is valid but not minimum; using4 or5 wraps some higher-degree contributions into earlier coefficients.'),
('Linear convolution coefficients',r'What is the coefficient array for multiplying$(1+2x+3x^2)$ by$(4+5x)$?', ['[4,13,22,15]','[4,10,12,15]','[4,13,15]','[4,5,6]'],'A',r'Constant is4. The$x$ coefficient is$1\cdot5+2\cdot4=13$. The$x^2$ coefficient is$2\cdot5+3\cdot4=22$, and$x^3$ is$3\cdot5=15$. Polynomial multiplication uses convolution, not entrywise multiplication. The expected length3+2-1=4 supplies a useful dimension check.'),
('Cyclic aliasing',r'The linear product in Question 12 has coefficients[4,13,22,15]. What length-two cyclic convolution results if coefficients wrap modulo$x^2-1$?', ['[4,13]','[22,15]','[26,28]','[17,37]'],'C',r'Degrees0 and2 share the first cyclic position, giving4+22=26. Degrees1 and3 share the second, giving13+15=28. Reducing modulo$x^2-1$ sets$x^2=1$ and$x^3=x$, explaining the wrap. Truncating high coefficients would give a different, incorrect cyclic result.'),
('Fourier inverse normalization',r'A forward length-eight transform uses$Y_k=\sum_j a_j\omega^{jk}$. The inverse uses the negative exponent but omits division by8. What coefficients are recovered?', ['The originals$a_j$.',r'$8a_j$.',r'$a_j/8$.','Always zero.'],'B',r'Root orthogonality gives an inner geometric sum equal to8 when indices match and0 otherwise. Without the inverse$1/8$ factor, every coefficient is multiplied by8. The negative exponent fixes orthogonality, but the normalization is a separate required factor.'),
('FFT butterflies',r'A radix-two length-eight FFT has three stages with four butterflies per stage. How many butterflies execute?', ['7','8','12','24'],'C',r'There are$\log_28=3$ stages and$8/2=4$ butterflies per stage, for12. Twenty-four counts two output values per butterfly rather than butterfly instances. Exact real multiplication counts depend on how special twiddle factors and complex products are implemented.'),
('Presorting versus sorting every level',r'A closest-pair implementation sorts by vertical coordinate anew at every recursive combine, causing$T(n)=2T(n/2)+\Theta(n\log n)$. What order results?', [r'$\Theta(n)$',r'$\Theta(n\log n)$',r'$\Theta(n\log^2n)$',r'$\Theta(n^2)$'],'C',r'The extra sorting toll gives$n(h-i)$ at depth$i$ for$h=\log_2n$. Summing across levels yields$n\Theta(h^2)$. Maintaining and linearly merging vertical order reduces the toll to linear and restores$n\log n$. The geometric idea alone does not determine the complexity; representation maintenance is part of the algorithm.'),
],[(
'Merge comparisons and writes',r'For two nonempty sorted inputs of lengths$p,q$, worst-case key comparisons are$p+q-1$ and output writes are$p+q$. An exhausted side requires copying but no further key comparison. Exact operation categories must remain separate.'),
('Strict inversion charge','When a right item is strictly smaller than the current left item, charge every remaining left item. Equal keys are not strict inversions. Left[2,4,7] and right[1,4,6] have cross count3+1+1=5.'),
('Nonempty maximum subarray','An all-negative array returns its least-negative singleton under a nonempty contract. Empty-allowed versions can return0. Initialize and combine according to the chosen contract rather than assuming all maxima are nonnegative.'),
('Crossing summary',r'Parent best is$\max(B_X,B_Y,S_X+P_Y)$. Child best sums alone cannot reconstruct a crossing interval. Prefix and suffix fields identify boundary-touching candidates; totals allow extensions across an entire child.'),
('Order of summary composition','Four-field concatenation summaries are associative because they represent the same joined sequence, but concatenation is not commutative. Reversing children changes prefixes, suffixes and interval witnesses even if some numeric fields coincide.'),
('Closest-pair strip',r'Any cross pair improving$\delta$ has both endpoints within$\delta$ of the divider and vertical separation below$\delta$. These are necessary filters. Tied divider coordinates retain their recursive-half membership in the packing proof.'),
('Seven successors','The half-specific packing window holds at most eight points including the current one, giving seven later candidates. The proof assumes same-half separation and a consistent cell-boundary convention. Coincident points yield distance0 and need early handling.'),
('Preserved vertical order',r'Presort and maintain vertical order through linear partitioning or merging to obtain$n\log n$. Sorting afresh at every combine adds a logarithmic factor. Sorting costs must appear in the recurrence rather than disappear from the algorithm description.'),
('Karatsuba difference identity',r'Mixed coefficient is$z_2+z_0-z_d$ for$z_d=(x_H-x_L)(y_H-y_L)$. With23 and45 it is22. Signed intermediate differences are valid; their product sign must be retained.'),
('Digit widths',r'Use the actual common low width$m$ in$B^m$ and$B^{2m}$. Odd-length splits need not have equal digit counts. Linear combine costs rely on a digit representation; unit-cost arbitrary-precision multiplication is a different model.'),
('Strassen block order',r'Block products do not commute. Preserve their factor order while verifying every output block. Seven products give exponent$\log_27$ with quadratic additions; exchanging a factor may leave scalar examples correct while breaking matrix cases.'),
('Padding overhead',r'Polynomial lengths$r,s$ require$N\ge r+s-1$. Square matrix power-of-two padding raises dimensions by less than a factor2 but changes exact costs. An asymptotic exponent does not justify ignoring a large constant for small instances.'),
('Convolution check',r'Coefficient$k$ is$\sum_i a_i b_{k-i}$ over valid indices. For[1,2,3] and[4,5], the result is[4,13,22,15]. Verify output length and one boundary coefficient before trusting a transform calculation.'),
('Cyclic wrap',r'Insufficient padding reduces degrees modulo$N$ under$x^N-1$, adding aliased coefficients. Length-two wrap of[4,13,22,15] gives[26,28]. It is cyclic reduction, not simple truncation.'),
('Fourier signs and scale',r'A forward positive-exponent convention pairs with inverse negative exponent and factor$1/N$. Omitting scale recovers$Na_j$. State the root order and sign convention before evaluating butterfly or inverse formulas.'),
('FFT work and arithmetic reliability',r'Radix-two FFT has$(N/2)\log_2N$ butterflies. Each shares a twiddle multiplication across two outputs. Floating recovery requires an error margin before integer rounding; exact NTT recovery requires a suitable root and sufficient modulus or CRT range.'),
])
