from author import chapter
chapter('l_vectors',r'''
### Turn geometric language into an optimization equation

For a nonzero direction$u$, minimize $\|v-tu\|^2$. Expanding gives $\|v\|^2-2t\langle u,v\rangle+t^2\|u\|^2$ over the reals. Completing the square yields the unique minimizing coefficient $t=\langle u,v\rangle/\langle u,u\rangle$. The projection vector is$tu$, its length is$|t|\|u\|$, and the distance is the norm of$v-tu$. These are three different requested quantities. The residual is orthogonal to$u$, supplying an independent computational check.

For a line$p+tu$, first replace$v$ by$v-p$, project that displacement, and add$p$ back. For a plane $a\cdot x=b$ with nonzero normal$a$, the distance from$p$ is $|a\cdot p-b|/\|a\|$. Normalizing an offset plane equation incorrectly can move the plane: scale both sides together.

### Independence and coordinates are linear systems

To decide whether$v_1,\ldots,v_k$ are independent, solve $c_1v_1+\cdots+c_kv_k=0$. One nonzero coefficient solution proves dependence. A zero vector always creates dependence, but nonzero vectors can also be dependent. If a family is a basis, expressing a target vector in that family is solving the corresponding system for its coordinate coefficients; these coefficients need not equal the standard coordinates.

### Change the inner product before applying a Euclidean shortcut

With positive definite diagonal weights$w_i$, use $\langle u,v\rangle_W=\sum_iw_iu_iv_i$ in both projection numerator and denominator. Complex inner products require conjugation; here $\langle u,v\rangle=\sum\overline{u_i}v_i$ is linear in the second argument. The sum of complex squares without conjugates can vanish for a nonzero vector and is not a norm.

In Gram–Schmidt, subtract projections onto previous orthogonal directions and only then normalize the residual. A zero residual records dependence and cannot be divided by its norm. The cross product measures oriented area only in three-dimensional real coordinates; its norm gives parallelogram area and half that gives triangle area.
''',[
('Projection coefficient and vector',r'For $v=(3,1)$ and $u=(1,2)$, what is the orthogonal projection of$v$ onto the line spanned by$u$?', [r'$(1,2)$',r'$(5,10)$',r'$(2,-1)$',r'$(3,1)$'],'A',r'The dot product is5 and $u\cdot u=5$, so the coefficient is1. Multiplying by$u$ yields$(1,2)$. The residual$(2,-1)$ has dot product0 with$u$, verifying the calculation. ChoiceB omits division by the squared norm; C is the residual rather than the projection; D would require$v$ already to be parallel to$u$.'),
('Projection distance',r'Use the vectors in Question 1. What is the distance from$v$ to the line?', [r'$1$',r'$\sqrt5$',r'$5$',r'$\sqrt{10}$'],'B',r'The residual is$(2,-1)$, whose squared norm is$4+1=5$. The distance is therefore$\sqrt5$. The coefficient1 is not the distance. The scalar5 is the squared distance, and$\sqrt{10}$ is the norm of$v$ rather than its perpendicular component.'),
('Affine line',r'Find the closest point to$q=(4,3)$ on the line$p+t u$, where$p=(1,1)$ and$u=(1,0)$.', [r'$(4,0)$',r'$(3,1)$',r'$(4,1)$',r'$(1,3)$'],'C',r'Translate to$q-p=(3,2)$, whose projection on$u$ is$(3,0)$. Add the base point to get$(4,1)$. The displacement from that point to$q$ is vertical and orthogonal to$u$. Projecting$q$ directly onto the direction space gives$(4,0)$, which lies on a different line.'),
('Plane distance',r'What is the distance from$p=(1,2,3)$ to the plane$x+2y+2z=5$?', ['1','2','3','6'],'B',r'The normal is$(1,2,2)$ with norm3. The plane expression at$p$ is$1+4+6=11$, so the signed discrepancy is6. Divide its absolute value by3 to obtain2. Six is not a distance unless the normal has unit norm. Scaling the entire plane equation leaves the quotient unchanged.'),
('Parameter-dependent independence',r'The vectors $(1,t)$ and$(2,4)$ in$\mathbb R^2$ are dependent for which real$t$?', ['0','1','2','4'],'C',r'If the second vector is twice the first, its second coordinate must satisfy$4=2t$, giving$t=2$. Conversely at2 that exact multiple relation proves dependence. The determinant$4-2t$ is a second check. Neither zero$t$ nor equal displayed coordinates by themselves establish dependence.'),
('Coordinates in a chosen basis',r'Let$b_1=(1,1)$ and$b_2=(1,-1)$. What are the coordinates of$v=(4,2)$ in this ordered basis?', [r'$(4,2)$',r'$(3,1)$',r'$(1,3)$',r'$(2,4)$'],'B',r'Solve$c_1+c_2=4$ and$c_1-c_2=2$. Adding gives$c_1=3$, and then$c_2=1$. Indeed $3(1,1)+(1,-1)=(4,2)$. Reversing the basis order would reverse these coordinates, but that is not the stated ordered basis. The standard components are not automatically basis coefficients.'),
('Weighted geometry',r'Use inner product $\langle x,y\rangle=x_1y_1+4x_2y_2$. For$v=(2,1)$ and$u=(1,1)$, what is the projection coefficient$t$?', ['3/2','6/5','3/5','1'],'B',r'The weighted numerator is$2+4=6$ and the weighted denominator is$1+4=5$. Thus$t=6/5$. The Euclidean coefficient3/2 uses the wrong geometry. With this coefficient, the weighted inner product of$u$ with$v-tu$ is zero, checking the minimizer. The same metric must be used in numerator and denominator.'),
('Complex norm',r'Under the standard Hermitian inner product, what is $\|(1,i)\|^2$?', ['0','1','2',r'$1+i$'],'C',r'Conjugation gives $|1|^2+|i|^2=1+1=2$. Adding ordinary squares would give$1+i^2=0$, incorrectly assigning zero squared norm to a nonzero vector. A squared norm is real and nonnegative. The conjugate factor is necessary, not a stylistic convention.'),
('Gram–Schmidt residual',r'With$v_1=(1,1,0)$ and$v_2=(1,0,1)$, what residual results after removing the projection of$v_2$ on$v_1$?', [r'$(0,-1,1)$',r'$(1/2,-1/2,1)$',r'$(1,1,0)$',r'$(1/2,1/2,0)$'],'B',r'The projection coefficient is $(v_1\cdot v_2)/(v_1\cdot v_1)=1/2$. Subtract$(1/2,1/2,0)$ from$v_2$ to obtain$(1/2,-1/2,1)$. Its dot product with$v_1$ is zero. OptionD is the removed projection. Normalizing this residual is a subsequent step, not part of merely computing it.'),
('Cauchy–Schwarz equality',r'For nonzero real vectors$u,v$, when does $|u\cdot v|=\|u\|\|v\|$ hold?', ['Exactly when they are perpendicular.','Exactly when one is a scalar multiple of the other.','Exactly when their lengths are equal.','Always in two dimensions.'],'B',r'Equality occurs precisely when the perpendicular residual in the projection proof has zero norm. That means$v$ lies in the span of$u$, so$v=tu$ for some real$t$. Negative$t$ is allowed because the dot product is inside an absolute value. Equal lengths alone do not force parallel directions.'),
('Triangle area',r'What is the area of the triangle generated from the origin by$u=(1,0,0)$ and$v=(0,3,0)$?', ['1','3/2','3','6'],'B',r'The cross product is$(0,0,3)$, whose norm3 is the parallelogram area. A triangle is half that region, so its area is3/2. OptionC omits the half factor. The norm-product shortcut works here because the directions are perpendicular, but in general a sine factor is required.'),
('Scalar triple product',r'For$u=(1,0,0)$,$v=(0,2,0)$,$w=(0,0,-3)$, what is the volume of the parallelepiped?', ['-6','3','6','12'],'C',r'$v\times w=(-6,0,0)$ and $u\cdot(v\times w)=-6$. The signed triple product records orientation; volume is its absolute value6. A negative signed value is not a negative geometric volume. Reversing two vectors changes the sign but leaves the requested volume unchanged.'),
],[(
'Projection versus residual',r'$\operatorname{proj}_u v=(\langle u,v\rangle/\langle u,u\rangle)u$ for nonzero$u$. For$(3,1)$ onto$(1,2)$, projection is$(1,2)$ and residual is$(2,-1)$. Check their orthogonality; do not return the scalar coefficient when the vector is requested.'),
('Distance formula',r'Distance to the span of$u$ is $\sqrt{\|v\|^2-|\langle u,v\rangle|^2/\|u\|^2}$. The root is required for distance, not squared distance. A slightly negative value from rounding needs a numerical error analysis, not a new geometric interpretation.'),
('Affine translation',r'For line$p+tu$, project$q-p$ and add$p$. Projecting$q$ directly solves the origin-line problem. For a plane normal$a$, use $|a\cdot q-b|/\|a\|$ and require$a\ne0$.'),
('Independence',r'Solve the homogeneous coefficient equation; dependence means some nonzero coefficient tuple yields zero. With$(1,t),(2,4)$, the condition is$t=2$. More than$d$ vectors in a$d$-dimensional space cannot be independent.'),
('Basis coordinates',r'Coordinates are coefficients relative to an ordered basis. Solve the column system rather than reusing standard entries. In basis$(1,1),(1,-1)$, vector$(4,2)$ has coefficients$(3,1)$. Reordering the basis reorders the coefficients.'),
('Span versus affine combinations',r'A linear span allows arbitrary coefficients; an affine combination requires their sum to be1. An affine line need not contain zero. A subset closed under differences need not be a subspace unless it also has the required scalar and origin properties.'),
('Metric consistency',r'Weighted projection uses the same positive definite inner product in numerator and denominator. For weights1,4, vectors$(2,1),(1,1)$ give coefficient6/5. Zero or negative weights can destroy the norm properties used by the projection proof.'),
('Complex conjugation',r'With the convention conjugate-linear in the first argument, use $\langle u,v\rangle=\sum\overline{u_i}v_i$. Vector$(1,i)$ has squared norm2, not0. State the convention before computing coefficients or adjoints.'),
('Gram–Schmidt order',r'Subtract all earlier orthogonal components before normalization. A zero residual detects dependence and cannot be normalized. Orthogonality alone implies independence only when every listed vector is nonzero.'),
('Angle conditions',r'For nonzero real vectors, $\cos\theta=(u\cdot v)/(\|u\|\|v\|)$. A zero vector has no direction angle under this formula. The absolute-value equality in Cauchy–Schwarz permits both parallel and antiparallel vectors.'),
('Area and orientation',r'In$\mathbb R^3$, parallelogram area is$\|u\times v\|$ and triangle area is half that. Reversing factors negates the cross product but preserves area. The cross product is not the general inner-product projection operator.'),
('Volume and coplanarity',r'Volume is $|u\cdot(v\times w)|$. A zero triple product detects linear dependence of three real3D vectors, including degenerate zero-vector cases. The signed value distinguishes orientation and must not be reported as a negative volume.'),
])
chapter('l_matrices',r'''
### Make shape and factor order part of every calculation

If$A$ is$m\times k$ and$B$ is$k\times n$, then $(AB)_{ij}=\sum_{r=1}^kA_{ir}B_{rj}$ and the output has shape$m\times n$. Row-column pairing fixes the answer. Composition applies the rightmost factor first to column vectors. Associativity permits changing parentheses, not changing factor order. A transpose or inverse reverses product order: $(AB)^T=B^TA^T$ and $(AB)^{-1}=B^{-1}A^{-1}$ when both square factors are invertible.

### Calculate operation counts from shapes

The ordinary product of$m\times k$ and$k\times n$ matrices uses$mkn$ scalar multiplications and$mn(k-1)$ additions if each dot product starts from its first product. Parenthesizing a chain changes intermediate shapes and work. For shapes$10\times100$, $100\times5$, $5\times50$, the left association uses5000+2500=7500 multiplications; the right uses25000+50000=75000. Both yield the same exact mathematical matrix while their computational cost differs by a factor10.

### Exploit structure without assuming cancellation

For $A=I+N$ with$N^2=0$, the inverse is$I-N$ because their product is$I-N^2=I$. For a nilpotent$N$ of index$r$, the finite geometric inverse has alternating powers through$r-1$. A scalar cancellation rule cannot justify matrix cancellation: nonzero matrices can multiply to zero. Left cancellation requires an injective left action, while right cancellation requires a suitable right-side condition. Square invertibility supplies both.

The Gram matrix$A^TA$ satisfies $x^TA^TAx=\|Ax\|^2\ge0$. It is positive definite precisely when$A$ has independent columns. Orthonormal columns imply$A^TA=I$, but a tall rectangular$A$ cannot also satisfy$AA^T=I$ on the larger space. The latter product is a projection onto its column space.
''',[
('Shape of a product',r'$A$ is$3\times2$ and$B$ is$2\times4$. What is the shape of$AB$?', ['2 by2','3 by4','4 by3','The product is undefined.'],'B',r'The shared inner dimension is2, so multiplication is defined. The surviving outer dimensions are3 and4. Each of the twelve output entries is a length-two dot product. Shape matching concerns inner dimensions, not equality of the complete input shapes.'),
('Compute a rectangular entry',r'$A$ has first row$(1,2)$ and$B$ has second column$(3,4)^T$. What is$(AB)_{12}$?', ['7','8','11','14'],'C',r'The requested entry pairs row1 of$A$ with column2 of$B$: $1\cdot3+2\cdot4=11$. Adding entries gives neither a matrix product nor a dot product. Matching rows instead of row and column can silently compute the wrong entry when matrices are square.'),
('Composition order',r'With column vectors, $S$ doubles the first coordinate and$R$ swaps the two coordinates. Which product maps$(1,3)^T$ to$(6,1)^T$?', [r'$RS$',r'$SR$',r'$R+S$',r'$S^2$'],'B',r'Apply$R$ first to get$(3,1)$ and then$S$ to get$(6,1)$. Composition therefore corresponds to$SR$, with the rightmost factor acting first. Reversing the order gives$(3,2)$, showing that factor order matters. Matrix addition describes a sum of outputs, not sequential transformations.'),
('Inverse order',r'For invertible square$A,B$, which expression equals$(AB)^{-1}$?', [r'$A^{-1}B^{-1}$',r'$B^{-1}A^{-1}$',r'$(A+B)^{-1}$',r'$A^TB^T$'],'B',r'Multiply $(AB)(B^{-1}A^{-1})$ and reassociate to obtain $A(BB^{-1})A^{-1}=I$. The opposite-side product also equals$I$. Reversing neither factor would require commuting matrices, which is not assumed. Transpose and inverse coincide only under additional orthogonality conditions.'),
('A two-by-two inverse entry',r'For$A$ with rows$(2,1)$ and$(3,2)$, what is$(A^{-1})_{12}$?', ['-3','-1','1','2'],'B',r'The determinant is$2\cdot2-1\cdot3=1$. The inverse has rows$(2,-1)$ and$(-3,2)$ after dividing by that determinant. Its row1,column2 entry is$-1$. Option$-3$ selects the wrong off-diagonal position. Swapping the diagonal and negating both off-diagonal entries must preserve their positions.'),
('Nilpotent inverse',r'$N\ne0$ is square and$N^2=0$. Which matrix is the inverse of$I+N$?', [r'$I+N$',r'$I-N$',r'$-N$',r'$N^{-1}$'],'B',r'Compute $(I+N)(I-N)=I-N^2=I$ and likewise in the other order. The finite geometric series terminates because the square vanishes. A nonzero square-zero matrix is not invertible: otherwise multiplying$N^2=0$ by an inverse would force$N=0$. ThusD is not available.'),
('Matrix-chain cost',r'Ordinary multiplication is used for shapes$10\times100$, $100\times5$, $5\times50$. Which association uses fewer scalar multiplications and how many?', ['Left,7500','Right,7500','Left,75000','Both,5000'],'A',r'The left product costs$10\cdot100\cdot5=5000$ and produces$10\times5$; multiplying by the third costs$10\cdot5\cdot50=2500$. Total7500. The right product costs25000, then the first-times-result costs50000, total75000. Both outputs have shape$10\times50$, but associativity does not imply equal operation counts.'),
('Rectangular orthonormal columns',r'$A$ is a real$5\times2$ matrix with orthonormal columns. Which assertion must hold?', [r'$A^TA=I_2$',r'$AA^T=I_5$',r'$A$ is square.',r'$A^T=A$'],'A',r'The entries of$A^TA$ are column dot products, yielding the two-dimensional identity. The product$AA^T$ has rank at most2 and cannot be the rank-five identity; it projects onto the column span. Equality with a transpose is not even shape-compatible here. Orthonormal columns give an isometry from a smaller domain, not a bijection on the larger space.'),
('Gram positivity',r'For a real$m\times n$ matrix$A$, when is$A^TA$ positive definite?', ['Whenever$A$ has no zero entries.','Exactly when the columns of$A$ are linearly independent.','Whenever$m<n$.','Only when$A$ is symmetric.'],'B',r'$x^TA^TAx=\|Ax\|^2$. This is strictly positive for every nonzero$x$ exactly when$Ax=0$ has only the zero solution, which is column independence. With$m<n$, dependence is unavoidable. Nonzero entries or symmetry alone do not decide whether a null vector exists.'),
('Trace with rectangular factors',r'$A$ is$2\times3$ and$B$ is$3\times2$. Which identity always holds?', [r'$AB=BA$',r'$\operatorname{tr}(AB)=\operatorname{tr}(BA)$',r'$\det(AB)=\det(BA)$',r'$A^TB=B^TA$'],'B',r'Expand the two traces as $\sum_i\sum_j A_{ij}B_{ji}$ and reverse the finite summation order. Both traces are defined even though the product shapes differ. The products cannot be equal as shaped arrays, and determinant equality need not hold for different-size square products. The transpose products inD may not even be defined.'),
('Outer product',r'For$u=(1,2)^T$ and$v=(3,4,5)^T$, what are the shape and$(2,3)$ entry of$uv^T$?', ['2 by3,10','3 by2,10','2 by3,7','1 by1,11'],'A',r'A column of length2 times a row of length3 produces a$2\times3$ array. Entry$(i,j)$ is$u_iv_j$, so the requested entry is$2\cdot5=10$. An outer product uses no summation across shared entries. The reversed product$v u^T$ has the swapped shape but is a different matrix.'),
('Kronecker structure',r'$A$ is$2\times3$ and$B$ is$4\times5$. What is the shape of$A\otimes B$?', ['6 by9','8 by15','4 by5','2 by3'],'B',r'The Kronecker product replaces each scalar of$A$ by a scaled copy of$B$. Two block rows each have four rows, and three block columns each have five columns, giving$8\times15$. Shape addition6 by8 is not the rule; an elementwise Hadamard product would require equal input shapes instead.'),
],[(
'Shape before arithmetic',r'$A_{m\times k}B_{k\times n}$ has shape$m\times n$. Entry$(i,j)$ pairs row$i$ with column$j$. If the inner dimensions do not match, the product is undefined rather than zero.'),
('Column-vector order',r'In$ABx$, apply$B$ first, then$A$. Associativity changes parentheses but does not exchange factors. A shear or coordinate swap combined with a scaling gives a concrete test of a proposed commutation.'),
('Transpose and inverse reversal',r'$(AB)^T=B^TA^T$ and, for invertible square factors, $(AB)^{-1}=B^{-1}A^{-1}$. The complex counterpart uses the adjoint. Reversal follows from the entry formula or the identity-product check, not from a visual mnemonic alone.'),
('Two-by-two inverse',r'For rows$(a,b),(c,d)$ with$ad-bc\ne0$, the inverse has rows$(d,-b),(-c,a)$ divided by$ad-bc$. A zero determinant prohibits this formula. The off-diagonal entries are negated without being swapped.'),
('Nonzero zero divisors',r'Nonzero matrices may satisfy$AB=0$. For example, complementary coordinate projections have zero product. Therefore$AB=AC$ permits cancellation of$A$ only under an injectivity or invertibility hypothesis, not just$A\ne0$.'),
('Finite inverse series',r'If$N^r=0$, $(I+N)^{-1}=I-N+N^2-\cdots+(-1)^{r-1}N^{r-1}$. Multiply and telescope to verify both sides. The result uses nilpotence; convergence of an infinite series is unnecessary.'),
('Ordinary product operations',r'Multiplying$m\times k$ by$k\times n$ costs$mkn$ multiplications and$mn(k-1)$ additions under first-product initialization. Initializing an accumulator to zero can change the addition count by$mn$. State which exact implementation is counted.'),
('Chain parenthesization',r'For10 by100,100 by5,5 by50, left association costs7500 multiplications versus75000 on the right. Track intermediate shapes separately. Changing factor order is not a permitted optimization.'),
('Gram condition',r'$A^TA$ is always positive semidefinite over real inputs and is positive definite exactly for independent columns. This follows from$\|Ax\|^2$. Having every entry nonzero does not rule out dependence.'),
('Tall isometry',r'Orthonormal columns give$A^TA=I$ on the domain. For a tall matrix,$AA^T$ is a projection, not the full codomain identity. Its fixed vectors are exactly those in the column span.'),
('Trace cycling',r'$\operatorname{tr}(AB)=\operatorname{tr}(BA)$ for compatible rectangular factors making both products square. With three factors, cyclic rotations preserve trace; arbitrary swaps need not. Product equality is much stronger and usually false.'),
('Outer versus elementwise versus Kronecker',r'An outer product of column lengths$m,n$ has shape$m\times n$. A Hadamard product requires matching shapes. A Kronecker product multiplies dimensions, so2 by3 with4 by5 gives8 by15. None is interchangeable with ordinary matrix multiplication.'),
])
